[ENH] Adds missing deprecation for parameter support_probabilities
aeon-toolkit/aeon pull request #1028
Opened 2024-01-08 21:09 UTC by patrickzib

Adds the missing deprecation for `support_probabilities`.

2024-01-11 22:34 UTC, MatthewMiddlehurst requested changes
Thanks for making these changes Patrick. Left some comments and suggestions.

As the parameter is functionally useless now just documents it as such really. Changes the deprecation date which is a pain but have to give people a bit of warning.

2024-01-11 22:34 UTC, MatthewMiddlehurst commented on aeon/classification/dictionary_based/_weasel_v2.py
> +         Deprecated and will be removed in v0.6.2.
```suggestion
    support_probabilities : str or bool, default="deprecated"
         Old parameter to support probabilities, no longer used as probabilities 
         are supported by default .
         
         Deprecated and will be removed in v0.8.0.
```

It no longer does any of the documented stuff when changing, so better just to say its useless IMO.

2024-01-11 22:34 UTC, MatthewMiddlehurst commented on aeon/classification/dictionary_based/_weasel_v2.py
> +        support_probabilities=False,
```suggestion
        support_probabilities="deprecated",
```

2024-01-11 22:34 UTC, MatthewMiddlehurst commented on aeon/classification/dictionary_based/_weasel_v2.py
> +        self.support_probabilities = support_probabilities
```suggestion
        # TODO remove 'support_probabilities' in v0.8.0
        self.support_probabilities = support_probabilities
        if support_probabiltiies == "deprecated":
                warnings.warn(
                        "the support_probabiltiies parameter is deprecated and will be" 
                        "removed in v0.8.0"   
                )
```

2024-01-11 22:34 UTC, MatthewMiddlehurst commented on aeon/classification/dictionary_based/_weasel_v2.py
> +            # return dists
Since there is no parameter to change the classifier from ridge, I'm pretty sure the whole method can just go.

2024-01-18 15:15 UTC, patrickzib commented on aeon/classification/dictionary_based/_weasel_v2.py
> +         Deprecated and will be removed in v0.6.2.
Thanks, I have updated the text.

2024-01-18 15:15 UTC, patrickzib commented on aeon/classification/dictionary_based/_weasel_v2.py
> +        support_probabilities=False,
Done

2024-01-18 15:15 UTC, patrickzib commented on aeon/classification/dictionary_based/_weasel_v2.py
> +        self.support_probabilities = support_probabilities
Done.

2024-01-18 15:16 UTC, patrickzib commented on aeon/classification/dictionary_based/_weasel_v2.py
> +            # return dists
Agreed. The current code was not well designed. I decided to add the LogisticRegression again. 

 If support_probabilities is set to False or "deprecated", a RidgeClassifierCV will be trained,
         which has higher accuracy and is faster. Now also supports probabilities.
         
 If support_probabilities is set to True, a LogisticRegression will be trained, which supports better
         probabilities, yet is slower and typically less accurate. 
         
 Once deprecation is done, we can remove LogisticRegression altogether.

2024-01-22 22:09 UTC, MatthewMiddlehurst approved these changes

2024-01-25 10:58 UTC, MatthewMiddlehurst commented
Thanks for the PR

2024-01-25 10:58 UTC, merged