[ENH] Load the regression results from tsc.com
aeon-toolkit/aeon pull request #1034
Opened 2024-01-11 14:23 UTC by TonyBagnall

provides capacity to load results of 19 regressors on 63 tser datasets. Currently regression and classification results are in different formats. This will change when we have finished the classification redux, but for now they are parameterised

2024-01-14 17:15 UTC, dguijo requested changes
Thank you, Tony. Good work :) Some minor minor changes 

PS. I'll check the python notebooks in the reviewNB.

2024-01-14 17:15 UTC, dguijo commented on aeon/benchmarking/results_loaders.py
> +                f"Cannot connect to {url} website down or results not " f"present"
This string can be simplified:
`f"Cannot connect to {url} website down or results not present"`

2024-01-14 17:15 UTC, dguijo commented on aeon/benchmarking/results_loaders.py
>      datasets=UCR,
I've seen you test if the measure and task are valid, but I'm not sure you also test the datasets.  (maybe in _load_results()?)

2024-01-14 20:07 UTC, TonyBagnall commented on aeon/benchmarking/results_loaders.py
>      "TSF": {"tsf", "TimeSeriesForest"},
no we should put them in, just were not part of the previous version so I missed them. thanks

2024-01-17 10:34 UTC, TonyBagnall commented on aeon/benchmarking/results_loaders.py
>      datasets=UCR,
cant really test this in aeon, since we cannot guarantee all datasets are available to all algorithms. By datasets where results not present are by default ignored if loaded into a dictionary
![image](https://github.com/aeon-toolkit/aeon/assets/9594042/8ea3e6da-d9c9-4e40-b441-552d50f52517)

but have the option of NaNs in load to array
![image](https://github.com/aeon-toolkit/aeon/assets/9594042/027a7b93-8cfc-443a-895c-aaa21a023ef4)

2024-01-17 11:24 UTC, dguijo reviewed
minor change :) thanks Tony!

2024-01-17 11:24 UTC, dguijo commented on aeon/benchmarking/results_loaders.py
> +    "5NN-DTW": {"1NNDTW", "1nn-dtw"},
I think it should be `"5NN-DTW": {"5NNDTW", "5nn-dtw"}`,

Also, I think the 1nn for the Euclidean Distance is still missing :) 

    "1NN-ED": {
        "1NNED",
        "1nn-ed",
    },
    "5NN-ED": {"5NNED", "1nn-ed"},

2024-01-17 19:45 UTC, TonyBagnall commented on aeon/benchmarking/results_loaders.py
> +    "5NN-DTW": {"1NNDTW", "1nn-dtw"},
good spot!

2024-01-18 09:41 UTC, dguijo approved these changes
LGTM! Good work, Tony! Thanks!

2024-01-18 11:53 UTC, merged