[DOC, REF] Add `TimeSeriesKernelKMeans` and `TimeSeriesKShapes` to `clustering/__init__.py` and also adds examples to dosctring
aeon-toolkit/aeon pull request #1097
Opened 2024-01-25 10:35 UTC by andregdmitri

#### Reference Issues/PRs
Solves #942. See also #1091.

#### What does this implement/fix? Explain your changes.
Adds `TimeSeriesKernelKMeans` and `TimeSeriesKShapes` to `clustering/__init__.py`.

Adds doc string example for:
- `TimeSeriesKernelKMeans` in file `_kernel_k_means`
- `TimeSeriesKShapes` in file `_k_shapes`

2024-01-25 11:31 UTC, TonyBagnall commented
ah unfortunately there is a problem doing the init for estimators with soft dependencies. iirc if we import in init it means everything in the package then requires the soft dependency to run. Am I remembering correctly @chrisholder @MatthewMiddlehurst ?

2024-01-25 11:58 UTC, MatthewMiddlehurst requested changes
That shouldn't be the case, it should only import on the estimator init/function calls. But yes, if it has a soft dependency I think the current workaround for examples is to explicitly skip the portions which use them. See the below suggestions. 

The examples are good, thanks for adding them!

2024-01-25 11:58 UTC, MatthewMiddlehurst commented on aeon/clustering/_k_shapes.py
> +    >>> preds = ks.predict(X_test)
```suggestion
    >>> ks = TimeSeriesKShapes(n_clusters=3, random_state=1)  # doctest: +SKIP
    >>> ks.fit(X_train)  # doctest: +SKIP
    TimeSeriesKShapes(n_clusters=3, random_state=1)
    >>> preds = ks.predict(X_test)  # doctest: +SKIP
```

2024-01-25 11:58 UTC, MatthewMiddlehurst commented on aeon/clustering/_kernel_k_means.py
> +    >>> preds = kkm.predict(X_test)
```suggestion
    >>> kkm = TimeSeriesKernelKMeans(n_clusters=3, kernel='rbf', random_state=1)  # doctest: +SKIP
    >>> kkm.fit(X_train)  # doctest: +SKIP
    TimeSeriesKernelKMeans(kernel='rbf', n_clusters=3, random_state=1)
    >>> preds = kkm.predict(X_test)  # doctest: +SKIP
```

2024-01-25 13:54 UTC, andregdmitri commented
I implemented the changes suggested by @MatthewMiddlehurst (thanks!), but I also had to remove `random_state=1`  from `TimeSeriesKernelKMeans.fit( )` so that the Linter would accept the line lenght.

I hope everything is in order now

2024-01-26 12:06 UTC, chrisholder approved these changes
Great change, this wasn't initially in init because the tests were crashing for soft depends. Think we since fixed the bug that caused that and forgot to re add it in. Great change!

2024-01-26 12:55 UTC, merged