[ENH] Deprecate Filter transformer
aeon-toolkit/aeon pull request #1110
Opened 2024-01-26 14:06 UTC by TonyBagnall

part of #1086 

Filter was ported in from aeon-neuro for unknown reasons, and introduces a soft dependency on mne which we dont really need.

2024-01-26 17:33 UTC, MatthewMiddlehurst commented
Fine with this. Deprecation message was left and needs updating.

2024-01-29 18:57 UTC, hadifawaz1999 approved these changes
lgtm !

2024-01-29 19:03 UTC, MatthewMiddlehurst approved these changes

2024-01-29 19:04 UTC, MatthewMiddlehurst requested changes
Oops above was an accident.

2024-01-29 19:04 UTC, MatthewMiddlehurst commented on aeon/transformations/filter.py
> +)
Message needs to be changed.

2024-01-29 19:51 UTC, TonyBagnall commented on aeon/transformations/filter.py
> +)
huh, thought Id done that

2024-01-30 17:46 UTC, MatthewMiddlehurst approved these changes

2024-01-30 18:32 UTC, merged