[ENH] Data and results loading update
aeon-toolkit/aeon pull request #1115
Opened 2024-01-27 15:58 UTC by TonyBagnall

I have wanted to sort this out for so long! We have finalised the next round of datasets and results for classification, regression and, to some extent, clustering. 

### Data loading

this will now load 128 classification and 63 regression data. I have updated the load_data_from_web notebook. More classification data to follow soon

```python
from aeon.datasets.tser_data_lists import tser_soton
from aeon.datasets.tsc_data_lists import univariate
from aeon.datasets import load_classification, load_regression
def download_all_classification_datasets(extract_path="C:\\Temp\\ClassificationData\\"):
    for s in sorted(list(univariate)):
        print("Downloading ",s)
        load_classification(s, extract_path=extract_path)

def download_all_regression_datasets(extract_path="C:\\Temp\\RegressionData\\"):
    for s in sorted(list(tser_soton)):
        print("Downloading ",s)
        load_regression(s, extract_path=extract_path)

download_all_classification_datasets()
download_all_regression_datasets()
```

## Results loading
List of available estimators is maintained on tsc.com, to avoid having to maintain lists in two locations.

```python
from aeon.benchmarking import get_available_estimators
cls=get_available_estimators(task="Classification", return_dataframe=False)
reg=get_available_estimators(task="Regression")
clst=get_available_estimators(task="Clustering")
```
these return dataframes or lists. To get the results for classifiers (see notebook for options and see results_loader.VALID_RESULT_MEASURES for available measures`

```python
from aeon.benchmarking.results_loaders get_estimator_results_as_array
res = get_estimator_results_as_array(
        estimators=cls,
        datasets=data,
        path=data_path,
        include_missing=True,
        default_only=False,
)
```
you can then plot a big old CD, which of course is silly, but shows functionality

```python
from aeon.visualisation import plot_critical_difference
plot = plot_critical_difference(results, cls)
plot.show()
```
![image](https://github.com/aeon-toolkit/aeon/assets/9594042/c05b261f-a727-4e57-9be4-44be16aff084)

Notebook is reference_results.ipynb

2024-01-29 06:57 UTC, dguijo requested changes
Good job, Tony! Thank you. I just request a few minor changes.

2024-01-29 06:57 UTC, dguijo commented on aeon/datasets/dataset_collections.py
> +        Whether to return problems as a list or a set.
I'm not sure of two things here:
- a study case in which returning the "list" as a dict is of interest.
- the function name includes "list" but it may return a dict. Maybe just remove the word "list" in case the functionality of returning it as a set has interest.

2024-01-29 06:57 UTC, dguijo commented on examples/benchmarking/reference_results.ipynb
>     "source": [
<p>Not sure what happened here, but there are 19 regressors. One is in the dataframe header.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/aeon-toolkit/aeon/pull/1115/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='2'/>

2024-01-29 06:57 UTC, dguijo commented on examples/benchmarking/reference_results.ipynb
>     "source": [
<p>Not sure why is this warning shown in this and all figures below. I think it may comes from the line of plot.show(). Try removing it. </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/aeon-toolkit/aeon/pull/1115/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='11'/>

2024-01-29 06:57 UTC, dguijo commented on examples/datasets/load_data_from_web.ipynb
>      "It is common to use standard collections of data to compare different estimators for\n",
<p>I'm not sure about this, but in the ReviewNB the sentence has a line break and is shown in two lines.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/aeon-toolkit/aeon/pull/1115/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='2'/>

2024-01-29 10:40 UTC, hadifawaz1999 commented on examples/benchmarking/reference_results.ipynb
>     "source": [
yes through aeon usually plt.show does not work, only saving the figures

2024-01-30 18:40 UTC, TonyBagnall commented on aeon/datasets/dataset_collections.py
> +        Whether to return problems as a list or a set.
I see your point, overloading the term list really. Changed to get_X

2024-01-30 19:00 UTC, TonyBagnall commented on examples/benchmarking/reference_results.ipynb
>     "source": [
good spot, missing a header on the website

2024-01-30 19:03 UTC, TonyBagnall commented on examples/benchmarking/reference_results.ipynb
>     "source": [
<p>its a notebook thing I think, tried removing the shows</p>

2024-01-30 19:05 UTC, TonyBagnall commented on examples/datasets/load_data_from_web.ipynb
>      "It is common to use standard collections of data to compare different estimators for\n",
<p>`not sure, maybe check after, looks of on my local version</p>

2024-01-31 07:26 UTC, dguijo commented on aeon/datasets/dataset_collections.py
> +        Whether to return problems as a list or a set.
sry, I said dict but wanted to say set. What is the goal in returning a set?

2024-01-31 08:05 UTC, dguijo approved these changes
LGTM. Good work, Tony.

2024-01-31 15:18 UTC, MatthewMiddlehurst approved these changes
May come back with a few comments when I visit benchmarking in more depth but no issues for now.

2024-01-31 21:52 UTC, merged