[ENH] `BaseClassifier` testing for new methods and tidy
aeon-toolkit/aeon pull request #1116
Opened 2024-01-28 20:57 UTC by MatthewMiddlehurst

Relies on #112

2024-01-30 08:54 UTC, TonyBagnall approved these changes
lgtm

2024-01-30 08:55 UTC, TonyBagnall requested changes
still draft and failing a test

2024-02-01 16:41 UTC, TonyBagnall commented on aeon/classification/base.py
> +        ``.fit(X, y).predict_proba(X)``.
not keen on this comment. I think something more explicit:

"fit_predict produces prediction estimates using just the train data. By default, this is through 10x cross validation, although some estimators may utilise specialist techniques such as bagging. Generally, this will not be the same as fitting on the whole train data then making train predictions. To do this, you should call
fit(X,y).predict(X)"

2024-02-01 19:30 UTC, MatthewMiddlehurst commented on aeon/classification/base.py
> +        ``.fit(X, y).predict_proba(X)``.
updated

2024-02-06 22:26 UTC, TonyBagnall approved these changes

2024-02-06 22:27 UTC, merged