[MNT] Further isolation of datatypes
aeon-toolkit/aeon pull request #1117
Opened 2024-01-28 22:21 UTC by TonyBagnall

see [#42](https://github.com/aeon-toolkit/aeon/issues/42)

Shifts some testing functionality out of the soon to be deprecated datatypes module, remove references to scitype and mtype

2024-01-29 18:43 UTC, TonyBagnall commented
broken by refactor

2024-02-07 14:54 UTC, merged

2024-02-07 14:54 UTC, MatthewMiddlehurst requested changes
Just one thing for now, will go through fully after other PRs

2024-02-07 15:18 UTC, MatthewMiddlehurst reviewed
this feels like it has some data generation stuff mixed up in it

2024-02-07 15:18 UTC, MatthewMiddlehurst commented on aeon/forecasting/base/tests/test_base.py
> -    preds = [res, "foo"]
why is this gone?

2024-02-07 15:18 UTC, MatthewMiddlehurst commented on aeon/forecasting/compose/tests/test_column_ensemble.py
> -    from aeon.datatypes import get_examples
keep it. I dont think its bad enough to remove yet.

2024-02-07 15:18 UTC, MatthewMiddlehurst commented on aeon/transformations/binning.py
> -    t = TimeBinAggregate([-1, 2, 10])
whats the issue with this?

2024-02-07 15:18 UTC, MatthewMiddlehurst commented on aeon/testing/utils/data_gen/_data_generators.py
> +def _make_3d_test_data(
is #1129 a follow up to this PR? it seems like this is going against the goal of that somewhat

2024-02-07 15:18 UTC, MatthewMiddlehurst commented on aeon/transformations/compose.py
> +        ],
does the new list break this somehow?

2024-02-07 15:18 UTC, MatthewMiddlehurst commented on aeon/transformations/compose.py
> +        self.set_tags(**{"X_inner_type": CORE_TYPES})
same as above

2024-02-07 15:18 UTC, MatthewMiddlehurst commented on aeon/utils/tests/test_index_functions.py
I dont know enough about this code to know whats going on here tbh

2024-02-07 15:25 UTC, MatthewMiddlehurst commented on aeon/utils/tests/test_index_functions.py
not a request, i'm just gonna trust its all ok

2024-02-08 13:38 UTC, TonyBagnall commented on aeon/transformations/binning.py
> -    t = TimeBinAggregate([-1, 2, 10])
its not an example, its just a comment

2024-02-08 13:39 UTC, TonyBagnall commented on aeon/testing/utils/data_gen/_data_generators.py
> +def _make_3d_test_data(
well these two are private and only make X, could port the code in directly but seemed pointless, just kept private functions

2024-02-13 17:12 UTC, TonyBagnall commented on aeon/transformations/compose.py
> +        self.set_tags(**{"X_inner_type": CORE_TYPES})
see #1179