Resnet4tscl
aeon-toolkit/aeon pull request #1124
Opened 2024-02-01 16:28 UTC by xiaopu222

Implemented a new Estimator based on autoencoder-resnet tailored for Time Series Clustering (tscl), situated at _aeon/clustering/deep_learning/ae_resnet.py_. The associated network structure is also integrated within _aeon/networks/ae_resnet.py_.

In addition, to ensure proper module imports during testing of this tscl Estimator, a new directory named network has been created under _aeon/clustering/deep_learning_. This temporary network folder houses the necessary files for testing and can be safely removed once adjustments are made. However, upon removal, please update the import statement in _aeon/clustering/deep_learning/ae_resnet.py_ from
`from networks.ae_resnet import AEResNetNetwork`
to
`from aeon.networks.ae_resnet import AEResNetNetwork`

2024-02-01 17:14 UTC, hadifawaz1999 requested changes
Thank you for this contribution ! it all looks good in general, with some changes requested below

2024-02-01 17:14 UTC, hadifawaz1999 commented on aeon/networks/ae_resnet.py
> +            for c in range(self.n_conv_per_residual_block):
Here it should be `range(self.n_conv_per_residual_block)[::-1]` so that we can decode symmetrically with respect to the encoder.

For instance resnet encodes with kernel sizes, 8-5-3-8-5-3-8-5-3, but we should decode with 3-5-8-3-5-8-3-5-8, same for the rest of the parameters so thats why we invert the loop range

2024-02-01 17:14 UTC, hadifawaz1999 commented on aeon/clustering/deep_learning/networks/ae_resnet.py
> +"""Residual Network (ResNet) (minus the final output layer)."""
It is best if we stay with ae_resnet in the aeon/networks module, to stay consistent through out all aeon, so we can remove this and only use the one in aeon/networks/ae_resnet

2024-02-01 17:33 UTC, MatthewMiddlehurst commented on aeon/clustering/deep_learning/ae_resnet.py
> +__all__ = ["ResNetClusterer"]
undecided but unsure if we are keeping this (see https://github.com/aeon-toolkit/aeon/issues/1095). still good to add anyway probably

2024-02-01 17:35 UTC, hadifawaz1999 commented on aeon/clustering/deep_learning/ae_resnet.py
> +__all__ = ["ResNetClusterer"]
oh forgot about that :) thanks @MatthewMiddlehurst

2024-02-02 05:32 UTC, xiaopu222 commented
> Thank you for this contribution ! it all looks good in general, with some changes requested below

I have addressed the issue you mentioned and submitted the changes.Thanks

2024-02-02 09:41 UTC, hadifawaz1999 commented
> > Thank you for this contribution ! it all looks good in general, with some changes requested below
> 
> I have addressed the issue you mentioned and submitted the changes.Thanks

Thank you ! could you resolve the conflict on the __init__ files ?

2024-02-02 14:50 UTC, hadifawaz1999 commented on aeon/clustering/deep_learning/ae_resnet.py
> +    >>> ae_resnet = AEResNetClusterer(n_clusters=2,
remove the batch_size in the example so that it would fit all on one line, it will not work with multiple lines

2024-02-02 14:53 UTC, hadifawaz1999 commented
you can keep it to "super().__init__()" no need to change it back

2024-02-02 15:00 UTC, xiaopu222 commented on aeon/clustering/deep_learning/ae_resnet.py
> +    >>> ae_resnet = AEResNetClusterer(n_clusters=2,
Thanks!

2024-02-05 11:21 UTC, hadifawaz1999 approved these changes
LGTM ! thank you for your contribution

2024-02-05 11:21 UTC, merged