[ENH] Split validation and conversion in utils
aeon-toolkit/aeon pull request #1134
Opened 2024-02-04 20:24 UTC by TonyBagnall

#### Reference Issues/PRs
dependent on #1129 

Splits the functionality of validation/checking and conversion into two separate packages in utils, tidies up file naming, moves test example generation to data_gen

2024-02-07 14:15 UTC, chrisholder requested changes

2024-02-07 14:15 UTC, chrisholder commented on aeon/utils/conversion/_convert_collection.py
> +    """Hierarchy of preference for internal supported types for equal length."""
Public function without parameter docs maybe should be private?

2024-02-07 14:15 UTC, chrisholder commented on aeon/utils/conversion/_convert_collection.py
> +def resolve_unequal_length_inner_type(inner_type):
Public function without parameter docs maybe should be private?

2024-02-07 14:15 UTC, chrisholder commented on aeon/utils/validation/_check_collection.py
> +    X : valid collection data structure
Parameter should have type and description on next line

2024-02-07 14:15 UTC, chrisholder commented on aeon/utils/validation/_check_collection.py
> +    X : data structure.
Parameter should have type and description on next line

2024-02-07 14:15 UTC, chrisholder commented on aeon/utils/validation/_check_collection.py
> +    int : number of cases
Return description should be on next line

2024-02-07 14:15 UTC, chrisholder commented on aeon/utils/validation/_check_collection.py
> +    input_type : string, one of COLLECTIONS_DATA_TYPES
Return description should be on next line

2024-02-07 14:15 UTC, chrisholder commented on aeon/utils/validation/_check_collection.py
> +    ValueError if
Dont need the if should just be ValueError

2024-02-07 14:15 UTC, chrisholder commented on aeon/utils/validation/_check_collection.py
> +    ValueError if input_type equals "dask_panel" or not in COLLECTIONS_DATA_TYPES.
Dont need the if and description on new line

2024-02-07 14:15 UTC, chrisholder commented on aeon/utils/validation/_check_collection.py
> +    X : data structure.
Parameter should have type and description on next line

2024-02-07 14:15 UTC, chrisholder commented on aeon/utils/validation/_check_collection.py
> +    boolean: True if all series in X are equal length, False otherwise
Return description should be on new line

2024-02-07 14:15 UTC, chrisholder commented on aeon/utils/validation/_check_collection.py
> +    X : data structure.
Parameter should have type and description on next line

2024-02-07 14:15 UTC, chrisholder commented on aeon/utils/validation/_check_collection.py
> +    ValueError if input_type equals "dask_panel" or not in COLLECTIONS_DATA_TYPES.
Remove the If and description should be on new line

2024-02-07 14:15 UTC, chrisholder commented on aeon/utils/validation/_check_collection.py
> +    X : data structure.
Parameter should have type and description on next line

2024-02-07 14:15 UTC, chrisholder commented on aeon/utils/validation/_check_collection.py
> +    boolean: True if all series in X are equal length, False otherwise
Return description should be on new line

2024-02-07 14:15 UTC, chrisholder commented on aeon/utils/validation/_check_collection.py
> +    ValueError if input_type not in COLLECTIONS_DATA_TYPES.
Remove if and description on new line

2024-02-07 14:15 UTC, chrisholder commented on aeon/base/_base_collection.py
>          X : data structure
Sometimes the docs say 'data strucuture' sometimes day 'valid data structure'.

IMO I dont think personally saying data sturcutre is a good definition of a type. May as well just label it as type 'Any' since it can be Any type

2024-02-07 14:15 UTC, chrisholder commented on aeon/testing/utils/data_gen/_collection.py
> +    return_y: bool = True,
Need to add parameter docstring for new param

2024-02-07 14:15 UTC, chrisholder commented on aeon/testing/utils/data_gen/_collection.py
> +) -> Union[np.ndarray, Tuple[np.ndarray, np.ndarray]]:
Need to update return docstring if this has changed

2024-02-07 14:15 UTC, chrisholder commented on aeon/testing/utils/data_gen/_collection.py
> +) -> Union[np.ndarray, Tuple[np.ndarray, np.ndarray]]:
Update return docstring

2024-02-07 14:15 UTC, chrisholder commented on aeon/testing/utils/data_gen/_collection.py
> +    return_y: bool = True,
This appears in a different order to make_example_3d_numpy (it's last for that) may want to make it consistent for ease of use

2024-02-07 14:15 UTC, chrisholder commented on aeon/testing/utils/data_gen/_collection.py
> +):
return type annotation

2024-02-07 14:15 UTC, chrisholder commented on aeon/testing/utils/data_gen/_series.py
> +):
Type annotation and return type would be nice (not needed)

2024-02-07 14:15 UTC, chrisholder commented on aeon/testing/utils/data_gen/_collection.py
> +def make_example_long_table(n_cases=50, n_channels=2, n_timepoints=20):
Type annotation and return type would be nice (not needed)

2024-02-07 14:15 UTC, chrisholder commented on aeon/utils/validation/_check_collection.py
> +def is_nested_univ_dataframe(X):
Public function with no param docs maybe should be private

2024-02-07 21:39 UTC, TonyBagnall commented on aeon/testing/utils/data_gen/_collection.py
> +    n_instances : int
prefer n_cases, but dont want to refactor here, too many changes

2024-02-08 13:16 UTC, MatthewMiddlehurst reviewed
This is just a refactor and the functionality is the same right? Bit hard to tell from the diff if anything is new or removed.

2024-02-08 13:26 UTC, TonyBagnall commented
> This is just a refactor and the functionality is the same right? Bit hard to tell from the diff if anything is new or removed.

yes its just creating a validation and checking package and moving functionality between.

2024-02-08 15:48 UTC, MatthewMiddlehurst approved these changes

2024-02-08 16:05 UTC, merged