[ENH]convert add dataset
aeon-toolkit/aeon pull request #1139
Opened 2024-02-06 15:47 UTC by TonyBagnall

#### Reference Issues/PRs

#### What does this implement/fix? Explain your changes.

#### Does your contribution introduce a new dependency? If yes, which one?

#### Any other comments?

### PR checklist

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [ ] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

##### For new estimators and functions
- [ ] I've added the estimator to the online [API documentation](https://www.aeon-toolkit.org/en/latest/api_reference.html).

##### For developers with write access
- [ ] Optionally, I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.

2024-02-06 20:31 UTC, dguijo requested changes
Thank you for this tedious work of changing and completing docs. 

The markdown format for the links changes a lot from rst. You can see here the [preview of one document, which is broken at the end](https://github.com/aeon-toolkit/aeon/blob/da1abff4f1c7ef6a24f2c32f6bf1d873bc3f03c1/docs/developer_guide/continuous_integration.md) 

I don't mind doing this if you want, let me know. 

Thank you again! Hard and thorough work :)

2024-02-06 20:31 UTC, dguijo commented on docs/developer_guide/continuous_integration.md
>  `development version <https://www.aeon-toolkit.org/en/stable/installation.html>`__
Be careful with links if you include them inside a code block. For example, this one does not create an hyperlink.

2024-02-06 20:31 UTC, dguijo commented on docs/developer_guide/continuous_integration.md
> +``_pre-commit: <https://pre-commit.com>`
Same here, this is shown as: 

``_pre-commit: <https://pre-commit.com>` 

and should be: 

`pre-commit`: <https://pre-commit.com>

or better:

[`pre-commit`](https://pre-commit.com)

2024-02-06 20:31 UTC, dguijo commented on docs/developer_guide/continuous_integration.md
>  We use `pre-commit`_ for code quality checks (a process we also refer to as "linting" checks).
remove the "_".

2024-02-06 20:31 UTC, dguijo commented on docs/developer_guide/continuous_integration.md
>  `development version <https://www.aeon-toolkit.org/en/stable/installation.html>`__
Now it is shown as:

`development version <https://www.aeon-toolkit.org/en/stable/installation.html>`__

while it should be:

`development version` <https://www.aeon-toolkit.org/en/stable/installation.html> 

or better:

[`development version`](https://www.aeon-toolkit.org/en/stable/installation.html)

2024-02-06 20:31 UTC, dguijo commented on docs/developer_guide/continuous_integration.md
>  For a detailed guide on code quality and linting for developers, see :ref:`coding_standards`.
The :ref:`coding_standards` should be:

[`coding_standards`](https://github.com/aeon-toolkit/aeon/blob/main/docs/developer_guide/coding_standards.rst)

2024-02-06 20:31 UTC, dguijo commented on docs/developer_guide/continuous_integration.md
>  We use `pytest <https://docs.pytest.org/en/latest/>`__ for unit testing.
[`pytest`](https://docs.pytest.org/en/latest/) and remove the __

2024-02-06 21:31 UTC, TonyBagnall commented
thanks david, the links need reformatting

2024-02-06 21:57 UTC, TonyBagnall commented
@dguijo I've gone through catching most, if you get a chance tomorrow to check through please feel free to jump in and correct it.

2024-02-07 08:53 UTC, dguijo requested changes
What a hard job, Tony. Some of the unresolved comments that I left yesterday should be done. Thank you!

2024-02-07 08:53 UTC, dguijo commented on docs/developer_guide/add_estimators.md
> +4.  run the ``aeon`` test suite and/or the ``check_estimator`` utility (see [here](https://www.aeon-toolkit.org/en/latest/developer_guide/add_estimators.html#using-the-check-estimator-utility)
missing ")" at the end of the link. There should be two, one for the hyperref and the other one for the (see here)

2024-02-07 08:53 UTC, dguijo commented on docs/developer_guide/coding_standards.md
> +*  the [PEP8](https://www.python.org/dev/peps/pep-0008/>) coding guidelines. A
The link does not work. remove the ">".

2024-02-07 08:53 UTC, dguijo commented on docs/developer_guide/coding_standards.md
> +* [flake8)(https://flake8.pycqa.org/en/latest/) with a ``max_line_length=88`` and
It should be [flake8](https://flake8.pycqa.org/en/latest/)

2024-02-07 08:53 UTC, dguijo commented on docs/developer_guide/coding_standards.md
> +[setup.cfg](https://github.com/aeon-toolkit/aeon/blob/main/setup.cfg).
can't find setup.cfg. Not sure where it is or even if it exists.

2024-02-07 08:53 UTC, dguijo commented on docs/developer_guide/coding_standards.md
> +-  Check out our `[glossary](https://www.aeon-toolkit.org/en/stable/glossary.html).
it should be:

[`glossary`](https://www.aeon-toolkit.org/en/stable/glossary.html).

2024-02-07 08:53 UTC, dguijo commented on docs/developer_guide/coding_standards.md
All this is duplicated. Consider removing. If you think it is important here as well, please, remove the setup.cfg as it does not exist.

2024-02-07 08:53 UTC, dguijo commented on docs/developer_guide/continuous_integration.md
> +[pre-commit:](<https://pre-commit.com)
remove the <

2024-02-07 08:53 UTC, dguijo commented on docs/developer_guide/continuous_integration.md
> +standards such as a common `coding style <#Coding-style>`__.
Don't know where this ref should redirect. Also, remove the two__ at the end.

2024-02-07 08:53 UTC, dguijo commented on docs/developer_guide/continuous_integration.md
> +   [nstallation instructions](https://www.aeon-toolkit.org/en/latest/installation.html).
installation

2024-02-07 08:53 UTC, dguijo commented on docs/developer_guide/continuous_integration.md
> +We use `coverage`_, the `pytest-cov`_ plugin, and `codecov`_ for test coverage.
Remove the _ behind coverage, pytest-cov and codecov.

2024-02-07 08:53 UTC, dguijo commented on docs/developer_guide/continuous_integration.md
> +[pytest-cov:](https://github.com/pytest-dev/pytest-cov)
Remove the ":" and introduce a new line between links. If not, they are all shown in the same line.

2024-02-07 08:53 UTC, dguijo commented on docs/developer_guide/continuous_integration.md
> +| GitHub Actions | Build/test/distribute on Linux, MacOS and Windows, run code quality checks | [`.github/workflows/`](https://github.com/aeon/skti/me/blob/main/.github/workflows/) |
The link should be: 

https://github.com/aeon-toolkit/aeon/tree/main/.github/workflows

2024-02-07 08:53 UTC, dguijo commented on docs/developer_guide/continuous_integration.md
> +| Read the Docs | Build/deploy documentation | [`.readthedocs.yml`](https://github.com/alan-turing-institute/aeon/blob/main/.github/workflows/code-quality.yml) |
The link should be: 

https://github.com/aeon-toolkit/aeon/blob/main/.readthedocs.yml

2024-02-07 08:53 UTC, dguijo commented on docs/developer_guide/continuous_integration.md
> +| Codecov       | Test coverage         | [`.codecov.yml`](https://github.com/aeon/aeon/blob/main/.codecov.yml), [`.coveragerc`](https://github.com/alan-turing-institute/aeon/blob/main/.coveragerc) |
The links should be:

https://github.com/aeon-toolkit/aeon/blob/main/.codecov.yml

https://github.com/aeon-toolkit/aeon/blob/main/.coveragerc

2024-02-07 08:53 UTC, dguijo commented on docs/developer_guide/continuous_integration.md
> +[build_tools](https://github.com/aeon-toolkit/aeon/tree/main/build_tools>).
Don't know where this folder is. Consider removing :)

2024-02-07 08:53 UTC, dguijo commented on docs/developer_guide/continuous_integration.md
> +1. Install the development version of aeon with developer dependencies:
`aeon`

2024-02-07 08:53 UTC, dguijo commented on docs/developer_guide/continuous_integration.md
> +   This installs an editable [development version](https://pip.pypa.io/en/stable/reference/pip_install/#editable-installs>)
The link now should be: 

https://pip.pypa.io/en/stable/topics/local-project-installs/#editable-installs

2024-02-07 08:53 UTC, dguijo commented on docs/developer_guide/dependencies.md
> +.. note::
Remove this line?

2024-02-07 08:53 UTC, dguijo commented on docs/developer_guide/dependencies.md
> +- `pyproject.toml`, adding the dependency or version bounds in the `dependencies` dependency set. ([pyproject.toml](https://github.com/aeon-toolkit/aeon/blob/main/pyproject.toml))
Include the link in the first appearance of pyproject.toml

2024-02-07 08:53 UTC, dguijo commented on docs/developer_guide/dependencies.md
> +- `pyproject.toml`, adding the dependency or version bounds in the `dev` dependency set. ([pyproject.toml](https://github.com/aeon-toolkit/aeon/blob/main/pyproject.toml))
Include the link in the first appearance of pyproject.toml

2024-02-07 08:53 UTC, dguijo commented on docs/developer_guide/documentation.md
> +`aeon's`` documentation standards include:
`aeon's` , remove one `

2024-02-07 08:53 UTC, dguijo commented on docs/developer_guide/documentation.md
> +[NumPy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html>).
Remove the > at the end of the link.

2024-02-07 08:53 UTC, dguijo commented on docs/developer_guide/documentation.md
>  aeon uses the numpydoc_ Sphinx extension and follows
`numpydoc`
remove the _

2024-02-07 08:53 UTC, dguijo commented on docs/developer_guide/documentation.md
>  - Mathematical details of a code object or other important implementation details (using ..math or :math:`` functionality)
Missing ``??

2024-02-07 08:53 UTC, dguijo commented on docs/developer_guide/testing_framework.md
> +* "package level": testing interface compliance with the ``BaseObject`` and ``BaseEstimator`` specifications, in ``tests/test_all_estimators.py``
maybe better to use bold **package level** ? 

Same for **module level** and **low level**

2024-02-07 09:16 UTC, TonyBagnall commented on docs/developer_guide/documentation.md
>  - Mathematical details of a code object or other important implementation details (using ..math or :math:`` functionality)
happy if you want to jump in and just correct, may be quicker?

2024-02-07 11:13 UTC, hadifawaz1999 requested changes
Thanks @TonyBagnall , can you for update the base deep part of the diagram with the fixed version we did ? the old one says BaseDeepClusterer 3 times
basically use this one:
![image](https://github.com/aeon-toolkit/aeon/assets/54309336/ff44db36-b20a-43e6-a5a6-0476065ecf22)

instead of this one:
![image](https://github.com/aeon-toolkit/aeon/assets/54309336/453b66ee-19a4-4c4e-bfbf-d146d7c95318)

2024-02-07 12:31 UTC, hadifawaz1999 approved these changes
lgtm !

2024-02-07 12:50 UTC, merged