[DOC] API tidy
aeon-toolkit/aeon pull request #1140
Opened 2024-02-06 18:18 UTC by TonyBagnall

Update and tidy up the API a bit

2024-02-06 20:34 UTC, dguijo requested changes
Just a minor change, Tony. Thank you again!

2024-02-06 20:34 UTC, dguijo commented on docs/api_reference.md
> +api_reference/visualization
The module is named `visualisation`, using UK spelling. Not sure if api should keep the same nomenclature though.

2024-02-06 21:32 UTC, TonyBagnall commented on docs/api_reference.md
> +api_reference/visualization
imagine me getting that wrong

2024-02-07 07:58 UTC, dguijo approved these changes
LGTM Thank you Tony!

2024-02-07 08:00 UTC, merged