[ENH] Loading equal length, no missing values classification problems
aeon-toolkit/aeon pull request #1157
Opened 2024-02-08 18:13 UTC by TonyBagnall

This PR:
1. Fixes #1059 because I have reconfigured tsc.com to return 404 when file not found. 

2. Adapts load_classification to match load_regression, so that the equal length and no missing value variants of problems can be loaded directly from the zip.

3. Adds a note book "data_unequal.ipynb" to demonstrate usage.

Draft until 0.7 is in.

2024-02-29 17:20 UTC, hadifawaz1999 commented
@TonyBagnall does this allow to load discrete version of regression problems using the load_classification or load_regression function ?

and second question, the equal length fix follows the padding zero or the 2nd bake off ? I think we already discussed but completely forgot which is why i am asking here to keep track :)

2024-03-04 12:55 UTC, MatthewMiddlehurst requested changes
Some comments. Please add the new notebook to the examples page. 

We are going to have to go through the API at some point and make sure these functions are all these, I am assuming they are not up to date currently.

2024-03-04 12:55 UTC, MatthewMiddlehurst commented on aeon/datasets/_data_loaders.py
> +    load_no_missing: bool = True,
I still think this should default to False for all functions. In the end its just swapping a bool so not big either way, but IMO it would return the original version by default.

2024-03-04 12:55 UTC, MatthewMiddlehurst commented on build_tools/run_examples.sh
> +  "examples/benchmarking/regression.ipynb"
does this load data from the webpage?

2024-03-23 17:39 UTC, TonyBagnall commented on aeon/datasets/tsc_datasets.py
> +# problem in one directory. You can then set which version through function arguments.
yes

2024-03-23 17:40 UTC, TonyBagnall commented on aeon/datasets/_data_loaders.py
> +    load_no_missing: bool = True,
I think we had a vote on this and it was 3 to 1 to do it this way?

2024-03-23 17:41 UTC, TonyBagnall commented on aeon/datasets/_data_loaders.py
> +                f"correctly formatted.",
picky! :)

2024-03-23 17:50 UTC, TonyBagnall commented on build_tools/run_examples.sh
> +  "examples/benchmarking/regression.ipynb"
yes 
```python
small_problems = [
    "CardanoSentiment",
    "NaturalGasPricesSentiment",
    "Covid3Month",
    "BinanceCoinSentiment",
    "Covid19Andalusia",
]

for problem in small_problems:
    X, y = load_regression(name=problem)
    print(problem, X.shape, y.shape)
```

2024-03-23 18:11 UTC, TonyBagnall commented
> @TonyBagnall does this allow to load discrete version of regression problems using the load_classification or load_regression function ?
> 
> and second question, the equal length fix follows the padding zero or the 2nd bake off ? I think we already discussed but completely forgot which is why i am asking here to keep track :)

loading discrete versions with load_classification is the plan, but I think in future PR. Series padded with mean+small amount of noise

2024-03-23 21:57 UTC, MatthewMiddlehurst commented on aeon/datasets/_data_loaders.py
> +    load_no_missing: bool = True,
I thought someone changed their mind, but I'm not going to fight for it if others agree. 

Think @baraline @hadifawaz1999 were part of the discussion?

2024-03-24 22:46 UTC, baraline commented on aeon/datasets/_data_loaders.py
> +    load_no_missing: bool = True,
Yes, I remember the debate a bit. It boiled down to the fact that many of the original problem that were unequal or missing have now been used in benchmarks in these “standardized” form, right ? So returning these version by default was the rationale behind this change (and maybe other reasons ?)

2024-03-25 06:30 UTC, hadifawaz1999 commented on aeon/datasets/_data_loaders.py
> +    load_no_missing: bool = True,
Yes i remember this discussion, my reasoning behind being with setting them to True is based on default behavior to always follow the bake off results

2024-03-25 18:31 UTC, TonyBagnall commented on aeon/datasets/_data_loaders.py
> +    load_no_missing: bool = True,
my thinking is that if we add standard unequal length versions for current equal length, the behaviour between datasets will be inconsistent

2024-03-26 12:45 UTC, MatthewMiddlehurst approved these changes

2024-03-26 13:43 UTC, hadifawaz1999 approved these changes
happy with this !

2024-03-26 15:18 UTC, merged