[ENH] Changes to `BaseClassifier` and `BaseRegressor`
aeon-toolkit/aeon pull request #1200
Opened 2024-02-18 00:02 UTC by MatthewMiddlehurst

Updates `BaseClassifier` and `BaseRegressor`. For the most part this is just adding docs and updating regressor functionality to be similar to that in classification. This probably requires additional tests to be added, but for now it just includes the base class changes.

`BaseClassifier`:
- docstring updates
- adds defaults to certain attributes in `__init__`
- adds `_check_y` to score (without updating `n_classes` etc.)
- removes (IMO) redundant `get_test_params` overload

`BaseRegressor`:
- docstring updates to fit the style of `BaseClassifier`
- adds defaults to certain attributes in `__init__`
- deprecates the * overload similar to classification, pipeline to follow
- adds `fit_predict` and associated methods (i.e. `_fit_setup`) similar to classification
- adds `_check_y` to score
- adds to `_check_y` i.e. using `type_of_target(y)`

Can add or remove from this PR if its too big.

2024-02-19 22:28 UTC, hadifawaz1999 requested changes
LGTM, just that one comment that actually is valid for many places in the docstrings, unless am mistaken, let me know

2024-02-19 22:28 UTC, hadifawaz1999 commented on aeon/classification/base.py
> +            2D array of shape ``(n_cases, n_classes)`` - predicted class probabilities
I think here it should be ``n_instances, n_classes`` to stay consistent with the rest of the doc, same goes for the predict_proba function, unless it was put like this on purpose

2024-02-19 22:49 UTC, dguijo reviewed
Thank you Matt for this PR. Good job. 

Just some minor comments. Thank you!

2024-02-19 22:49 UTC, dguijo commented on aeon/classification/base.py
> +        probabilities: np.ndarray
sorry for being picky, but there should be an space between probabilities and :

2024-02-19 22:49 UTC, dguijo commented on aeon/regression/base.py
>  __author__ = ["MatthewMiddlehurst", "TonyBagnll", "mloning", "fkiraly"]
TonyBagnall, though I think we are getting rid of all of this `__author__` stuff.

2024-02-19 22:49 UTC, dguijo commented on aeon/regression/base.py
>          X : np.ndarray
I was going to leave you a message in the BaseClassifier. There you used "Train data", and here you use the type np.ndarray. 

I'm not sure about the best way, but maybe saying something like `X : np.ndarray or list` may be better. 

Not sure if there is a better nomenclature for when you have two possible options.

2024-02-19 22:49 UTC, dguijo commented on aeon/regression/base.py
>          X : np.ndarray
same here.

2024-02-19 22:49 UTC, dguijo commented on aeon/regression/base.py
>          X : np.ndarray
Not going to write more comments related to this issue to avoid overloading this PR :)

2024-02-19 22:49 UTC, dguijo commented on aeon/regression/base.py
>          return r2_score(y, self.predict(X))
I'm not sure if it is just me or not. But I don't like R2 as the score default measure for regression. I prefer MSE, RMSE or MAE, which are more descriptive imho. Not sure if you aim to change this in this PR though.

2024-02-23 11:47 UTC, MatthewMiddlehurst commented on aeon/classification/base.py
> +            2D array of shape ``(n_cases, n_classes)`` - predicted class probabilities
Good spot. This is kinda inconsistent everywhere, but I have swapped it to `n_cases` for the base classes. 

In the same file there is the method `get_n_cases` and the metadata dict use `n_cases` as a key, so it would be odd to deviate from that IMO. Would have to decide which one to use in a larger conversation.

2024-02-23 11:49 UTC, MatthewMiddlehurst commented on aeon/regression/base.py
>  __author__ = ["MatthewMiddlehurst", "TonyBagnll", "mloning", "fkiraly"]
yeah gonna leave it for now to avoid conflicts 🙂

2024-02-23 11:57 UTC, MatthewMiddlehurst commented on aeon/regression/base.py
>          X : np.ndarray
Included `or list`. Will keep the private methods as they are, as the internal datatype can be other stuff.

2024-02-23 11:57 UTC, MatthewMiddlehurst commented on aeon/regression/base.py
>          return r2_score(y, self.predict(X))
swapped to MSE

2024-02-26 07:29 UTC, dguijo approved these changes
LGTM! Thank you Matt! Good work :)

2024-02-26 13:04 UTC, hadifawaz1999 approved these changes
LGTM !

2024-02-27 12:12 UTC, TonyBagnall approved these changes

2024-02-27 12:13 UTC, TonyBagnall commented
looks good, we should start populating the maintainers maybe though?

2024-02-27 12:36 UTC, MatthewMiddlehurst commented
Agreed, but wanted to do it in a separate PR

2024-02-27 12:36 UTC, merged