[ENH] Refactored  _TestRegressor in regression testing module to be a MockRegressor in testing/mock_estimators
aeon-toolkit/aeon pull request #1213
Opened 2024-02-20 21:54 UTC by tvilight4

solves  #1171
I have refactored _TestRegressor in regression testing module to be a MockRegressor in testing/mock_estimators.

Tasks done:
1. I created a file named  _mock_regressors.py in aeon/testing/mock_estimators. 
2. Renamed the class names in accordance to the pattern of naming of other classes and added them to _mock_regressors.py.
3. Updated the aeon/testing/mock_estimators/_ _init_ _.py  file also .

Please let me know if any more changes are required,
PR checklist:
For all contributions

- [ ] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc).

- [x] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

2024-02-23 13:42 UTC, MatthewMiddlehurst commented
Hi @tvilight4, thanks for the PR.

It appears to be failing due to the random values. Would it be possible to add a `random_state` parameter to the estimators?

2024-02-23 13:43 UTC, MatthewMiddlehurst commented
Also, it would be good to remove the previous test estimators if there are to replace them.

2024-02-23 16:11 UTC, tvilight4 commented
@MatthewMiddlehurst Thanks for the inputs I will make the changes and update the same.

2024-02-26 12:05 UTC, MatthewMiddlehurst commented on aeon/testing/mock_estimators/_mock_regressors.py
> +        self.random_state = random_state
The current error appears to be because there is no super call for the base class, I think. At the end of the `__init__` there should be a `super().__init__()`

2024-02-27 18:52 UTC, tvilight4 commented on aeon/testing/mock_estimators/_mock_regressors.py
> +        return rng.random(size=(len(X)))
@MatthewMiddlehurst thanks I will resolve this a nd update the pr within 12 to 15 hrs.

2024-02-29 20:24 UTC, tvilight4 commented
@MatthewMiddlehurst  I had closed the PR by mistake while I  was trying to solve the issue related to isort error in the pre commit(which was the sole error i the commit at that time ) , but now the precomit is showing a few more errors , I am working on them.

2024-02-29 21:02 UTC, MatthewMiddlehurst commented
@tvilight4 if you install pre-commit (see the [dev install guide](https://www.aeon-toolkit.org/en/latest/developer_guide/dev_installation.html)), most of these should be automatically taken care of when the hooks are run on commiting.

2024-03-03 20:09 UTC, AnonymousCodes911 commented on aeon/utils/validation/tests/test_collection.py
> +from aeon.utils.validation._check_collection import (
@tvilight4 , I think as per #1179, this should be 
`from aeon.utils import COLLECTIONS_DATA_TYPES `<br>
`from aeon.utils.validation.collection import`
See [this](https://github.com/aeon-toolkit/aeon/pull/1179/files#diff-3144bbc5f2b304d07ccdbe3cfe8b68b29b8496414694ad5f0b04bd0e58b9857e)

2024-03-04 11:33 UTC, MatthewMiddlehurst requested changes
Good job, thanks for implementing these. I made a quick change to fix the links.

I think the only remaining changes left are to remove the old test regressors and use these instead.

If you want we can merge these and that can be done in a separate PR, but I think it would be best to do it here.

2024-03-04 16:26 UTC, tvilight4 commented
@MatthewMiddlehurst @AnonymousCodes911 , Thanks for reviewing the PR.
I will make the required changes by tomorrow and push them.

2024-03-14 11:30 UTC, MatthewMiddlehurst approved these changes

2024-03-14 11:35 UTC, MatthewMiddlehurst commented
Ok thats great. Will leave this for a bit then merge if there are no other comments. Feel free to expand on this is another PR whenever is convenient to you.

Is `isort` making changes when you commit but then those are being immediately reverted? Sounds a bit strange if so, may have to manually make the changes prior to committing if it persists.

2024-03-15 16:50 UTC, merged

2024-03-15 18:02 UTC, tvilight4 commented
> Ok thats great. Will leave this for a bit then merge if there are no other comments. Feel free to expand on this is another PR whenever is convenient to you.
> 
> Is `isort` making changes when you commit but then those are being immediately reverted? Sounds a bit strange if so, may have to manually make the changes prior to committing if it persists.
yes

2024-03-15 18:04 UTC, tvilight4 commented
> @all-contributors add @tvilight4 for code

Thanks !!!