[ENH] Add MLPRegressor
aeon-toolkit/aeon pull request #1214
Opened 2024-02-21 13:59 UTC by aadya940

#### Reference Issues/PRs

Related to #1198 
Fix #1217 

#### What does this implement/fix? Explain your changes.

1. Create _mlp.py Module in aeon.regression
2. Call MLPNetwork
3. Replace Ouput-Layer Activation by "linear"
4. Update Loss to "mse"
5. Update docstrings

2024-02-21 15:51 UTC, hadifawaz1999 requested changes
thanks for taking care of this, just a few comments

2024-02-21 15:51 UTC, hadifawaz1999 commented on aeon/regression/deep_learning/_mlp.py
> +        X : np.ndarray of shape = (n_instances (n), n_channels (d), series_length (m))
could you replace the information to (n_instances, n_channels, n_timepoints)

2024-02-21 15:51 UTC, hadifawaz1999 commented on aeon/regression/deep_learning/_mlp.py
> +            The training output data.
here it should be "The training data target values" for the y parameter

2024-02-21 15:51 UTC, hadifawaz1999 commented on aeon/regression/deep_learning/_mlp.py
> +    """Multi Layer Perceptron Network (MLP).
can you re-arrange the docstring so that the order of the documentation of each parameter is in the same order as they are listed inside __init__ ?

2024-02-21 16:22 UTC, aadya940 commented
@hadifawaz1999 The docstring for `callback` is not present in both `MLPClassifier` as well as `MLPRegressor`. Should I add it to both?

2024-02-21 19:18 UTC, aadya940 commented on aeon/regression/deep_learning/_mlp.py
@AnonymousCodes911 No, the reason being `convert_y_to_keras` converts `y` to a One-Hot Array that is a Mutually Exclusive Array of `y` values typically used for categorical data in classification. We don't need it in Regression!

2024-02-24 16:55 UTC, hadifawaz1999 commented
> @hadifawaz1999 The docstring for `callback` is not present in both `MLPClassifier` as well as `MLPRegressor`. Should I add it to both?

Yes it would be great if you add it thanks ! could you also take care of the comments i left above ?

2024-02-24 16:56 UTC, hadifawaz1999 requested changes
can you merge with main to apply the network module changes for the random_state parameter ?

2024-02-25 08:07 UTC, aadya940 commented
@hadifawaz1999 I've added docstrings for `callbacks` in `regression._mlp` as well as `classification._mlp` as well as merged the changes for `random_state` and also resolved the review comments. Thanks :-)

2024-02-29 17:30 UTC, hadifawaz1999 approved these changes
LGTM! thanks

2024-02-29 17:30 UTC, merged