[ENH] Add IndividualLITERegressor
aeon-toolkit/aeon pull request #1221
Opened 2024-02-21 20:07 UTC by aadya940

Closes #1219 

### What does this implement/fix? Explain your changes.

  1.Create _lite_time.py Module in aeon.regression
  2. Call LITENetwork
  3. Replace Ouput-Layer Activation by "linear"
  4. Update Loss to "mse"
  5. Update docstrings

2024-03-02 17:08 UTC, MatthewMiddlehurst reviewed
Just one comment for now, @hadifawaz1999 would know better if these are as expected.

2024-03-02 17:08 UTC, MatthewMiddlehurst commented on aeon/regression/deep_learning/_lite_time.py
> +        self.classifers_ = []
not classifiers

2024-03-02 17:27 UTC, hadifawaz1999 requested changes
Thanks for this, just some comments to be fixed

2024-03-02 17:27 UTC, hadifawaz1999 commented on aeon/regression/deep_learning/_lite_time.py
> +    n_classifiers : int, default = 5,
its n_regressors not n_classifiers

2024-03-02 17:27 UTC, hadifawaz1999 commented on aeon/regression/deep_learning/_lite_time.py
> +        will be set to accuracy as default if None
will be set to "mean_squared_error" instead

2024-03-02 17:27 UTC, hadifawaz1999 commented on aeon/regression/deep_learning/_lite_time.py
> +    random_state : int, default = 0
random_state default to None  not 0

2024-03-02 17:27 UTC, hadifawaz1999 commented on aeon/regression/deep_learning/_lite_time.py
> +            cls = IndividualLITERegressor(
rgs instead of cls
cls is for classifier and rgs for regressor

2024-03-02 17:27 UTC, hadifawaz1999 commented on aeon/regression/deep_learning/_lite_time.py
> +        for cls in self.regressors_:
rgs

2024-03-02 17:27 UTC, hadifawaz1999 commented on aeon/regression/deep_learning/_lite_time.py
> +            cls.fit(X, y)
rgs

2024-03-02 17:27 UTC, hadifawaz1999 commented on aeon/regression/deep_learning/_lite_time.py
> +    """Single LITETime Regressor.
single LITE regressor, LITETime is the ensemble of LITE

2024-03-02 17:27 UTC, hadifawaz1999 commented on aeon/regression/deep_learning/_lite_time.py
> +    random_state : int, default = 0
random_state default to None not 0

2024-03-02 17:27 UTC, hadifawaz1999 commented on aeon/regression/deep_learning/_lite_time.py
> +    metrics : keras metrics, default = None,
same comment on the metrics as before

2024-03-02 17:27 UTC, hadifawaz1999 commented on aeon/regression/deep_learning/_lite_time.py
> +            metrics = ["accuracy"]
metric should be default to mean_squared_error

2024-03-02 18:20 UTC, aadya940 commented
Thanks for the Review :-) @MatthewMiddlehurst @hadifawaz1999

2024-03-08 11:14 UTC, MatthewMiddlehurst submitted a review, later dismissed
Looks like @hadifawaz1999 comments have been resolved. I don't see anything noticeably off, but it's not my code 🙂

2024-03-10 15:10 UTC, hadifawaz1999 requested changes
Thanks, it all looks good, last changes are:

1- merge branch main
2- do the changes as we did yesterday in #1292  for the model saving format from hdf5 to keras

2024-03-10 19:18 UTC, aadya940 commented
@hadifawaz1999 Thanks for the Review :-), The changes have been done.

2024-03-12 15:38 UTC, aadya940 commented
Done, Thanks :-) @hadifawaz1999

2024-03-12 18:14 UTC, aadya940 commented
Hey @hadifawaz1999 @MatthewMiddlehurst , The tests are failing in certain python versions but seems to be unrelated to this issue. wdyt?

2024-03-14 10:25 UTC, MatthewMiddlehurst commented
@aadya940 apologies for the late reply, yes we were having a general failure on CI. If you update the branch to main this should be resolved.

2024-03-15 19:17 UTC, hadifawaz1999 approved these changes
LGTM !

2024-03-15 19:17 UTC, merged