[ENH] Updated EncoderRegressor
aeon-toolkit/aeon pull request #1226
Opened 2024-02-23 10:10 UTC by AnonymousCodes911

#### Reference Issues/PRs
fixes: #1218 

#### What does this implement/fix? Explain your changes.
Adapts `EncoderClassifier` to `EncoderRegressor`

#### Does your contribution introduce a new dependency? If yes, which one?

#### Any other comments?
Closes: #1204 

### PR checklist

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [x] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

##### For new estimators and functions
- [ ] I've added the estimator to the online [API documentation](https://www.aeon-toolkit.org/en/latest/api_reference.html).

##### For developers with write access
- [ ] Optionally, I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.

2024-02-24 17:07 UTC, hadifawaz1999 requested changes
Thanks for this. All of the mentioned comments can be solved by comparing FCNClassifier and FCNRegressor as a baseline to know how to create EncodeRegressor

2024-02-24 17:07 UTC, hadifawaz1999 commented on aeon/regression/deep_learning/_encoder.py
> +        metrics=("mean_squared_error",),
metrics should be None by default and then if the user does not change it, we set a value for it when its used inside `_fit`

2024-02-24 17:07 UTC, hadifawaz1999 commented on aeon/regression/deep_learning/_encoder.py
> +        y : np.ndarray of shape n
its not class labels its target values

2024-02-24 17:07 UTC, hadifawaz1999 commented on aeon/regression/deep_learning/_encoder.py
> +        # changed n_classes to 1
no need just remove the n_classes parameter

2024-02-24 17:07 UTC, hadifawaz1999 commented on aeon/regression/deep_learning/_encoder.py
> +        activation="linear",
activation is the activation of the hidden layers, in the case of regression we add a new parameter output_activation and we set it to linear by default

2024-02-24 17:07 UTC, hadifawaz1999 commented on aeon/regression/deep_learning/_encoder.py
> +        X : np.ndarray of shape = (n_instances (n), n_channels (d), series_length (m))
can you change this to (n_instances, n_channels, n_timepoints)

2024-02-24 17:07 UTC, hadifawaz1999 commented on aeon/regression/deep_learning/_encoder.py
> +            random_state=self.random_state,
can you merge with main ? we just got in the removal of random_state in networks module

2024-02-24 17:07 UTC, hadifawaz1999 commented on aeon/regression/deep_learning/_encoder.py
> +    Parameters
a lot of parameters are missing from the docstring

2024-02-26 11:29 UTC, AnonymousCodes911 commented on aeon/regression/deep_learning/_encoder.py
> +    Parameters
Added the missing parameters

2024-02-26 11:30 UTC, AnonymousCodes911 commented on aeon/regression/deep_learning/_encoder.py
> +        y : np.ndarray of shape n
changed `class labels` to `Target Value`

2024-02-26 11:31 UTC, AnonymousCodes911 commented on aeon/regression/deep_learning/_encoder.py
> +    def build_model(self, input_shape, n_classes, **kwargs):
removed the parameter `n_classes`

2024-02-26 11:32 UTC, AnonymousCodes911 commented on aeon/regression/deep_learning/_encoder.py
> +        n_classes : int
removed the definition of `n_classes` from the documentation.

2024-02-26 11:33 UTC, AnonymousCodes911 commented on aeon/regression/deep_learning/_encoder.py
> +        metrics=("mean_squared_error",),
changed metrics to `None`

2024-02-26 11:34 UTC, AnonymousCodes911 commented on aeon/regression/deep_learning/_encoder.py
> +        # changed n_classes to 1
removed the `n_classes` parameter

2024-02-26 11:34 UTC, AnonymousCodes911 commented on aeon/regression/deep_learning/_encoder.py
> +        activation="linear",
added the new parameter `output_activation`

2024-02-26 11:35 UTC, AnonymousCodes911 commented on aeon/regression/deep_learning/_encoder.py
> +        X : np.ndarray of shape = (n_instances (n), n_channels (d), series_length (m))
done as directed.

2024-02-26 11:36 UTC, AnonymousCodes911 commented on aeon/regression/deep_learning/_encoder.py
> +            random_state=self.random_state,
removed `random_state`

2024-03-10 15:08 UTC, hadifawaz1999 requested changes
Thanks it all looks good now, last thing to modify is:

1- merge branch main
2- do the changes on model saving as we did yesterday in #1292  from hdf5 to keras format

2024-03-10 15:40 UTC, AnonymousCodes911 commented on aeon/regression/deep_learning/_encoder.py
@hadifawaz1999 , did the needful ! thank you!

2024-03-10 16:06 UTC, hadifawaz1999 commented on aeon/regression/deep_learning/_encoder.py
Could you merge main branch with this one ? thanks

2024-03-10 16:26 UTC, AnonymousCodes911 commented on aeon/regression/deep_learning/_encoder.py
its already up to date!

2024-03-10 17:09 UTC, hadifawaz1999 approved these changes
lgtm !

2024-03-10 17:09 UTC, merged