[ENH] Add implementation for sbd distance (from k-Shape)
aeon-toolkit/aeon pull request #1231
Opened 2024-02-23 16:09 UTC by CodeLionX

> [!WARNING]
> will be filled out soon

#### What does this implement/fix? Explain your changes.

#### Does your contribution introduce a new dependency? If yes, which one?

#### Any other comments?

### PR checklist

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [ ] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

##### For new estimators and functions
- [ ] I've added the estimator to the online [API documentation](https://www.aeon-toolkit.org/en/latest/api_reference.html).

##### For developers with write access
- [ ] Optionally, I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.

2024-02-26 22:58 UTC, chrisholder requested changes
Looks great! Great code nicely formatted, fantastic docs and great job figuring the tests out! Two very minor changes just to pass through arguments if used with the utility functions.

2024-02-26 22:58 UTC, chrisholder commented on aeon/distances/_distance.py
> +        return sbd_distance(x, y)
You probably want to pass through the standardize argument:
`return sbd_distance(x, y, kwargs.get('standardize', True)`

2024-02-26 22:58 UTC, chrisholder commented on aeon/distances/_distance.py
> +        return sbd_pairwise_distance(x, y)
Again you probably want to pass through the standardize argument:
`return sbd_distance(x, y, kwargs.get('standardize', True)`

2024-02-27 08:53 UTC, CodeLionX commented on aeon/distances/_distance.py
> +        return sbd_distance(x, y)
You are absolutely right. I completely missed that, thanks!

2024-02-27 11:29 UTC, chrisholder approved these changes

2024-02-27 11:31 UTC, merged