Learning Shapelet Classifier
aeon-toolkit/aeon pull request #1247
Opened 2024-02-25 14:27 UTC by itsdivya1309

#### Reference Issues/PRs
Fixes #1246 

#### What does this implement/fix? Explain your changes.

#### Does your contribution introduce a new dependency? If yes, which one?

#### Any other comments?

### PR checklist

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [ ] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

##### For new estimators and functions
- [ ] I've added the estimator to the online [API documentation](https://www.aeon-toolkit.org/en/latest/api_reference.html).

##### For developers with write access
- [ ] Optionally, I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.

2024-02-29 17:15 UTC, MatthewMiddlehurst commented
Wrappers from other packages need some extra considerations. See `MrSQMClassifier` for an example.

2024-03-14 10:33 UTC, MatthewMiddlehurst reviewed
Some of these errors are quite strange, let me know if you need a hand.

I have updated the branch to the latest version of main since we were having some CI issues.

2024-03-14 10:33 UTC, MatthewMiddlehurst commented on aeon/benchmarking/results_loaders.py
> +    },
We do not have any results uploaded currently, so this does not have to be included.

2024-03-14 11:08 UTC, MatthewMiddlehurst commented
Ah we currently dont support TensorFlow for version 3.8 due to some deprecations and 3.12 because of its recency. Did not think that this would impact tslearn though?

2024-03-17 13:38 UTC, itsdivya1309 commented
> Some of these errors are quite strange, let me know if you need a hand.
> 
> I have updated the branch to the latest version of main since we were having some CI issues.

Sure, I'll try to figure it out.

2024-03-17 13:53 UTC, MatthewMiddlehurst commented
You may have to add it as an additional dependency to the classifier for now in tags. I think SignatureClassifier has an example of a dependency that does not accept all python version

2024-03-19 08:26 UTC, itsdivya1309 commented
@MatthewMiddlehurst I think the examples are failing because we don't have any results for LearningShapelet. How can I resolve it?

2024-03-19 22:52 UTC, MatthewMiddlehurst commented
I think you are correct, we may have to change the notebook. Any thoughts @TonyBagnall?

2024-03-23 12:32 UTC, TonyBagnall commented
yep, I have hard coded it to the ones we have, I can run the LS after this is in and add the results. Hopefully merging once this is in will fix the above

https://github.com/aeon-toolkit/aeon/pull/1331

2024-03-23 13:03 UTC, TonyBagnall commented
hi @itsdivya1309 if you update from main now it should be fine, thanks for doing this. I havent tried running LS for some time, it will be interesting to see how it performs

2024-03-26 09:08 UTC, TonyBagnall reviewed
sorry for how long this has taken. Things you should add 
get_test_params(
which sets the parameters to be really small, to test interface compliance. look at , for example. RDSTClassifier. 

Things that could be done in a subsequent PR: You might want to add a test function to test the locate function and also to add expected results in the test function.

2024-03-26 10:55 UTC, itsdivya1309 commented
> sorry for how long this has taken. Things you should add get_test_params( which sets the parameters to be really small, to test interface compliance. look at , for example. RDSTClassifier.
> 
> Things that could be done in a subsequent PR: You might want to add a test function to test the locate function and also to add expected results in the test function.

Thanks for looking into this, I'll add the get_test_params()

2024-03-28 11:58 UTC, MatthewMiddlehurst requested changes
Looking good, very close to done I feel. Thanks for working on this. Few documentation and testing requests.

2024-03-28 11:58 UTC, MatthewMiddlehurst commented on aeon/classification/shapelet_based/_ls.py
> +
Could you add a bit more documentation here above the parameters, at least mentioning that this is a wrapped for the `tslearn` package.

2024-03-28 11:58 UTC, MatthewMiddlehurst commented on aeon/classification/shapelet_based/_ls.py
> +        time.a
Trailing "a" at the end, typo?

2024-03-28 11:58 UTC, MatthewMiddlehurst commented on aeon/classification/shapelet_based/_ls.py
> +        return {"n_shapelets_per_size": None, "shapelet_length": 0.15}
Generally we want to set these to be fast running parameters. No need to set them if they are the default. I would change `max_iter` to something like 50.

2024-03-28 17:33 UTC, itsdivya1309 commented on aeon/classification/shapelet_based/_ls.py
> +        time.a
Yes :)

2024-03-29 05:08 UTC, itsdivya1309 commented on aeon/classification/shapelet_based/_ls.py
> +        return {"n_shapelets_per_size": None, "shapelet_length": 0.15}
Well `max_iter` does have a default value of 10000, but that would indeed make it slow. So I'll set it to 50.

2024-03-30 14:45 UTC, MatthewMiddlehurst approved these changes
Good work, thanks for implementing my requests.

Don't mind adding to the documentation in a separate PR, up to others.

2024-04-02 18:43 UTC, merged