[MNT] Modified test_base_rocketGPU.py
aeon-toolkit/aeon pull request #1272
Opened 2024-03-02 16:57 UTC by AnonymousCodes911

Refactored the test funcs to use `numpy.testing.assert_array_almost_equal` for more robust testing.

#### Reference Issues/PRs
fixes : #1248

2024-03-02 17:10 UTC, MatthewMiddlehurst commented
Where are the expected results coming from? If it is the output of the GPU rocket then it is not what the issue requested I believe.

2024-03-02 17:31 UTC, hadifawaz1999 requested changes
This is not actually what the issue was mentionning, the idea was to use both Rocket and RocketGPU with the same random seed and on the same dataset and make sure the outputs are the same

2024-03-02 17:34 UTC, AnonymousCodes911 commented
> Where are the expected results coming from? If it is the output of the GPU rocket then it is not what the issue requested I believe.

I misunderstood the issue, apologies for the same, I assumed we had to set an arbitrary seed and test it accordingly. I 'll update the PR at the earliest.

2024-03-04 15:31 UTC, MatthewMiddlehurst commented
This has gotten very confused and should probably start from scratch. If you are confused by the issue contents, please ask for clarification.

There should be:
1. new test function created
2. this function could create and fit a [`Rocket`](https://github.com/aeon-toolkit/aeon/blob/main/aeon/transformations/collection/convolution_based/_rocket.py) and [`ROCKETGPU`](https://github.com/aeon-toolkit/aeon/blob/main/aeon/transformations/collection/convolution_based/rocketGPU/_rocket_gpu.py) transform using the same data, parameters and seed
3. this function should then check if the results are the same

2024-03-04 15:33 UTC, AnonymousCodes911 commented
> This has gotten very confused and should probably start from scratch. If you are confused by the issue contents, please ask for clarification.
> 
> There should be:
> 
> 1. new test function created
> 2. this function could create and fit a [`Rocket`](https://github.com/aeon-toolkit/aeon/blob/main/aeon/transformations/collection/convolution_based/_rocket.py) and [`ROCKETGPU`](https://github.com/aeon-toolkit/aeon/blob/main/aeon/transformations/collection/convolution_based/rocketGPU/_rocket_gpu.py) transform using the same data, parameters and seed
> 3. this function should then check if the results are the same

Got it thank you for the clarification! Apologies for the hassle and confusion!

2024-03-10 15:18 UTC, hadifawaz1999 requested changes
just some comments that should be helpful

2024-03-10 15:18 UTC, hadifawaz1999 commented on aeon/transformations/collection/convolution_based/_rocket.py
> +        n_filters=1000,
in rocket the num_kernels is itself the n_filters, you do not need to add a n_filters parameter

2024-03-10 15:18 UTC, hadifawaz1999 commented on aeon/transformations/collection/convolution_based/rocketGPU/tests/test_base_rocketGPU.py
> +@pytest.mark.parametrize("n_channels", [1, 3])
here you should add, as for the other tests in the same file

`@pytest.mark.skipif(
    not _check_soft_dependencies("tensorflow", severity="none"),
    reason="skip test if required soft dependency not available",
)`

2024-03-10 15:18 UTC, hadifawaz1999 commented on aeon/transformations/collection/convolution_based/rocketGPU/tests/test_base_rocketGPU.py
> +def random_seed():
not sure where this is used, if its not used it should be removed

2024-03-10 15:18 UTC, hadifawaz1999 commented on aeon/transformations/collection/convolution_based/rocketGPU/tests/test_base_rocketGPU.py
> +    rocket_cpu = Rocket(n_filters=n_filters, random_state=random_seed)
could you also set the parameter `normalise` in Rocket to false ? this way we are sure both rocket cpu and gpu take the same version of the dataset

2024-03-10 16:04 UTC, AnonymousCodes911 commented on aeon/transformations/collection/convolution_based/rocketGPU/tests/test_base_rocketGPU.py
> +def random_seed():
![image](https://github.com/aeon-toolkit/aeon/assets/67187480/12f757b3-c1ad-421a-bc03-97bfc7922440)
It was showing this when i tried without this, so i added the fixture is there a way to bypass this?

2024-03-10 16:12 UTC, AnonymousCodes911 commented on aeon/transformations/collection/convolution_based/_rocket.py
> +        n_filters=1000,
Yes you are right!, sorry for the oversight

2024-03-10 16:13 UTC, AnonymousCodes911 commented on aeon/transformations/collection/convolution_based/rocketGPU/tests/test_base_rocketGPU.py
> +@pytest.mark.parametrize("n_channels", [1, 3])
done!, rearranged it

2024-03-10 16:14 UTC, AnonymousCodes911 commented on aeon/transformations/collection/convolution_based/rocketGPU/tests/test_base_rocketGPU.py
> +    rocket_cpu = Rocket(n_filters=n_filters, random_state=random_seed)
done

2024-03-10 16:19 UTC, AnonymousCodes911 commented
after making thee changes, and running `pytest -vv` resulted in : 
![image](https://github.com/aeon-toolkit/aeon/assets/67187480/0a018c5b-aff2-438e-885e-49e40675464b)
is this expected? if not how should we tackle this?

2024-03-19 09:38 UTC, AnonymousCodes911 commented
continued in #1325

2024-03-19 09:38 UTC, closed without merging