[MNT] Cleanup code in aeon.util.conversion module
aeon-toolkit/aeon pull request #1289
Opened 2024-03-08 14:52 UTC by CodeLionX

#### Reference Issues/PRs

None.

#### What does this implement/fix? Explain your changes.

When familiarizing myself with the implementation of `aeon.utils.conversion.convert_collection` for #1287, I found some smelly code and docstrings. Thus, I quickly fixed them.

#### Does your contribution introduce a new dependency? If yes, which one?

No.

### PR checklist

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [x] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

2024-03-10 15:28 UTC, MatthewMiddlehurst commented
Looks like we are testing for a specific error message here, will have to change that as well if the new one is kept.

2024-03-11 17:22 UTC, TonyBagnall requested changes
great, thanks for sorting our smelly code :) Small change on the resolve functions, they are passed lists

2024-03-11 17:22 UTC, TonyBagnall commented on aeon/utils/conversion/_convert_collection.py
> +    inner_types: str
inner_types is actually a list of str

2024-03-11 17:22 UTC, TonyBagnall commented on aeon/utils/conversion/_convert_collection.py
> +    inner_types: str
also a list

2024-03-11 18:02 UTC, TonyBagnall commented
ah also, we just had a discussion about n_cases vs n_instances  n_cases there are 113 matches and n_instances 123! we think we will standardise to n_cases, its a bit shorter :)

2024-03-11 19:05 UTC, TonyBagnall approved these changes

2024-03-12 07:54 UTC, TonyBagnall commented
sorry about the conflict @CodeLionX , we just put in a big refactor to make everything `n_cases` and `n_timepoints`

2024-03-12 09:17 UTC, CodeLionX commented
> ah also, we just had a discussion about n_cases vs n_instances n_cases there are 113 matches and n_instances 123! we think we will standardise to n_cases, its a bit shorter :)

I would prefer `n_instances` because I associate the number of classes or clusters with `n_cases` instead of the number of time series within a dataset. But consistency is even more important to me 👍🏼

I reverted the renaming so that it says `n_cases` now. Please check again.

2024-03-13 20:39 UTC, TonyBagnall approved these changes

2024-03-14 08:28 UTC, CodeLionX commented
I am not allowed to merge, but please go ahead.

2024-03-14 09:30 UTC, merged