[MNT] Distance test refactor
aeon-toolkit/aeon pull request #1294
Opened 2024-03-10 22:09 UTC by chrisholder

#### Reference Issues/PRs

#### What does this implement/fix? Explain your changes.
This PR refactors the distance tests to use the new testing utils for test time series generation. Specifically the '_create_test_distance_numpy' has been removed and where it was called replaced with make_series or make_example_3d_numpy which is consistent with the rest of the package.

#### Does your contribution introduce a new dependency? If yes, which one?

#### Any other comments?
The test results have been updated because new time series were generated compared to the old.

### PR checklist

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [x] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

##### For new estimators and functions
- [x] I've added the estimator to the online [API documentation](https://www.aeon-toolkit.org/en/latest/api_reference.html).
- [x] (OPTIONAL) I've added myself as a `__maintainer__` at the top of relevant files and want to be contacted regarding its maintenance. Unmaintained files may be removed.

##### For developers with write access
- [x] (OPTIONAL) I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.

2024-03-10 22:09 UTC, chrisholder commented on aeon/distances/_distance.py
> +        return minkowski_distance(x, y, kwargs.get("p", 2.0), kwargs.get("w", None))
I also spotted a bug and fixed the utils function call for minkowski_distance

2024-03-11 10:35 UTC, CodeLionX commented on aeon/distances/tests/test_pairwise.py
> +        make_example_3d_numpy(5, 1, 5, random_state=1)[0],
I find this more explicit:
```suggestion
        make_example_3d_numpy(5, 1, 5, random_state=1, return_y=False),
```

2024-03-11 10:41 UTC, CodeLionX commented on aeon/distances/tests/test_pairwise.py
> +        make_series(5, 5, return_numpy=True, random_state=2),
Yes, this creates two multivariate time series as input, but the `pairwise_distance`-functions do not support a single multivariate time series as 2-dim. ndarray. If a 2-dim. ndarray is passed, it is assumed to be a collection of univariate time series:

https://github.com/aeon-toolkit/aeon/blob/93726dc04caa2a83a61553100ac62c9cc8db9104/aeon/distances/_utils.py#L39-L42

2024-03-11 10:44 UTC, CodeLionX commented on aeon/distances/tests/test_pairwise.py
>      )
We should also test for:

```python
X = make_example_3d_numpy(3, 1, 5, random_state=2)[0]
y = make_series(5, 1, return_numpy=True, random_state=1)
```

2024-03-11 10:47 UTC, CodeLionX commented on aeon/distances/tests/test_pairwise.py
> +        make_example_3d_numpy(5, 1, 5, random_state=2)[0],
This creates:

```python
X.shape = (5, 1)    # --reshaped--> (5, 1, 1)
y.shape = (5, 1, 5) # --reshaped--> (5, 1, 5)
```

It is not obvious to me, why we need this test, and why you use `make_series` to create `X`.

2024-03-11 10:48 UTC, CodeLionX commented on aeon/distances/tests/test_pairwise.py
> +        make_example_3d_numpy(5, 5, 5, random_state=2)[0],
Again, `X` is not a multivariate time series, but interpreted as `(5, 1, 5)`. This is compared to `(5, 5, 5)` testing for multivariate time series with different number of channels.

2024-03-11 10:49 UTC, CodeLionX commented on aeon/distances/tests/test_pairwise.py
> +        make_example_3d_numpy(3, 1, 3, random_state=2)[0],
This is an equal-length test `(1, 1, 3)` vs. `(3, 1, 3)`.

2024-03-11 10:50 UTC, CodeLionX commented on aeon/distances/tests/test_pairwise.py
> +        make_series(5, 3, return_numpy=True, random_state=1),
To make it an unequal-length test:
```suggestion
        make_series(3, 5, return_numpy=True, random_state=1),
```

2024-03-11 10:52 UTC, CodeLionX commented on aeon/distances/tests/test_pairwise.py
> +from aeon.distances.tests.test_utils import _make_3d_series
Do we still need `_make_3d_series` or can we replace it as well?

2024-03-11 13:40 UTC, TonyBagnall commented on aeon/distances/tests/test_pairwise.py
> +        make_example_3d_numpy(5, 1, 5, random_state=1)[0],
I agree with @CodeLionX :)

2024-03-11 15:18 UTC, chrisholder commented on aeon/distances/tests/test_pairwise.py
> +        make_example_3d_numpy(5, 1, 5, random_state=1)[0],
So this maybe a crazy reason for doing this: The type hint for the function indicated it returns a tuple always and it was setting off my linter. I will just the type hint of the function as well and add return_y=False.

2024-03-11 15:32 UTC, chrisholder commented on aeon/distances/tests/test_pairwise.py
> +        make_series(5, 5, return_numpy=True, random_state=2),
The intention of passing all of these in different formats is hitting the logic inside pairwise that does the reshaping:

```
    if y is None:
        # To self
        if X.ndim == 3:
            return _msm_pairwise_distance(X, window, independent, c, itakura_max_slope)
        if X.ndim == 2:
            _X = X.reshape((X.shape[0], 1, X.shape[1]))
            return _msm_pairwise_distance(_X, window, independent, c, itakura_max_slope)
        raise ValueError("x and y must be 2D or 3D arrays")
    elif y.ndim == X.ndim:
        # Multiple to multiple
        if y.ndim == 3 and X.ndim == 3:
            return _msm_from_multiple_to_multiple_distance(
                X, y, window, independent, c, itakura_max_slope
            )
        if y.ndim == 2 and X.ndim == 2:
            _x = X.reshape((X.shape[0], 1, X.shape[1]))
            _y = y.reshape((y.shape[0], 1, y.shape[1]))
            return _msm_from_multiple_to_multiple_distance(
                _x, _y, window, independent, c, itakura_max_slope
            )
        if y.ndim == 1 and X.ndim == 1:
            _x = X.reshape((1, 1, X.shape[0]))
            _y = y.reshape((1, 1, y.shape[0]))
            return _msm_from_multiple_to_multiple_distance(
                _x, _y, window, independent, c, itakura_max_slope
            )
        raise ValueError("x and y must be 1D, 2D, or 3D arrays")
```

Here im just using make_series as a way to create a collection univariate (even though I know the function is technically creating a multivariate series). I'll add comments for clarity.

2024-03-11 16:15 UTC, CodeLionX commented on aeon/distances/tests/test_pairwise.py
> +        make_series(5, 5, return_numpy=True, random_state=2),
I get your intention, but I don't know if `make_series` is a good way of achieving this. At least a brief explanation would help with understanding the tests, if we stick to `make_series` for 2d-ndarray input, agreed 👍🏼

2024-03-12 16:53 UTC, CodeLionX requested changes
Nice work and way more clearer tests than before 👍🏼 
I guess, you forgot to actually use/enable the recursive option for all unequal-length tests. I left comments hinting at this just for some files.

2024-03-12 16:53 UTC, CodeLionX commented on aeon/distances/tests/test_utils.py
> +    the time series x[i] = (d, m).
Isn't it rather like this?
```suggestion
    If given a 1d array the time series is reshaped to (1, 1, m). This is so when
    looped over x[i] = (1, m).

    If given a 2d array then the time series is reshaped to (d, 1, m). The dimensions
    are put to the start so the ts can be looped through correctly. When looped over
    the time series x[i] = (1, m).
```

2024-03-12 16:53 UTC, CodeLionX commented on aeon/distances/tests/test_distances.py
> +    x, y, name, distance, expected_result=10, recursive_call=False
I would rename `recursive_call` to `check_xy_permuted` or similar to express the intention behind the _recursion_.

2024-03-12 16:53 UTC, CodeLionX commented on aeon/distances/tests/test_distances.py
>          _expected_distance_results[dist["name"]][3],
Did you forget to enable `recursive_call` (`check_xy_permuted`) for the unequal-length tests?

2024-03-12 16:53 UTC, CodeLionX commented on aeon/distances/tests/test_alignment_path.py
> +    recursive_call=False,
Again, not used. Did you forget to enable it?

2024-03-12 17:05 UTC, chrisholder commented on aeon/distances/tests/test_pairwise.py
> +        make_series(5, 5, return_numpy=True, random_state=1),
Talked on slack about this and the new changes resolve this

2024-03-12 17:06 UTC, chrisholder commented on aeon/distances/tests/test_pairwise.py
> +from aeon.distances.tests.test_utils import _make_3d_series
There are tests that need this to convert into a known format that works. For now will keep but maybe will removed in the near future. I have moved it into test utils as it is the only place it is used.

2024-03-12 17:07 UTC, chrisholder commented on aeon/distances/tests/test_pairwise.py
> +        make_example_3d_numpy(5, 5, 5, random_state=2)[0],
Fixed in update

2024-03-12 17:07 UTC, chrisholder commented on aeon/distances/tests/test_pairwise.py
> +        make_example_3d_numpy(5, 1, 5, random_state=2)[0],
Fixed in update

2024-03-12 17:07 UTC, chrisholder commented on aeon/distances/tests/test_pairwise.py
>      )
Added in update

2024-03-12 17:07 UTC, chrisholder commented on aeon/distances/tests/test_pairwise.py
> +        make_series(5, 5, return_numpy=True, random_state=2),
Fixed in new update and talked further on slack

2024-03-12 17:12 UTC, chrisholder commented on aeon/distances/tests/test_cost_matrix.py
> +    recursive_call=False,
It's snuck in at the end of line 51

2024-03-12 17:17 UTC, chrisholder commented on aeon/distances/tests/test_utils.py
> +    the time series x[i] = (d, m).
Excellent spot yes!

2024-03-14 08:31 UTC, CodeLionX reviewed
This would be clearer to me.

2024-03-14 08:31 UTC, CodeLionX commented on aeon/distances/tests/test_alignment_path.py
> +    check_xy_permuted=False,
```suggestion
    check_xy_permuted=True,
```

2024-03-14 08:31 UTC, CodeLionX commented on aeon/distances/tests/test_alignment_path.py
> +        )
```suggestion
    if original_x.shape[-1] != original_y.shape[-1] and check_xy_permuted:
        _validate_alignment_path_result(
            original_y,
            original_x,
            name,
            distance,
            alignment_path,
            check_xy_permuted=False,
        )
```

2024-03-14 10:27 UTC, chrisholder commented on aeon/distances/tests/test_alignment_path.py
> +    check_xy_permuted=False,
I agree

2024-03-14 13:04 UTC, CodeLionX approved these changes
This is a great refactoring of the distance tests; no more comments from my side! 🚀 I'm really looking forward to basing my additions on this in #1287

2024-03-15 13:46 UTC, TonyBagnall approved these changes

2024-03-15 13:46 UTC, merged