[MNT] Initializing metrics to "accuracy" In Deep Learning Models
aeon-toolkit/aeon pull request #1317
Opened 2024-03-17 12:35 UTC by harshithasudhakar

#### Reference Issues/PRs

Fixes #1230 

#### What does this implement/fix? Explain your changes.

Modified the __inti__() such that it sets metrics=["accuracy"] by default in case of no metric passed. In case of multiple metrics passed, it will be taken as a list of metrics(strings). 

Also removed the code block that checks if metrics is none, and updated the docstring.

### PR checklist

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [x] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

2024-03-17 17:35 UTC, harshithasudhakar commented on aeon/regression/deep_learning/_encoder.py
> +        metrics=["accuracy"],
Yes, it is. Thanks for spotting it!

2024-03-17 17:43 UTC, harshithasudhakar commented on aeon/regression/deep_learning/_tapnet.py
>          padding="same",
Some of the parameters seem to be missing in the docstring: ‎rp_params, ‎padding‎, ‎callbacks

2024-03-17 18:13 UTC, AnonymousCodes911 commented
@harshithasudhakar , pre-commit is prompting these:
`aeon/regression/deep_learning/_encoder.py:204:21: F821 undefined name 'metrics' `
`aeon/regression/deep_learning/_fcn.py:204:21: F821 undefined name 'metrics' `
`aeon/regression/deep_learning/_mlp.py:166:21: F821 undefined name 'metrics' `
`aeon/regression/deep_learning/_resnet.py:224:21: F821 undefined name 'metrics' `
`aeon/regression/deep_learning/_tapnet.py:192:21: F821 undefined name 'metrics'` 
but can these be just managed by editing the function?
 `
         model.compile(
            loss=self.loss,
            optimizer=self.optimizer_,
            metrics=metrics,  # should this be metrics="accuracy"?
        )
 `

2024-03-18 06:39 UTC, hadifawaz1999 commented
keras only accepts a list of metrics, which is why originally the parameter is default to a list. An inner conversion to a list should be done, its an obligation from keras, even if one metric is used

2024-03-18 10:31 UTC, MatthewMiddlehurst commented on aeon/regression/deep_learning/_tapnet.py
>          padding="same",
Feel free to fix if they are missing.

2024-03-19 21:38 UTC, MatthewMiddlehurst commented
An issue i think you may run into with the current method is the parameter attribute must be unchanged.

So if the input is "accuracy", `self.metrics` must also be "accuracy". You can either create `self._metrics` or do the processing in `_fit`. Feel free to ask questions if anything is confusing.

2024-03-20 14:55 UTC, harshithasudhakar commented
> An issue i think you may run into with the current method is the parameter attribute must be unchanged.
> 
> So if the input is "accuracy", `self.metrics` must also be "accuracy". You can either create `self._metrics` or do the processing in `_fit`. Feel free to ask questions if anything is confusing.

Thanks for your suggestion, I'll modify _fit() accordingly

2024-03-21 10:15 UTC, harshithasudhakar commented
`_fcn.py` is raising an AssertionError as the metrics attribute is modified in `_fit()`. So, I created a `self._metrics` attribute that holds the list version of the metrics. And made sure `self._metrics` is passed to `build_model`. This should resolve the error as `metrics` is not modified.

2024-03-21 17:04 UTC, harshithasudhakar commented
> if a variable is set to private with self, it should not be overridden throughout all the code, for this reason we create self.metrics_ It is still the case in some of the models, once this is fixed it should pass the tests

Yes, I have fixed it all now :)

2024-03-22 17:21 UTC, harshithasudhakar commented
@MatthewMiddlehurst @hadifawaz1999 @AnonymousCodes911 would be nice if you can review this pr 😁

2024-03-22 18:38 UTC, AnonymousCodes911 commented
@harshithasudhakar , 
I am just a fellow contributor 😅  , @hadifawaz1999 and @MatthewMiddlehurst are the maintainers!

2024-03-22 18:50 UTC, MatthewMiddlehurst requested changes
The currently changes estimators are regressors, is accuracy the correct metric to use @hadifawaz1999?

2024-03-22 18:50 UTC, MatthewMiddlehurst commented on aeon/regression/deep_learning/_encoder.py
> +        provided, all will be used for evaluation.
The default should be changed here. Make sure you update the documentation for other DL estimators which have been changed also.

2024-03-22 18:50 UTC, MatthewMiddlehurst commented on aeon/regression/deep_learning/_encoder.py
> +            metrics=self.metrics,
This one has not been updated, the changes for each estimator should be different.

2024-03-24 15:05 UTC, harshithasudhakar commented
@MatthewMiddlehurst Hi. I am new to DL, but I'm eager to dive deep. To tailor each of these models according to it's specific characteristics, I would require to read more and understand the models better. Are there any supporting docs or links I can refer to, to contribute effectively? Would greatly appreciate if the community can help me with this :)

2024-03-25 06:26 UTC, hadifawaz1999 commented
> The currently changes estimators are regressors, is accuracy the correct metric to use @hadifawaz1999?

No it should be `mean_squared_error` instead

2024-03-25 06:28 UTC, hadifawaz1999 commented
> @MatthewMiddlehurst Hi. I am new to DL, but I'm eager to dive deep. To tailor each of these models according to it's specific characteristics, I would require to read more and understand the models better. Are there any supporting docs or links I can refer to, to contribute effectively? Would greatly appreciate if the community can help me with this :)

Hello @harshithasudhakar yes you can refer to the deep learning for time series classification review in 2019. [link](https://arxiv.org/abs/1809.04356)

2024-03-25 06:28 UTC, hadifawaz1999 requested changes
In the case of regression, the default metric should be "mean_squared_error"

2024-03-25 15:48 UTC, harshithasudhakar commented
> ###
> [Mar 25, 2024](#issuecomment-2017314004)

Thanks! I'll look into it!

2024-03-28 16:22 UTC, MatthewMiddlehurst reviewed
Two of the docstrings of look like they still need to be updated also for metrics. Think this is close though, thanks for the work.

2024-03-28 19:35 UTC, harshithasudhakar commented
> It looks like the old variable for setting the metric is stiff there, it should be removed.
> 
> Please remove the bits of code added setting random states etc., I think there were probably accidentally added during a merge.

Yes, there were accidental changes but I fixed them now.

2024-03-30 14:46 UTC, MatthewMiddlehurst approved these changes
LGTM, thanks.

2024-04-01 14:09 UTC, hadifawaz1999 requested changes
Thanks, just a couple last changes

2024-04-01 14:09 UTC, hadifawaz1999 commented on aeon/regression/deep_learning/_cnn.py
> +    metrics         : list of strings, default="mean_squared_error",
should add here "If
        a single string metric is provided, it will be
        used as the only metric. If a list of metrics are
        provided, all will be used for evaluation."

2024-04-01 14:09 UTC, hadifawaz1999 commented on aeon/regression/deep_learning/_tapnet.py
> +    metrics             : list of str, default = "mean_squared_error"
should add here "If
        a single string metric is provided, it will be
        used as the only metric. If a list of metrics are
        provided, all will be used for evaluation."

2024-04-01 15:29 UTC, hadifawaz1999 approved these changes
lgtm thanks

2024-04-02 18:43 UTC, merged

2024-04-02 18:45 UTC, MatthewMiddlehurst commented
@all-contributors add @harshithasudhakar for code