[MNT] Modified `test_base_rocketGPU.py`
aeon-toolkit/aeon pull request #1325
Opened 2024-03-19 09:37 UTC by AnonymousCodes911

Refactored the test funcs to use `numpy.testing.assert_array_almost_equal` for more robust testing.
- added `normalize=False` in _rocket.py  so that both rocket cpu and gpu take the same version of the dataset

### Reference Issues/PRs

fixes : #1248 , #1272

2024-03-19 17:52 UTC, MatthewMiddlehurst requested changes
A few comments

2024-03-19 17:52 UTC, MatthewMiddlehurst commented on aeon/transformations/collection/convolution_based/_rocket.py
> +        self.normalize = normalize
There is already a normalise parameter available.

2024-03-19 17:52 UTC, MatthewMiddlehurst commented on aeon/transformations/collection/convolution_based/rocketGPU/tests/test_base_rocketGPU.py
> +__maintainer__ = ["hadifawaz1999", "AnonymousCodes911"]
People may @ you about the contents of the file if you add yourself here, FYI.

2024-03-19 17:52 UTC, MatthewMiddlehurst commented on aeon/transformations/collection/convolution_based/rocketGPU/tests/test_base_rocketGPU.py
> +@pytest.mark.parametrize("random_seed, n_channels", [(42, 1), (42, 3)])
The random seed can be static, it does not have to be a parameter.

2024-03-19 17:52 UTC, MatthewMiddlehurst commented on aeon/transformations/collection/convolution_based/rocketGPU/tests/test_base_rocketGPU.py
> +        X, _ = make_example_3d_numpy()
By default `make_example_3d_numpy` only creates an array with 1 channel, be sure to check the documentation. `make_example_3d_numpy` can be used for both univariate and multivariate.

2024-03-19 17:52 UTC, MatthewMiddlehurst commented on aeon/transformations/collection/convolution_based/rocketGPU/tests/test_base_rocketGPU.py
> +    rocket_gpu = ROCKETGPU(random_state=random_seed)
The number of kernels is not set here (i think its `n_filters`, not sure why its named differently)

2024-03-19 17:52 UTC, MatthewMiddlehurst commented on aeon/transformations/collection/convolution_based/rocketGPU/tests/test_base_rocketGPU.py
> +    n_instances = 100
The functions are creating arrays smaller than this by default

2024-03-19 18:08 UTC, AnonymousCodes911 commented on aeon/transformations/collection/convolution_based/_rocket.py
> +        self.normalize = normalize
I thought we needed a separate parameter for this test, hence I tweaked the spelling, will correct this.

2024-03-19 21:11 UTC, AnonymousCodes911 commented on aeon/transformations/collection/convolution_based/rocketGPU/tests/test_base_rocketGPU.py
> +    rocket_gpu = ROCKETGPU(random_state=random_seed)
removed `num_kernels` and changed it to `n_filters`

2024-03-19 21:12 UTC, AnonymousCodes911 commented on aeon/transformations/collection/convolution_based/rocketGPU/tests/test_base_rocketGPU.py
> +@pytest.mark.parametrize("random_seed, n_channels", [(42, 1), (42, 3)])
removed `random_seed` from the parameters

2024-03-19 21:29 UTC, AnonymousCodes911 commented on aeon/transformations/collection/convolution_based/rocketGPU/tests/test_base_rocketGPU.py
> +    rocket_gpu = ROCKETGPU(random_state=random_seed)
I dont know how I missed this! 😅

2024-03-20 10:31 UTC, hadifawaz1999 commented
I see the issue now, the new test will never be able to pass, because ROCKET implementation in aeon still uses directly the number generation with np.random.normal() and sets the seed globally with np.random.seed. However with ROCKETGPU we started using the [new random number generators that numpy introduced](https://numpy.org/doc/stable/reference/random/generator.html) to avoid deprecations in the future (compare both implementations). I tested and it gived different generations on the same seed.

Given this, do we hold this off until we update the random number generation in rocket and hopefully other models that uses np.random @MatthewMiddlehurst  ?

Would like your input on this @TonyBagnall @baraline

2024-03-20 10:39 UTC, MatthewMiddlehurst commented
Hmm that makes sense, good to know. I think what we can do is add a `@pytest.mark.xfail` over the test for now, until we can get around to better unifying the present implementations?

2024-03-20 10:46 UTC, hadifawaz1999 commented
> `pytest.mark.xfail`

Seems like a good solution for now yes

2024-03-20 13:50 UTC, AnonymousCodes911 commented
based on this discussion, implementing `@pytest.mark.xfail` is a suitable approach should I implement it? @MatthewMiddlehurst

2024-03-20 23:08 UTC, MatthewMiddlehurst approved these changes
LGTM. We can update the issue to note the above.

2024-03-21 07:11 UTC, hadifawaz1999 approved these changes
LGTM! thanks

2024-03-22 13:04 UTC, merged