[ENH]Update Channel Selection code
aeon-toolkit/aeon pull request #135
Opened 2023-03-01 22:05 UTC by haskarb

#### Reference Issues/PRs

#107 

#### What does this implement/fix? Explain your changes.
Updated channel selection code.

#### Does your contribution introduce a new dependency? If yes, which one?

#### What should a reviewer concentrate their feedback on?

#### Did you add any tests for the change?

#### Any other comments?

#### PR checklist

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/sktime/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

2023-03-01 22:18 UTC, lmmentel commented on sktime/transformations/panel/channel_selection.py
> +class Class_Prototype:
I wonder if there would be a more descriptive name for the class? The word `Class_` in the class name is a bit redundant, Could you propose an alternative that would maybe be more meaningful here? Happy to help in case you're stuck but I would need a bit more context about the class.

2023-03-01 22:22 UTC, haskarb commented on sktime/transformations/panel/channel_selection.py
> +class Class_Prototype:
Actually it's an implementation from paper.

> The proposed channel selection techniques depend on three components: class prototype, distance matrix and distance aggregation (Fig. [2](https://link.springer.com/article/10.1007/s10618-022-00909-1#Fig2)).

2023-03-01 22:29 UTC, lmmentel requested changes

2023-03-01 22:29 UTC, lmmentel commented on sktime/transformations/panel/channel_selection.py
> +    def __init__(self, cp: str = "mean", mean_centering: bool = False):
Please add a docstring documenting `cp` and `mean_centering` arguments.

2023-03-01 22:29 UTC, lmmentel commented on sktime/transformations/panel/channel_selection.py
> +    def _mad_median(self, class_X, median=None):
Please add a docstring and it would be great if you could add type hints for the arguments.

2023-03-01 22:29 UTC, lmmentel commented on sktime/transformations/panel/channel_selection.py
> +    def _class_mad(self, X, y):
Missing docstring and type annotations.

2023-03-01 22:29 UTC, lmmentel commented on sktime/transformations/panel/channel_selection.py
> +    def __init__(
Any chance you could add type hints to the arguments?

2023-03-01 22:29 UTC, lmmentel commented on sktime/transformations/panel/channel_selection.py
> +        self.class_prototype_ = centroid_obj.create_class_prototype(X.copy(), y)
It seems there a bit of a name clash here, since you have `Class_Prototype`, `self.class_prototype` and `create_class_prototype`, would it be possible to come up with unique names that reflect what the objects are and what they do?

2023-03-01 22:29 UTC, lmmentel commented on sktime/transformations/panel/channel_selection.py
> +        Distance metric to use for creating the class prototype.
Could you add what are the allowed values of `distance`?

2023-03-01 22:29 UTC, lmmentel commented on sktime/transformations/panel/channel_selection.py
> +    class_prototype : str
Could you add what are the allowed values of `class_prototype`?

2023-03-01 22:29 UTC, lmmentel commented on sktime/transformations/panel/channel_selection.py
>  class ElbowClassPairwise(BaseTransformer):
Consider dropping the `Class` from the class name since it's redundant

2023-03-01 22:29 UTC, lmmentel commented on sktime/transformations/panel/channel_selection.py
> +        distance="euclidean",
Any chance you could add type hints?

2023-03-01 22:29 UTC, lmmentel commented on sktime/transformations/panel/channel_selection.py
> +    def _rank(self):
missing docstring

2023-03-01 22:29 UTC, lmmentel commented on sktime/transformations/panel/channel_selection.py
> +        all_chs.fill(0)
could this be simplified with `np.zeros(self.class_prototype_.shape[1] - 1)` ?

2023-03-01 22:43 UTC, haskarb commented
Thanks @lmmentel. I will update the docstring and type hints. However, I'm not sure about changing name of classes, as they refer to class in the dataset, and referenced paper.

2023-03-02 13:06 UTC, TonyBagnall requested changes
so this is a great start but will need a bit of tweaking to go in, sorry. I think ultimately we can integrate this with our clustering and distances, but I'm ok for this to go in when ready without that if others are also. As for the name, I agree with @lmmentel that the name would be better changed. The problem is overloading Class == possible values of the target variable and Class as in a template for an object in code. Obviously this is in the algorithm name ECP and I dont think you should change that, since its published name. I'll have a think, but at the minimum, dont mix snake and camel class, 
Class_Prototype -> ClassPrototype
but possibly LabelPrototype
and also can it be a private class? If not, could you add a more descriptive doc string?

2023-03-02 14:31 UTC, TonyBagnall commented
can you change this to use numpy3d in shape (n_instances, n_dimensions, series_length)? We are moving to remove nested_univ and pandas from classification related code

2023-03-08 12:03 UTC, haskarb commented on sktime/transformations/panel/channel_selection.py
> +        all_chs.fill(0)
Removed this piece of code.

2023-03-08 12:11 UTC, haskarb commented on sktime/transformations/panel/channel_selection.py
> +class Class_Prototype:
This is fixed.

2023-03-08 13:52 UTC, haskarb commented on sktime/transformations/panel/channel_selection.py
> +        Distance metric to use for creating the class prototype.
I'm using sktime's distance function, so if a distance is out of the list, they error should pop from there.

2023-03-08 17:21 UTC, TonyBagnall submitted a review, later dismissed
great job, thanks

2023-03-08 17:56 UTC, TonyBagnall commented
I'm happy with this @lmmentel would you like to review again?

2023-03-08 19:27 UTC, lmmentel requested changes
Overall great progress, although it would be great to have some of the new comments addressed before merging

2023-03-08 19:27 UTC, lmmentel commented on sktime/transformations/panel/channel_selection.py
> +    distance_: str = "euclidean",
the underscore after `distance` could be dropped, any reason to have it? in scikit-learn it's used to indicate computed attrbutes but it does not seem like the case here

2023-03-08 19:27 UTC, lmmentel commented on sktime/transformations/panel/channel_selection.py
> +    """Create a distance matrix between class_prototypes.
```suggestion
    """Create a distance matrix between class prototypes.
```

2023-03-08 19:27 UTC, lmmentel commented on sktime/transformations/panel/channel_selection.py
> +    prototype : pd.DataFrame or np.ndarray
`prototype` and `class` are very generic names that do not say much about what the parameters should be. Could you add an extra sentence to each docstring explaining the meaning or give an example value?

2023-03-08 19:27 UTC, lmmentel commented on sktime/transformations/panel/channel_selection.py
> +    ), "Prototype and class values must be of same length."
Assets are dangerous in production since they can be switched by an interpreter flag, consider changing to a if/except block
```suggestion
    if prototype.shape[0] != len(class_vals):
        raise ValueError(f"Prototype {prototype.shape[0]} and class values {len(class_vals)} must be of same length.")
```

2023-03-08 19:27 UTC, lmmentel commented on sktime/transformations/panel/channel_selection.py
> +def _clip(x: np.array, low_value: float, high_value: float):
this function seems redundant since it call a numpy function directly, why not use `np.clip` instead?

2023-03-08 19:27 UTC, lmmentel commented on sktime/transformations/panel/channel_selection.py
> +    Class prototype for each class.
this is a bit too self referential, any chance you could some clarification?

2023-03-08 19:27 UTC, lmmentel commented on sktime/transformations/panel/channel_selection.py
> +        ], "Class prototype not supported."
consider switching to if/except since assert might be skipped in production

2023-03-08 19:29 UTC, haskarb commented on sktime/transformations/panel/channel_selection.py
> +    distance_: str = "euclidean",
There is a function in sktime which I'm using, and it could conflict with that.

2023-03-08 19:36 UTC, TonyBagnall commented on sktime/transformations/panel/channel_selection.py
> +    Class prototype for each class.
I think this class should be private

2023-03-08 20:15 UTC, lmmentel commented on sktime/transformations/panel/channel_selection.py
> +    distance_: str = "euclidean",
How about changing the import to `from sktime.distances import distance as sktime_distance` that way we can avoid unnecessary underscore.

2023-03-08 20:20 UTC, haskarb commented on sktime/transformations/panel/channel_selection.py
> +    distance_: str = "euclidean",
ok. I can do that.

2023-03-08 20:23 UTC, haskarb commented on sktime/transformations/panel/channel_selection.py
> +    Class prototype for each class.
I want to keep this public because I thought it could be used to create just a prototype frame.

2023-03-08 20:23 UTC, haskarb commented on sktime/transformations/panel/channel_selection.py
> +        ], "Class prototype not supported."
Will do this.

2023-03-08 20:59 UTC, haskarb commented on sktime/transformations/panel/channel_selection.py
> +    prototype : pd.DataFrame or np.ndarray
Updated the doc string.

2023-03-08 20:59 UTC, haskarb commented on sktime/transformations/panel/channel_selection.py
> +def _clip(x: np.array, low_value: float, high_value: float):
Fixed.

2023-03-08 21:22 UTC, lmmentel approved these changes
Looks great!

2023-03-09 07:01 UTC, merged