[ENH] Included RSAST as a alternative to SAST (2.0)
aeon-toolkit/aeon pull request #1383
Opened 2024-04-08 06:58 UTC by nirojasva

#### What does this implement/fix? Explain your changes.

I included a transformer RSAST and a classifier RSASTClassifier which are tools to use in time series classification. The method RSAST is based on shapelets in order to transform dataset of Time Series.

#### Does your contribution introduce a new dependency? If yes, which one?
 
Yes, I used f_oneway, DegenerateDataWarning, ConstantInputWarning from the "scipy.stats" toolkit. Also,  acf and pacf from the "statsmodels.tsa.stattools" implementation.

### PR checklist

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [x] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

##### For new estimators and functions
- [ ] I've added the estimator to the online [API documentation](https://www.aeon-toolkit.org/en/latest/api_reference.html).
- [ ] (OPTIONAL) I've added myself as a `__maintainer__` at the top of relevant files and want to be contacted regarding its maintenance. Unmaintained files may be removed. This is for the full file, and you should not add yourself if you are just making minor changes or do not want to help maintain its contents.

##### For developers with write access
- [ ] (OPTIONAL) I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.

2024-04-08 08:33 UTC, nirojasva commented
Hello, I have another question, I'm using two new libraries "statsmodels" and "scipy". How can I included in aeon these libraries since it seems it is generating conflict?
Thanks,

2024-04-08 13:58 UTC, MatthewMiddlehurst commented
scipy is fine, statsmodels will have to be added as a tag i.e. https://github.com/aeon-toolkit/aeon/blob/main/aeon/classification/shapelet_based/_ls.py#L95

Check out the [contributing guide](https://www.aeon-toolkit.org/en/latest/contributing.html) for some tips. The developer install would be helpful for pre-commit.

2024-04-11 10:25 UTC, MatthewMiddlehurst commented
The tag also has to be included for the transformer, and the imports must be inside the function rather than at the top of the file.

2024-04-15 22:23 UTC, MatthewMiddlehurst commented
I think the remaining failure is because of the examples. No good way to get around this unfortunately, I would recommend using `# doctest: +SKIP`. The QUANT example does this in `interval_based`.

2024-04-16 14:19 UTC, nirojasva commented
Ok @MatthewMiddlehurst thanks, it seems the validation worked for the library issues. However there are still errors in "pre-commit" and there is no a detail about why they are caused.

2024-04-16 14:36 UTC, MatthewMiddlehurst commented
These are our code quality checks, for the most part it is probably white space. I would recommend following the pre-commit section of the [dev install guide](https://www.aeon-toolkit.org/en/latest/developer_guide/dev_installation.html) or I can run it through at some point.

2024-04-23 10:02 UTC, TonyBagnall requested changes
looks good, a few minor things, thanks very much for the contribution

2024-04-23 10:02 UTC, TonyBagnall commented on aeon/classification/shapelet_based/_rsast_classifier.py
> +    def plot_most_important_feature_on_ts(self, ts, feature_importance, limit=5):
we now have a visualisation module, this would be better plasced there as I dont think its classifier specific

2024-04-23 10:02 UTC, TonyBagnall commented on aeon/classification/shapelet_based/_rsast_classifier.py
> +    """Classification pipeline using RSAST [1]_ transformer and an sklearn classifier.
could you say in the docstring what RSAST stands for?

2024-04-24 07:51 UTC, nirojasva commented on aeon/classification/shapelet_based/_rsast_classifier.py
> +__maintainer__ = []
Hello, yes, I set myself as a maintainer of RSAST, althougth for SAST I could ask Michael.

2024-05-13 18:40 UTC, TonyBagnall approved these changes
LGTM, sorry for the delay

2024-05-18 17:16 UTC, merged

2024-05-18 17:16 UTC, MatthewMiddlehurst commented
We are releasing next week, this should be available then.