[ENH] `BaseSeriesEstimator` rework
aeon-toolkit/aeon pull request #1394
Opened 2024-04-09 15:56 UTC by MatthewMiddlehurst

todo

2024-04-09 16:09 UTC, TonyBagnall commented on aeon/base/_base_series.py
> +                X = pd.Series(X)
dont need to do this, squeeze makes it a pd.Series if 1 dimensional I think

2024-04-09 16:27 UTC, MatthewMiddlehurst commented on aeon/base/_base_series.py
> +                X = pd.Series(X)
This is the bit for converting to a pd.Series. May be a better way to do it, but it if you just pass a pd.DataFrame it crashes.

2024-04-10 09:55 UTC, MatthewMiddlehurst commented
@TonyBagnall @baraline likely to impact your stuff

2024-04-10 10:30 UTC, baraline requested changes
Changes lgtm, just a possible typo in an if condition and some docstring. I think tests cover every case so that's good.

2024-04-10 10:30 UTC, baraline commented on aeon/base/_base_series.py
> +    def _check_X(self, X, axis):
Missing docstring for axis parameter

2024-04-10 10:30 UTC, baraline commented on aeon/base/_base_series.py
> +            X = X.reshape(1, -1) if axis == 1 else X.reshape(1, -1)
I would prefer to use `X=X[np.newaxis, :]` instead of reshape, but in this case the end result is the same. 
Additionaly both condition are the same, here probably a typo. (One should be the reverse for axis=0 right ?)

2024-04-10 10:37 UTC, MatthewMiddlehurst commented on aeon/base/_base_series.py
> +            X = X.reshape(1, -1) if axis == 1 else X.reshape(1, -1)
yeah, looks incorrect, may be a blind spot in testing. Will look at coverage.

2024-04-10 15:09 UTC, MatthewMiddlehurst commented on aeon/base/_base_series.py
> +    def _check_X(self, X, axis):
This has a doc string now. Still have to update the main class one at least.

2024-04-10 15:09 UTC, MatthewMiddlehurst commented
I have updated the notebook.

2024-04-10 16:07 UTC, baraline approved these changes

2024-04-11 12:49 UTC, baraline approved these changes
Nice changes for `BaseSeriesEstimator` docs, much clearer now. Otherwise previous issues are resolved and the notebook explain the internal working of preprocess clearly to me. We could add a bit on postprocess too but that can maybe be made as a good first issue ?

2024-04-11 15:58 UTC, MatthewMiddlehurst commented
I'm fine with defaulting the multivariate capability to true.

2024-04-11 18:47 UTC, TonyBagnall commented
its quite hard to review on files changed tab, so will do it here, re _convert_X. Some minor points

if pd.Series is passed we have this
```
            elif inner_type[0] == "Series":
                if self.get_tag("capability:multivariate"):
                    raise ValueError(
                        "Cannot convert to pd.Series for multivariate capable "
                        "estimators"
                    )
                if X.ndim > 1:
                    n_channels = X.shape[0] if axis == 1 else X.shape[1]
                    if n_channels > 1:
                        raise ValueError(
                            "Cannot convert to pd.Series for multivariate data. Found "
                            f"{n_channels} channels"
                        )
```
1. Why cant we convert a series to multivariate capable? We do with 1D numpy. You can just put it in a DataFrame? It seems inconsistent to me. 
2. If you squeeze a DataFrame with 1D it becomes a pd.Series, so this conversion is redundant
```
                X = X.squeeze()
                X = pd.Series(X)
```
e.g.
```import pandas as pd
X = pd.DataFrame([1,2,3,4,5])
y = X.squeeze()
print(type(y)) 
```
is pd.Series
3. So figured this out, but it seems a bit twisty. 
```
            elif inner_type[0] == "DataFrame":
                # converting a 1d array will create a 2d array in axis 0 format
                transpose = False
                if X.ndim == 1 and axis == 1:
                    transpose = True

                X = pd.DataFrame(X)

                if transpose:
                    X = X.T
```
cant you just have
```
                X = pd.DataFrame(X)
               if X.ndim == 1 and axis == 1:
                    X = X.T
```
it all looks like it could be condensed to fewer lines of code tbh. 

4. Why do we have to call get tag again? Already called it earlier,
```
            else:
                tag = self.get_tag("X_inner_type")
                raise ValueError(
                    f"Unknown inner type {inner_type[0]} derived from {tag}"
                )
```
5. Multiple values of inner_type seem to just be ignored, since you only test inner_type[0], so why have them? I still dont see the use case, and this means any list is ignored I think, which could be very confusing. if my inner type were ["np.ndarray", "pd.Series"], my expectation would be that if either were passed, the base class would not convert them. However, atm, it would I think get converted to np.ndarray?

2024-04-11 18:47 UTC, TonyBagnall requested changes
see comments

2024-04-11 19:52 UTC, MatthewMiddlehurst commented
> Why cant we convert a series to multivariate capable? We do with 1D numpy. You can just put it in a DataFrame? It seems inconsistent to me.

We can, but that would involve removing `pd.Series` as an inner type altogether essentially. Not opposed.

> If you squeeze a DataFrame with 1D it becomes a pd.Series, so this conversion is redundant

This is also used for `np.ndarray` > `pd.Series`, where squeeze turns a 2D array into a 1D one (it would all go if we do the above).

> So figured this out, but it seems a bit twisty. cant you just have
```
X = pd.DataFrame(X)
if X.ndim == 1 and axis == 1:
    X = X.T
```

`pd.DataFrame` is always `X.ndim==2`, no such thing as a 1D `pd.DataFrame`, that's just a `pd.Series`. No idea why. What I want to do there is check if we have a 1D `np.ndarray` or `pd.Series` and see if we have to transpose the new `pd.DataFrame` (as it will always be `(n_timepoints, n_channels)` if given a 1D input).

> Why do we have to call get tag again? Already called it earlier,

I edit the output of the previous call. Can just use a different variable name for the edited version and ditch this line.

> Multiple values of inner_type seem to just be ignored, since you only test inner_type[0], so why have them? I still dont see the use case, and this means any list is ignored I think, which could be very confusing. if my inner type were ["np.ndarray", "pd.Series"], my expectation would be that if either were passed, the base class would not convert them. However, atm, it would I think get converted to np.ndarray?

This is mostly for compatibility with the tag. It says it (or other usages can) can take an array. The following line does what you suggest `if input not in inner_type:`, if input is already of an accepted type no conversion is done. Though now that I say that, it seems to be skipping some bits we wouldn't want it too currently. `inner_type[0]` is only used if we have to convert to something different.

2024-04-12 09:36 UTC, TonyBagnall approved these changes

2024-04-12 09:38 UTC, TonyBagnall commented
yeah ok, can put this in if you resolve conflicts and we can discuss 1D options after

2024-04-12 12:45 UTC, MatthewMiddlehurst commented
I have merged main into this. Please do double-check the postprocess function, some changes to match the new contents. Also changes to include docs and to testing.

2024-04-13 07:58 UTC, TonyBagnall approved these changes

2024-04-14 09:36 UTC, TonyBagnall commented
weirdly, code cov is failing with these errors
<img width="626" alt="image" src="https://github.com/aeon-toolkit/aeon/assets/9594042/e83724b7-9f52-42d6-bb8c-9fb1dc802e08">

2024-04-14 09:56 UTC, MatthewMiddlehurst commented
unrelated

2024-04-14 13:23 UTC, TonyBagnall commented
Unrelated codecov fails

2024-04-14 13:23 UTC, merged