[DOC] Fixes mis-wording/typo in mentoring docs
aeon-toolkit/aeon pull request #1396
Opened 2024-04-10 04:14 UTC by wayneadams

#### What does this implement/fix? Explain your changes.

These changes fix what looks to be mis-wording/typos in mentoring docs. Though, I'm not 100% sure what the intention was, so this PR is just to start the editing process.

#### Does your contribution introduce a new dependency? If yes, which one?

No

### PR checklist

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [x] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

2024-04-10 04:16 UTC, wayneadams commented
@all-contributors please add @wayneadams for doc

2024-04-10 10:33 UTC, baraline commented
Hi, thanks and nice spot ! Tell us when you are done with the editting so we can review.

2024-04-10 20:55 UTC, wayneadams commented
@baraline , I'm done editing and the PR is ready for review.

2024-04-10 21:34 UTC, baraline requested changes
Just a small typo, otherwise looking good and in line with the other projects, thanks again !

2024-04-10 21:34 UTC, baraline commented on docs/mentoring.md
> +implmentation for the shapelet transform that gets accepted into the toolkit.
Small typo on `implmentation`

2024-04-11 11:07 UTC, wayneadams commented on docs/mentoring.md
> +implmentation for the shapelet transform that gets accepted into the toolkit.
Good eye!

2024-04-11 17:00 UTC, baraline approved these changes
LGTM!

2024-04-11 17:00 UTC, merged