[ENH] Update MPDist function
aeon-toolkit/aeon pull request #1415
Opened 2024-04-11 16:13 UTC by itsdivya1309

#### Reference Issues/PRs
Fixes #423

#### What does this implement/fix? Explain your changes.

#### Does your contribution introduce a new dependency? If yes, which one?

#### Any other comments?

### PR checklist

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [ ] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

##### For new estimators and functions
- [ ] I've added the estimator to the online [API documentation](https://www.aeon-toolkit.org/en/latest/api_reference.html).
- [ ] (OPTIONAL) I've added myself as a `__maintainer__` at the top of relevant files and want to be contacted regarding its maintenance. Unmaintained files may be removed. This is for the full file, and you should not add yourself if you are just making minor changes or do not want to help maintain its contents.

##### For developers with write access
- [ ] (OPTIONAL) I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.

2024-04-12 09:17 UTC, CodeLionX commented
If you JIT `_mpdist`, please already consider the unequal-length implementation. #1287 and #1356 are good pointers.

2024-04-23 09:50 UTC, TonyBagnall approved these changes
create stuff, one minor change suggested but its not a blocker

2024-04-23 09:50 UTC, TonyBagnall commented on aeon/distances/_mpdist.py
> +        )
I think its easier to read if you split these operations to make this more readable? i.e.
temp =(dot_prod[i] - q_len * q_mean * t_mean[i])/ (q_len * q_std * t_std[i])
d[i] = 2* q_len* (1-temp)
I realise this was not your code, but may as well take the opportunity to tidy it up.

2024-04-23 17:12 UTC, itsdivya1309 commented on aeon/distances/_mpdist.py
> +    """
Hi @TonyBagnall, I have kept the code logic the same, but I just noticed that there may be an issue with the results it generates. As you can see here in the examples it gives for `mpdist_pairwise_distance`, I doubt this is the desired output.
Also, please look at the `mpdist` example. Is this the way this function is supposed to work?

2024-04-24 08:41 UTC, CodeLionX commented
Nice work 👍🏼
However, the `pairwise_distance`-function is not jitted yet and might be slow. @chrisholder and I need to take a look if it is possible to jit it and actually measure if it makes sense.

When the discussion about the correct output is resolved, I'm in favor of merging and having another PR considering the potential performance bottleneck.

2024-04-27 14:04 UTC, itsdivya1309 commented on aeon/distances/_mpdist.py
> +    """
I have updated the code, but it still produces the same results. I think this is how the MPDist algo performs altogether because even the mpdist gives minimal values.

2024-04-29 15:57 UTC, CodeLionX requested changes

2024-04-29 15:57 UTC, CodeLionX commented on aeon/distances/_mpdist.py
> +    raise ValueError("x and y must be a 1D array of shape (n_timepoints,)")
All distances in aeon support multivariate TS, some natively, others by just summing up the channel-wise distances, e.g.

https://github.com/aeon-toolkit/aeon/blob/957704a45ab130cf19d6302d9e9f6c4e13dc2001/aeon/distances/_manhattan.py#L52-L63

Is there a reason to not do this with MPDist?

2024-04-29 15:59 UTC, CodeLionX commented on aeon/distances/_mpdist.py
> +    raise ValueError("x and y must be a 1D array of shape (n_timepoints,)")
Sry for requesting more work so late. I have not seen this before. We can also merge this PR first and create a second one for making `mpdist` support multivariate TS. I can imagine that it requires a lot of modification to the different functions.

2024-04-30 15:16 UTC, itsdivya1309 commented on aeon/distances/_mpdist.py
> +    raise ValueError("x and y must be a 1D array of shape (n_timepoints,)")
Hi! MPDist was proposed for univariate time series data in the paper. This PR aimed to update the mpdist to work with numba and introduce pairwise distance.
I would like to implement it for multivariate data, but I have my end-semester exams, so I'll not be able to take this up this week :)
We can open another PR for this.

2024-05-02 08:37 UTC, CodeLionX approved these changes

2024-05-02 08:38 UTC, CodeLionX commented on aeon/distances/_mpdist.py
> +    raise ValueError("x and y must be a 1D array of shape (n_timepoints,)")
Alright. Please create a new issue for this so that we don't forget it 😉 Thank you for working on this!

2024-05-02 08:47 UTC, itsdivya1309 commented on aeon/distances/_mpdist.py
> +    raise ValueError("x and y must be a 1D array of shape (n_timepoints,)")
> Alright. Please create a new issue for this so that we don't forget it 😉 Thank you for working on this!

Sure 👍

2024-05-06 15:58 UTC, TonyBagnall approved these changes
LGTM

2024-05-06 15:58 UTC, merged

2024-05-07 15:33 UTC, MatthewMiddlehurst commented on aeon/distances/_mpdist.py
> +    raise ValueError("x and y must be a 1D array of shape (n_timepoints,)")
We still need this issue I think, grateful if you could @itsdivya1309 as I have not been following this closely 🙂