[DOC] Add estimator overview table with capabilities
aeon-toolkit/aeon pull request #1426
Opened 2024-04-15 10:29 UTC by baraline

#### Reference Issues/PRs

Fixes #1242 

#### What does this implement/fix? Explain your changes.

Add back the estimator overview table from 0.3, but add capabilities of individual estimators to the table.

2024-04-17 20:27 UTC, CodeLionX requested changes
I like the overview table. It already provides a good overview and the capabilities are displayed as well. For now, one can just use the browsers search functionality to navigate it. 👍🏼 

The generation-function contains quite a lot of code. Should we extract it to a separate file?

There is also `build_tools/generate_developer_tables.py`, which also generates an html table... I don't know if this is similar enough, though.

2024-04-17 20:27 UTC, CodeLionX commented on docs/conf.py
> +html_js_files = []
unused

2024-04-17 20:27 UTC, CodeLionX commented on docs/conf.py
> +                data[f"Support {_str}"].append("\u2705")
```suggestion
            if not _val or _val is None:
                data[f"Supports {_str}"].append("\u274C")
            else:
                data[f"Supports {_str}"].append("\u2705")
```

2024-04-17 20:27 UTC, CodeLionX commented on docs/conf.py
> +            + "/auto_generated/"
```suggestion
            '<a href="api_reference/auto_generated/'
```
This always referenced the _latest_ version of the documentation instead of the currently selected/displayed version, e.g. the PR build.

2024-04-17 20:27 UTC, CodeLionX commented on docs/conf.py
> +            data["Family of method"].append("/".join(algorithm_type[1:]))
Personal preference:
```suggestion
            data["Method family"].append("/".join(algorithm_type[1:]))
```

2024-04-17 20:27 UTC, CodeLionX commented on docs/conf.py
> +    COLNAMES = ["Estimator name", "Module", "Family of method"]
Personal preference:
```suggestion
    COLNAMES = ["Estimator name", "Module", "Method family"]
```
(also see below)

2024-04-17 20:27 UTC, CodeLionX commented on docs/conf.py
> +        COLNAMES.append(f"Support {_str}")
```suggestion
        COLNAMES.append(f"Supports {_str}")
```

2024-04-17 20:27 UTC, CodeLionX commented on docs/conf.py
> +        by=["Module", "Family of method", "Estimator name"]
Personal preference
```suggestion
        by=["Module", "Method family", "Estimator name"]
```

2024-04-18 07:19 UTC, baraline commented
The trick is that it should be generated while building the docs, and I don't know if `build_tools` would be accessible while readthedocs builds. But I agree we should put it in a separate file, maybe create a folder/python script inside `docs/` for script that generate content ?

2024-04-18 10:14 UTC, CodeLionX approved these changes

2024-04-18 12:12 UTC, MatthewMiddlehurst approved these changes
Looks great. I agree searching can wait with an issue raised. Do we want to close #1242? There is still an issue maybe in not having tags on individual API pages.

2024-04-18 12:40 UTC, baraline commented
Ok, a quick try on moving the script somewhere else made a mess, I'll keep it that way for now. I opened #1430 for individual estimators, and I'll create the issue for search/sort. So I guess we can close #1242 for now.

2024-04-18 12:40 UTC, merged