[ENH] Add control over the score method of classification and regression
aeon-toolkit/aeon pull request #1443
Opened 2024-04-20 08:45 UTC by aadya940

Closes #1062

2024-04-21 08:06 UTC, baraline commented
Nice work, althought I would suggest that rather listing some/all metrics for a task, you could use a sklearn defined method such as [get_scorer](https://github.com/scikit-learn/scikit-learn/blob/8721245511de2f225ff5f9aa5f5fadce663cd4a3/sklearn/metrics/_scorer.py#L359). Then you could do the following to get back the metric function from the scorer 

```python
from sklearn.metrics import get_scorer
get_scorer('accuracy')._score_func(y_true, y_pred)
```

Thought on this @hadifawaz1999 ? ( as you raised the issue )

2024-04-22 09:41 UTC, MatthewMiddlehurst reviewed
Agree with the above, but that could get awkward when it comes to parameterising some i.e. auroc. Maybe a mix?

Tests should include an invalid input for metric.

2024-04-22 11:47 UTC, baraline commented
We could do something like this to also accept callable and deal with parameterization ?

```python
def score(self, X, y, metric="accuracy", metrics_params=None):
  ...
  if metrics_params is None:
    metrics_params_ = {}
  # let score func raise error if metrics params is not right format
  if isinstance(metric, str):
    return  get_scorer(metric')._score_func(y_true, y_pred, **metrics_params_)
  elif callable(metric):
    return  metric(y_true, y_pred, **metrics_params_)
  else:
    # throw an error
```

2024-04-22 13:33 UTC, aadya940 commented
@baraline 
What about the cases where `y_pred` is `predict_proba(X)` instead of `predict(X)`?

2024-04-22 13:46 UTC, baraline commented
I'm not sure, but I see your point, it is indeed a problem.

For example [roc_auc_score](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.roc_auc_score.html) would handle probabilities estimates but not [accuracy_score](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html#sklearn.metrics.accuracy_score) according to docs. 
To summarize:
- If the metric support probabilities, we want to support both probabilities estimate and predicted class as input
- Otherwise, we only accept predicted class as inputs.

This raise the question of how should the user be able to use probabilities estimates over predict class (i.e. score with the output of `predict_probas` instead of `predict`). 

One easy solution is to introduce another parameter in the `score` function, something like a boolean `use_probabilities_estimate` to determine wheter `predict_probas` should be used over `predict`. Then let sklearn raise the error if the metric does not support probabilities estimate.

I'm pretty sure there might be a better way to do this though...

2024-04-22 15:01 UTC, aadya940 commented
I'm not completely sure but we could do something along the following lines?

```
scorer = get_scorer(metric)
try:
        return scorer._score_func(y_true, predict(X))
    except:
        try:
            return scorer._score_func(y_true, predict_proba(X))
        except:
            # throw an exception
```

2024-04-25 18:53 UTC, aadya940 commented
I think, for now, wouldn't supporting a few scoring methods be a good idea? Since we already claim that aeon is sklearn compatible so it wouldn't be much of an issue if someone wants to use another scoring method.

2024-04-25 20:07 UTC, MatthewMiddlehurst commented
I think the string and callable input with `use_probabilities_estimate` or however you name it is fine. Changes to base classes should be more strictly curated IMO so better to get it correct now.

2024-04-26 05:04 UTC, aadya940 commented
> I think the string and callable input with `use_probabilities_estimate` or however you name it is fine. Changes to base classes should be more strictly curated IMO so better to get it correct now.

Sounds Good! I'll change it accordingly.

2024-04-27 08:35 UTC, baraline requested changes
Some minor changes for error message. The rest looks good, test are added for both unknown metrics and callable inputs, so LGTM !

2024-04-27 08:35 UTC, baraline commented on aeon/classification/base.py
> +                                 a valid metric name instead."""
I would give a more expressive error message, something along the line of :
```python
raise ValueError(
    f"Metric {metric} is incompatible with `sklearn.metrics.get_scorer` function."
    "Valid list of metrics can be obtained using the `sklearn.metrics.get_scorer_names` function"
)
```

2024-04-27 08:35 UTC, baraline commented on aeon/classification/base.py
> +            raise ValueError("Enter a valid metric format.")
Again the same here, something along the lines of 
```python
raise ValueError(
    "The metric parameter should be either a string or a callable"
     f", but got {metric} of type {type(metric)}"
)
```

2024-04-27 08:35 UTC, baraline commented on aeon/regression/base.py
> +                )
Same comment as in classification base

2024-04-27 08:35 UTC, baraline commented on aeon/regression/base.py
> +            raise ValueError("Enter a valid metric format.")
Same comment as in classification base

2024-04-27 18:33 UTC, aadya940 commented
I've done the needed changes. @baraline Thankyou for reviewing.

2024-04-28 07:45 UTC, baraline submitted a review, later dismissed
Thanks, the rest LGTM. As this is touching base class, I'd wait for another review to merge it, nice work !

2024-04-28 12:39 UTC, MatthewMiddlehurst requested changes
Good changes IMO, spotted one doc error. Any thoughts @TonyBagnall?

2024-04-28 12:39 UTC, MatthewMiddlehurst commented on aeon/regression/base.py
> +        metric : Union[str, callable], default="accuracy",
incorrect default here

2024-04-28 16:42 UTC, aadya940 commented on aeon/regression/base.py
> +        metric : Union[str, callable], default="accuracy",
Sorry for the oversight :-)

2024-04-28 17:09 UTC, hadifawaz1999 approved these changes
lgtm !

2024-04-29 16:04 UTC, baraline approved these changes
LGTM, didn't catch the documentation issue.

2024-05-02 14:45 UTC, MatthewMiddlehurst approved these changes

2024-05-02 14:45 UTC, merged