[MNT] Update similarity search with new base classes : Query Search
aeon-toolkit/aeon pull request #1508
Opened 2024-05-09 14:41 UTC by baraline

#### Reference Issues/PRs

Part of #1243

#### What does this implement/fix? Explain your changes.

As described in #1243, this is a first PR that implement base classes for query search task, and transfers the existing code under this new submodule.

### PR checklist

##### For new estimators and functions
- [X] I've added the estimator to the online [API documentation](https://www.aeon-toolkit.org/en/latest/api_reference.html).
- [X] (OPTIONAL) I've added myself as a `__maintainer__` at the top of relevant files and want to be contacted regarding its maintenance. Unmaintained files may be removed. This is for the full file, and you should not add yourself if you are just making minor changes or do not want to help maintain its contents.

2024-05-29 12:08 UTC, MatthewMiddlehurst requested changes
Some comments. All experimental so there some leeway, not going to say I went through every function with a fine tooth comb. Some of the comments may be a bit more general and apply to more than the highlighted code.

Would be good to update https://github.com/aeon-toolkit/aeon-admin/pull/1 with the contents of your comments just so there a centralised document for interested people until we decide to make this non-experimental.

I would be careful with the base class parameters, if it does not apply to all (or the vast majority) of inheriting classes then it probably should not be here. Not saying that is the case, but there are some bases i.e. clustering with `n_clusters` where we are going to run into issues later.

2024-05-29 12:08 UTC, MatthewMiddlehurst commented on aeon/similarity_search/tests/test_base.py
> +class BaseInstance(BaseSimiliaritySearch):
1. Does it make sense to create a test class for this? I assumes it was abstract and each submodule would have its own base class
2. I would continue with the "MockEstimator" format we current have in `testing` if possible.

2024-05-29 12:08 UTC, MatthewMiddlehurst commented on aeon/similarity_search/series_search/__init__.py
> +"""Series search module."""
Empty

2024-05-29 12:08 UTC, MatthewMiddlehurst commented on aeon/similarity_search/query_search/dummy.py
> +class DummyQuerySearch(BaseQuerySearch):
Similar to a different comment, but I would say the dummy estimators provide a "reasonable" baseline with a strategy (i.e. intentional random guessing or mean of the label), while mock estimators try to go through the interface as quick as possible even if the output is nonsense. May not apply here, but the top of the docstring gives that impression.

2024-05-29 12:09 UTC, MatthewMiddlehurst commented on aeon/similarity_search/distance_profiles/naive_distance_profile.py
> -@njit(cache=True, fastmath=True)
If this is kept, at the very least it should be noted in the docstring and we should change the test config to disable numba threading.

2024-06-02 09:36 UTC, baraline commented on aeon/similarity_search/query_search/dummy.py
> +class DummyQuerySearch(BaseQuerySearch):
The goal of dummy search is to return only the best match to the query, while other estimator may return something else (e.g. top k matches), changed doc string accordingly.

2024-06-02 09:38 UTC, baraline commented on aeon/similarity_search/tests/test_base.py
> +class BaseInstance(BaseSimiliaritySearch):
The only thing of interest to test, that will be common to all future similarity search classes, here is the mean/std computation function, would this be a case for a Mock or a Dummy estimator ? Or just test these functions outside of this context ?

2024-06-04 16:26 UTC, MatthewMiddlehurst commented on aeon/similarity_search/tests/test_base.py
> +class BaseInstance(BaseSimiliaritySearch):
If the main purpose is the test the function, I would just test it directly. If you are also testing other base class functionality i.e. the contents of `fit` and `predict` I would create a "mock" estimator to do so in the style of other modules.

2024-06-06 15:53 UTC, baraline commented on aeon/similarity_search/distance_profiles/naive_distance_profile.py
> -@njit(cache=True, fastmath=True)
Added set_num_threads back to prev_num_threads as in rocket, and #1604

2024-06-09 14:22 UTC, baraline commented on aeon/similarity_search/tests/test_base.py
> +class BaseInstance(BaseSimiliaritySearch):
After some reflection, I removed the base class for similarity search and moved its content to the base class of query search. A mock estimator has been created for query search base class.

2024-06-09 15:27 UTC, MatthewMiddlehurst commented
Any reason for the new base class direction? Do they other base classes not have much shared functionality?

2024-06-09 15:52 UTC, baraline commented
> Any reason for the new base class direction? Do they other base classes not have much shared functionality?

Yeah, after doing some pen and paper for the other two classes, the base class for similarity search would be pretty much empty. For example, index search will actually do things differently during fit as it need to build a similarity model, while series-search in the most naive way (without computational optimisations like MP) is simply looping over a query search for all possible candidates. The computational optimisations do require some rethinking of the fit also compared to query search.
So if we consider the three submodule, at least for now, I don't see a use for BaseSimilaritySearch class. Still possible to refactor afterward if we find a good reason to.

2024-06-09 15:55 UTC, baraline commented
On second thought, we could do the preprocess of the collection in it ... Would that be better for structure’s sake's ?

2024-06-09 16:12 UTC, MatthewMiddlehurst commented
Couple of things to consider but ofc can change later as you say.

If there are a significant number of shared parameters/attributes/functions used then it may be a good idea to keep even if its mostly abstract methods.

Also there may be some situations where you want to use `isinstance` to cover all of them? Maybe not also, not thought about it that much 🙂.

2024-06-09 17:45 UTC, baraline commented
> If there are a significant number of shared parameters/attributes/functions used then it may be a good idea to keep even if its mostly abstract methods.

For some reason, I forgot to consider this ... a bit out of touch today ! Swapping structure to add it back with the adjustment.

2024-06-14 14:09 UTC, baraline commented
Noticed some issue with the base class structure for the case of #1311, where the optimisation relies on lower bounding and not returning the distance profile fully computed, so I'll revamp it to be useable for all type of optimisations.

2024-06-16 18:02 UTC, baraline commented
Sorry for the mess in this PR ... To summarize :

The base query search class was made in the spirit of allowing any matching condition at the ouput of the search (e.g. top k matches, all matches below a distance threshold, ...). In practice, as there are only few plausible conditions: top k and/or threshold and worse-k and/or threshold, I just made a `QuerySearch` estimator with `k`, `threshold` and `inverse_distance` parameter that cover all these cases.

Additionally, there was the problem of computational optimisations that only compute part of the distance profiles (e.g. dtw lower bounding), but these optimisations need to know the matching condition (top-k, ...) to work. The previous structure would not have allowed that has distance profile computations were happening in the `BaseQuerySearch` class, which didn't have access to the matching condition.

2024-06-17 10:29 UTC, MatthewMiddlehurst commented on aeon/similarity_search/base.py
> +        set_num_threads(self._n_jobs)
where is `self._n_jobs` defined? may be missing it.

2024-06-17 10:29 UTC, MatthewMiddlehurst commented on aeon/similarity_search/base.py
> +            X = List(X)
May be worth just doing this always? not sure how much the code differs later because of the different from lists and numpy arrays. If it has to be separate anyway no issue.

Doesnt have to be now, feel free to ignore.

2024-06-17 11:53 UTC, baraline commented on aeon/similarity_search/base.py
> +            X = List(X)
I'm asking myself the same question, as you have to use the List indexing anyway to be compatible with unequal length... I think there was something performance related, but I'll have to take a closer look and do some benchmarking to be sure.

2024-06-17 11:55 UTC, baraline commented on aeon/similarity_search/base.py
> +        set_num_threads(self._n_jobs)
It is defined in the preprocess collection method of the BaseCollectionEstimator [here](https://github.com/aeon-toolkit/aeon/blob/d37a77fcd506757112e1f4dfccfca64c2b64acee/aeon/base/_base_collection.py#L46C9-L46C31)

2024-06-17 13:13 UTC, MatthewMiddlehurst approved these changes
Fine with this going in if you are happy with it @baraline. If any issues arise can be dealt with in a separate PR.

2024-06-17 13:17 UTC, merged