[DOC] Update classification API docs
aeon-toolkit/aeon pull request #1510
Opened 2024-05-10 14:33 UTC by itsdivya1309

#### Reference Issues/PRs
Closes: #1497 

#### What does this implement/fix? Explain your changes.

Adds classifiers to the existing list and arranges them in lexicographic order.

### PR checklist

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [x] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

2024-05-12 13:06 UTC, baraline requested changes
Hi @itsdivya1309 Thanks for the PR. Mostly looking good, see the two comments, also, you can add the TEASER classifier in the early classification section.

2024-05-12 13:06 UTC, baraline commented on docs/api_reference/classification.rst
>      CanonicalIntervalForestClassifier
Aren't we missing RSTSF as classifier in this section ?

2024-05-12 13:06 UTC, baraline commented on docs/api_reference/classification.rst
> +    RDSTClassifier
RDSTClassifier is a shapelet classifier

2024-05-12 14:42 UTC, itsdivya1309 commented on docs/api_reference/classification.rst
>      CanonicalIntervalForestClassifier
Yeah, I missed that, thanks.

2024-05-12 14:42 UTC, itsdivya1309 commented on docs/api_reference/classification.rst
> +    RDSTClassifier
Yup, thanks for pointing this out. I've corrected this.

2024-05-13 05:19 UTC, baraline approved these changes
Everything looks good to me !

2024-05-13 05:20 UTC, merged