[BUG] mpdist window length
aeon-toolkit/aeon pull request #1513
Opened 2024-05-11 16:23 UTC by TonyBagnall

fixes https://github.com/aeon-toolkit/aeon/issues/1498

the window length (called m for some reason) has as default value of 0, which means its set to a quarter of the length of the series. However, this check was happening after forming the windows, so it was trying to form windows with 0 length. 

I think it might be better to just use stumpy for this, m = None should be the default and k/threshold should definitely be a parameter. I will see if it makes a difference in a separate PR

2024-05-12 19:15 UTC, MatthewMiddlehurst commented
could you make a change to run the CI again? If there are other problems would be good to create an issue.

2024-05-13 06:57 UTC, baraline requested changes

2024-05-13 06:57 UTC, baraline commented on aeon/distances/_mpdist.py
> +            m = int(len_y / 4)
If you do this operation here but `len_x > 4 * len_y` you are going to throw errors down the line.

2024-05-13 06:57 UTC, baraline commented on aeon/distances/_mpdist.py
> +        )
This should be after the handling of the `m=0` case

2024-05-13 06:58 UTC, baraline commented
Overall I agree that having m=0 just feels weird as default value, None would be better !

2024-05-13 18:47 UTC, baraline approved these changes
LGTM to me now !

2024-05-14 08:04 UTC, merged