[ENH] Type hints for primitives and string arguments:Part3
aeon-toolkit/aeon pull request #1525
Opened 2024-05-13 20:25 UTC by nileenagp

Reference Issues/PRs
Part of https://github.com/aeon-toolkit/aeon/issues/1454

What does this implement/fix? Explain your changes.
Adding type hints to remaining scripts in : aeon/classification/sklearn/_continuous_interval_tree.py ( Existing class _TreeNode, has been moved above ContinuousIntervalTree, in order to include the type[_TreeNode] in the type hints)  

aeon/classification/shapelet_based scripts. 

Does your contribution introduce a new dependency? If yes, which one?
None

Any other comments?
Type hints are NOT added in other methods since they were not primitive types.

2024-05-20 08:58 UTC, baraline requested changes

2024-05-20 08:58 UTC, baraline commented on aeon/classification/shapelet_based/_rdst.py
>          threshold_percentiles=None,
Both shapelet lengths and threshold percentiles can be Union of None and list of int

2024-05-20 08:58 UTC, baraline commented on aeon/classification/shapelet_based/_sast_classifier.py
>          length_list=None,
Same, this could be Union of None and list of int

2024-05-20 08:58 UTC, baraline commented on aeon/classification/sklearn/_continuous_interval_tree.py
> +        self, random_state: Union[int, Type[np.random.RandomState], None] = None
Why is this different from the one that you defined before ? (`random_state: Union[int, np.random.RandomState, None]`) Is there a reason to use `Type` here ?

2024-05-20 08:58 UTC, baraline commented on aeon/classification/sklearn/_continuous_interval_tree.py
> +        random_state: Union[int, Type[np.random.RandomState], None] = None,
Same as previous comment.

2024-05-22 19:04 UTC, nileenagp commented on aeon/classification/sklearn/_continuous_interval_tree.py
> +        self, random_state: Union[int, Type[np.random.RandomState], None] = None
I have used Type to indicate the that it could be a Type of np.random.RandomState class.  I missed to include that in 2 places, which are updated now, Thanks for pointing it out!

2024-05-22 19:07 UTC, nileenagp commented on aeon/classification/shapelet_based/_rdst.py
>          threshold_percentiles=None,
Yes, for now I am including the type hints for primary types and other simple types. array types are excluded for now as per the issue description, hence these are left blank.

2024-05-25 20:35 UTC, baraline approved these changes
Looks good to me, thanks for the contribution !

2024-05-25 20:36 UTC, merged