[DOC] Update the `ElasticEnsemble` documentation
aeon-toolkit/aeon pull request #1544
Opened 2024-05-20 15:12 UTC by itsdivya1309

#### Reference Issues/PRs
Closes: #1496 

#### What does this implement/fix? Explain your changes.
- Changes `dwdtw` to `wddtw` in the Parameters section of distance_measures 
-  Modifies docstring for `get_metric_params()`
-  Adds docstring for `_get_100_param_options()`

2024-05-20 19:46 UTC, baraline requested changes
Other than the these two comments, it solves the described issue, distances and references sections are correctly reformatted. Nice job !

2024-05-20 19:46 UTC, baraline commented on aeon/classification/distance_based/_elastic_ensemble.py
>      https://link.springer.com/article/10.1007/s10618-014-0361-2
It would be better if the link was after the reference it links to. See [BOSSEnsemble API doc](https://www.aeon-toolkit.org/en/stable/api_reference/auto_generated/aeon.classification.dictionary_based.BOSSEnsemble.html#aeon.classification.dictionary_based.BOSSEnsemble) as example.

2024-05-20 19:46 UTC, baraline commented on aeon/classification/distance_based/_elastic_ensemble.py
> +      ``lcss``, ``erp``, ``msm``, ``twe``, all
To me, the `all` option should be presented after the list of distances, as it doesn't make sense to have, for example, `["dtw", "all"]`. 
Something like:
`
... , ``msm``, ``twe``. The default value ``all`` means that all the previously listed distances are used.
`

2024-05-21 08:06 UTC, baraline approved these changes
LGTM ! Did you have anything else in mind @MatthewMiddlehurst ?

2024-05-21 09:55 UTC, MatthewMiddlehurst commented
Nope, LGTM.

2024-05-21 09:55 UTC, merged