[ENH] Simple feature based clusterers
aeon-toolkit/aeon pull request #1548
Opened 2024-05-20 17:14 UTC by MatthewMiddlehurst

Implements simple feature clusterers. Includes:
- Catch22Clusterer
- SummaryClusterer
- TSFreshClusterer

2024-05-23 19:29 UTC, hadifawaz1999 commented on aeon/clustering/feature_based/_catch22.py
> +    estimator : sklearn clusterer, default=None
suggestion, in deep clustering we went with these two parameters:
n_clusters
clustering_algorithm: str
and clustering_params: dict, containng by default n_clusters
do you think we should do the same here ? or even change deep learning to be like here ? just to be consistent

2024-05-23 19:33 UTC, hadifawaz1999 commented on aeon/clustering/feature_based/_catch22.py
> +    """
would be good to have an example

2024-05-23 19:37 UTC, hadifawaz1999 requested changes
let me know what you think of the comments

2024-05-23 19:37 UTC, hadifawaz1999 commented on aeon/clustering/feature_based/_catch22.py
> +        y : 1D np.array, of shape [n_cases] - class labels for fitting
maybe should add that is ignored ? because i think C22 is class independent

2024-05-23 19:37 UTC, hadifawaz1999 commented on aeon/clustering/feature_based/_catch22.py
> +        }
maybe we should add a predict proba too ?

2024-05-23 19:37 UTC, hadifawaz1999 commented on aeon/clustering/feature_based/_summary.py
> +    def __init__(
same comments for the 2 other clusterers

2024-05-29 13:15 UTC, MatthewMiddlehurst commented on aeon/clustering/feature_based/_catch22.py
> +    estimator : sklearn clusterer, default=None
estimator fits better with the rest of the package IMO. 

I dont think `n_clusters` fits here? What is the base estimator does not have a `n_clusters` parameter?

2024-05-29 14:53 UTC, hadifawaz1999 commented on aeon/clustering/feature_based/_catch22.py
> +    estimator : sklearn clusterer, default=None
okay i see, good point

2024-06-15 15:41 UTC, MatthewMiddlehurst commented
@hadifawaz1999 could you re-review this. Thanks.

2024-06-17 06:57 UTC, hadifawaz1999 approved these changes
LGTM !

2024-06-17 16:41 UTC, merged