[ENH] Implement Proximity Forest classifier using aeon.distances
aeon-toolkit/aeon pull request #1566
Opened 2024-05-24 14:48 UTC by itsdivya1309

Will fix: #159 
(Work under progress)
Tried to code the `get_candidate_splitter`, will try to make it work with numba.

2024-05-25 18:31 UTC, TonyBagnall commented
this is good. From our end @MatthewMiddlehurst we should set up a pipeline for running experiments to check equivalence to the Java results, as that was the heart of the problem last time. No rush of course, project has not started yet :)

2024-06-17 03:27 UTC, itsdivya1309 commented
I have completed the framework for Proximity Tree along with it's API.

2024-06-17 14:45 UTC, baraline reviewed
Some first comment on “surface” content, I'll have a proper look at the algorithmic correctness a bit later

2024-06-17 14:45 UTC, baraline commented on aeon/classification/distance_based/_proximity_tree.py
> +
The docstring for the Node class parameter is missing.

2024-06-17 14:45 UTC, baraline commented on aeon/classification/distance_based/_proximity_tree.py
> +        y : np.array shape (n_cases,) or (n_cases,1)
Missing the description of `y`.

2024-06-17 14:45 UTC, baraline commented on aeon/classification/distance_based/_proximity_tree.py
> +            exemplars[y_new[id]] = X_new[id, :]
You could simplify this bit to avoid creating the `X_new` and `y_new` arrays. For example, you could create at the beginning of fit a private class attribute that store the class locations :
``` python
self.class_locs = []
for label in np.unique(y):
    self.class_locs.append(np.where(y==label)[0]) # use [0] as y is 1D
```
Then you could use this attribute to pick a sample by `id` from it directly
```python
for label in np.unique(y):
      id = rng.randint(0, self.class_locs[label].shape[0])
      exemplars[label] = X[id, :]
```

2024-06-18 22:25 UTC, MatthewMiddlehurst requested changes
Looks good for the most part, left a few comments. We may revisit this later down the line if there are issues, but appears to be fine for now.

I would add this to the API documentation in `docs/` in this PR.

There are some `if` statements here which are not covered by testing. Not going to block this PR because of them, but if you find the time and can figure out how to get to them reasonably it would be nice. https://app.codecov.io/gh/aeon-toolkit/aeon/pull/1566/blob/aeon/classification/distance_based/_proximity_tree.py

2024-06-18 22:25 UTC, MatthewMiddlehurst commented on aeon/classification/distance_based/_proximity_tree.py
> +    weighted sum of Gini impurity of the child nodes.
Think this needs another read-through, we can help if required.

i.e. "A Proximity Tree is similar to a decision tree classifier" It is a decision tree classifier rather than similar to and the final sentence ends a bit abruptly.

2024-06-18 22:25 UTC, MatthewMiddlehurst commented on aeon/classification/distance_based/_proximity_tree.py
> +    n_jobs : int, default = None
defaults to 1

2024-06-18 22:25 UTC, MatthewMiddlehurst commented on aeon/classification/distance_based/_proximity_tree.py
> +
It would be nice to have a bit of documentation here summarising the function.

2024-06-18 22:25 UTC, MatthewMiddlehurst commented on aeon/classification/distance_based/tests/test_proximity_tree.py
I think it would be good to add a test giving the tree an extremely easy problem (i.e. random data where one half has larger values for class 0 and the other half has larger values for class 1). You can then test that the `accuracy_score` after `fit` and `predict` is `>=0.9` or similar. It should be able to do this IMO.

2024-06-18 22:27 UTC, MatthewMiddlehurst commented
Try merging the main branch for the `pre-commit` test, I will take a further look if it does not work after.

2024-06-19 03:53 UTC, itsdivya1309 commented on aeon/classification/distance_based/_proximity_tree.py
> +            exemplars[y_new[id]] = X_new[id, :]
Hi, thanks for the suggestion, but when I define the `class_locs` in the fit method, it gives an error, probably because the splitter method is called at every node, and only parts of the data are present there.

So, would it be OK to define the `class_locs` attribute in the splitter method? I tried it, and it doesn't raise an error.

2024-06-19 05:32 UTC, baraline commented on aeon/classification/distance_based/_proximity_tree.py
> +            exemplars[y_new[id]] = X_new[id, :]
Oh, what type of errors exactly ? The point is to avoid recomputations when possible, especially as the method will be called many time

2024-06-19 06:16 UTC, itsdivya1309 commented on aeon/classification/distance_based/_proximity_tree.py
> +            exemplars[y_new[id]] = X_new[id, :]
It gives Index Error, index out of bound.

2024-06-19 06:42 UTC, itsdivya1309 commented
> Try merging the main branch for the `pre-commit` test, I will take a further look if it does not work after.

I have merged the main branch, but it is still failing.

2024-06-19 15:28 UTC, itsdivya1309 commented on aeon/classification/distance_based/tests/test_proximity_tree.py
I have added a test for this.

2024-06-19 15:30 UTC, itsdivya1309 commented on aeon/classification/distance_based/_proximity_tree.py
> +    weighted sum of Gini impurity of the child nodes.
Please have a look, I have updated the text.

2024-06-19 15:58 UTC, baraline commented on aeon/classification/distance_based/_proximity_tree.py
> +            exemplars[y_new[id]] = X_new[id, :]
Ok, then don't worry about it for now, we'll look at such optimisations once the base structure will be validated

2024-06-21 14:29 UTC, TonyBagnall submitted a review, later dismissed
non blocking changes from me, looks good

2024-06-27 15:26 UTC, TonyBagnall approved these changes
lgtm, thanks

2024-06-27 15:26 UTC, merged