[ENH] Add DummyClusterer
aeon-toolkit/aeon pull request #1567
Opened 2024-05-25 10:11 UTC by aadya940

Closes #1528 .

2024-05-25 17:19 UTC, TonyBagnall requested changes
great stuff, but could you also test the _score function for coverage?

2024-05-25 18:58 UTC, aadya940 commented
> great stuff, but could you also test the _score function for coverage?

I will, sorry for the oversight. 🙂

2024-05-26 09:59 UTC, aadya940 commented
@TonyBagnall Hello, I don't think the failure is related to this PR. wdyt?

2024-05-27 11:20 UTC, MatthewMiddlehurst commented
Agreed, rerunning it.

Unrelated to this PR but I'm not sure I'm a fan of score being the way it is currently. See https://github.com/aeon-toolkit/aeon/issues/1530.

2024-05-28 22:27 UTC, MatthewMiddlehurst approved these changes

2024-06-03 19:33 UTC, TonyBagnall approved these changes

2024-06-03 19:33 UTC, merged