[ENH] Convert stray and add max iterations for MERLIN
aeon-toolkit/aeon pull request #1571
Opened 2024-05-25 17:30 UTC by MatthewMiddlehurst

#### What does this implement/fix? Explain your changes.

Converts `STRAY` to the new anomaly detection format. Currently only outs booleans, previous some sort of score was stored in a class attribute.

Adds max iterations to `MERLIN` and stops it from processing NaNs

2024-05-26 20:27 UTC, CodeLionX requested changes
Having the distance-calculation loop repeated three times really hurts my eyes. There are some minor differences from loop to loop, but maybe we can improve this. In addition, I don't know how fast this MERLIN implementation is, but the loops in the `_predict`-function also look like good candidates for jitting.

I have also found this useless comparison of numbers with `np.nan`, which always holds:

https://github.com/aeon-toolkit/aeon/blob/4135913df01fd1d84658858497d38d15649691d7/aeon/anomaly_detection/_merlin.py#L135-L137

`np.nan != np.nan` is also true:
![image](https://github.com/aeon-toolkit/aeon/assets/10573700/04391b54-558f-4b50-9a6b-fe43ad868219)

2024-05-26 20:27 UTC, CodeLionX commented on aeon/anomaly_detection/_merlin.py
> +                distances[0] = 2 * np.sqrt(self.min_length)
Where is the upper-bound distance `2 * np.sqrt(self.min_length)` coming from? `r` is also initialized to it. Should we create a constant for it?

2024-05-26 20:27 UTC, CodeLionX commented on aeon/anomaly_detection/_merlin.py
> +            if it > 500:
Why 500 iterations? Should this be a parameter?

2024-05-29 14:47 UTC, MatthewMiddlehurst commented on aeon/anomaly_detection/_merlin.py
> +            if it > 500:
done

2024-05-29 14:49 UTC, MatthewMiddlehurst commented on aeon/anomaly_detection/_merlin.py
> +                distances[0] = 2 * np.sqrt(self.min_length)
That just happens to be the length for this loop, it's reset to the current length in later ones. 

This is not part of the algorithm, but it seems sensible to reset the upper bound if we have to cancel due to no anomalies being found for the length, given that the later `r` values are derived from the previous distances.

2024-05-29 14:50 UTC, MatthewMiddlehurst commented
Removed the `np.nan` and moved the loop to a function. Could probably work it around to jit it, but would have to remove the function input

2024-05-29 15:47 UTC, CodeLionX commented on aeon/anomaly_detection/_merlin.py
> +                distances[0] = 2 * np.sqrt(self.min_length)
Ah, I see. This was not obvious to me.

2024-05-29 15:48 UTC, CodeLionX approved these changes
LGTM now.

2024-06-03 19:34 UTC, merged