[ENH] Add DCNNEncoderNetwork
aeon-toolkit/aeon pull request #1576
Opened 2024-05-27 09:07 UTC by aadya940

Implement Dilated Convolutional Neural Network based Auto-Encoder.

2024-05-27 10:00 UTC, hadifawaz1999 requested changes
good start, a few comments on the network

2024-05-27 10:00 UTC, hadifawaz1999 commented on aeon/networks/_dcnn.py
> +        dilation_rate=None,
activation not placed in correct order following the docstring

2024-05-27 10:00 UTC, hadifawaz1999 commented on aeon/networks/_dcnn.py
> +        """Construct a network and return its input and output layers.
its preferable to keep the constructor to assigning private members, and all this stuff to be inside the build network function

2024-05-27 10:00 UTC, hadifawaz1999 commented on aeon/networks/_dcnn.py
> +        def DCNNLayer(inputs, num_filters, dilation_rate, activation):
the function should be a private function and direct member of the class, not a function inside the build network. Should be called _dcnn_layer

2024-05-27 10:00 UTC, hadifawaz1999 commented on aeon/networks/_dcnn.py
> +        kernel_size=3,
i think its good to even give user ability to control the kernel size for each layer, same for activation as well, shouldnt be obligation that its the same through all the network

2024-05-27 10:00 UTC, hadifawaz1999 commented on aeon/networks/_dcnn.py
> +            self.num_filters = [32 * i for i in range(1, self.model_depth + 1)]
should check the same for num_filters if it was a list, that it has the same length as model_depth

2024-05-27 10:00 UTC, hadifawaz1999 commented on aeon/networks/_dcnn.py
> +        self.model_depth = num_layers
naming shouldnt change, should stay num_layers

2024-05-27 10:00 UTC, hadifawaz1999 commented on aeon/networks/_dcnn.py
> +        encoder : a keras Model.
the build_network at the end should return model not encoder (check first comment above)

2024-05-27 10:00 UTC, hadifawaz1999 commented on aeon/networks/_dcnn.py
> +class DCNNEncoderNetwork(BaseDeepNetwork):
If am not mistaken DCNN is not an auto encoder based, so you can actually remove the naming "Encoder" and just keep DCNNNetwork

2024-05-27 14:51 UTC, aadya940 commented
Done :-) , Thanks for the quick review.

2024-05-31 13:28 UTC, hadifawaz1999 commented
make an issue to add again the weight normalization code

2024-05-31 13:33 UTC, hadifawaz1999 commented on aeon/networks/_dcnn.py
> +    """Establish the network structure for a DCNN-Model.
do not override private members

2024-06-14 08:46 UTC, hadifawaz1999 submitted a review, later dismissed
lgtm!

2024-06-21 13:30 UTC, MatthewMiddlehurst commented
> make an issue to add again the weight normalization code

Was this done?

2024-06-21 13:35 UTC, aadya940 commented
> > make an issue to add again the weight normalization code
> 
> Was this done?

Nope, will do it.

2024-07-09 08:38 UTC, hadifawaz1999 requested changes
LGTM this one given its not an AUTO ENCODER network, you can remove the temporal_latent_space thing
And you should add the _config parameter

2024-07-12 06:53 UTC, hadifawaz1999 requested changes

2024-07-12 06:53 UTC, hadifawaz1999 commented on aeon/networks/tests/test_dcnn.py
> +
temporal_latent_space should be removed from the tests also for this network

2024-08-02 19:29 UTC, hadifawaz1999 commented
there is a conflict with main @aadya940

2024-08-07 15:50 UTC, hadifawaz1999 commented on aeon/networks/_dcnn.py
> +    num_layers: int, default=4
i would prefer if n_layers is the same on all networks instead of num_layers

2024-08-10 10:05 UTC, hadifawaz1999 requested changes

2024-08-10 10:05 UTC, hadifawaz1999 commented on aeon/networks/_dcnn.py
> +    num_filters: int, default=None
n_filters

2024-08-10 10:05 UTC, hadifawaz1999 commented on aeon/networks/_dcnn.py
> +        num_filters=None,
n_filters

2024-08-12 17:25 UTC, hadifawaz1999 commented on aeon/networks/_dcnn.py
> +    @article{franceschi2019unsupervised,
can you put the citation in non bib format ?

2024-08-12 17:25 UTC, hadifawaz1999 commented on aeon/networks/_dcnn.py
> +        Arguments
Parameters instead of Arguments

2024-08-12 17:27 UTC, hadifawaz1999 commented on aeon/networks/_dcnn.py
> +            assert len(self._activation) == self.n_layers
typo activation instead of _activation in assert

2024-08-12 17:28 UTC, hadifawaz1999 commented on aeon/networks/_dcnn.py
> +        Dimension of the models's latent space.
can you add for the input parameters that are list format what would be the default list in the docstring ?

2024-08-12 17:28 UTC, hadifawaz1999 requested changes
last comments :)

2024-08-13 10:30 UTC, aadya940 commented
#1962

2024-08-16 16:20 UTC, aadya940 commented on aeon/networks/_dcnn.py
> +            assert len(self._activation) == self.n_layers
Once, `self._activation` is equal to `self.activation` in line 106, It doesn't really make a difference.

2024-08-17 11:43 UTC, hadifawaz1999 commented on aeon/networks/_dcnn.py
> +    n_filters: Union[int, List[int]], default=None
can you add a sentence to n_filters and dilation_rate to how the default values are calculated ?

2024-08-17 11:46 UTC, hadifawaz1999 commented on aeon/networks/_dcnn.py
> +        n_filters=None,
should have a padding parameter, default to the value used in the original paper, also will be a list for all layers like you handle activation

2024-08-17 11:53 UTC, hadifawaz1999 requested changes
final changes i think, also can you make the activation detached as its own layer instead then inside the conv ?

2024-08-19 08:09 UTC, aadya940 commented on aeon/networks/_dcnn.py
> +    n_filters: Union[int, List[int]], default=None
Haven't I already? Check Line 31 and Line 28.

2024-11-01 02:04 UTC, hadifawaz1999 approved these changes

2024-11-01 02:04 UTC, merged