[ENH] Add AEDRNNNetwork
aeon-toolkit/aeon pull request #1577
Opened 2024-05-27 15:32 UTC by aadya940

Implements Auto-Encoder Network based on Dilated Recurrent Neural Networks.

2024-05-31 13:12 UTC, hadifawaz1999 commented on aeon/networks/_ae_drnn.py
> +        dilation_rate=None,
even if decoder doesnt have dilation, define dilation_rate_decoder and default to1, make sure to put this in the docstrings

2024-05-31 13:35 UTC, hadifawaz1999 requested changes

2024-05-31 13:35 UTC, hadifawaz1999 commented on aeon/networks/_ae_drnn.py
> +    activation : str, default="relu"
if the input is a list keep a list, by default none transformed to a list of default values, and if one element wrap it to list

2024-06-03 08:04 UTC, aadya940 commented
@MatthewMiddlehurst Do the tests look Okay?

2024-06-03 14:59 UTC, hadifawaz1999 commented on aeon/networks/_ae_drnn.py
> +        dilation_rate=None,
dilation_rate_encoder

2024-06-03 15:00 UTC, hadifawaz1999 commented on aeon/networks/_ae_drnn.py
> +        n_units=None,
also 2 parameters for n_units, encoder and decoder

2024-06-03 15:03 UTC, hadifawaz1999 requested changes

2024-06-03 15:03 UTC, hadifawaz1999 commented on aeon/networks/_ae_drnn.py
> +    temporal_latent_space : bool, default = False
would be good to have it as the first parameter next to latent space dim

2024-06-03 15:03 UTC, hadifawaz1999 commented on aeon/networks/_ae_drnn.py
> +                activation="relu",
activation here should be linear as for the dense in the case its not a temporal latent space

2024-06-03 16:30 UTC, MatthewMiddlehurst commented on aeon/networks/tests/test_ae_drnn.py
> +def pytest_generate_tests():
This seems very overkill, if you want to parameterise I would just do it in the decorator rather than using a function to generate it.

This is probably generating way too many tests. Unless there is a reason to have them together, try split some off into different functions so it isn't growing the parameter set multiplicatively.

2024-06-03 16:30 UTC, MatthewMiddlehurst commented on aeon/networks/tests/test_ae_drnn.py
> +    encoder, decoder = aedrnn.build_network((1000, 5))
What is the input here? Does this need to be 1000, and does the input size impact how long this takes to run? 

We want these to be as quick as possible while remaining useful.

2024-06-03 16:50 UTC, aadya940 commented on aeon/networks/tests/test_ae_drnn.py
> +    encoder, decoder = aedrnn.build_network((1000, 5))
Nope, when we call `build_network` , tensorflow will only compile the code to Tensorflow Graph (tf.Graph) which is invariant of the input shape. It's just a dummy input shape.

2024-06-04 07:14 UTC, aadya940 commented on aeon/networks/_ae_drnn.py
> +        n_units=None,
From what I understand, number of units in the decoder are computed using number of units in the encoder as per this line "The decoder is composed of a single RNN layer with GRU units of size (100+50+50) × 2 = 400". Hence, I've done this deliberately. What do you think?

2024-06-04 10:41 UTC, MatthewMiddlehurst commented on aeon/networks/tests/test_ae_drnn.py
> +    encoder, decoder = aedrnn.build_network((1000, 5))
What exactly is the input doing if it has no impact on performance? I assume theres no actual building going on in the method its all just initialisation. I would still reduce it if possible just in case its using extra memory under the hood.

2024-06-04 10:43 UTC, MatthewMiddlehurst commented
Coverage reports are being uploaded now, see the checks. 

Report for the network is here: https://app.codecov.io/gh/aeon-toolkit/aeon/pull/1577/blob/aeon/networks/_ae_drnn.py

2024-06-04 10:59 UTC, aadya940 commented on aeon/networks/tests/test_ae_drnn.py
> +    encoder, decoder = aedrnn.build_network((1000, 5))
So what happens is when we call the `build_network` method, it will Compute the shape of the tensor before/after passing through each layer (use `model.summary()` to take a look). However, it doesn't allocate any memory under the hood until we call the `fit` method. Hence, the magnitude of the input shape doesn't amount to any additional overhead until we call the `fit` method on the model.

2024-06-04 11:01 UTC, aadya940 commented on aeon/networks/tests/test_ae_drnn.py
> +    encoder, decoder = aedrnn.build_network((1000, 5))
I'll reduce it though.

2024-06-04 11:42 UTC, aadya940 commented
Can we recheck the coverage? @MatthewMiddlehurst

2024-06-04 14:46 UTC, MatthewMiddlehurst commented
You can navigate to it in the actions tab.

2024-06-05 07:49 UTC, aadya940 commented
Now its 95% coverage, which is Okay I guess? @MatthewMiddlehurst

2024-06-05 13:19 UTC, MatthewMiddlehurst commented
It would be good to cover the partials if possible, but I'm not going to demand 100%. Keep in mind testing is more than coverage, there probably not a lot to do here since its a single method with general testing also, but we do want to make sure that the output is correct and errors are properly raised as well where possible.

2024-06-14 07:37 UTC, hadifawaz1999 commented on aeon/networks/_ae_drnn.py
> +        n_units=None,
the default behavior can be like that, but i think its best to give ability to the user to control this parameter
if none is chosen for the number of units decoder, than it can be this as default

2024-06-26 16:06 UTC, MatthewMiddlehurst commented on aeon/networks/_ae_drnn.py
> +    _config["auto-encoder"] = True
Would this work? I was assuming you would have to redefine the dictionary here.

It's fine I guess as long as it is isolated to this class and does not impact others.

2024-06-26 17:10 UTC, aadya940 commented on aeon/networks/_ae_drnn.py
> +    _config["auto-encoder"] = True
Yes , it will work :)

![image](https://github.com/aeon-toolkit/aeon/assets/77720426/3e6f0424-d7c6-4fc6-8d7c-418fac500e03)

2024-06-26 17:19 UTC, aadya940 commented on aeon/networks/_ae_drnn.py
> +    _config["auto-encoder"] = True
However, this will also tweak the "auto-encoder" key of the base class as well.

2024-06-26 17:21 UTC, aadya940 commented on aeon/networks/_ae_drnn.py
> +    _config["auto-encoder"] = True
So, we should also explicitly define _config["auto-encoder"]=False for non auto encoders as it could cause issues while spawning multiple threads?

2024-06-27 08:02 UTC, aadya940 commented on aeon/networks/_ae_drnn.py
> +    _config["auto-encoder"] = True
Then we could remove `_config` from the Base Class, else wouldn't it be the same thing?

2024-07-09 08:16 UTC, hadifawaz1999 requested changes
just left some final comments

2024-07-09 08:16 UTC, hadifawaz1999 commented on aeon/networks/_ae_drnn.py
> +    n_layers_decoder : int, default = 3
default in doc should be 1 not 3

2024-07-09 08:16 UTC, hadifawaz1999 commented on aeon/networks/_ae_drnn.py
> +            self._n_units_decoder = [
i would name the two variables 2 different things
so i would do this:
```
self._n_units_decoder_ = sum(self._n_units_encoder) * 2
self._n_units_decoder = [
                self._n_units_decoder_ for _ in range(self.n_layers_decoder)
            ]
```

2024-07-09 08:16 UTC, hadifawaz1999 commented on aeon/networks/_ae_drnn.py
> +            if i < self.n_layers_decoder - 1:
why dilate only on last layer ?

2024-07-10 09:39 UTC, aadya940 commented on aeon/networks/_ae_drnn.py
> +            if i < self.n_layers_decoder - 1:
Isn't it all layers except the last layer?

2024-07-12 06:49 UTC, hadifawaz1999 commented on aeon/networks/_ae_drnn.py
> +            if i < self.n_layers_decoder - 1:
gonna reformulate my question then, why not dilate the last layer:p

2024-07-12 07:39 UTC, aadya940 commented on aeon/networks/_ae_drnn.py
> +            if i < self.n_layers_decoder - 1:
From what I remember it was to make it symmetric with the encoder. In the encoder we dilate the input for all layers except the last one and so we follow the same in the decoder.

2024-07-12 16:35 UTC, hadifawaz1999 commented on aeon/networks/_ae_drnn.py
> +            if i < self.n_layers_decoder - 1:
but in this case the decoder should dilate every layer except the first one
to be symmetrical
if the encoder has 4 layers, the first three dilated the last one no, then the decoder should be made of 4 layers, the first not dilated and the last three yes

2024-07-24 13:14 UTC, hadifawaz1999 commented on aeon/networks/_ae_drnn.py
> +                )
two issues here:

- decoder_gru is calling Lambda layer wihtout taking any input
- the loop seems to take the same input again and again "expanded_latent_space"

2024-07-26 14:04 UTC, hadifawaz1999 commented on aeon/networks/_ae_drnn.py
> +    class _TensorDilation(tf.keras.layers.Layer):
the fail on drnn i think is coming from here, because u didnt add a docstring to the new class
simply put a sentence that ends will full stop between """ """ under the class definition
image.png

2024-07-28 14:50 UTC, hadifawaz1999 requested changes

2024-07-28 14:50 UTC, hadifawaz1999 commented on aeon/networks/_ae_drnn.py
> +    class _TensorDilation(tf.keras.layers.Layer):
@aadya940 probably should check python version as well

2024-07-28 14:58 UTC, hadifawaz1999 commented on aeon/networks/_ae_drnn.py
> +if _check_soft_dependencies(["tensorflow"], severity=None):
its "none" to my knowledge not None

2024-07-28 23:34 UTC, hadifawaz1999 requested changes
For this network, some changes should be done as follows:

- Given the encoder dilates all layers except the last one, then the symmetrical view is to dilate all layers in the decoder except the first one, the code is not currently doing this
- Following the above comment, in the case of default setup where the decoder has only one layer, simply follow what the original paper decided to do, if they dilate it then yes if not then no
- When temporal latent space is chosen, the logic of the whole network changes as the final states are no longer being used, given this is not the in the original proposal and more an enhancement we are adding, am happy to leave the logic as is for now like you did (i dont see other options now) but we should brainstorm a better way to do it

2024-07-28 23:43 UTC, hadifawaz1999 commented on aeon/networks/_ae_drnn.py
> +    class _TensorDilation(tf.keras.layers.Layer):
python version here probably is breaking CI as for some reason CI is failing on 3.12 (talking about the clusterer PR depends on this one)

2024-07-29 08:30 UTC, aadya940 commented
Looks good now? @hadifawaz1999

2024-07-30 07:52 UTC, hadifawaz1999 commented
> Looks good now? @hadifawaz1999

you seem to be dilating all encoder's layers now, why the change ? @aadya940

2024-07-30 10:21 UTC, aadya940 commented
Oh by the way @hadifawaz1999, I forgot to tell you that dilation layers are placed as they currently are because this is the configuration that works with `temporal_latent_space = True`, this is a little different from the paper implementation because they don't use dilation in the decoder but we decided to use it. I hope it makes sense :)) 

If we aim for symmetrical `_TensorDilation` layer configurations for encoder and decoder, the output shape of the decoder deviates from what it should be eg: Instead of (100, 2), the output shape would turn out (50, 2). Thats why I've built the network in such a way that we don't have this issue.

2024-07-30 12:28 UTC, hadifawaz1999 commented
> Oh by the way @hadifawaz1999, I forgot to tell you that dilation layers are placed as they currently are because this is the configuration that works with `temporal_latent_space = True`, this is a little different from the paper implementation because they don't use dilation in the decoder but we decided to use it. I hope it makes sense :))
> 
> If we aim for symmetrical `_TensorDilation` layer configurations for encoder and decoder, the output shape of the decoder deviates from what it should be eg: Instead of (100, 2), the output shape would turn out (50, 2). Thats why I've built the network in such a way that we don't have this issue.

aaahh okay okay i see what you did there :) i understand why you did the condition now, okay keep it like that then thanks for the explanation

2024-08-02 19:30 UTC, hadifawaz1999 commented
should merge main to remove pre-commit fail @aadya940

2024-08-10 10:03 UTC, hadifawaz1999 approved these changes
all looks good should just add it to api

2024-08-13 10:30 UTC, aadya940 commented
#1962

2024-08-16 14:35 UTC, merged