Add AEBiGRUNetwork
aeon-toolkit/aeon pull request #1583
Opened 2024-05-31 08:19 UTC by aadya940

Implements Auto-Encoder based on BiDirectional GRU Network.

2024-05-31 13:36 UTC, hadifawaz1999 requested changes

2024-05-31 13:36 UTC, hadifawaz1999 commented on aeon/networks/_ae_bgru.py
> +        latent_space_dim : int, default=128
temporal_latent_space, default False, and if set to True, make sure that the output of the encoder is temporal series

2024-06-14 07:45 UTC, hadifawaz1999 commented on aeon/networks/tests/test_ae_bgru.py
> +from aeon.networks import AEBiGRUNetwork
would be good to test if when temporal_latent_space is True does the space really become temporal or not, just checking the shapes i mean

2024-06-14 07:57 UTC, hadifawaz1999 commented on aeon/networks/tests/test_ae_bgru.py
> +from aeon.networks import AEBiGRUNetwork
can leave that for later though :)
wanna get the networks in

2024-07-09 08:23 UTC, hadifawaz1999 requested changes
this is good to go, just need the test to assert the shapes of input and output of the network are the same

2024-07-09 08:25 UTC, hadifawaz1999 approved these changes
lgtm

2024-07-10 09:34 UTC, aadya940 commented
> this is good to go, just need the test to assert the shapes of input and output of the network are the same

Already done in `test_all_networks.py`.

2024-07-11 21:41 UTC, merged

2024-07-12 07:24 UTC, aadya940 commented
There's a mistake here.
`_config.structure` should be "auto-encoder" not "encoder".

2024-08-16 17:09 UTC, aadya940 commented
#1962