[ENH] Lower Bounding Distances for SAX and SFA
aeon-toolkit/aeon pull request #1622
Opened 2024-06-07 12:52 UTC by patrickzib

#### What does this implement/fix? Explain your changes.

This implements Euclidean lower bounding distances for SFA and SAX. These can be used for indexing. It adds a test case, too.

It fixes two bugs in PAA/SAX for z-normalization with 0 std (dividing my 0) and for segments of size 0.

2024-06-09 18:47 UTC, baraline reviewed
Hey Patrick, just a quick review of the surface for now, I'll have a look at the paper during the week to refresh myself on the core of it and come back to it, but overall looks good !
The comment on the @njit comment is true for most new distances you introduced, was there something wrong with numba ?

2024-06-09 18:47 UTC, baraline commented on aeon/distances/_dft_sfa_mindist.py
> +# @njit(cache=True, fastmath=True)
Is this supposed to stay commented ?

2024-06-09 18:47 UTC, baraline commented on aeon/distances/tests/test_symbolic_mindist.py
> +    # print("SAX-Min-Dist Tightness:    \t", tightness_sax / X_train.shape[0])
Some print comments to clean out

2024-06-09 18:47 UTC, baraline commented on aeon/transformations/collection/dictionary_based/_sfa_fast.py
> +#     return 1 << msb
Comments to clean up

2024-06-10 07:41 UTC, patrickzib commented on aeon/distances/_dft_sfa_mindist.py
> +# @njit(cache=True, fastmath=True)
`squeeze()` is not supported by numba. However, `squeeze()` was just a convenience method, and can be removed. Thus, I did add njit again.

2024-06-10 07:41 UTC, patrickzib commented on aeon/distances/tests/test_symbolic_mindist.py
> +    # print("SAX-Min-Dist Tightness:    \t", tightness_sax / X_train.shape[0])
Thank you. I cleaned it up

2024-06-10 07:41 UTC, patrickzib commented on aeon/transformations/collection/dictionary_based/_sfa_fast.py
> +#     return 1 << msb
Done :)

2024-06-10 08:32 UTC, baraline commented
Great ! An alternative to `squeeze`, if you are sure that there is only 1D might be to use `ravel`, which should be supported.

2024-06-10 08:58 UTC, patrickzib commented
> Great ! An alternative to `squeeze`, if you are sure that there is only 1D with "empty" subdimensions might be to use `flatten` or `ravel`, which should both be supported.

`ravel()` and `flatten()` would turn any 2d array to a 1d array, right? For this to work, the input must be 1d with one empty subdimension. Otherwise, I kind of break the logic. Might be better to just leave it and throw the ValueError.

2024-06-10 18:48 UTC, baraline requested changes
Didn't find much to say on the distance themselves, looks good to me. Some comment on possible typos.

Additionally, more out of curiosity than for this PR, would a multivariate version of the lower bounds where you consider each channel independently and sum the result work, as we are working with (squared) Euclidean distance ?

2024-06-10 18:48 UTC, baraline commented on aeon/distances/tests/test_symbolic_mindist.py
> +            tightness_paa_sax += mindist_paa_sax / ed
The tightness values are not used for in the following, did you want to assert that the tightness of paa_sax will be higher than sax ?

2024-06-10 18:48 UTC, baraline commented on aeon/distances/tests/test_symbolic_mindist.py
> +                tightness_dft_sfa += mindist_dft_sfa / ed
Same comment on tightness values not used

2024-06-10 18:48 UTC, baraline commented on aeon/transformations/collection/dictionary_based/_sax.py
> +            )
You could use the functions defined in `aeon.utils.numba.general` (which ever of "z_normalise_series", "z_normalise_series_2d" and "z_normalise_series_3d" you need) for this, but this works fine as well

2024-06-10 18:48 UTC, baraline commented on aeon/transformations/collection/dictionary_based/_sfa.py
> +                1.0 / math.sqrt(window_size) if lower_bounding_distances else 1.0
Don't you mean `1.0 / math.sqrt(window_size) if lower_bounding else 1.0` here instead of `if lower_bounding_distances else 1.0` ?

2024-06-10 18:48 UTC, baraline commented on aeon/transformations/collection/dictionary_based/_sfa.py
> +            warnings.simplefilter("ignore", category=NumbaTypeSafetyWarning)
What were the warning raised here, if you remember ?

Additionally, I'm not sure filtering the warning by default is a good solution, do we have some kind of policy on this @MatthewMiddlehurst ?

2024-06-10 18:48 UTC, baraline commented on aeon/transformations/collection/dictionary_based/_sfa_fast.py
> +                1.0 / math.sqrt(window_size) if lower_bounding_distances else 1.0
Same comment on `lower_bounding_distances` than above

2024-06-10 18:48 UTC, baraline commented on aeon/transformations/collection/dictionary_based/_sfa_fast.py
> +#     return 1 << msb
You might have forgotten it ? Or maybe it will be in the next commit, then nevermind.

2024-06-11 13:03 UTC, patrickzib commented on aeon/distances/tests/test_symbolic_mindist.py
> +                tightness_dft_sfa += mindist_dft_sfa / ed
Good catch :)

2024-06-11 13:07 UTC, patrickzib commented on aeon/transformations/collection/dictionary_based/_sax.py
> +            )
I was not aware of this method 👍 

The issue with z_normalise_series is that I have to know if the data is 1d, 2d or 3d and call the corresponding one, right? The code above will work regardless of the input dimension. Thus, I would prefer to keep it like that, ok?

2024-06-11 13:20 UTC, patrickzib commented on aeon/transformations/collection/dictionary_based/_sfa.py
> +            warnings.simplefilter("ignore", category=NumbaTypeSafetyWarning)
Good question. I have not touched this part of the code.

When debugging, I do not see any warnings. Not sure, if pytest catches these. I have removed the filter.

2024-06-11 13:35 UTC, patrickzib commented on aeon/transformations/collection/dictionary_based/_sfa.py
> +                1.0 / math.sqrt(window_size) if lower_bounding_distances else 1.0
This one is tricky. When I implemented the mindistances, I have noticed that the semantics of `lower_bounding` are wrong. To allow for lower-bounding distances, it must be set to `lower_bounding=False`, which is rather unintuitive. 

Thus, I have added a new `lower_bounding_distances` to the class. `not lower_bounding = lower_bounding_distances`. I have simplified the code.

I cannot simply change `lower_bounding` as it is heavily used in dictionary-based classification.

2024-06-11 17:05 UTC, patrickzib commented
> Didn't find much to say on the distance themselves, looks good to me. Some comment on possible typos.
> 
> Additionally, more out of curiosity than for this PR, would a multivariate version of the lower bounds where you consider each channel independently and sum the result work, as we are working with (squared) Euclidean distance ?

Very Interesting research question! I am not aware of a multivariate lower bounding distance measure. Yet, as you suggest, it should be possible to transform each channel ro SFA/SAX and sum up the lower bounds on each channel.

2024-06-11 20:02 UTC, baraline approved these changes
Changes have been adressed and things looks good to me now. 
Althougt I would consider for a future PR is to change the naming on `lower bounding` and `lower bounding distance` to avoid confusions in the future.

2024-06-12 12:26 UTC, merged