[DOC] #1568 - Find good images for examples docs [documentation] [good first issue]
aeon-toolkit/aeon pull request #1651
Opened 2024-06-12 14:48 UTC by Abhash297

#### Reference Issues/PRs

Gathered relevant images for the topics.
Added a few references where it was necessary. 

No new dependency

### PR checklist

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [ ] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

##### For new estimators and functions
- [ ] I've added the estimator to the online [API documentation](https://www.aeon-toolkit.org/en/latest/api_reference.html).
- [ ] (OPTIONAL) I've added myself as a `__maintainer__` at the top of relevant files and want to be contacted regarding its maintenance. Unmaintained files may be removed. This is for the full file, and you should not add yourself if you are just making minor changes or do not want to help maintain its contents.

##### For developers with write access
- [ ] (OPTIONAL) I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.

2024-06-12 15:11 UTC, TonyBagnall commented
[@all-contributors](https://allcontributors.org/docs/en/bot/usage) add @Abhash297 for doc

2024-06-12 15:17 UTC, Abhash297 commented
Please review and merge

2024-06-12 17:16 UTC, TonyBagnall commented
so I appreciate the effort. Can you confirm that all these images are freely available not under copywrite?

2024-06-12 18:29 UTC, Abhash297 commented
The images I took from research papers have been added to the reference section in the subsequent pages. Some Images like the one in "pre processing" were taken from an article but it was a generic image so I did not add it to the reference.

2024-06-13 14:48 UTC, TonyBagnall requested changes
lgtm, one small change

2024-06-13 14:48 UTC, TonyBagnall commented on docs/examples.md
> +# Example
I think it should remain Examples

2024-06-13 15:05 UTC, Abhash297 commented on docs/examples.md
> +# Example
Yes, change made to examples.md

2024-06-14 08:30 UTC, TonyBagnall submitted a review, later dismissed

2024-06-14 09:41 UTC, MatthewMiddlehurst commented
IMO we should cut this back a bit, select a few examples/images and just focus on this in this PR. If the image is in `examples/*/img`, it should be used in the notebook itself.

2024-06-14 09:48 UTC, MatthewMiddlehurst commented
`examples/benchmarking/img/benchmark_algo1.png`
`examples/classification/img/early.png`
`examples/clustering/img/partition_tscl.png`
`examples/datasets/img/example_ds.png`
`examples/datasets/img/load_data.png`
`examples/transformations/img/catch22.png`
`examples/transformations/img/mini_rocket.png`

These look fine, but some could use more informative names. Would select a couple from these for the first version of this PR (you can keep all of them in this one or a separate PR if you wish).

2024-06-14 10:10 UTC, MatthewMiddlehurst reviewed
There is an extra `typecasting.png` is the `docs/` directory

2024-06-27 17:58 UTC, closed without merging