[ENH] Add AEDCNNNetwork
aeon-toolkit/aeon pull request #1702
Opened 2024-06-19 04:36 UTC by aadya940

Implements the AEDCNNNetwork.

2024-07-09 08:33 UTC, hadifawaz1999 requested changes
small changes requested

2024-07-09 08:33 UTC, hadifawaz1999 commented on aeon/networks/_ae_dcnn.py
> +        activation_decoder="relu",
the decoder parameters i wouldnt make them input arguments, as i dont want to give the user ability to have a non symetrical view of the auto encoder, you can keep the parameters but internally just not as input args

2024-07-09 08:33 UTC, hadifawaz1999 commented on aeon/networks/_ae_dcnn.py
> +            shape_before_flattent = x.shape[1:]
typo "shape_before_flattent" should flatten not flattent
and use tf.keras.layers.Flatten() instead of GAP, in case of auto encoder, theoretically, GAP doesnt make sense

2024-07-09 08:37 UTC, hadifawaz1999 commented on aeon/networks/_ae_dcnn.py
> +            shape_before_flattent = x.shape[1:]
for example you can see the original FCNNetwork does a GAP at the end, but in AEFCNNetwork, we use a flatten, because the GAP removes any information about the time, so wouldnt be possible to reconstruct it, so using  a flatten is more suitable

2024-07-10 09:32 UTC, aadya940 commented on aeon/networks/_ae_dcnn.py
> +            shape_before_flattent = x.shape[1:]
Oh, didn't know. Will do it. :))

2024-07-11 12:03 UTC, aadya940 commented
@MatthewMiddlehurst @TonyBagnall  Hello, the fail is not related to this PR.

2024-07-12 06:51 UTC, hadifawaz1999 commented
@aadya940 update to main to resolve the fail

2024-08-02 19:52 UTC, hadifawaz1999 requested changes
The decoder should contain transpose convolutions not standard ones, check how AEFCN and AEResNet are made

2nd thing, why is there AEBiGRU on this PR as well ?

2024-08-04 12:48 UTC, aadya940 commented
> The decoder should contain transpose convolutions not standard ones, check how AEFCN and AEResNet are made
> 
> 2nd thing, why is there AEBiGRU on this PR as well ?

They use normal convolutions in the decoder as well, check here:

[https://github.com/blafabregue/TimeSeriesDeepClustering/blob/main/networks/dilated_causal_cnn.py#L250](https://github.com/blafabregue/TimeSeriesDeepClustering/blob/main/networks/dilated_causal_cnn.py#L250)

2024-08-04 12:52 UTC, hadifawaz1999 commented
> > The decoder should contain transpose convolutions not standard ones, check how AEFCN and AEResNet are made
> > 2nd thing, why is there AEBiGRU on this PR as well ?
> 
> They use normal convolutions in the decoder as well, check here:
> 
> https://github.com/blafabregue/TimeSeriesDeepClustering/blob/main/networks/dilated_causal_cnn.py#L250

@aadya940 
I had this discussion with the first author of the deep clustering bake off, they used normal convolution because back then there was no convolution transpose defined, so we decided if we want to get them into aeon we will get them with the technique done in AEFCNNetwork, so the same should be applied on AEDCNNNetwork

2024-08-04 13:05 UTC, aadya940 commented
Oh Okay, however, Conv1DTranspose doesn't have padding="causal" kwarg. What to do?

2024-08-04 13:11 UTC, hadifawaz1999 commented
> @hadifawaz1999 Oh Okay, however, Conv1DTranspose doesn't have padding="causal" kwarg. What to do?

i see, yes because it doesn't make sense mathematically to do causal conv transpose, put it as convT with padding same for now, we'll see later if we add another option to use conv normal with causal

2024-08-06 06:35 UTC, hadifawaz1999 commented
@aadya940 you should be able to merge main now to fix the fail

2024-08-10 10:08 UTC, hadifawaz1999 commented on aeon/networks/_ae_dcnn.py
> +        activation_decoder="relu",
could you take care of this @aadya940 when you have time ? to be like AEFCN and AEResNet, as long as original authors didnt propose a non symmetrical version, i prefer obligating it

2024-08-10 10:09 UTC, hadifawaz1999 requested changes
small request, and should n_ not num

2024-08-12 17:34 UTC, hadifawaz1999 requested changes

2024-08-12 17:34 UTC, hadifawaz1999 commented on aeon/networks/_ae_dcnn.py
> +    .. [1] Network originally defined in:
reference in non bib format, and no need to say "Network originally.." just the citation i think

2024-08-12 17:34 UTC, hadifawaz1999 commented on aeon/networks/_ae_dcnn.py
> +    """Establish the network structure for a DCNN-Model.
can u mention its the auto encoder version ?

2024-08-12 17:34 UTC, hadifawaz1999 commented on aeon/networks/_ae_dcnn.py
> +    Parameters
if a parameter can be a list, it should be mentioned in the docstring

2024-08-12 17:34 UTC, hadifawaz1999 commented on aeon/networks/_ae_dcnn.py
> +            input_layer_decoder = reshape_layer
why re-assign "input_layer_decoder" here to reshape_layer ?

2024-08-13 10:30 UTC, aadya940 commented
#1962

2024-08-17 11:42 UTC, hadifawaz1999 commented on aeon/networks/_ae_dcnn.py
> +    n_filters: Union[int, List[int]], default=None
can you add a sentence to n_filters and dilation_rate to how the default values are calculated ?

2024-08-17 11:49 UTC, hadifawaz1999 commented on aeon/networks/_ae_dcnn.py
> +    """Establish the Auto-Encoder based structure for a DCN Network.
padding should be a parameter, and default to "same", having causal in encoder and same in decoder won't work i think, won't be an issue if we no longer use causal

2024-08-17 11:50 UTC, hadifawaz1999 commented on aeon/networks/_ae_dcnn.py
> +            input_layer_decoder = reshape_layer
yes but the input of the decoder is changing, it should not be overridden it won't work like that

2024-08-17 11:52 UTC, hadifawaz1999 commented on aeon/networks/_ae_dcnn.py
> +            input_layer_decoder = reshape_layer
you should define a temp layer that in the case of temporal latent space is set to input layer, and the other case is set to reshape layer, then y would be set to the temp layer

2024-08-17 11:52 UTC, hadifawaz1999 requested changes
some changes and bug fix for the input decoder

2024-08-19 08:30 UTC, aadya940 commented on aeon/networks/_ae_dcnn.py
> +    """Establish the Auto-Encoder based structure for a DCN Network.
From what I remember "causal" in encoder & "same" in decoder does work.

2024-08-19 08:55 UTC, aadya940 commented on aeon/networks/_ae_dcnn.py
> +    """Establish the Auto-Encoder based structure for a DCN Network.
The tests do run successfully.

2024-10-28 16:29 UTC, hadifawaz1999 approved these changes

2024-10-28 16:30 UTC, merged