[MNT] Only install binder dependencies for examples tests
aeon-toolkit/aeon pull request #1719
Opened 2024-06-25 11:42 UTC by MatthewMiddlehurst

2026-09-16 15:28 UTC, MatthewMiddlehurst commented
@copilot resolve the merge conflicts in this pull request

2026-09-16 16:38 UTC, TonyBagnall requested changes
my oracle says this:

dropping all_extras from the two example-notebook workflows silently removes torch, and the new binder extra doesn't add it back. In full-run mode this breaks two classification notebooks.

The blocking finding, reproduced. Both workflows install .[binder,dev]. The exclusion in run_examples.sh is gated on $1: normal PR runs pass $1=true and skip the heavy notebooks, but periodic_tests.yml runs run_examples.sh false true ($1=false, full set) and pr_examples.yml passes $1=false on push-to-main and on any full examples run-labelled PR. In the full set, classification/convolution_based.ipynb (HydraClassifier, MultiRocketHydraClassifier) and classification/interval_based.ipynb (QUANTClassifier) execute torch-backed estimators. With aeon installed minus torch:

HydraClassifier: ModuleNotFoundError: HydraClassifier requires package 'torch' ... 'torch' was not found
MultiRocketHydraClassifier: ModuleNotFoundError: ... requires package 'torch' ...
QUANTClassifier: ModuleNotFoundError: ... requires package 'torch' ...

torch is in all_extras but not in the new binder, so this is a straight regression from dropping all_extras. The trap is that this PR's own PR-examples check goes green (it runs with $1=true, which excludes both notebooks); the failure only surfaces on the periodic run and on the push-to-main examples run after merge. Fix: add torch>=1.13.1 (matching all_extras) to the binder extra. I confirmed torch 2.14.0 ships a cp312 macosx_14_0_arm64 wheel, so it installs on the macos-14 runners both jobs use.

2026-09-16 20:14 UTC, MatthewMiddlehurst commented
Good catch, added it to the list. Installing the CPU version for binder to reduce bloat a bit.

2026-09-18 18:17 UTC, TonyBagnall approved these changes

2026-09-18 18:18 UTC, merged