[ENH] Implement Proximity Forest classifier
aeon-toolkit/aeon pull request #1729
Opened 2024-06-27 16:09 UTC by itsdivya1309

#### Reference Issues/PRs
Fixes #159 

#### What does this implement/fix? Explain your changes.
A basic implementation of Proximity Forest algorithm built using the Proximity Trees.

2024-07-04 14:55 UTC, MatthewMiddlehurst reviewed
Great work, we'll have to give it a run through on the UCR archive datasets as we discussed. Next steps are up to you really, we can discuss on Slack.

2024-07-04 14:55 UTC, MatthewMiddlehurst commented on aeon/classification/distance_based/_proximity_forest.py
> +                raise ValueError("X should be univariate.")
Not sure about this here and in the tree as well actually. Probably better to just have "numpy2D" as the input type and let the base class handle conversion.

2024-07-04 14:55 UTC, MatthewMiddlehurst commented on aeon/classification/distance_based/_proximity_forest.py
> +        self._is_fitted = True
Shouldn't need this, handled in the base class.

2024-07-04 14:56 UTC, MatthewMiddlehurst commented
This needs to be included in the API documentation also.

2024-07-07 21:51 UTC, baraline commented on aeon/classification/distance_based/_proximity_forest.py
> +        return clf
Similar comment for predict, but I think it might be better to define the function you parallelize with joblib outisde of the object you call them from. Something to do with pickling the objects, if I remember right ? 

For example, here, you would define `_fit_tree` as a function outside `ProximityForest`, as it don't even use the `self` reference

2024-07-08 14:41 UTC, itsdivya1309 commented on aeon/classification/distance_based/_proximity_forest.py
> +        return clf
Thanks for pointing this out.

2024-07-08 20:22 UTC, baraline requested changes
Oher than this testing issue, the rest LGTM !

2024-07-08 20:22 UTC, baraline commented on aeon/classification/distance_based/tests/test_proximity_forest.py
> +    assert score >= 0.9
Testing the classifier for accuracy is a good practice, but doing it on randomly generated data might cause the test to fail at some point. If you want to do this, you can use the [unit test dataset](https://github.com/itsdivya1309/aeon/blob/2d74d4d3f8ed8041ca6b17eeb0443fb0ded81f83/aeon/datasets/_single_problem_loaders.py#L183).

2024-07-09 16:18 UTC, MatthewMiddlehurst commented on aeon/classification/distance_based/_proximity_forest.py
> +        return clf
Is this true, I think we have functions elsewhere that do this. Interesting to see if that needs to be changed.

2024-07-09 16:20 UTC, MatthewMiddlehurst reviewed
You should investigate how we use joblib in other estimators in the classification module. Typically we use "threads" as a default backend, with a parameter to change that,

The docstring `n_jobs` needs updating.

2024-07-12 04:28 UTC, itsdivya1309 commented on aeon/classification/distance_based/tests/test_proximity_forest.py
> +    assert score >= 0.9
I have updated the code to use unit test. Thank you for suggesting this.

2024-07-14 10:36 UTC, baraline requested changes
Only this small parameter missing and it should be good to go !

2024-07-14 10:36 UTC, baraline commented on aeon/classification/distance_based/_proximity_forest.py
> +        output_probas = Parallel(n_jobs=self._n_jobs, prefer="threads")(
We discussed the need of a parameter for the joblib backend (i.e. threads vs processes), you should add a class parameter that default to threads

2024-07-15 04:13 UTC, itsdivya1309 commented on aeon/classification/distance_based/_proximity_forest.py
> +        output_probas = Parallel(n_jobs=self._n_jobs, prefer="threads")(
I thought I had added the parameter; thank you, I have added the parameter

2024-07-15 10:32 UTC, MatthewMiddlehurst commented on aeon/classification/distance_based/_proximity_forest.py
> +        self.classes_ = list(np.unique(y))
This is done in the base class, don't want to do so here. Caused an issue when trying to run it 🙂

2024-07-16 10:09 UTC, MatthewMiddlehurst commented on aeon/classification/distance_based/_proximity_forest.py
> +                self.n_jobs,
The random state needs to be different. See the Arsenal classifier for an example. If we are multithreading the forest, we probably dont want to thread the trees also.

2024-07-16 10:09 UTC, MatthewMiddlehurst commented on aeon/classification/distance_based/_proximity_forest.py
> +        return output_probas
Rather than averaging probabilities, it may be better to just sum votes from each tree i.e. https://github.com/aeon-toolkit/aeon/blob/main/aeon/base/estimator/interval_based/base_interval_forest.py#L252

Unless this is how the original does it, then we should keep it as is.

2024-07-17 05:00 UTC, itsdivya1309 commented on aeon/classification/distance_based/_proximity_forest.py
> +        self.classes_ = list(np.unique(y))
Sorry, I'll keep this in mind.

2024-07-17 05:01 UTC, itsdivya1309 commented on aeon/classification/distance_based/_proximity_forest.py
> +        return output_probas
The paper indeed uses majority voting.

2024-07-17 07:20 UTC, itsdivya1309 commented on aeon/classification/distance_based/_proximity_forest.py
> +        return output_probas
I think it is also averaging the probabilities: https://github.com/aeon-toolkit/aeon/blob/main/aeon/base/estimator/interval_based/base_interval_forest.py#L267
Correct me if I am wrong, but I can't see the difference.

2024-07-17 10:20 UTC, MatthewMiddlehurst commented on aeon/classification/distance_based/_proximity_forest.py
> +        return output_probas
ah sorry bad link. this should be better, but with 1 rather than a weight https://github.com/aeon-toolkit/aeon/blob/main/aeon/classification/dictionary_based/_tde.py#L422.

Just want to count the predictions and then normalise the array basically. Have to be careful for string labels 🙂

2024-07-17 10:21 UTC, MatthewMiddlehurst commented on aeon/classification/distance_based/_proximity_forest.py
> +        self.classes_ = list(np.unique(y))
No problem, was good to catch it.

2024-07-24 11:19 UTC, baraline commented on aeon/classification/distance_based/_proximity_forest.py
> +                check_random_state(rng.randint(np.iinfo(np.int32).max)),
Very unlikely to happen, but you could still get trees with the same random state using this. Initializing the random states values with something like ```rng_list = rng.choice(np.iinfo(np.int32).max, size=self.n_trees, replace=False)``` before the Parallel loop would fix this (again, very unlikely to happen) issue.

2024-07-24 11:20 UTC, baraline commented on aeon/classification/distance_based/_proximity_forest.py
> +            n_jobs=self._n_jobs, backend=self.parallel_backend, prefer="threads"
If `backend` is specified, you can remove the `prefer` parameter here and default `backend` to `threading` during initialization.

2024-07-24 11:21 UTC, baraline commented on aeon/classification/distance_based/_proximity_forest.py
> +            n_jobs=self._n_jobs, backend=self.parallel_backend, prefer="threads"
Same comment for this `prefer` parameter.

2024-07-25 04:41 UTC, itsdivya1309 commented on aeon/classification/distance_based/_proximity_forest.py
> +                check_random_state(rng.randint(np.iinfo(np.int32).max)),
When I add this code, the algo becomes very slow, probably because of the large range.

2024-07-26 07:29 UTC, baraline commented on aeon/classification/distance_based/_proximity_forest.py
> +                check_random_state(rng.randint(np.iinfo(np.int32).max)),
Maybe my bad here, does storing `np.iinfo(np.int32).max` in a variable and using that in the choice function makes it better ? Can't test it right now sorry :/ 

Its weird anyway ... could you provide some timing with and without the change ? (you can use the %timeit magic in a IPython environment to do that)

2024-07-26 09:32 UTC, itsdivya1309 commented on aeon/classification/distance_based/_proximity_forest.py
> +                check_random_state(rng.randint(np.iinfo(np.int32).max)),
It's taking more than 45 mins, just to run this single line of code `rng_list = rng.choice(np.iinfo(np.int32).max, size=self.n_trees, replace=False)`, even after using a variable.
Maybe we can use `self.n_trees * 100` and do it like this:
`rng_list = rng.choice(self.n_trees*100, size=self.n_trees, replace=False)`

2024-07-26 09:35 UTC, MatthewMiddlehurst commented on aeon/classification/distance_based/_proximity_forest.py
> +                check_random_state(rng.randint(np.iinfo(np.int32).max)),
I think the risk here is minimal. We seed ensemble members in a similar way elsewhere. this is essentially a 1/2,147,483,647 situation, no?

2024-07-26 09:36 UTC, MatthewMiddlehurst commented on aeon/classification/distance_based/_proximity_forest.py
> +            n_jobs=self._n_jobs, backend=self.parallel_backend, prefer="threads"
This is now a bit inconsistent with how to do it in other estimators, we mention in the docs that `threading` is the default.

2024-07-26 09:36 UTC, MatthewMiddlehurst commented on aeon/classification/distance_based/_proximity_forest.py
> +            n_jobs=self._n_jobs, backend=self.parallel_backend, prefer="threads"
Same as above.

2024-07-26 11:52 UTC, baraline commented on aeon/classification/distance_based/_proximity_forest.py
> +        return clf
Just seen your comment Matthew, will try to provide some benchmark script.

2024-07-29 06:03 UTC, itsdivya1309 commented on aeon/classification/distance_based/_proximity_forest.py
> +            n_jobs=self._n_jobs, backend=self.parallel_backend, prefer="threads"
I've revert the changes.

2024-07-29 14:32 UTC, MatthewMiddlehurst approved these changes
LGTM

2024-08-01 15:51 UTC, MatthewMiddlehurst commented
@baraline any more improvements you think this needs? No rush to merge if so.

2024-08-01 16:16 UTC, baraline approved these changes
Lgtm for now, i'll try to do the joblib testing this evening, we can iterarate on this afterward.

2024-08-02 13:32 UTC, merged