Unit testing revamp part 2: classification
aeon-toolkit/aeon pull request #1770
Opened 2024-07-08 10:51 UTC by MatthewMiddlehurst

todo

2024-07-16 18:18 UTC, TonyBagnall requested changes
I think I need to sit doown and work through it all, but I think its all good. Only question was about setting "classifier" in test_all_estimators

2024-07-16 18:18 UTC, TonyBagnall commented on aeon/testing/tests/test_all_estimators.py
> +    estimator_types=["classifier"],
is this meant to be just classifier?

2024-07-17 10:01 UTC, MatthewMiddlehurst commented on aeon/testing/tests/test_all_estimators.py
> +    estimator_types=["classifier"],
For now yes, the issue currently is that if I did more it would be duplicated by the old framework for others.

Current plan is to take it out module by module except for legacy and add them until we can remove the filter altogether.

2024-08-01 14:48 UTC, TonyBagnall submitted a review, later dismissed
LGTM, but there is a conflict with main

2024-08-01 14:58 UTC, hadifawaz1999 commented
there was a new test i added recently for saving/loading in classification/deep_learning, might put it in yield as well ?

2024-08-01 22:57 UTC, MatthewMiddlehurst commented
Can leave that for next PR IMO. A lot going on here.

2024-08-05 10:50 UTC, hadifawaz1999 commented
we're working on the same testing functions [here](https://github.com/aeon-toolkit/aeon/pull/1904)
how should we proceed with this, i can wait for your PR to get in and then adjust on the new placed test

2024-08-06 11:51 UTC, MatthewMiddlehurst commented
I don't mind which one goes in first, this has other PRs waiting on it however.

2024-08-10 18:21 UTC, TonyBagnall approved these changes
lets get this one in first

2024-08-11 11:36 UTC, hadifawaz1999 commented
> lets get this one in first

i dont mind for sure, can put my changes on the new placed test functions after this

2024-08-11 11:36 UTC, hadifawaz1999 approved these changes

2024-08-12 09:15 UTC, merged