[ENH] Add AEDRNNClusterer
aeon-toolkit/aeon pull request #1784
Opened 2024-07-10 14:07 UTC by aadya940

Implements Clusterer based on Dilated Recurrent Neural Network (DRNN).

2024-07-30 12:30 UTC, hadifawaz1999 commented
@aadya940 i think an issue is happening when importing the custom layer from the networks package, one possibility is because its wrapped under a condition, to debug this (i dont think its the best solution) can you implement as well the custom layer inside ae_drnn.py but the clusterer ? it is just to see if CI is failing because of this

2024-08-01 10:21 UTC, hadifawaz1999 requested changes
.

2024-08-01 16:52 UTC, aadya940 commented
@hadifawaz1999 Now they are the same :))

2024-08-13 10:32 UTC, aadya940 commented
#1962

2024-08-15 11:48 UTC, hadifawaz1999 requested changes
- the default for clustering_algorithm should be "deprecated" in the docstring
- the example should not use n_clusters
- the _score function should use self._estimator not self.clusterer
- the test parameters function should set the estimator to DummyClusterer, to make testing fast, and not set the old parameters to be deprecated

2024-08-15 17:22 UTC, hadifawaz1999 commented on aeon/clustering/deep_learning/_ae_drnn.py
> +    >>> aefcn = AEDRNNClusterer(n_clusters=2,
n_clusters should not be set in AEDRNNCluster as it is set in the estimator used

2024-08-15 17:23 UTC, hadifawaz1999 commented on aeon/clustering/deep_learning/_ae_drnn.py
> +            "clustering_params": {
test params should be changes, n_clusters and clustering_algorithm should be removed here and replaced by estimator set to dummy clusterer

2024-11-09 15:29 UTC, hadifawaz1999 submitted a review, later dismissed

2024-11-11 13:11 UTC, hadifawaz1999 approved these changes

2024-11-11 13:11 UTC, merged