[ENH] PLA and Catch22
aeon-toolkit/aeon pull request #1807
Opened 2024-07-15 21:16 UTC by Moonzyyy

#### What does this implement/fix? Explain your changes.
Implements #948 and Fixes #1384. Added tests for new series transformer PLA.

#### Does your contribution introduce a new dependency? If yes, which one?
No new dependency

2024-07-16 08:53 UTC, TonyBagnall submitted a review, later dismissed
couple very minor things, but looks good to me. Could you change the title of the PR, this is just PLA not catch22

2024-07-16 08:53 UTC, TonyBagnall commented on aeon/transformations/series/_pla.py
> +    """
could you add an example?

2024-07-16 08:53 UTC, TonyBagnall commented on aeon/transformations/series/_pla.py
> +    class Transformer(Enum):
I think I would rather it were called something else, overloading the term Transformer can be confusing. Alternatively could make it private?

2024-07-16 08:54 UTC, TonyBagnall commented
might be worth looking at numba at some point?

2024-07-16 15:00 UTC, MatthewMiddlehurst commented on aeon/transformations/series/_pla.py
> +        "python_dependencies": "sklearn",
this is not required, sklearn is always installed.

2024-07-16 15:00 UTC, MatthewMiddlehurst commented on aeon/transformations/series/_pla.py
> +            raise ValueError("Invalid buffer_size: use a number only or keep empty.")
better to do error checking like this in fit

2024-07-16 15:00 UTC, MatthewMiddlehurst commented on aeon/transformations/series/_pla.py
> +        self.segment_dense = np.array([])
same with this, better to initialise in fit so it resets on multiple runs. Though in this case there is no fit, so we dont want to store it at all really.

2024-07-16 15:01 UTC, MatthewMiddlehurst commented on aeon/transformations/series/_pla.py
> +__maintainer__ = []
There should be  a docstring at the top of the file

2024-07-17 22:06 UTC, Moonzyyy commented on aeon/transformations/series/_pla.py
> +    class Algorithm(Enum):
Was thinking of doing that, will make SWAB the default one and then allow users to just swap algorithm

2024-07-25 13:27 UTC, Moonzyyy commented on aeon/transformations/series/_pla.py
> +        self.segment_dense = np.array([])
So are the changes now fine? I can't change the parameters of _fit as its an inherited method

2024-07-25 15:53 UTC, MatthewMiddlehurst commented on aeon/transformations/series/_pla.py
> +            self.segment_dense = segment_dense
This is eventually going to break testing as transform what finished for series transformers as it shouldn't change any attributes (`self.segment_dense = segment_dense`).

2024-07-25 15:53 UTC, MatthewMiddlehurst commented on aeon/transformations/series/_pla.py
> +        self.segment_dense = np.array([])
noticed other issues, needs to be structured differently but resolve this conversation.

2024-07-25 15:54 UTC, MatthewMiddlehurst commented on aeon/transformations/series/_pla.py
> +            raise ValueError("Invalid buffer_size: use a number only or keep empty.")
Resoling this in favour of new comments, but this is only the case if fit should exist.

2024-07-25 16:02 UTC, MatthewMiddlehurst requested changes
A few comments. I did not notice initially that `_fit` should not exist due to the tag setting, unless you think it is the tag which is wrong and the method should exist.

I am going to turn on the code coverage tests to its easier to see what lines are covered by unit tests.

2024-07-25 16:02 UTC, MatthewMiddlehurst commented on aeon/transformations/series/tests/test_pla.py
There is a bit of a testing gap here, as the string option for `transformer` is never used. I'm pretty sure in the current state this would result in a crash.

2024-07-26 10:40 UTC, Moonzyyy commented on aeon/transformations/series/_pla.py
> +            self.segment_dense = segment_dense
Well honestly I don't think it has much use since we aren't segmenting the data

2024-07-26 10:41 UTC, Moonzyyy commented on aeon/transformations/series/_pla.py
> +        "fit_is_empty": True,
Right, will remove it! I thought it was meant to see if the model has been fitted or not, my bad.

2024-07-26 13:49 UTC, MatthewMiddlehurst commented on aeon/transformations/series/_pla.py
> +        "fit_is_empty": True,
If there is no fitting to be done it can remain and `_fit` can go. I dont really see much currently which would require fit

2024-08-01 16:53 UTC, TonyBagnall commented on aeon/transformations/series/_pla.py
> +__maintainer__ = []
Could you add TonyBagnall as the maintainer?

2024-08-01 17:25 UTC, Moonzyyy commented on aeon/transformations/series/_pla.py
> +__maintainer__ = []
Should be done :)

2024-08-02 13:55 UTC, MatthewMiddlehurst reviewed
Still a bit to go I think. Not fully checked the transformer functions yet.

In the testing please use keywords for parameters

2024-08-02 13:55 UTC, MatthewMiddlehurst commented on aeon/transformations/series/_pla.py
> +            SWAB: "swab", 4
no ints, just lower case strings

2024-08-02 13:55 UTC, MatthewMiddlehurst commented on aeon/transformations/series/_pla.py
> +        The endpoints of each found segment of the series for transformation.
no longer exists

2024-08-02 13:55 UTC, MatthewMiddlehurst commented on aeon/transformations/series/_pla.py
> +    >>> pla = PiecewiseLinearApproximation(0.001, transformer=3)
will need to be updated

2024-08-02 13:55 UTC, MatthewMiddlehurst commented on aeon/transformations/series/_pla.py
> +            raise ValueError("Invalid transformer: choose between 1-4")
looking now the first 3 of these would be better at the start of transform, and the third does not need to exist (but the error message can replace the current one in transform).

2024-08-02 13:55 UTC, MatthewMiddlehurst commented on aeon/transformations/series/_pla.py
> +        return self._linear_regression(X)
Some of these functions seem a bit unnecessary, especially  `_create_segment` which just calls another function.

2024-08-02 13:55 UTC, MatthewMiddlehurst commented on aeon/transformations/series/_pla.py
> +    and two online algorithms: SlidingWindow and SWAB (Sliding Window and Bottom Up).
Could you expand on this a bit, what is the output of the transformation (and how would the different methods effect this)

2024-08-02 13:55 UTC, MatthewMiddlehurst commented on aeon/transformations/series/tests/test_pla.py
> +            182.0,
this seems very similar to the input series

2024-08-02 13:55 UTC, MatthewMiddlehurst commented on aeon/transformations/series/tests/test_pla.py
> +            182.0,
this also 🙂

2024-08-02 13:55 UTC, MatthewMiddlehurst commented on aeon/transformations/series/tests/test_pla.py
> +            199.9,
This seems to be the same as bottom up

2024-08-02 15:28 UTC, Moonzyyy commented on aeon/transformations/series/tests/test_pla.py
> +            199.9,
It is bound to be similar to bottom up as it uses bottom up for transforming a time series

2024-08-02 15:36 UTC, Moonzyyy commented on aeon/transformations/series/tests/test_pla.py
> +            182.0,
![image](https://github.com/user-attachments/assets/d2b2a306-063b-47b4-a57d-12cf6ccf63ea)

From the research paper the output will be a more sharpened version of the input series, however I can decrease the error margin if that is what is wanted in the tests

2024-08-06 10:19 UTC, MatthewMiddlehurst commented on aeon/transformations/series/tests/test_pla.py
> +            199.9,
unless I'm misreading it is exactly the same however, would be better to find an example which changes and verify the output is what you expect

2024-08-06 10:22 UTC, MatthewMiddlehurst commented on aeon/transformations/series/tests/test_pla.py
> +            182.0,
There does not seem to be any large differences like the example shown here though. Only the last few values change and it is small.

2024-08-06 10:28 UTC, Moonzyyy commented on aeon/transformations/series/_pla.py
> +        return self._linear_regression(X)
I removed functions that only appeared once or called other functions. The only functions that remain are sliding window, top up, bottom up, Swab, SEE and linear regression.

2024-08-06 10:29 UTC, Moonzyyy commented on aeon/transformations/series/_pla.py
> +            raise ValueError("Invalid transformer: choose between 1-4")
I completely removed numbering, only leaving it to strings. Therefore there are less given error messages and the code should look more clean

2024-08-08 11:48 UTC, Moonzyyy commented on aeon/transformations/series/tests/test_pla.py
> +            199.9,
Should be changed now, all tests should be different

2024-08-09 11:26 UTC, MatthewMiddlehurst commented
Could you plot the test series and each of the options similar to the image above? We have utilities in the visualisation module which can do this.

2024-08-09 11:36 UTC, MatthewMiddlehurst commented on aeon/transformations/series/_pla.py
> +    The algorithms available are two offline algorithms: TopDown and BottomUp
no space between the first two options here

2024-08-09 11:36 UTC, MatthewMiddlehurst commented on aeon/transformations/series/_pla.py
> +        The buffer size, used only for SWAB.
The default value should be included on the first line. See other classes.

2024-08-09 11:36 UTC, MatthewMiddlehurst commented on aeon/transformations/series/_pla.py
> +    performance is only slightly reduced versus it's competitor Bottom Up.
I don't feel these new paragraphs explain the output for each algorithm. What do they do differently and when would you want to use one over the other? Is there a source for the second paragraph? 

If you can't do this we can just remove these bits and move on for now.

2024-08-15 09:59 UTC, Moonzyyy commented on aeon/transformations/series/_pla.py
> +    performance is only slightly reduced versus it's competitor Bottom Up.
I re-wrote the paragraphs and added the reference paper

2024-09-03 12:03 UTC, merged