[ENH] Shapelet Transform improvements
aeon-toolkit/aeon pull request #185
Opened 2023-03-10 16:09 UTC by TonyBagnall

the main thing here is that the conversion from numpy to dataframe is removed. All that was happening was the numpy was getting put into a dataframe in the transform, then converted back to numpy in classifier. The base transformer does this conversion automatically, unless you set this argument in the constructor

super(RandomShapeletTransform, self).__init__(_output_convert=False)

other changes:
1. Docstrings tidied up, dimensions changed to channels, all reference to DataFrames removed
2. Helper classes for full ShapeletTransform made private
3. Order of classes in file changed to put RandomShapeleTransform first
4. Remove pointless tags

2023-03-10 20:41 UTC, GuzalBulatova requested changes
I've got a couple of comments and a general suggestion to break down the big PRs into smaller ones where possible. 
Overall this is absolutely fantastic work! Definitely a significant improvement. The code flow is easy to read and I really appreciate the comprehensive documentation.

2023-03-10 20:41 UTC, GuzalBulatova commented on sktime/transformations/panel/shapelet_transform.py
> +        output : pandas DataFrame
Looks like it's a numpy array here?

2023-03-10 20:41 UTC, GuzalBulatova commented on sktime/transformations/panel/shapelet_transform.py
> +        # Here we establish the order of cases to sample. We need to sample
Might worth putting the description of core logic into the method's docstring, what do you think? *Not a blocker

2023-03-10 20:41 UTC, GuzalBulatova commented on sktime/transformations/panel/shapelet_transform.py
> +                            if candidate_rejected is False:
Below was probably automatically redacted by a formatter, it was quite hard to read for me. By line 1061 I lost the track of what bracket was closing what and what the operation was referring to. I'd say either override the auto-formatting or break it down. Maybe it's just my perception. What's your view?

2023-03-10 20:41 UTC, GuzalBulatova commented on sktime/transformations/panel/shapelet_transform.py
> +            # j = np.asanyarray(j)
Is this line left here on purpose for future work?

2023-03-10 21:25 UTC, MatthewMiddlehurst commented
I agree that it is extremely difficult to tell what has actually changed without going through the full file (both pre and post change). Maybe moving them around should be a separate thing.

2023-03-11 08:49 UTC, TonyBagnall commented
thanks for the feedback @GuzalBulatova, really helpful. I did wonder about the complexity of reviewing when moving classes, just wanted to reprioritise since the ShapeletTransformClassifier is there for legacy only, but it is purely cosmetic, I will shift them back. I have a more systemic issues about the tests for which I will raise an issue

2023-03-11 09:26 UTC, TonyBagnall commented on sktime/transformations/panel/shapelet_transform.py
> +        output : pandas DataFrame
fixed, thanks

2023-03-11 09:27 UTC, TonyBagnall commented on sktime/transformations/panel/shapelet_transform.py
> +            # j = np.asanyarray(j)
I have no idea! So I have removed it, if it was there for a purpose it should have been commented

2023-03-11 09:28 UTC, TonyBagnall commented
> I agree that it is extremely difficult to tell what has actually changed without going through the full file (both pre and post change). Maybe moving them around should be a separate thing.

agreed, I will shift order on its own PR, hopefully more readable now

2023-03-11 09:40 UTC, TonyBagnall commented on sktime/transformations/panel/shapelet_transform.py
> +                            if candidate_rejected is False:
I think that whole comment was left in for debugging, it can go! I have shortened the print, jason put them in before we could assume print(f"ddd") was available I think.

2023-03-11 10:21 UTC, TonyBagnall commented
Im working on a notebook change, but I think as I am here with STC I will write a shapelet notebook, which make take a while

2023-03-11 17:32 UTC, TonyBagnall commented on sktime/transformations/panel/shapelet_transform.py
> +        # Here we establish the order of cases to sample. We need to sample
I'd like to, but I think I will leave it for now, its quite a lot of work for a legacy classifier, and Jason's comments are very good, albeit in a style of inline comments we dont use now

2023-03-11 17:48 UTC, TonyBagnall commented
I have added a notebook on using the transform. I want to put more details in, but I need to work out how it interacts with the classification notebooks I'm changing on #123 so would like to leave it at this for now.

2023-03-16 13:15 UTC, MatthewMiddlehurst approved these changes
I'm fine with the changes, but the shapelet notebook may conflict with the previous notebook PR. Just not getting picked up because it's in a different dir.

2023-03-17 10:14 UTC, merged