[BUG] Check data shape in `predict`-like functions
aeon-toolkit/aeon pull request #1865
Opened 2024-07-29 21:14 UTC by MatthewMiddlehurst

#### Reference Issues/PRs

Fixes #1774
Fixes #1775

#### What does this implement/fix? Explain your changes.

Adds a check to collection base classes which raises an error if length and channels does not match fit. Removed redundant check from interval base class.

2024-07-30 21:03 UTC, MatthewMiddlehurst commented
@TonyBagnall @hadifawaz1999 do these changes seem reasonable? DLs are breaking, but i think that is more of a DL issues than the changes here.

2024-07-31 10:30 UTC, hadifawaz1999 commented
@MatthewMiddlehurst not only DL seems dictionary based are failing too [https://github.com/aeon-toolkit/aeon/actions/runs/10151952868/job/28072315499?pr=1865#step:7:260](here)
is there something that these changes assume sub classes are doing ? because it seems it assumes n_timepoints is an attribute somewhere defined, which most sub classes don't do

2024-07-31 11:02 UTC, MatthewMiddlehurst commented
It likely has to do with no longer allowing storage of metadata via `predict`. Just want to make sure the current changes are fine before we fix any of the broken stuff.

2024-07-31 11:38 UTC, hadifawaz1999 commented on aeon/base/_base_collection.py
> +            if get_n_channels(X) != self.metadata_["n_channels"]:
maybe redundent, but should we also check if same length is on all channels when "capability:unequal_length" is false ?

2024-07-31 11:38 UTC, hadifawaz1999 commented on aeon/base/_base_collection.py
> +                    get_n_timepoints(X),
should be get_n_channels no ?

2024-07-31 11:39 UTC, hadifawaz1999 commented on aeon/classification/base.py
> +        X = self._preprocess_collection(X, store_metadata=False)
just as a reminding note to fix the breaks later, this is the change that caused so should adapt to it

2024-07-31 11:40 UTC, hadifawaz1999 requested changes
Changes look good just a couple of comments @MatthewMiddlehurst

2024-08-02 10:09 UTC, MatthewMiddlehurst commented on aeon/base/_base_collection.py
> +            if get_n_channels(X) != self.metadata_["n_channels"]:
If there are a different number of channels at any point it should throw an error, thats not supported. 

Unequal length data where the unequal tag is false will be picked up in data preprocessing.

Only things we want to check are consistent in both `fit` to `predict` is these two I think.

2024-08-02 10:09 UTC, MatthewMiddlehurst commented on aeon/base/_base_collection.py
> +                    get_n_timepoints(X),
yep

2024-08-02 19:08 UTC, TonyBagnall commented
basic structure looks good to me

2024-08-05 14:40 UTC, MatthewMiddlehurst commented
@chrisholder any issue with the cache change? currently I think it runs when collecting tests, or at least it did for some reason locally.

2024-08-12 13:32 UTC, hadifawaz1999 submitted a review, later dismissed

2024-08-13 09:45 UTC, MatthewMiddlehurst commented
@hadifawaz1999 there was a conflict with the testing PRs, could you approve again?

2024-08-13 09:46 UTC, hadifawaz1999 approved these changes

2024-08-13 14:28 UTC, merged