[DOC][REF] K-Shape rename and add references
aeon-toolkit/aeon pull request #1899
Opened 2024-08-02 20:46 UTC by Cyril-Meyer

#### Reference Issues/PRs

Fixes #1595

#### What does this implement/fix? Explain your changes.

Replace `TimeSeriesKShapes` with `TimeSeriesKShape` as the original name is K-Shape

#### Does your contribution introduce a new dependency? If yes, which one?

No.

#### Any other comments?

The citation format is ACM instead of proposed in #1595 as it's the one proposed by the official website and also include DOI.
I'm not sure about the PR title tags, its [DOC] for the reference, but I don't know how to classify the renaming between [REF] and [MNT].

### PR checklist

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [x] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

2024-08-02 20:54 UTC, hadifawaz1999 requested changes
Thanks for taking care of this, however it requires deprecation policy, https://www.aeon-toolkit.org/en/stable/developer_guide/deprecation.html

2024-08-02 21:41 UTC, Cyril-Meyer commented
> Thanks for taking care of this, however it requires deprecation policy, https://www.aeon-toolkit.org/en/stable/developer_guide/deprecation.html

Thanks for the info, I had completely forgotten about that, even though I had already seen it for other modules I worked on.
For now, I've deprecated the original class as I previously see in `networks/_cnn.py` for v0.12.0.
* Kept the `TimeSeriesKShapes` version with new `TimeSeriesKShape` in module `__init__` and documentation
* Only use `TimeSeriesKShape` For tests and base module, we

2024-08-04 11:27 UTC, hadifawaz1999 approved these changes
LGTM ! @TonyBagnall  any thoughts for the deprecation version ? 0.12 or 1.0 ?

2024-08-05 16:13 UTC, TonyBagnall commented on aeon/clustering/_k_shapes.py
> +    reason="TimeSeriesKShapes class has been renamed to TimeSeriesKShape and "
Maybe reword "TimeSeriesKShapes class has been renamed to TimeSeriesKShape.  The TimeSeriesKShapes version will be removed in version 1.0.0"

2024-08-05 22:44 UTC, MatthewMiddlehurst commented
Can rename any incorrect versions later, but I agree 1.0.0 is safer

2024-08-06 11:59 UTC, Cyril-Meyer commented on aeon/clustering/_k_shapes.py
> +    reason="TimeSeriesKShapes class has been renamed to TimeSeriesKShape and "
Done in 93635a123df1cc3ddc205e5d6d8d6f86ccc59012

2024-08-06 12:00 UTC, Cyril-Meyer commented
Related to the previous work, I propose to rename the file k_shapes to k_shape (done in ed5041b960b1b165f4f7dbb59a14c9def5db7e45).
Is there something to do about the deprecation ?

2024-08-06 22:07 UTC, MatthewMiddlehurst commented
No deprecation need there, the public access is through `aeon.clustering` and that has not changed.

2024-08-12 11:21 UTC, MatthewMiddlehurst submitted a review, later dismissed

2024-08-12 11:21 UTC, MatthewMiddlehurst commented
LGTM unless @TonyBagnall has any more comments

2024-08-13 09:55 UTC, hadifawaz1999 submitted a review, later dismissed
LGTM! @TonyBagnall all good for this one ?

2024-08-15 18:12 UTC, Cyril-Meyer commented
> soz, been away. lgtm, but there is a conflict with main @Cyril-Meyer

This should be resolved.
Conflict came from #1944 from @hadifawaz1999 on `aeon/clustering/deep_learning/base.py` and its addition make that my changes on the file becamed useless :)

2024-08-15 18:14 UTC, hadifawaz1999 commented
> > soz, been away. lgtm, but there is a conflict with main @Cyril-Meyer
> 
> This should be resolved. Conflict came from #1944 from @hadifawaz1999 on `aeon/clustering/deep_learning/base.py` and its addition make that my changes on the file becamed useless :)

ah yes forgot we worked on the same file my bad !

2024-08-15 18:14 UTC, hadifawaz1999 approved these changes

2024-08-15 18:34 UTC, merged