[ENH] Add performance metrics for anomaly detection (from TimeEval)
aeon-toolkit/aeon pull request #1938
Opened 2024-08-09 17:18 UTC by CodeLionX

#### Reference Issues/PRs

none

#### What does this implement/fix? Explain your changes.

- Adds a host of performance metrics for anomaly detection (with tests and docs, directly taken from [TimeEval](https://github.com/TimeEval/TimeEval/tree/main/timeeval/metrics)):
  - range-based classification metrics [Tatbul et al. 2018] (Precision, Recall, F1, AUC-score of the range-based precision-recall curve)
  - VUS-metrics [Paparrizos et al. 2022] (Range PR AUC, Range ROC AUC, Range PR VUS, Range ROC VUS)
  - F-score @ k ranges, F-score @ k points
  - enhanced versions of ROC AUC and PR AUC

#### Does your contribution introduce a new dependency? If yes, which one?

New soft-dependency: [`prts`](https://pypi.org/project/prts/) for range-based classification metrics

#### Any other comments?

### PR checklist

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [x] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

##### For new estimators and functions
- [x] I've added the estimator to the online [API documentation](https://www.aeon-toolkit.org/en/latest/api_reference.html).
- [x] (OPTIONAL) I've added myself as a `__maintainer__` at the top of relevant files and want to be contacted regarding its maintenance. Unmaintained files may be removed. This is for the full file, and you should not add yourself if you are just making minor changes or do not want to help maintain its contents.

##### For developers with write access
- [x] (OPTIONAL) I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.

2024-08-13 11:53 UTC, CodeLionX commented on aeon/utils/validation/_dependencies.py
>          class_name = type(obj).__name__
if `obj="func"`, this would have returned `type(obj).__name__` (`"str"`) instead of the expected `"func"`

2024-08-14 14:33 UTC, MatthewMiddlehurst requested changes
Good work. Made a few comments related to docs and consistency, some of which can be applied to multiple functions/files.

2024-08-14 14:33 UTC, MatthewMiddlehurst commented on aeon/performance_metrics/anomaly_detection/__init__.py
> +from ._vus_metrics import (
I would use absolute references for consistency with the rest of the package

2024-08-14 14:33 UTC, MatthewMiddlehurst commented on aeon/performance_metrics/anomaly_detection/_binary.py
> +__all__ = []
Can you fill these out, has no functional benefit but good documentation

2024-08-14 14:33 UTC, MatthewMiddlehurst commented on aeon/performance_metrics/anomaly_detection/_binary.py
> +    [TatbulEtAl2018]_.
We dont have a comm reference format i.e. APA or Harvard, but in all doc strings I have seen we use numbers to link to reference

i.e. https://github.com/aeon-toolkit/aeon/blob/main/aeon/classification/dictionary_based/_cboss.py

2024-08-14 14:33 UTC, MatthewMiddlehurst commented on aeon/performance_metrics/anomaly_detection/_binary.py
If the function uses a soft dependency I would mention that in the docstring IMO

2024-08-14 14:33 UTC, MatthewMiddlehurst commented on aeon/performance_metrics/anomaly_detection/_util.py
missing summary at the file top

2024-08-14 14:33 UTC, MatthewMiddlehurst commented on aeon/performance_metrics/anomaly_detection/_continuous.py
> +from __future__ import annotations
What is happening with this? Cant see any usages. Should be below the lists if possible

2024-08-14 14:33 UTC, MatthewMiddlehurst commented on aeon/performance_metrics/anomaly_detection/_vus_metrics.py
missing summary at the file top

2024-08-14 14:33 UTC, MatthewMiddlehurst commented on pyproject.toml
> +    "prts>=1.0.0.3",
Any reason for the current version threshold? not a requirement for it to earlier, just interested.

2024-08-15 09:41 UTC, CodeLionX commented on aeon/performance_metrics/anomaly_detection/_binary.py
> +    [TatbulEtAl2018]_.
Sure, will change that

2024-08-15 09:47 UTC, CodeLionX commented on aeon/performance_metrics/anomaly_detection/_continuous.py
> +from __future__ import annotations
This is required for the type annotation `int | None` as a replacement for `Optional[int]` to work with `python<3.10`.
Is also required to be on the top of the file and the first import!

2024-08-15 09:55 UTC, CodeLionX commented on pyproject.toml
> +    "prts>=1.0.0.3",
No specific reason, I did not test with any earlier versions.

I took a look at the changes between the versions, and earlier versions of v1.0.0 should still be fine; earlier is missing the f-score, tho. Thus, changing to `>=1.0.0.0`.

2024-08-15 11:05 UTC, MatthewMiddlehurst commented on aeon/performance_metrics/anomaly_detection/_continuous.py
> +from __future__ import annotations
I dislike this for some reason, but no changes required 🙂

2024-08-15 11:12 UTC, MatthewMiddlehurst approved these changes
I'm fine for this to go in as-is for now, may want to wait for input from others unless they are required for a tutorial. 

I have not verified the output correctness of these functions, I'm giving it a bit of trust as they have been used in other packages and publications AFAIK.

2024-08-17 18:45 UTC, baraline approved these changes
The additions of these metrics look fine to me, from what I remember of the actual maths, this seems to be accurate, LGTM !

2024-09-02 09:24 UTC, merged