Added Type Hints for _dilated_shapelet_transform
aeon-toolkit/aeon pull request #1949
Opened 2024-08-12 06:54 UTC by aryanpola

What does this implement/fix? Explain your changes.
I have added type hints for function variables and return values as described in issue.
#1910

2024-08-12 12:20 UTC, MatthewMiddlehurst commented
Hi, I can take a look at this in a bit if you are still having issues. Feel free to @ me with any questions. @baraline left a comment on your previous PR so im sure he would be open to questions as well

2024-08-12 20:22 UTC, MatthewMiddlehurst submitted a review, later dismissed
Some changes required IMO, @baraline might have more for the later function hints

2024-08-12 20:22 UTC, MatthewMiddlehurst commented on aeon/transformations/collection/shapelet_based/_dilated_shapelet_transform.py
> +        random_state: Optional[int] = None,
not sure about this one, may have to look into what others do as this can also be a `RandomState` object.

2024-08-12 20:22 UTC, MatthewMiddlehurst commented on aeon/transformations/collection/shapelet_based/_dilated_shapelet_transform.py
> +        distance: CPUDispatcher = "manhattan",
Is `CPUDispatcher` for functions? at the very least, this also accepts string inputs so that needs to be included.

2024-08-12 20:22 UTC, MatthewMiddlehurst commented on aeon/transformations/collection/shapelet_based/_dilated_shapelet_transform.py
> +from typing import Dict, List, Optional, Union
You cant import `List` here as `from numba.typed import List` happens later. One has to change (probably the numba one)

2024-08-13 05:22 UTC, baraline commented on aeon/transformations/collection/shapelet_based/_dilated_shapelet_transform.py
> +        distance: CPUDispatcher = "manhattan",
It is indeed for function, but made with numba njit, so users can give custom distance functions. String is indeed accepted too.

2024-08-13 05:25 UTC, baraline commented on aeon/transformations/collection/shapelet_based/_dilated_shapelet_transform.py
> +from typing import Dict, List, Optional, Union
I would suggest to import numba List as TypedList, as its exactly what it is under the hood.

2024-08-13 07:02 UTC, aryanpola commented on aeon/transformations/collection/shapelet_based/_dilated_shapelet_transform.py
> +from typing import Dict, List, Optional, Union
Added alias to differentiate between numba's list and typing's list.

2024-08-13 07:02 UTC, aryanpola commented on aeon/transformations/collection/shapelet_based/_dilated_shapelet_transform.py
> +        distance: CPUDispatcher = "manhattan",
I added union function which includes string.

2024-08-13 07:06 UTC, aryanpola commented on aeon/transformations/collection/shapelet_based/_dilated_shapelet_transform.py
> +        random_state: Optional[int] = None,
Added for hint for `RandomState` object

2024-08-13 10:59 UTC, aryanpola commented
@baraline Is there any reason for the tests to be canceled, they were all successful when I committed but got canceled when I updated the branch.

2024-08-13 11:16 UTC, baraline commented
I don't think that should be happening, let me check

2024-08-13 12:04 UTC, baraline requested changes
Re-runned the test, maybe something went wrong with the CI pipeline ? Some small changes and we should be good to go !

2024-08-13 12:04 UTC, baraline commented on aeon/transformations/collection/shapelet_based/_dilated_shapelet_transform.py
> +    n_timepointss: np.ndarray = np.zeros(n_cases, dtype=np.int64)
Same comment for type hint inside function

2024-08-13 12:04 UTC, baraline commented on aeon/transformations/collection/shapelet_based/_dilated_shapelet_transform.py
> +    distance: Union[CPUDispatcher, str],
Same comment as above, only CPUDispatcher is supported here.

2024-08-13 12:04 UTC, baraline commented on aeon/transformations/collection/shapelet_based/_dilated_shapelet_transform.py
> +    distance: Union[CPUDispatcher, str],
Same comment as above, only CPUDispatcher is supported here.

2024-08-13 14:21 UTC, baraline commented
Some changes were made to the document you are working with on #1959, which added two arguments to the `_init_random_shapelet_params` and `random_dilated_shapelet_extraction` function, which both are ndarray of integers. (need to merge main to see them)
Concerning the test, they seem to be canceling from time to time for yet unknown reasons, will keep an eye out and relaunch them if necessary.

2024-08-13 16:26 UTC, aryanpola commented
> Some changes were made to the file you are working with on #1959, which added two parameters to the `_init_random_shapelet_params` and `random_dilated_shapelet_extraction` function, which both are ndarray of integers. (need to merge main to see them). Edit : also to `dilated_shapelet_transform`, the shapelet tuple with have two additional ndarrays Concerning the test, they seem to be canceling from time to time for yet unknown reasons, will keep an eye out and relaunch them if necessary.

Are there any changes that I am supposed to make?

2024-08-13 16:57 UTC, baraline commented
Yes, could you should first merge the main branch into this and had the type hints for the new parameters of the functions I listed ?

2024-08-13 17:44 UTC, aryanpola commented
> Yes, could you should first merge the main branch into this and had the type hints for the new parameters of the functions I listed ?

Added the type hints after merging the main branch. Is there anything else to do?

2024-08-13 19:00 UTC, baraline commented on aeon/transformations/collection/shapelet_based/_dilated_shapelet_transform.py
> +        classes: np.ndarray[np.int32],
Type hints here are causing the test failures, you can't add them in the return statement

2024-08-13 19:01 UTC, baraline commented on aeon/transformations/collection/shapelet_based/_dilated_shapelet_transform.py
> +        random_state: Optional[int] = None,
Just checked, this estimator only supports int or None. So the other types can be removed.

2024-08-13 19:03 UTC, baraline commented
Just need to resolve the remaining conversation, and we'll be good to go I think ! 😄

2024-08-13 19:05 UTC, baraline commented on aeon/transformations/collection/shapelet_based/_dilated_shapelet_transform.py
> +        np.ndarray,
The two additional np.ndarray I was talking about are here, as `classes` and `startpoints` where added in the PR that got merged.

2024-08-13 20:48 UTC, aryanpola commented on aeon/transformations/collection/shapelet_based/_dilated_shapelet_transform.py
> +        classes: np.ndarray[np.int32],
Removed the type hints for return statement.

2024-08-13 20:49 UTC, aryanpola commented on aeon/transformations/collection/shapelet_based/_dilated_shapelet_transform.py
> +        np.ndarray,
Added 2 more np.ndarray's in the tuple.

2024-08-13 21:37 UTC, aryanpola commented on aeon/transformations/collection/shapelet_based/_dilated_shapelet_transform.py
> +        random_state: Optional[int] = None,
> Just checked, this estimator only supports int or None. So the other types can be removed.

The one for the random_state right?

2024-08-14 05:08 UTC, baraline commented on aeon/transformations/collection/shapelet_based/_dilated_shapelet_transform.py
> +        random_state: Optional[int] = None,
Exactly !

2024-08-14 09:30 UTC, aryanpola commented on aeon/transformations/collection/shapelet_based/_dilated_shapelet_transform.py
> +        random_state: Optional[int] = None,
I've changed the type hint, can you let me know if there's anything else to do.

2024-08-14 20:59 UTC, baraline approved these changes
Looking good to me! Thanks for your patience! 😄

2024-08-14 21:45 UTC, aryanpola commented
> Looking good to me! Thanks for your patience! 😄

Thanks a lot for the help!

2024-08-17 20:18 UTC, merged