[GOV] Slimmed down `Scikit-learn`-like governance document.
aeon-toolkit/aeon pull request #195
Opened 2023-03-13 18:03 UTC by MatthewMiddlehurst

This PR contains changes to the governance document in the style on `Scikit-learn`, based off my opinions from #2. All of this is flexible, but I think we should cut down the size of the original document whatever we go with.

2023-03-13 18:36 UTC, TonyBagnall requested changes

2023-03-13 18:36 UTC, TonyBagnall commented on docs/source/get_involved/governance.md
> +New Core Developers are nominated by existing Core Developers, and are subject to a two-third majority vote of existing Core Developers. Core Developers are expected to maintain a reasonable amount o
I probably wouldn't put the bit about "losing status" at all, and may not have the 2/3 bit. I would prefer "New Core Developers can be nominated by any contributor (including themselves) and are appointed with the agreement of the current Core Developers" and scrap this whole paragraph

2023-03-13 18:36 UTC, TonyBagnall commented on docs/source/get_involved/governance.md
> +Code of Conduct Committee (CoCC) members are contributors which are tasked with maintaining the ``aeon`` Code of Conduct (CoC) and managing CoC reports. CoC members are expected to review reports of
managing CoC reports -> " managing reports of breaking the CoC."

2023-03-13 18:36 UTC, TonyBagnall commented on docs/source/get_involved/governance.md
> +For most decisions a consensus seeking process of all interested contributions is used. Contributors try to find a resolution that has no open objections among Core Developers. If a reasonable amount
interested contributions -> interested contributors

2023-03-13 18:36 UTC, TonyBagnall commented on docs/source/get_involved/governance.md
> +For most decisions a consensus seeking process of all interested contributions is used. Contributors try to find a resolution that has no open objections among Core Developers. If a reasonable amount
lazy consensus means no one has approved it. I say remove the concept all together. Lack of interest in a PR is to me a sign that its not really needed or of interest

2023-03-13 18:36 UTC, TonyBagnall commented on docs/source/get_involved/governance.md
> +All changes to the ``aeon`` code or documentation should be done via Pull Request. By default, push rights to the ``main`` GitHub branch are restricted for all developers. In emergencies, the Communi
"happen only in emergencies where harm will come to the project unless timely action is taken"

2023-03-13 18:51 UTC, MatthewMiddlehurst commented on docs/source/get_involved/governance.md
> +For most decisions a consensus seeking process of all interested contributions is used. Contributors try to find a resolution that has no open objections among Core Developers. If a reasonable amount
Scikit-learn uses it in a different context at least, the line is similar to what they have. Can remove it as it doesn't really change the meaning, though.

2023-03-13 18:59 UTC, MatthewMiddlehurst commented on docs/source/get_involved/governance.md
> +New Core Developers are nominated by existing Core Developers, and are subject to a two-third majority vote of existing Core Developers. Core Developers are expected to maintain a reasonable amount o
Think we should keep the requirements to join there, but the exact thresholds and who can nominate are up for debate as you suggest.

I think we should be upfront about expectations (if there are any and whatever they are). Having nothing would kind of imply as long as you get voted in you remain forever.

2023-03-13 19:13 UTC, TonyBagnall commented
an alternative for discussion

2023-03-13 19:14 UTC, TonyBagnall commented on docs/source/get_involved/governance.md
> +For most decisions a consensus seeking process of all interested contributions is used. Contributors try to find a resolution that has no open objections among Core Developers. If a reasonable amount
I just dont like the term "lazy consensus" personally, otheres might like it.

2023-03-13 19:29 UTC, TonyBagnall commented
chatgpt likes it. Here is what is says about the rest

The text is generally well written and clear. However, here are some suggestions to improve it:

Governance and decision-making
The purpose of this document is to formalize the governance process used by the aeon project, to clarify how decisions are made and how the various elements of our community interact. Our goal is to ensure a transparent, democratic, and inclusive decision-making process that empowers all community members to contribute to the project.

Aeon is a community-owned and community-run project. Anyone with an interest in the project can join the community, contribute to the project design, and participate in the decision-making process. We believe that diversity and inclusivity are critical to the success of the project and welcome contributions from all backgrounds and perspectives.

This document establishes the decision-making structure used by aeon, which strives to find consensus from the community while avoiding any deadlocks. Our decision-making process involves different roles, each with specific responsibilities.

Roles
Contributors
Contributors are community members who have contributed in concrete ways to the project. Anyone can become a contributor, and contributions can take many forms – not only code – as detailed in the contributing guide. Contributors play a crucial role in shaping the project and can participate in discussions and decision-making processes.

Core Developers
Core developers are community members who have made significant contributions and are trusted to continue the development of the project and engage with its community. Core developers are granted write access to the aeon repository and voting rights on most project decisions. They are expected to review code contributions and engage with topics or code they are knowledgeable about.

New core developers are nominated by existing core developers and are subject to a two-thirds majority vote of existing core developers. Core developers are expected to maintain a reasonable amount of engagement with the project and may lose their status after a long period of inactivity and lack of engagement with fellow developers. Developing code, interacting with contributions, and engaging with the broader community are all valid contributions for core developers.

Community Council
The Community Council (CC) consists of core developers who have additional responsibilities to ensure the smooth running of the project. This includes strategic planning, project infrastructure management, and release management. In the event that core developers fail to reach a consensus, the CC is responsible for resolving the issue.

CC membership is subject to a two-thirds majority vote of core developers, and terms last for two years, after which a new vote must be held. The CC is accountable to the community and must report regularly on its activities and decisions.

Code of Conduct Committee
The Code of Conduct Committee (CoCC) consists of contributors tasked with maintaining the aeon Code of Conduct (CoC) and managing reports of breaking the CoC. CoCC members are expected to review reports of CoC violations, contact and discuss with involved individuals, and make recommendations on actions to take.

Any CoCC members involved in a CoC report or CoCC members who have a conflict of interest regarding the report are expected to recuse themselves from the process. If no CoCC members are available to review a report in a timely manner, the responsibility will fall to the Community Council.

CoCC membership is subject to a two-thirds majority vote of core developers, and terms last for two years, after which a new vote must be held. CC members cannot simultaneously be CoCC members to avoid conflicts of interest.

2023-03-30 16:25 UTC, aiwalter reviewed
left some comments. I think we need to define also when a core developer role ends. Would like to avoid having people that do not contribute but want to make decisions.

2023-03-30 16:25 UTC, aiwalter commented on docs/source/get_involved/governance.md
> +Decisions about the future of the project are made publicly to allow discussion with all members of the community. All non-sensitive project management discussion takes place on the contributors chan
> Decisions about the future of the project are made publicly

this is not clear to me, does it mean decision hae to be made involving public or just comunication of decision? I prefer the later here. We can still always have public discussions and sometimes also decisions if we want, but it should not be a requirement imho

2023-03-30 16:25 UTC, aiwalter commented on docs/source/get_involved/governance.md
> +For most decisions a consensus seeking process of all interested contributors is used. Contributors try to find a resolution that has no open objections among Core Developers. If a reasonable amount
> reasonable amount of time

I would propose to add 7 days here to be clear

2023-03-30 16:25 UTC, aiwalter commented on docs/source/get_involved/governance.md
> +At any point during the discussion, any Core Developer in favour of a change can call for a vote, which will conclude two weeks from the call for the vote. Any vote must be backed by an AEP (see foll
```suggestion
At any point during the discussion, any Core Developer in favour of a change can call for a vote, which will conclude one weeks from the call for the vote. Any vote must be backed by an AEP (see following section) or an issue or PR describing the objective of the vote. If no option can gather two-thirds of the votes cast, the decision is escalated to the Community Council, which in turn will use consensus seeking with the fallback option of a simple majority vote if no consensus can be found.
```

2023-03-30 16:25 UTC, aiwalter commented on docs/source/get_involved/governance.md
> +All changes to the ``aeon`` code or documentation should be done via Pull Request. By default, push rights to the ``main`` GitHub branch are restricted for all developers. In emergencies, the Communi
> developers

is it a Core Developer?

2023-03-30 16:25 UTC, aiwalter commented on docs/source/get_involved/governance.md
> +For all non-appointment decision-making votes, a proposal must have been made public and discussed before the vote. Such proposal must be a consolidated document, in the form of a “aeon Enhancement P
I think we need clearer description when an AEP has to be done. I thought that we had this better before? I think it shoukd mostly be optional to lower the entry point to make a contribution. AEP can be ok for major feature requests or interface changes. Basically I would say if 2/3 of CC says an AEP should be done for an enhancement then it has to be done, otherwise optional. What you think?

2023-03-30 16:32 UTC, MatthewMiddlehurst commented on docs/source/get_involved/governance.md
> +Decisions about the future of the project are made publicly to allow discussion with all members of the community. All non-sensitive project management discussion takes place on the contributors chan
Depends on the decision, really. Most decisions will be core-developer votes, but the fact that these votes are happening should be public to allow people to comment or involve themselves.

2023-03-30 16:34 UTC, MatthewMiddlehurst commented on docs/source/get_involved/governance.md
> +For most decisions a consensus seeking process of all interested contributors is used. Contributors try to find a resolution that has no open objections among Core Developers. If a reasonable amount
I would think it depends on the change, for small bugfixes or typos we probably don't need 7 days, but we can clarify that non-trivial changes should try to give at least 7 days.

2023-03-30 16:41 UTC, MatthewMiddlehurst commented on docs/source/get_involved/governance.md
> +All changes to the ``aeon`` code or documentation should be done via Pull Request. By default, push rights to the ``main`` GitHub branch are restricted for all developers. In emergencies, the Communi
Don't think its role specific, no one should be pushing to main unless it's an emergency.

2023-03-30 16:49 UTC, MatthewMiddlehurst commented on docs/source/get_involved/governance.md
> +For all non-appointment decision-making votes, a proposal must have been made public and discussed before the vote. Such proposal must be a consolidated document, in the form of a “aeon Enhancement P
Ideally we should be avoiding votes, and any PR where a vote is required will be somewhat controversial if people are unable to reach a consensus through discussion. Given that the onus is on the person making the pull request to call a vote to try to push their contribution through, it should probably be accompanied by some sort of proposal.

What this proposal is and how detailed it has to be is up for debate really. @TonyBagnall did not seem so keen on having a templated "AEP". Having a reasonably detailed issue or PR description should be fine.

2023-04-27 14:39 UTC, MatthewMiddlehurst commented on docs/source/get_involved/governance.md
> +Decisions about the future of the project are made publicly to allow discussion with all members of the community. All non-sensitive project management discussion takes place on the contributors chan
"Decisions about the future of the project are announced publicly to allow discussion with all members of the community, ideally with the whole process from proposal to implementation remaining fully visible, barring sensitive topics."

2023-04-27 14:39 UTC, MatthewMiddlehurst commented on docs/source/get_involved/governance.md
> +For most decisions a consensus seeking process of all interested contributors is used. Contributors try to find a resolution that has no open objections among Core Developers. If a reasonable amount
"If a reasonable amount of time (at least 7-days for non-trivial changes) has passed since the last change to a proposed contribution"

2023-05-05 15:32 UTC, TonyBagnall commented on docs/source/get_involved/governance.md
> +For all non-appointment decision-making votes, a proposal must have been made public and discussed before the vote. Such proposal must be a consolidated document, in the form of a “aeon Enhancement P
I dont mind really, not my kind of thing but others may like the formal AEP

2023-05-05 15:46 UTC, TonyBagnall submitted a review, later dismissed
I'm fine with this

2023-05-05 15:46 UTC, TonyBagnall commented on docs/get_involved/governance.md
> +Core Developers are granted write access to the `aeon` repository and voting rights
Developers -> developers here and later

2023-05-05 15:46 UTC, TonyBagnall commented on docs/get_involved/governance.md
> +New Core Developers are nominated by existing Core Developers, and are subject to a
core developers

2023-05-05 15:46 UTC, TonyBagnall commented on docs/get_involved/governance.md
> +implementation remaining fully visible, barring sensitive topics. All non-sensitive
I would reword this 

"Decisions about the future of the project are announced publicly to allow discussion
with all members of the community. The whole process from proposal to
implementation is fully visible, apart from topics considered sensitive. All non-sensitive
project management discussion takes place on the contributors channel on the project
Slack and/or the issue tracker. Occasionally, sensitive discussion and votes such as
appointments will occur in private Slack channels.

2023-05-05 17:21 UTC, ltsaprounis commented on docs/get_involved/governance.md
> +simultaneously be CoCC members.
I want to propose removing these 2 committees/councils and replace them with "Workgroups" like pandas: 
https://pandas.pydata.org/about/team.html

What do you all think?

2023-05-05 17:56 UTC, MatthewMiddlehurst commented on docs/get_involved/governance.md
> +simultaneously be CoCC members.
I'm not opposed to this. Would the current groups be CoC/Infrastructure/Communications/Release?

How would someone be included into a group, 50% core dev vote for regular members, 66% for lead? Do term limits still apply for both?

If this were the case, would each workgroup retain full control of the related accounts? i.e. infrastructure github/pypi/readthedocs and comms twitter/linkedin/slack?

2023-05-05 18:33 UTC, ltsaprounis commented on docs/get_involved/governance.md
> +simultaneously be CoCC members.
I think the control over the accounts makes sense for the workgroups. For the appointment, a vote is a good option for the future. For now I think we can aim to all agree on who does what.

2023-05-06 20:40 UTC, MatthewMiddlehurst commented on docs/get_involved/governance.md
> +simultaneously be CoCC members.
"If no option can gather two-thirds of the votes cast, the decision is escalated to the CC, which in turn will use consensus seeking with the fallback option of a simple majority vote if no consensus can be found."

Not quite sure what to do with this. Do all votes just become two-thirds or simple majority? Or would it depend on type/contents?

2023-05-08 14:18 UTC, MatthewMiddlehurst commented
I have incorporated suggestions and made a PR into this branch for the workgroups suggestion by @ltsaprounis in #389. I suppose we can discuss that either in that PR or here as it is relevant to both.

2023-06-05 23:48 UTC, hadifawaz1999 approved these changes

2023-06-07 07:51 UTC, aiwalter commented
Will review next week, on vacation this week.

2023-06-22 07:31 UTC, TonyBagnall submitted a review, later dismissed

2023-06-24 08:40 UTC, aiwalter reviewed
left a few mostly minor comments. This means we will not have sth like a Community Council anymore, right? Which would be fine with me, but I think then we need to better define the deprecation process of inactive core developers

2023-06-24 08:40 UTC, aiwalter commented on docs/get_involved/governance.md
> +engaging with the broader community are all valid contributions for core developers.
I think this is quite informal e.g. what means "long period of time"?

2023-06-24 08:40 UTC, aiwalter commented on docs/get_involved/governance.md
> +The Code of Conduct Workgroup (CoCW) consists of contributors tasked with making sure
we might then have to rename the `COCC` on website as well?

2023-06-24 08:40 UTC, aiwalter commented on docs/get_involved/governance.md
> +By default, push rights to the `main` GitHub branch are restricted for all developers.
```suggestion
By default, push rights to the `main` GitHub branch are restricted for all core developers.
```

2023-06-24 08:40 UTC, aiwalter commented on docs/get_involved/governance.md
> +For all non-appointment decision-making votes, a proposal must have been made public
I would add here the possibility to create a simple issue on GH to lower the barrier? Not every decision objective requires an AEP imo. E.g. adding a dependency e.g. ?

2023-06-24 13:08 UTC, lmmentel approved these changes

2023-06-24 16:35 UTC, MatthewMiddlehurst commented on docs/get_involved/governance.md
> +The Code of Conduct Workgroup (CoCW) consists of contributors tasked with making sure
True, I can make a follow-up for the governance page, code of conduct document, etc if this is approved.

2023-06-24 16:39 UTC, MatthewMiddlehurst commented on docs/get_involved/governance.md
> +For all non-appointment decision-making votes, a proposal must have been made public
A definition for an "AEP" does not really exist, so it could be a big templated thing like sklearn does or just an issue giving some explanation. I can include a statement like that in the section if you want.

This would only be for situations where someone vetos a decision/PR, and instead of finding a consensus the one pushing the change decides to call a vote. Which from experience so far, seems to be a pretty rare occurrence.

2023-06-24 16:40 UTC, MatthewMiddlehurst commented on docs/source/get_involved/governance.md
> +At any point during the discussion, any Core Developer in favour of a change can call for a vote, which will conclude two weeks from the call for the vote. Any vote must be backed by an AEP (see foll
Given the new comments, is the length of votes still a change you think should happen?

2023-06-24 16:44 UTC, MatthewMiddlehurst commented on docs/get_involved/governance.md
> +engaging with the broader community are all valid contributions for core developers.
We can formalise it a bit more, but we would have to define A. in what situation would someone be removed (no contribution for x amount of time, no contact on any communication channels for x amount of time?), B. how long does someone have to be inactive to be removed, how much advance warning do they need to be given? C. who/what group has the responsibility to start this procedure and try to make contact with the inactive person

2023-09-06 14:36 UTC, MatthewMiddlehurst commented on docs/source/get_involved/governance.md
> +At any point during the discussion, any Core Developer in favour of a change can call for a vote, which will conclude two weeks from the call for the vote. Any vote must be backed by an AEP (see foll
An issue or PR as an altenrative to an AEP has been included in the enhancment proposal section if everyone involed agrees.

I have clarified when a AEP is needed (contentious PR votes where there is a rejection or major framework changes).

2023-09-06 14:41 UTC, MatthewMiddlehurst commented on docs/get_involved/governance.md
> +engaging with the broader community are all valid contributions for core developers.
I have formalised this a bit more deciding on some of the above.

As of the current document, after 1 year with no contributions (Developing code, interacting with contributions and engaging with the broader community), any core developer can make a PR to remove another core developer meeting this criteria. If this PR passes they are formally removed from the role.

2023-09-06 14:43 UTC, MatthewMiddlehurst commented on docs/get_involved/governance.md
> +For all non-appointment decision-making votes, a proposal must have been made public
See above comments. I have clarified when a AEP is needed, what an AEP is with a template suggestion, and alternative methods of making a proposal.

For changes that no one rejects (even with rejections as long as there is no vote called), there is no need to make such a document.

2023-09-08 14:37 UTC, TonyBagnall approved these changes

2023-09-08 14:42 UTC, hadifawaz1999 approved these changes

2023-09-08 15:32 UTC, dguijo approved these changes

2023-09-08 15:59 UTC, patrickzib approved these changes

2023-09-08 18:09 UTC, chrisholder approved these changes

2023-09-10 11:37 UTC, MatthewMiddlehurst commented
This currently has 5 approvals and one previous approval by @lmmentel. Could you respond to the comments on the open conversations @aiwalter when you find the time? No pressure to approve if you still have issues, but would be good to make progress.

2023-10-09 09:23 UTC, MatthewMiddlehurst commented
I am calling a vote on this PR. It will conclude 16/10/2023. Core developers can either signal approval (i.e. '+1' or 'I approve') or rejection (i.e. -1 or 'I reject') in the posts below this. Going by current rules, a 2/3 majority is required to pass.

2023-10-09 09:27 UTC, MatthewMiddlehurst commented
+1

2023-10-09 09:32 UTC, chrisholder commented
+1

2023-10-09 09:33 UTC, TonyBagnall commented
+1

2023-10-09 09:34 UTC, baraline commented
+1

2023-10-09 10:38 UTC, dguijo commented
+1

2023-10-10 12:12 UTC, hadifawaz1999 commented
+1

2023-10-11 09:07 UTC, patrickzib commented
+1

2023-10-11 16:24 UTC, ltsaprounis commented
+1

2023-10-16 09:08 UTC, MatthewMiddlehurst commented
Vote has passed 8 Yes to 0 No. Merging.

2023-10-16 09:08 UTC, merged