[ENH] Add a warping path series transformer
aeon-toolkit/aeon pull request #2001
Opened 2024-08-21 14:50 UTC by hadifawaz1999

After finding a warping path from elastic measures, this transformer re-aligns a series to adjust for warping corrections.
For example, on two samples of the ECG200 dataset:
![image](https://github.com/user-attachments/assets/161d3b5e-4c2a-4d5e-86ea-964a6f9dcbbe)

With a dtw path as such:
![image](https://github.com/user-attachments/assets/d2d66f96-c704-4c81-8b81-7cbfe775bc6c)

After transforming both series (see example in docstring), we get these two new series:
![image](https://github.com/user-attachments/assets/00d444b6-e4fe-4287-b628-726e1dfd493e)

And this is the new dtw path between them:
![image](https://github.com/user-attachments/assets/81973b62-5003-400e-85ca-0e5a7bfeceda)

2024-09-12 15:07 UTC, TonyBagnall requested changes
not sure what this is for, but seems fine except for the warping path in the  constructor, I do not think it should default to None

2024-09-12 15:07 UTC, TonyBagnall commented on aeon/transformations/series/_warping.py
> +        self, series_index: int = 0, warping_path: List[Tuple[int, int]] = None
I think this should be required, not clear what happens if it is not passed

2024-09-12 15:07 UTC, TonyBagnall commented on aeon/transformations/series/_warping.py
> +            time series in shape (n_channels, n_timepoints)
series of shape

2024-09-12 15:25 UTC, hadifawaz1999 commented on aeon/transformations/series/_warping.py
> +        self, series_index: int = 0, warping_path: List[Tuple[int, int]] = None
yeah  makes sense

2024-09-24 10:37 UTC, TonyBagnall approved these changes

2024-09-24 10:37 UTC, merged