Added Methods for Normalisation
aeon-toolkit/aeon pull request #2005
Opened 2024-08-23 05:39 UTC by aryanpola

What does this implement/fix? Explain your changes.
I have added a new file normalise in aeon\transformations\collection as requested in issue #2000.

2024-08-23 20:36 UTC, hadifawaz1999 requested changes
Thank you for the new transformer, just some comments that i left
would be good to add a test for it , simple one to call it on random data

2024-08-23 20:36 UTC, hadifawaz1999 commented on aeon/transformations/collection/Normalise.py
> +        The normalization method to apply.
duplicate sentence in docs

2024-08-23 20:36 UTC, hadifawaz1999 commented on aeon/transformations/collection/Normalise.py
> +        elif self.method == "standardize":
what is the difference between z_norm  and standarize ? they seem to have the same code unless am mistaken

2024-08-23 20:36 UTC, hadifawaz1999 commented on aeon/transformations/collection/Normalise.py
> +    def _fit(self, X, y=None):
no need to code fit, can add it in the tag, and the tags are missing, it should be 
_tags = {
        "X_inner_type": ["np-list", "numpy3D"],
        "fit_is_empty": True,
        "capability:multivariate": True,
    }

2024-08-23 20:36 UTC, hadifawaz1999 commented on aeon/transformations/collection/Normalise.py
> +        The training input samples.
x and y are parameters in transform not init of the class, here it should only mention "method" and "axis"

2024-08-23 20:36 UTC, hadifawaz1999 commented on aeon/transformations/collection/Normalise.py
> +            return (X - min_val) / (max_val - min_val)
should probably handle 0 values in denominator (case where max = min)

2024-08-23 20:36 UTC, hadifawaz1999 commented on aeon/transformations/collection/Normalise.py
> +            mean = np.mean(X, axis=self.axis, keepdims=True)
would be good to handle cases where std = 0 (stationary series) in this case we dont divide by std and only normalize on the mean

2024-08-23 20:36 UTC, hadifawaz1999 commented on aeon/transformations/collection/Normalise.py
> +    def _fit(self, X, y=None):
_tags should be added before the definition of the constructor

2024-08-24 13:07 UTC, aryanpola commented on aeon/transformations/collection/Normalise.py
> +        elif self.method == "standardize":
I noticed that but left it in as the issue stated them as two different normalisation methods so chose to keep. I'll change it if you want me to.

2024-08-24 13:09 UTC, aryanpola commented on aeon/transformations/collection/Normalise.py
> +            return (X - min_val) / (max_val - min_val)
Should I raise an error if the min and max values are the same?

2024-08-24 13:16 UTC, hadifawaz1999 commented on aeon/transformations/collection/Normalise.py
> +        elif self.method == "standardize":
@TonyBagnall did you have something in mind for difference between standard norm and znorm ? i think sklearn's standard scalar does the same as done here in both

2024-08-24 13:20 UTC, hadifawaz1999 commented on aeon/transformations/collection/Normalise.py
> +            return (X - min_val) / (max_val - min_val)
not sure, so if min=max it means the series is stationary, in that case maybe divide by 1 instead of max-min, so the transformer would return 0s

2024-08-24 17:47 UTC, aryanpola commented
@hadifawaz1999 The windows 11 python 3.12 test is passing but the windows 11 python 3.11 is failing. can you please check it.

2024-08-24 17:49 UTC, hadifawaz1999 commented
> @hadifawaz1999 The windows 11 python 3.12 test is passing but the windows 11 python 3.11 is failing. can you please check it.

just re-ran it now, random fail :)

2024-08-24 18:41 UTC, aryanpola commented
> > @hadifawaz1999 The windows 11 python 3.12 test is passing but the windows 11 python 3.11 is failing. can you please check it.
> 
> just re-ran it now, random fail :)

Are there any more changes needed?

2024-08-24 18:43 UTC, hadifawaz1999 commented
i would like your input @TonyBagnall  on this given you made the feature request

2024-09-02 00:07 UTC, hadifawaz1999 requested changes
All changes look great thanks, could you just add the transformer to api ? then we can merge it

2024-09-02 14:29 UTC, aryanpola commented on aeon/transformations/collection/Normalise.py
> +        Axis along which to apply the normalization.
I've taken a numpy array as an example in the test for normaliser, I'm not so sure how the effect will be if there are list of numpy arrays inputed. I'll look into it and let you know.
But the current module only takes numpy arrays as input.

2024-09-02 14:29 UTC, aryanpola commented on aeon/transformations/collection/Normalise.py
> +scaling across datasets.
Removed them

2024-09-02 14:31 UTC, aryanpola commented on aeon/transformations/collection/Normalise.py
> +    }
same as the above, the input is only numpy arrays.

2024-09-02 15:12 UTC, aryanpola commented on aeon/transformations/collection/Normalise.py
> +    }
Would padding the arrays be a good idea? This would convert the different shapes to the same ones, later concatenate the arrays to form a single array to normalise, and then get back the original array.

2024-09-03 14:48 UTC, MatthewMiddlehurst commented on aeon/transformations/collection/Normalise.py
> +    }
Leave it for another issue IMO. Would not pad in the class itself.

2024-09-03 14:53 UTC, MatthewMiddlehurst commented on aeon/transformations/collection/Normalise.py
> +        Axis along which to apply the normalization.
The tag means that inputs are converted to a numpy array internally, users can still input a list of numpy arrays which will then be converted.

given that we use `(n_cases, n_channels, n_timepoints)` i assume `axis=1` would normalise channels and `axis=2` would normalise the series (like expected). Maybe it does not make much sense to have `axis`? i dont really know when you would want to normalise by channel.

2024-09-05 07:46 UTC, aryanpola commented on aeon/transformations/collection/Normalise.py
> +        Axis along which to apply the normalization.
What would the selection of axes values be based on?
Like would the resultant numpy array being normalised in a smaller range be better?

2024-09-05 07:47 UTC, aryanpola commented on aeon/transformations/collection/Normalise.py
> +        Axis along which to apply the normalization.
> What would the selection of axes values be based on? Like would the resultant numpy array being normalised in a smaller range be better?

All the axes values confine the resulatant values to a specific range

2024-09-06 12:23 UTC, MatthewMiddlehurst commented on aeon/transformations/collection/Normalise.py
> +        Axis along which to apply the normalization.
My original request was to expand the documentation, because we accept other input types than 3d numpy arrays and it may not be obvious what the parameter is doing for those (it all gets converted to 3d numpy anyway so its the same).

But it doesnt really make sense to have an `axis` parameter anyway after more thought.

2024-09-07 11:08 UTC, aryanpola commented on aeon/transformations/collection/Normalise.py
> +        Axis along which to apply the normalization.
I've looked at other 3d array use cases in code and fixed `axis=-1` which normalises across all the timepoints in a 3d array.

2024-09-16 10:44 UTC, MatthewMiddlehurst approved these changes

2024-09-16 11:18 UTC, hadifawaz1999 requested changes
so if am not mistaken @TonyBagnall standard would mean just zero mean and not divide by std ?

2024-09-16 17:05 UTC, TonyBagnall requested changes
thanks for this, just need to either change the meaning of standardise or stick with the two allowed values, its up to you

2024-09-16 17:05 UTC, TonyBagnall commented on aeon/transformations/collection/Normalise.py
> +"""Normalization like z-normalization, standardization and min-max scaling."""
could you change the file name to _normalise please?

2024-09-16 17:05 UTC, TonyBagnall commented on aeon/transformations/collection/Normalise.py
> +        z_norm, standardize: Subtracts the mean and divides by the standard deviation
to mean, standardise would just remove the mean, z_norm then also divide by the standard deviation. Either way, I think its better to have a single meaning

2024-09-16 17:05 UTC, TonyBagnall commented on aeon/transformations/collection/Normalise.py
> +        if self.method in {"z_norm", "standardize"}:
I agree, see my comment above. If you want standardise, it should simply subtract the mean

2024-09-16 19:19 UTC, aryanpola commented on aeon/transformations/collection/Normalise.py
> +        z_norm, standardize: Subtracts the mean and divides by the standard deviation
So, would there be two different methods for z-norm and standardization?
standardization returns `X - mean` and z-norm `X - mean/std_nonzero`

2024-09-16 20:23 UTC, aryanpola commented
```
INTERNALERROR> ImportError: cannot import name 'BaseCollectionTransformer' from partially initialized module 'aeon.transformations.collection' (most likely due to a circular import) (C:\aeon\aeon\transformations\collection\__init__.py)
```
@TonyBagnall can you please help with this error.

2024-09-17 15:15 UTC, merged