Added tags for clustering
aeon-toolkit/aeon pull request #2041
Opened 2024-09-08 11:02 UTC by aryanpola

What does this implement/fix? Explain your changes.
I've added the necessary tags for some files under clustering.
#2035

2024-09-08 11:08 UTC, aryanpola commented
@chrisholder I've run the pre-commit and showed no errors. Can you help me with the errors.

2024-09-09 15:49 UTC, TonyBagnall commented
thanks for this, but it not what quite what I meant. If you look at classification,  we have a tag on the type of algorithm, e.g

"algorithm_type": "distance"

or

"algorithm_type": "deeplearning",

this is the only tag we want adding, not all the constructor arguments.

2024-09-10 09:16 UTC, aryanpola commented
> thanks for this, but it not what quite what I meant. If you look at classification, we have a tag on the type of algorithm, e.g
> 
> "algorithm_type": "distance"
> 
> or
> 
> "algorithm_type": "deeplearning",
> 
> this is the only tag we want adding, not all the constructor arguments.

@TonyBagnall I've made changes, please let me know if there's more to do.

2024-09-11 08:59 UTC, TonyBagnall requested changes
thanks for this, minor things
1. could you change KShape to just "distance"
2. You do not need to repeat the tag for classes that inherit from KMedoids, you can just remove them for CLARANS and CLARA

2024-09-11 09:15 UTC, aryanpola commented
> thanks for this, minor things
> 
> 1. could you change KShape to just "distance"
> 2. You do not need to repeat the tag for classes that inherit from KMedoids, you can just remove them for CLARANS and CLARA

I've changed them. Thanks for the help😊

2024-09-11 12:17 UTC, TonyBagnall requested changes

2024-09-11 12:17 UTC, TonyBagnall commented on aeon/clustering/base.py
> +
dont want this

2024-09-11 12:17 UTC, TonyBagnall commented on aeon/clustering/_kernel_k_means.py
> +        "algorithm_type": "kernel-k-means",
can you just remove this? I dont want to introduce a new type here

2024-09-12 06:07 UTC, TonyBagnall approved these changes

2024-09-12 06:08 UTC, TonyBagnall commented
thanks for this

2024-09-12 06:08 UTC, merged