Similarity docstring
aeon-toolkit/aeon pull request #2056
Opened 2024-09-15 10:00 UTC by aryanpola

What does this implement/fix? Explain your changes.
Added docstrings for similarity search and made the description of the same parameters in different functions the same.
#2023 

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [ ] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

2024-09-24 05:31 UTC, baraline requested changes
Great additions thank you ! :) 
Minor typos and formatting comment, and we will be good to go

2024-09-24 05:31 UTC, baraline commented on aeon/similarity_search/_commons.py
> +        Wheter to return the worst matches instead of the bests. The default is False.
I don't think it changes much in the docs rendering, but for consistency, could you remove the additional line break between each parameter?

2024-09-24 05:31 UTC, baraline commented on aeon/similarity_search/distance_profiles/squared_distance_profile.py
> +    Compute squared distance profiles between query subsequences and time series.
I think `subsequences` would imply that there is multiple queries ? (removing the `s` should do it)

2024-09-24 05:31 UTC, baraline commented on aeon/similarity_search/distance_profiles/squared_distance_profile.py
> +    Compute the normalized squared distance profiles between query subsequences and input time series.
same comment on `subsequences`

2024-09-24 05:31 UTC, baraline commented on aeon/similarity_search/distance_profiles/squared_distance_profile.py
> +        List of 2D arrays, each of shape (n_channels, n_timepoints - query_length + 1), where `profile_length` is the length of the distance profile for each time series.
`where `profile_length` is the length of the distance profile for each time series.` this can be removed as the value is not used

2024-09-24 05:31 UTC, baraline commented on aeon/similarity_search/distance_profiles/squared_distance_profile.py
> +        Each array contains the normalized squared distance profile between the query subsequences and the corresponding time series.
same comment on `subsequences`

2024-09-24 05:31 UTC, baraline commented on aeon/similarity_search/matrix_profiles/stomp.py
> +        The number of best matches to return during predict for each subsequence.
Same comment on the additional line breaks.

2024-09-24 07:52 UTC, aryanpola commented
@baraline Made the changes, let me know if there is anything more to do. Thanks!

2024-09-26 05:07 UTC, baraline approved these changes
Thanks lgtm !

2024-09-26 05:08 UTC, merged