[ENH] Add BORF transformer
aeon-toolkit/aeon pull request #2062
Opened 2024-09-16 14:08 UTC by fspinna

#### What does this implement/fix? Explain your changes.
I am trying to add a Bag-Of-Receptive-Fields transformer as seen in `Spinnato, Francesco, et al. "A Bag of Receptive Fields for Time Series Extrinsic Predictions." arXiv preprint arXiv:2311.18029 (2023)`. It is basically a Bag-Of-Pattern transform, where a time series is transformed in a sparse matrix of counts of discretized subsequences.

#### Does your contribution introduce a new dependency? If yes, which one?
This contribution introduces a dependency to the pydata sparse library (https://sparse.pydata.org/en/stable/). 

#### Any other comments?

I have a couple of issues/doubts:
1. the transformer fails 2 tests: 
```
'test_persistence_via_pickle(estimator=BORF(),datatype=EqualLengthUnivariate-Classification-numpy3D)': "FAILED: 'csr_matrix' object has no attribute 'ravel'",
'check_fit_deterministic(estimator=BORF(),datatype=EqualLengthUnivariate-Classification-numpy3D)': "FAILED: 'csr_matrix' object has no attribute 'ravel'"
```
This is because the output of the transformer is a sparse scipy matrix (https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html#scipy.sparse.csr_matrix). I don't know if this is a problem. In practice, the sparse matrix is compatible with downstream sklearn estimators/transformers.

2. the sparse package is used as a soft dependency, which is imported in the transform of `IndividualBORF`, which inherits from sklearn's BaseEstimator, TransformerMixin, and not BaseCollectionTransformer. Is this a problem?

### PR checklist

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [x] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

##### For new estimators and functions
- [x] I've added the estimator to the online [API documentation](https://www.aeon-toolkit.org/en/latest/api_reference.html).
- [x] (OPTIONAL) I've added myself as a `__maintainer__` at the top of relevant files and want to be contacted regarding its maintenance. Unmaintained files may be removed. This is for the full file, and you should not add yourself if you are just making minor changes or do not want to help maintain its contents.

2024-09-16 16:25 UTC, TonyBagnall commented
great, thanks for that

2024-09-16 17:56 UTC, TonyBagnall commented on aeon/transformations/collection/dictionary_based/_borf.py
> +    window_size_min : int, optional (default=4)
thanks for the PR, we will look into the test fails, but just on style, sorry to be annoying but we use
window_size_min : int, default=4
as our style. Could you use that?

2024-09-17 07:40 UTC, fspinna commented on aeon/transformations/collection/dictionary_based/_borf.py
> +    window_size_min : int, optional (default=4)
No problem, style is important! Let me know if it's okay now and if there are any other issues.

2024-10-12 17:23 UTC, TonyBagnall commented
hi @fspinna sorry for the delay on this, we will definitely review this week. I'm afraid there are a couple of conflicts which should be easy to resolve

2024-10-14 16:28 UTC, TonyBagnall reviewed
thanks again, but my this is huge! A couple of questions
1. You use the sparse package. Elsewhere we use from scipy.sparse import csr_matrix. scipy is a core dependency, so it would be preferable to use this if it is fit for purpose.
2. It would also be good to have a constructor option to return the whole sparse array rather than the compressed version
3. there are two arguments for n_jobs
            n_jobs=self.n_jobs,
            n_jobs_numba=self.n_jobs_numba,
how come?
4. You have reimplemented SAX. We have a version of SAX already, would it be possible to use that? If not, see 5 below.
5. There are a lot of specific public functions which will bloat the docs, could you make the file specific functions private? things like `are_window_size_and_dilation_compatible_with_signal_length` Same with all the small sklearn transformers, better off private imo. 
6. You have implemented a hash table?

2024-10-15 09:36 UTC, patrickzib commented
> One of the contributions of the paper was a better/faster way of computing window-wise SAX. Also, this version has dilation, stride and other parameters that are not usually in SAX. So I don't believe I can use your implementation.

It might be a bit ambitious for this PR, but it would be wonderful to include a fast sliding window SAX-transform with dilation if possible.

2024-10-16 11:45 UTC, TonyBagnall commented
do we need a lower bound on the sparse package?

2024-10-16 11:46 UTC, TonyBagnall commented
re SAX, we could investigate using this version as our standard and extending it as you say @patrickzib but not in this PR :) IT would be good to make an issue on improving SAX

2024-10-16 12:06 UTC, chrisholder requested changes

2024-10-16 12:06 UTC, chrisholder commented on aeon/transformations/collection/dictionary_based/_borf.py
> +        ):  # if alphabet_slope <= 1, word_length=1 is useless
Does this comment need to exist still?

2024-10-16 12:06 UTC, chrisholder commented on aeon/transformations/collection/dictionary_based/_borf.py
> +    ):  # if window_size * dilation exceeds the length of the sequence
Does this comment need to exist still?

2024-10-16 12:06 UTC, chrisholder commented on aeon/transformations/collection/dictionary_based/_borf.py
> +        # if window_size == word_length:
Does this comment need to exist still?

2024-10-17 07:38 UTC, fspinna commented
> It might be a bit ambitious for this PR, but it would be wonderful to include a fast sliding window SAX-transform with dilation if possible.

> re SAX, we could investigate using this version as our standard and extending it as you say @patrickzib but not in this PR :) IT would be good to make an issue on improving SAX

Also, it's not a perfect replacement for standard SAX, as the window size has to be divisible by the word length in my case.

2024-10-17 07:52 UTC, fspinna commented on aeon/transformations/collection/dictionary_based/_borf.py
> +        ):  # if alphabet_slope <= 1, word_length=1 is useless
It can be removed, but it's more of an explanatory comment. Should I remove these kinds of comments in general?

2024-10-17 07:52 UTC, fspinna commented on aeon/transformations/collection/dictionary_based/_borf.py
> +        # if window_size == word_length:
No, I'll remove it.

2024-10-18 07:47 UTC, TonyBagnall commented
> > It might be a bit ambitious for this PR, but it would be wonderful to include a fast sliding window SAX-transform with dilation if possible.
> 
> > re SAX, we could investigate using this version as our standard and extending it as you say @patrickzib but not in this PR :) IT would be good to make an issue on improving SAX
> 
> Also, it's not a perfect replacement for standard SAX, as the window size has to be divisible by the word length in my case.

I like the idea of having a speed optimised constrained version and a more general case one, but its a project in its own right really. This looks ready to go in to me, thanks for the contribution. There are a couple of minor conflicts to resolve caused by changes elsewhere, sorry about that

2024-10-18 07:51 UTC, TonyBagnall commented
could we add your paper to this? https://www.aeon-toolkit.org/en/stable/papers_using_aeon.html

Even better, can you add your paper to this (in a separate PR)? :)

2024-10-18 08:05 UTC, fspinna commented
> do we need a lower bound on the sparse package?

I am using the latest (0.15.4)


> could we add your paper to this? https://www.aeon-toolkit.org/en/stable/papers_using_aeon.html
> 
> Even better, can you add your paper to this (in a separate PR)? :)

Sure!


> I like the idea of having a speed optimised constrained version and a more general case one, but its a project in its own right really. This looks ready to go in to me, thanks for the contribution. There are a couple of minor conflicts to resolve caused by changes elsewhere, sorry about that

Thank you! No problem, let me know if there is anything else to do!

2024-10-18 08:27 UTC, TonyBagnall commented on aeon/transformations/collection/dictionary_based/_borf.py
> +        ):  # if alphabet_slope <= 1, word_length=1 is useless
its fine to leave. Generally we have gone for longer docstrings and fewer in line comments, but I think I actually prefer a few more inline comments for more complex constructs to aid readability

2024-10-18 13:23 UTC, TonyBagnall commented
hi @fspinna if you resolve the conflicts I think this is ready to go in

2024-10-18 13:31 UTC, fspinna reviewed
Fixed unused comments

2024-10-18 16:22 UTC, fspinna commented
> hi @fspinna if you resolve the conflicts I think this is ready to go in

@TonyBagnall I fixed a few things (tags, doctest) but I am still failing on a few OS. Not really sure what's the issue here.

2024-10-20 18:00 UTC, MatthewMiddlehurst commented
Hi @fspinna, not too up to date with this PR but its only failing on some workflows because we split the tests up when running on PRs to save time.

I can take a look at whats failing at some point if no one else finds the time.

2024-10-20 18:02 UTC, MatthewMiddlehurst commented
Alternatively, there is a `non-deteminsitic` and `cant-pickle` tag which will skip these particular tests, but we try to only use them if it is not an easily fixable issue.

Adding it temporarily to the skipped test list is also an option, and revisiting in another PR.

2024-10-21 19:53 UTC, TonyBagnall approved these changes
LGTM, thanks for the contribution

2024-10-21 19:54 UTC, merged