[ENH] Issue 1641 - Matrix profile-based anomaly detectors: left STAMPi
aeon-toolkit/aeon pull request #2091
Opened 2024-09-24 12:23 UTC by ferewi

#### Reference Issues/PRs
Fixes #1641 

#### What does this implement/fix? Explain your changes.
This PR implements the LeftSTAMPi Anomaly Detector based on the implementation in TimeEval (https://github.com/TimeEval/TimeEval-algorithms/blob/main/left_stampi/algorithm.py)

The Algorithm can be run in two modes.
1. Batch mode: Here the whole time series is put in at once. Internally the LeftSTAMPi algorithm is applied incrementally.
2. Stream mode: Here the Algorithm is initialized on a specified number of data points. The Matrix profile is then calculated incrementally. 

Remarks:
The batch mode is implemented in the `fit_predict` method. 
The stream mode is implemented in the `fit` and `predict`methods, where `fit`is used to init the algorithm and `predict` is used for imcremental updates. As the `predict`method only accepts `np.ndarray` as its argument, on every update the new data point, which is a scalar has to be wrapped in a one-element numpy array.  This is actually unnecessarry but avoiding this would involve a change to the interface in `BaseAnomalyDetector`.

#### Does your contribution introduce a new dependency? If yes, which one?
No.

#### Any other comments?
See remarks in the implementation description.

### PR checklist

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
  @all-contributors please add @ferewi for code, doc and test
- [x] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

##### For new estimators and functions
- [x] I've added the estimator to the online [API documentation](https://www.aeon-toolkit.org/en/latest/api_reference.html).
- [x] (OPTIONAL) I've added myself as a `__maintainer__` at the top of relevant files and want to be contacted regarding its maintenance. Unmaintained files may be removed. This is for the full file, and you should not add yourself if you are just making minor changes or do not want to help maintain its contents.

##### For developers with write access
- [ ] (OPTIONAL) I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.

2024-09-24 13:35 UTC, CodeLionX requested changes
Thank you for your contribution!

I'm in favor of supporting streaming use cases, and I also like the idea of repeatedly calling `predict`. However, this violates the convention that no internal representation is updated in `predict`. We can neither use repeated calls to `fit` because it is assumed to reset the estimator on the beginning of each call.

I guess, we need to design a new API for streaming. @MatthewMiddlehurst how do you think about this?

Until we have decided on the new API, I would suggest adding leftSTAMPi only with its batch API.

2024-09-24 13:35 UTC, CodeLionX commented on aeon/anomaly_detection/_left_stampi.py
> +    in the time series, in an incremental manner. The matrix profile is then
More precise: The distance to the nearest neighbor of already observed subsequences (all preceding subsequences)

2024-09-24 13:35 UTC, CodeLionX commented on aeon/anomaly_detection/_left_stampi.py
> +        The discord will not be found in this segment.
Only used in batch-case, right?

2024-09-24 13:35 UTC, CodeLionX commented on aeon/anomaly_detection/_left_stampi.py
> +        self.mp: np.ndarray | None = None
The `self.mp`-member is not an algorithm parameter and set during `fit`, so must be named `mp_` (sklearn and aeon convention).

2024-09-24 13:35 UTC, CodeLionX commented on aeon/anomaly_detection/_left_stampi.py
> +        self.n_init_train = len(X)
sklearn forbids overwriting algorithm parameters. You can either use an internal variable (`self._n_init_train`) or a local one.

2024-09-24 16:03 UTC, ferewi commented
@CodeLionX Thanks for your comments and suggestions. The failing test-suite made me aware that the approach I took for the streaming case is violating the concept of `fit`, `predict`and `fit_predict`. I'll remove the streaming case for now. An idea for the streaming API might be to have an `update` method that is allowed to modify the internal representation after the intitial fitting. 

Also, could you point me to the documentation of the sklearn and aeon conventions regarding the naming conventions (`self.mp_`vs `self.mp`), etc.? (If you have that at hand - I surely can google that myself)

2024-09-25 08:17 UTC, ferewi commented on aeon/anomaly_detection/_left_stampi.py
> +            X = X.squeeze()
Yes, I testesd this. When I pass an univariate time series of length 20 as an array of shape (20, 1), the X.squeeze() is requireed. 
Is there a better way to ave this handled by the base class?

2024-09-25 08:17 UTC, ferewi commented on aeon/anomaly_detection/_left_stampi.py
> +            X = X.squeeze()
please see above

2024-09-25 08:18 UTC, ferewi commented on aeon/anomaly_detection/tests/test_left_stampi.py
> +)
That's right. But the library has to be installed to be mocked. Is there a standard way to avoid this?

2024-09-25 08:21 UTC, ferewi commented on aeon/anomaly_detection/_left_stampi.py
> +    in the time series, in an incremental manner. The matrix profile is then
I amended the sentence.

2024-09-25 08:22 UTC, ferewi commented on aeon/anomaly_detection/_left_stampi.py
> +        The discord will not be found in this segment.
That's right. As there is nothing but the batch mode now, I did not add this comment. To be added when/if the streaming case gets implemented.

2024-09-25 08:22 UTC, ferewi commented on aeon/anomaly_detection/_left_stampi.py
> +        self.mp: np.ndarray | None = None
Thankss for pointing that out. I renamed the variable

2024-09-25 08:22 UTC, ferewi commented on aeon/anomaly_detection/_left_stampi.py
> +        self.n_init_train = len(X)
This has been removed.

2024-09-25 09:09 UTC, ferewi commented
Still making changes to fix the failling tests. I will re-request a new review when I am done.

2024-09-25 09:34 UTC, CodeLionX commented on aeon/anomaly_detection/tests/test_left_stampi.py
> +)
Ah, true ... you could mock/overwrite the `_call_stumpi`-method and fill the `self._mp`-member with your mocked data structures.

2024-09-25 09:37 UTC, CodeLionX commented
> Also, could you point me to the documentation of the sklearn and aeon conventions regarding the naming conventions (`self.mp_`vs `self.mp`), etc.? (If you have that at hand - I surely can google that myself)

It is sprinkled in this guide: https://scikit-learn.org/dev/developers/develop.html

2024-09-25 11:32 UTC, MatthewMiddlehurst commented
Thanks for the contribution. Feel free to ask if you have any questions regarding the failures, i.e. we have a tag for estimators which can't be pickled (usually due to dependencies outside of our control).

2024-09-25 11:33 UTC, MatthewMiddlehurst commented
Think adding to the base API should be a separate PR yeah, would need to see a proposal but if `update` or a similar method would work that sounds fine.

2024-09-25 13:35 UTC, CodeLionX commented
> Think adding to the base API should be a separate PR yeah, would need to see a proposal but if `update` or a similar method would work that sounds fine.

Another question is whether we actually want to introduce streaming algorithms in aeon. Are there already other streaming/online estimators? The current architecture is tailored to the batch-case. Maybe this is a topic for the next dev-meeting.

2024-09-25 13:44 UTC, ferewi commented on aeon/anomaly_detection/tests/test_left_stampi.py
> +)
I found a way of mocking the entire stumpy package that works even if the package is not installed

2024-09-25 13:53 UTC, ferewi commented
Then maybe you discuss this in your next dev meeting and if you decide that you want to integrat a streaming api, I am happy to put in a proposal and another PR to implement this for the LeftSTUMPi algorithm.

2024-09-25 14:06 UTC, ferewi commented
> Thanks for the contribution. Feel free to ask if you have any questions regarding the failures, i.e. we have a tag for estimators which can't be pickled (usually due to dependencies outside of our control).

I guess I figured it out. I tagged the class with 'cant-pickle' and the tests are green now.

2024-09-25 17:26 UTC, CodeLionX requested changes
Otherwise, looks good 👍🏼

2024-09-25 17:26 UTC, CodeLionX commented on aeon/anomaly_detection/_left_stampi.py
> +
Please add a call to `_check_soft_dependencies("stumpy", severity="error")` before importing to produce the correct error message when `stumpy` is not available.

2024-09-25 17:37 UTC, ferewi commented on aeon/anomaly_detection/_left_stampi.py
> +
As I understood it, the availability of stumpy is already checked by the parent `BaseSeriesEstimator` constructor by calling `_check_estimator_deps(self)` - the package is specified as python dependency in `tags`.

This was meant to prevent importing the module twice. Happy to remove it though.

2024-09-26 07:24 UTC, CodeLionX commented on aeon/anomaly_detection/_left_stampi.py
> +
Sorry, you are right `BaseSeriesEstimator` does this automatically 👍🏼 

The Python import-system, however, already [caches imported modules (in `sys.modules`)](https://docs.python.org/3/reference/import.html#the-module-cache) and guarantees that every module is imported just once. I should be safe to just import stumpy multiple times.

2024-09-26 08:48 UTC, ferewi commented on aeon/anomaly_detection/_left_stampi.py
> +
Well, that's true. I removed that piece.

2024-09-26 09:34 UTC, CodeLionX approved these changes

2024-09-27 14:02 UTC, ferewi commented
@CodeLionX How is the process after the PR is approved? Do I have to do something or is this simply integrated at some point?

2024-09-27 14:14 UTC, MatthewMiddlehurst commented
Don't have to do anything, can be merged at any point really. Usually give it some time for other comments though. Not really a massive rush until it's close to release time 🙂

2024-09-27 14:15 UTC, CodeLionX commented
We will wait a bit, so that other maintainers / core decs get the chance to object; otherwise, I'll merge it in later.

2024-09-27 14:17 UTC, CodeLionX commented
@ferewi regarding the online-API, we decided in our dev-meeting that aeon will not support this in the near future. If you have a use case for streaming/online anomaly detection, we can, of course, talk about this again.

2024-09-27 17:47 UTC, TonyBagnall commented
Fantastic, thanks for this

2024-09-27 17:47 UTC, merged

2024-09-27 21:43 UTC, ferewi commented
Cool - I was just interested in how the usual process is :) 

Thank you for your help @CodeLionX @MatthewMiddlehurst :)