[ENH] Implemented IsolatedForest in anomaly detection with some test cases
aeon-toolkit/aeon pull request #2118
Opened 2024-09-29 18:59 UTC by notaryanramani

#### Reference Issues/PRs

Fixes 2108

#### What does this implement/fix? Explain your changes.

Implements `PyODAdapter` for `IsolationForest` in `anomaly_detection` along with some test cases.

#### Does your contribution introduce a new dependency? If yes, which one?

No

#### Any other comments?

No.

### PR checklist

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [x] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

##### For new estimators and functions
- [ ] I've added the estimator to the online [API documentation](https://www.aeon-toolkit.org/en/latest/api_reference.html).
- [ ] (OPTIONAL) I've added myself as a `__maintainer__` at the top of relevant files and want to be contacted regarding its maintenance. Unmaintained files may be removed. This is for the full file, and you should not add yourself if you are just making minor changes or do not want to help maintain its contents.

##### For developers with write access
- [ ] (OPTIONAL) I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.

2024-10-07 13:52 UTC, MatthewMiddlehurst requested changes
Few comments. Would be good to hear if you have any additional thoughts @CodeLionX.

2024-10-07 13:52 UTC, MatthewMiddlehurst commented on aeon/anomaly_detection/_iforest.py
> +            Only applicable for sklearn 0.20 above.
dont need these bits, more confusing then useful imo

2024-10-07 13:52 UTC, MatthewMiddlehurst commented on aeon/anomaly_detection/_iforest.py
> +        Stride of the sliding window.
Can you use this style for the above docstrings as well.

2024-10-07 13:52 UTC, MatthewMiddlehurst commented on aeon/anomaly_detection/_iforest.py
> +    using PyODAdadpter to be used in the Aeon framework.
aeon not Aeon

2024-10-07 13:52 UTC, MatthewMiddlehurst commented on aeon/anomaly_detection/_iforest.py
> +    using PyODAdadpter to be used in the Aeon framework.
If the docstrings for parameters are copied from the original, please acknowledge that somewhere here.

Good to mention which parameters are sent directly to the inherited model as well, can just say all parameters buy x, y etc.

2024-10-07 13:52 UTC, MatthewMiddlehurst commented on aeon/anomaly_detection/tests/test_iforest.py
> +    assert params == expected_dict
Don't need this test

2024-10-07 13:52 UTC, MatthewMiddlehurst commented on aeon/anomaly_detection/_iforest.py
> +        }
These should be the parameters used in unit tests i.e. a reduced value for `n_estimators`. no needs to include defaults.

2024-10-07 13:52 UTC, MatthewMiddlehurst commented on aeon/anomaly_detection/_iforest.py
> +            )
There is an option in `severity` to raise an error, use that instead if checking the dependency is necessary here.

2024-10-09 15:07 UTC, CodeLionX requested changes
Thank you for your contributions. I annotated some parts that can be simplified.

2024-10-09 15:07 UTC, CodeLionX commented on aeon/anomaly_detection/_iforest.py
> +
Please add the capabilities table to the documentation, similar to the other anomaly detectors. You can copy it from the `PyODAdapter` because the capabilities are the same.

2024-10-09 15:07 UTC, CodeLionX commented on aeon/anomaly_detection/_iforest.py
> +        _check_soft_dependencies("pyod")
Please consider using the class-tags instead of this check:

```python
    _tags = {
        "capability:multivariate": True,
        "capability:univariate": True,
        "capability:missing_values": False,
        "fit_is_empty": False,
        "python_dependencies": ["pyod"],
    }
```

2024-10-09 15:07 UTC, CodeLionX commented on aeon/anomaly_detection/_iforest.py
> +        return super()._fit_predict(X, y)
These overrides are not necessary. IMHO, we can remove them.

2024-10-09 15:07 UTC, CodeLionX commented on aeon/anomaly_detection/_iforest.py
> +        }
```suggestion
        return {
            "n_estimators": 10,
        }
```

2024-10-09 15:07 UTC, CodeLionX commented on aeon/anomaly_detection/tests/test_iforest.py
> +    iforest = IsolationForest(window_size=10, stride=1)
Please set `random_state` in all tests to avoid spurious test failures.

2024-10-09 15:07 UTC, CodeLionX commented on aeon/anomaly_detection/tests/test_iforest.py
> +    assert hasattr(iforest, "pyod_model")
This check is not necessary; also in the following tests.
```suggestion
```

2024-10-09 20:52 UTC, notaryanramani commented on aeon/anomaly_detection/_iforest.py
> +        return super()._fit_predict(X, y)
I think `_predict` override is necessary because without it, a test in `aeon/testing/estimator_checking/_yield_anomaly_detection_checks.py` fails with the following error:

```bash
        # Test that all anomaly detectors implement abstract predict.
>       assert "_predict" in estimator_class.__dict__
E       AssertionError
```

Or is there another way to implement abstract predict?

2024-10-10 07:25 UTC, CodeLionX commented on aeon/anomaly_detection/_iforest.py
> +        return super()._fit_predict(X, y)
Hm, I did not know that we test that 🤔 let me discuss this with the other core devs.

2024-10-11 07:27 UTC, CodeLionX commented on aeon/anomaly_detection/_iforest.py
> +        return super()._fit_predict(X, y)
Ok, so we decided to adjust the tests soon. For now, you can keep the current overwrites, and we will remove them once the tests are changed as well.

2024-10-11 16:59 UTC, CodeLionX commented
@notaryanramani please do not use force-pushes in the future. This breaks GitHub's differential reviewing feature.

2024-10-11 17:04 UTC, CodeLionX requested changes
- Please add the estimator to our API reference in `docs/api_reference/anomaly_detection.rst` (alphabetically sorted).
- We might not need all the tests with different windows because we already test this in the `PyODAdapter` tests. (no change needed)

Otherwise, this looks good, thank you! 👍🏼

2024-10-12 11:22 UTC, CodeLionX approved these changes

2024-10-14 15:16 UTC, MatthewMiddlehurst approved these changes

2024-10-14 21:20 UTC, TonyBagnall commented
thanks for this

2024-10-14 21:20 UTC, merged

2024-10-15 20:17 UTC, notaryanramani commented
@all-contributors add @notaryanramani for enhancement

2024-10-15 20:19 UTC, notaryanramani commented
@all-contributors add @notaryanramani for code