[ENH] Add Yeo Johnson Transform
aeon-toolkit/aeon pull request #2164
Opened 2024-10-08 12:45 UTC by alexbanwell1

#### Reference Issues/PRs

Fixes #1475

#### What does this implement/fix? Explain your changes.

I have added the basic YeoJohnson Transform to the series transform section. This uses the scipy implementation to compute the transform, but implements the aeon interface on top of this.

#### Does your contribution introduce a new dependency? If yes, which one?

No new dependencies

#### Any other comments?

N/A

### PR checklist

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [ ] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

##### For new estimators and functions
- [ ] I've added the estimator to the online [API documentation](https://www.aeon-toolkit.org/en/latest/api_reference.html).
- [ ] (OPTIONAL) I've added myself as a `__maintainer__` at the top of relevant files and want to be contacted regarding its maintenance. Unmaintained files may be removed. This is for the full file, and you should not add yourself if you are just making minor changes or do not want to help maintain its contents.

2024-10-08 12:48 UTC, alexbanwell1 commented
@all-contributors please add @alexbanwell1 for code, design and documentation

2024-10-08 12:57 UTC, TonyBagnall requested changes
thanks for this, but given its so simple it might be nice to have our own implementation, then test it is same as scipy? That way its easy to make multivariate, just do each channel separately.

2024-10-08 13:42 UTC, TonyBagnall commented on aeon/transformations/series/_yeojohnson.py
> +    def _fit(self, X, y=None):
actually ignore that

2024-10-08 14:22 UTC, alexbanwell1 commented on aeon/transformations/series/tests/test_yeojohnson.py
> +__maintainer__ = [Alex Banwell]
Done

2024-10-08 15:49 UTC, TonyBagnall commented
ah failed pre-commit, I got the tag name wrong :) Good to install pre-commit locally though

https://www.aeon-toolkit.org/en/stable/developer_guide/dev_installation.html

pip install --editable .[dev]

you should not actually need these capability tags, as they are the same as in BaseSeriesEstimator

2024-10-09 00:33 UTC, alexbanwell1 commented
I have implemented the YeoJohnson Transform natively in the code, and tested it against the scipy implementation as requested!

2024-10-09 07:00 UTC, TonyBagnall requested changes
good stuff, very minor changes now

2024-10-11 12:30 UTC, alexbanwell1 commented on aeon/transformations/series/_yeojohnson.py
> +    ----------
Changed lambda_ to lmbda

2024-10-11 12:30 UTC, alexbanwell1 commented on aeon/transformations/series/_yeojohnson.py
> +            self.lambda_ = yeojohnson_normmax(X, brack=self.bounds)
Done!

2024-10-11 12:30 UTC, alexbanwell1 commented on aeon/transformations/series/_yeojohnson.py
> +def _yeo_johnson_transform(X, lambda_):
Done! Parameter is now called lmbda

2024-10-12 13:55 UTC, TonyBagnall approved these changes
good job, thanks

2024-10-12 13:56 UTC, merged

2024-10-12 17:29 UTC, TonyBagnall commented
@all-contributors add @alexbanwell1 as a contributor for code, design, doc.