[ENH] More base class method removals
aeon-toolkit/aeon pull request #2171
Opened 2024-10-09 22:08 UTC by MatthewMiddlehurst

- make `check_is_fitted()` private
- remove `save()` and both loading methods
- rework `get_fitted_params` to behave more like `get_params`, removes unused functions as a result

2024-10-10 07:48 UTC, CodeLionX requested changes

2024-10-14 19:42 UTC, MatthewMiddlehurst commented on aeon/base/_base.py
> +        fitted_params = [x for x in fitted_params if hasattr(est, x)]
Thought it was a bit odd, left over from the previous version but did not check if it actually did anything. Your suggestion is much cleaner.

2024-10-14 19:44 UTC, MatthewMiddlehurst commented on aeon/base/_meta.py
> +        return fitted_param_dict
Honestly, this is a hack to avoid errors. This class is next on the block for changes and was going to deal with it then. Should have made the clearer but forgot really. Don't mind making it right in this PR if you want.

2024-10-14 19:47 UTC, MatthewMiddlehurst commented on aeon/base/tests/test_base.py
> +    assert set(non_comp_f_params.keys()) == {"foo_"}
Thought about this and can go either way, really. On one hand,  "foo___foo_" is dumb, on the other, "foo" does not exist as an attribute (or worse, does exist as a parameter and is different to the fitted param).

2024-10-14 19:48 UTC, MatthewMiddlehurst commented
Thanks for the comments. May ask in the developer channel re: `foo` v `foo_`.

2024-10-15 06:42 UTC, CodeLionX commented on aeon/base/tests/test_base.py
> +    assert set(non_comp_f_params.keys()) == {"foo_"}
Hm, good point. I am also not sure about this.

2024-10-15 06:43 UTC, CodeLionX commented on aeon/base/_meta.py
> +        return fitted_param_dict
I'm a fan of small consecutive PRs 😉 So, unless you forget it, change it in a new PR.

2024-10-15 07:15 UTC, CodeLionX reviewed
Metaclasses are inherited from base classes. This means that we do not need to specify them for all our sub-base classes, such as `BaseAnomalyDetector`, `BaseClusterer`, …).

This is a comprehensive guide to Python metaclasses: https://stackoverflow.com/a/6581949

2024-10-15 07:15 UTC, CodeLionX commented on aeon/anomaly_detection/base.py
> +class BaseAnomalyDetector(BaseSeriesEstimator, metaclass=ABCMeta):
All of those are redundant. The `__metaclass__` is inherited from the base class (`BaseSeriesEstimator` --> `BaseAeonEstimator` in this case)

2024-10-15 07:15 UTC, CodeLionX commented on aeon/base/_base.py
> +class BaseAeonEstimator(BaseEstimator, metaclass=ABCMeta):
This is the only part, where I would keep the `, metaclass=ABCMeta` to avoid relying to heavily on `sklearn`. We make sure that all our base classes have the metaclass `ABCMeta` independent of the changes in sklearn.

2024-10-15 07:15 UTC, CodeLionX commented on aeon/base/_meta.py
> +class _HeterogenousMetaEstimator(metaclass=ABCMeta):
It is recommended to use `_HeterogenousMetaEstimator(ABC)` instead of specifying the metaclass directly because this is easier to read and does the same.

However, I don't find any abstract methods in this class, so there is no need for `ABC`. To me, this looks more like a [Mixin](https://en.wikipedia.org/wiki/Mixin).

2024-10-15 07:15 UTC, CodeLionX commented on aeon/networks/base.py
> +class BaseDeepLearningNetwork(metaclass=ABCMeta):
The original usage of `ABC` is more idiomatic.

2024-10-15 07:42 UTC, TonyBagnall commented on aeon/base/_meta.py
> +        return fitted_param_dict
my preference would be to make an issue for meta and sort it in another PR

2024-10-15 10:25 UTC, MatthewMiddlehurst commented on aeon/base/_meta.py
> +class _HeterogenousMetaEstimator(metaclass=ABCMeta):
The `__init__` should be abstract IMO but not gonna do that here (same with other base classes).

2024-10-17 07:46 UTC, CodeLionX approved these changes

2024-10-18 15:34 UTC, MatthewMiddlehurst commented
The changed way makes more sense for me. Pretty obvious the `get_params` way of displaying attributes was not means for fitted attributes, but if we are keeping the method this is better than the alternative IMO.

2024-10-19 10:58 UTC, CodeLionX approved these changes

2024-10-19 13:58 UTC, merged