[ENH] Implemented COPOD for anomaly detection
aeon-toolkit/aeon pull request #2202
Opened 2024-10-14 19:15 UTC by notaryanramani

#### Reference Issues/PRs

Fixes #2111 

#### What does this implement/fix? Explain your changes.

Implements COPOD from PyOD to be used in aeon framework along with some test cases.

#### Does your contribution introduce a new dependency? If yes, which one?

No

#### Any other comments?

### PR checklist

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [x] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

##### For new estimators and functions
- [ ] I've added the estimator to the online [API documentation](https://www.aeon-toolkit.org/en/latest/api_reference.html).
- [ ] (OPTIONAL) I've added myself as a `__maintainer__` at the top of relevant files and want to be contacted regarding its maintenance. Unmaintained files may be removed. This is for the full file, and you should not add yourself if you are just making minor changes or do not want to help maintain its contents.

##### For developers with write access
- [ ] (OPTIONAL) I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.

2024-10-15 14:17 UTC, CodeLionX requested changes
Well done. Thank you again!
I still think that the tests are excessive because we already test all cases with the `PyODAdapter`. Could you boil it down to a couple of tests specific for the `COPOD`-estimator? In addition, the current tests still refer to `iforest` 😉

2024-10-15 14:17 UTC, CodeLionX commented on aeon/anomaly_detection/_copod.py
> +        _check_soft_dependencies(*self._tags["python_dependencies"])
Not necessary as long as the `"python_dependencies"`-tag is set correctly. The base class checks for the soft dependency, then.

2024-10-15 14:17 UTC, CodeLionX commented on aeon/anomaly_detection/_copod.py
> +    n_jobs : int, default=-1
```suggestion
    n_jobs : int, default=1
```

2024-10-15 14:17 UTC, CodeLionX commented on aeon/anomaly_detection/_copod.py
> +    def __init__(self, n_jobs: int = -1, window_size: int = 10, stride: int = 1):
Please use 1 as the default for `n_jobs`. All other estimators use this default.

2024-10-15 14:17 UTC, CodeLionX commented on aeon/anomaly_detection/_copod.py
> +        return {}
Is inherited from the base class with `{}`, so can be omitted.

2024-10-15 15:31 UTC, notaryanramani commented on aeon/anomaly_detection/_copod.py
> +        _check_soft_dependencies(*self._tags["python_dependencies"])
When I tried not using this function last time in `IsolationForest`, one of the test cases was failing. That's why it is also included there.

2024-10-15 15:37 UTC, notaryanramani commented
@CodeLionX I am not familiar with COPOD algorithm. Could you please give an idea what kind of tests are required?

2024-10-15 15:44 UTC, notaryanramani commented on aeon/anomaly_detection/_copod.py
> +        return {}
I think the `PyODAdapater`'s `get_test_params` returns the following dictionary:

```python
return {"pyod_model": LOF(), "window_size": 5, "stride": 1}
```

2024-10-15 18:08 UTC, CodeLionX commented on aeon/anomaly_detection/_copod.py
> +        return {}
Ah, you are right. I forgot. Sry, then disregard this comment!

2024-10-15 18:11 UTC, CodeLionX commented on aeon/anomaly_detection/_copod.py
> +        _check_soft_dependencies(*self._tags["python_dependencies"])
Strange... there should not be any input parameter checking in the constructor (`__init__`) according to the sklearn-conventions. This is instead done in `fit` (in our case `_fit`). I would consider checking soft-dependencies follows similar principles. Thus, I cannot understand why this is necessary 🤔

2024-10-15 20:02 UTC, notaryanramani commented on aeon/anomaly_detection/_copod.py
> +        _check_soft_dependencies(*self._tags["python_dependencies"])
I don't think COPOD from pyod here is an input parameter, I am importing it in the constructor itself to pass it to the base class. 

I tried not using `_check_soft_dependencies`. I got the following test case fail message:
```bash
E           AssertionError: Estimator COPOD requires soft dependencies ['pyod'] according to tags, 
but does not raise an appropriate error message on __init__, when a soft dependency is missing. 
Likely reason is that __init__ does not call super(cls).__init__, or imports super(cls).__init__ 
only after an attempted import.
```

2024-10-16 13:51 UTC, CodeLionX commented on aeon/anomaly_detection/_copod.py
> +        _check_soft_dependencies(*self._tags["python_dependencies"])
Yes, that makes sense to me now! I apologize for the confusion on my side. Your approach is correct!

2024-10-16 13:54 UTC, CodeLionX commented
> @CodeLionX I am not familiar with COPOD algorithm. Could you please give an idea what kind of tests are required?

I trust that the implementation in PyOD is correct. So, our tests would check that we integrate it in aeon correctly:

- instantiating the class should work (when pyod is installed): you can just keep one of the end-to-end tests
- the parameters of the algorithm should be correctly passed down to the PyOD model
- aeon with `window_size=1` and `stride=1` should produce the same results as calling the PyOD model directly, when I am not mistaken

2024-10-16 17:10 UTC, notaryanramani commented
Umm... sorry I was trying to rebase the branch and something wild happened 😅. Should I close this PR and open a new one?

2024-10-17 12:49 UTC, CodeLionX requested changes
Looks good. Just some minor changes so that we don't need to clean it up later 👍🏼

2024-10-17 12:49 UTC, CodeLionX commented on aeon/anomaly_detection/__init__.py
> +    "COPOD",
Duplicated entry

2024-10-17 12:49 UTC, CodeLionX commented on aeon/anomaly_detection/tests/test_copod.py
> +    _series, _ = sliding_windows(series, window_size=1, stride=1, axis=0)
```suggestion
    _series = series.reshape(-1, 1)
```

2024-10-17 12:49 UTC, CodeLionX commented on aeon/anomaly_detection/tests/test_copod.py
> +    series = make_series(n_timepoints=100, return_numpy=True, random_state=0)
Please use [`aeon.testing.data_generation.make_example_1d_numpy`](https://github.com/aeon-toolkit/aeon/blob/main/aeon/testing/data_generation/_series.py#L17) instead of the legacy method.

2024-10-18 07:58 UTC, CodeLionX approved these changes

2024-10-24 10:53 UTC, TonyBagnall commented
great, thanks for this

2024-10-24 10:54 UTC, merged