[ENH] Implementation of LOF using PyODAdapter
aeon-toolkit/aeon pull request #2209
Opened 2024-10-16 08:43 UTC by aryanpola

#### Reference Issues/PRs
Fixes #2109 

#### What does this implement/fix? Explain your changes.

Implemented Local Outlier Factor using PyODadapter

### PR checklist

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [ ] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

2024-10-22 05:47 UTC, aryanpola commented
@CodeLionX some tests ran with no `window_size` parameter causing errors, would it be a good idea to set the default window size if not provided, to be the same as that of stride?

2024-10-23 08:43 UTC, CodeLionX requested changes
Thanks for your contribution! The `window_size` and `stride` parameters should have a proper default that should get picked up during the tests. I cannot explain why this is not happening in your tests.

This already looks good. However, LOF is special because of its different calling conventions for unsupervised (outlier detection) and semi-supervised (novelty detection) problems. Please refer to my comment below on how to best integrate this into our API.

The tests in their current version are not very helpful. They mostly test the functionality of the `PyODAdapter`. Similar to the tests in COPOD (https://github.com/aeon-toolkit/aeon/pull/2202#issuecomment-2416920728), I would like to test that the integration into aeon works as expected. We should also test that the `metric`-parameter works for our distance implementations and that the different calling conventions (unsupervised and semi-supervised) work correctly.

2024-10-23 08:43 UTC, CodeLionX commented on aeon/anomaly_detection/_lof.py
> +    """Local Outlier Factor (LOF) algorithm anomaly detection.
```suggestion
    """Local Outlier Factor (LOF) algorithm for anomaly detection.
```

2024-10-23 08:43 UTC, CodeLionX commented on aeon/anomaly_detection/_lof.py
> +        threshold on the decision function.
This parameter is just used to compute a threshold to predict the labels. We do not use this and return the anomaly scores. It can be safely removed (use the PyOD default).

2024-10-23 08:43 UTC, CodeLionX commented on aeon/anomaly_detection/_lof.py
> +
Please add the capability tables (see other anomaly detectors as an example)

2024-10-23 08:43 UTC, CodeLionX commented on aeon/anomaly_detection/_lof.py
> +        on new unseen data and not on the training set.
This is important for the correct usage of the detector. However, I would not expose this parameter to the user and handle it internally according to our usage styles:

We want to support both learning types: semi-supervised and unsupervised. We can distinguish between those because different functions are called:

- Unsupervised

  ```python
  lof = LOF()
  scores = lof.fit_predict(X)
  ```
  
  In this case, we need to set `novelty=False` in the internal model.

- Semi-supervised

  ```python
  lof = LOF()
  lof.fit(X_train)
  scores = lof.predict(X_test)
  ```
  
  In this case, we need to set `novelty=True` in the internal model.

Please override the `novelty`-parameter in the corresponding functions before using the internal model, and remove the parameter from the init.
Example for `_fit_predict()`:

```python
def _fit_predict(self, X: np.ndarray, y: np.ndarray | None = None) -> np.ndarray:
    self.pyod_model.novelty = False
    super()._fit_predict(X, y)
```

2024-10-23 08:43 UTC, CodeLionX commented on aeon/anomaly_detection/_lof.py
> +            )
Parameter checking should not be implemented in the `__init__` method according to sklearn-conventions. In addition, the base class already provides this for you:

https://github.com/aeon-toolkit/aeon/blob/baed5324ed447ac69f6b2f4b5acf62882b99d3fb/aeon/anomaly_detection/_pyodadapter.py#L134-L147

This is automatically called if you forward the function calls correctly using `super()`.

2024-10-23 08:43 UTC, CodeLionX commented on aeon/anomaly_detection/_lof.py
> +        return super()._fit_predict(X, y)
Do not override `fit`, `predict`, and `fit_predict`! They contain important input validation and transformation logic from the base classes. They are also declared final; it is unclear to me how Python allows overwriting them 🤷🏼 

Please just override the internal methods `_fit`, `_predict`, and `_fit_predict`

2024-10-23 08:43 UTC, CodeLionX commented on aeon/anomaly_detection/_lof.py
> +            )
Please remove. The `PyODAdapter` already contains this method, but has more checks.

2024-10-23 08:43 UTC, CodeLionX commented on aeon/anomaly_detection/_lof.py
> +        matrix.
We do not support `precomputed` within aeon.

2024-10-24 05:50 UTC, aryanpola commented
@CodeLionX The output values from aeon_lof and pyod_lof don't match. I've tried normalizing the series but the error persists.
```
FAILED aeon/anomaly_detection/tests/test_lof.py::test_lof_compare_with_pyod_direct - AssertionError: 
Not equal to tolerance rtol=1e-05, atol=0

Mismatched elements: 80 / 80 (100%)
Max absolute difference: 0.11725756
Max relative difference: 0.06374909
 x: array([1.516172, 1.018181, 1.222005, 1.838367, 1.574194, 1.062766,
       1.206536, 0.994702, 0.994427, 1.020478, 0.952964, 1.365051,
       1.122292, 0.956126, 1.028726, 1.004674, 1.378998, 0.982227,...
 y: array([1.433783, 1.000109, 1.184898, 1.728743, 1.486901, 1.06169 ,
       1.170488, 0.986849, 0.976589, 1.001037, 0.951811, 1.295437,
       1.097627, 0.952606, 1.020956, 1.000109, 1.308204, 0.981894,...
```

2024-10-24 12:59 UTC, CodeLionX requested changes

2024-10-24 12:59 UTC, CodeLionX commented on aeon/anomaly_detection/tests/test_lof.py
> +from aeon.testing.data_generation._legacy import make_series
Please consider using `from aeon.testing.data_generation import make_example_1d_numpy` instead of the legacy testing methods

2024-10-24 12:59 UTC, CodeLionX commented on aeon/anomaly_detection/tests/test_lof.py
> +    np.testing.assert_allclose(pred_aeon, pred_pyod, rtol=1e-5)
This mixes calling conventions:

- you use `fit_predict` for aeon's `LOF` = unsupervised
- however, calling `fit` and `decision_function` corresponds to semi-supervised usage

Please have two separate tests. If the results still do not match, we need to take a deeper look.

2024-10-24 12:59 UTC, CodeLionX commented on aeon/anomaly_detection/_lof.py
> +    ----------
Please add the following statement:

```
    The documentation for parameters has been adapted from the
    [PyOD documentation](https://pyod.readthedocs.io/en/latest/pyod.models.html#id117).
    Here, `X` refers to the set of sliding windows extracted from the time series
    using :func:`aeon.utils.windowing.sliding_windows` with the parameters
    ``window_size`` and ``stride``. The internal `X` has the shape
    `(n_windows, window_size * n_channels)`.
```

2024-10-24 12:59 UTC, CodeLionX commented on aeon/anomaly_detection/_lof.py
> +         - binary classification
Is that true? It should return anomaly scores, right?

2024-10-24 12:59 UTC, CodeLionX commented on aeon/anomaly_detection/_lof.py
> +        model = pyod_model or LOF(
Where should the `pyod_model` come from? It is not defined in this scope, so please remove.

2024-10-24 12:59 UTC, CodeLionX commented on aeon/anomaly_detection/_lof.py
> +        self.stride = stride
Not necessary
```suggestion
```

2024-10-24 12:59 UTC, CodeLionX commented on aeon/anomaly_detection/_lof.py
> +        return self
The super classes take care of this; remove.
```suggestion
```

2024-10-24 12:59 UTC, CodeLionX commented on aeon/anomaly_detection/_lof.py
> +            )
This should also be handled by the `BaseAnomalyDetector`-class.
```suggestion
```

2024-10-24 12:59 UTC, CodeLionX commented on aeon/anomaly_detection/_lof.py
> +        self.pyod_model.novelty = True
Has no effect because the `PyODAdapter` uses a copy (`fitted_pyod_model_`) internally. Is not necessary either because **`_fit`** and `_fit_predict` set it already.
```suggestion
```

2024-10-26 19:20 UTC, aryanpola commented on aeon/anomaly_detection/_lof.py
> +         - binary classification
I think it's binary when the novelty=false (unsupervised) and returns anomaly scores when novelty=true (semi-supervised).

2024-10-27 14:38 UTC, CodeLionX commented on aeon/anomaly_detection/_lof.py
> +         - binary classification
Nope, both cases return anomaly scores:

```python
>>> import numpy as np
>>> from pyod.models.lof import LOF
>>> X_train = np.random.random((20, 10))
>>> X_test = np.random.random((5, 10))
>>> unsupervised_lof = LOF(novelty=False).fit(X_train)
>>> unsupervised_lof.decision_scores_
array([1.00537546, 0.99799013, 0.99987937, 0.98546212, 1.00148011,
       1.01117638, 0.98546212, 1.00241542, 0.99992492, 0.99799013,
       0.99809342, 1.00128371, 0.99665617, 0.99972901, 0.99762421,
       1.00798589, 1.00472376, 1.0027196 , 1.00820678, 0.99657257])
>>> semi_supervised_lof = LOF(novelty=True).fit(X_train)
>>> semi_supervised_lof.decision_function(X_test)
array([0.98546212, 0.99972901, 1.00128371, 0.98546212, 0.98546212])
```

2024-11-04 08:56 UTC, aryanpola commented
@CodeLionX Hey! I am unable to resolve these conflicts. I have tried everything, but I am stuck. Please tell me how to proceed from here.

2024-11-05 08:12 UTC, CodeLionX requested changes

2024-11-05 08:12 UTC, CodeLionX commented on aeon/anomaly_detection/tests/test_lof.py
> +    scores_aeon = lof_aeon._fit_predict(series)
Always use the original methods!
```suggestion
    scores_aeon = lof_aeon.fit_predict(series)
```

2024-11-05 08:12 UTC, CodeLionX commented on aeon/anomaly_detection/tests/test_lof.py
> +    scores_aeon = lof_aeon._fit_predict(series)
```suggestion
    scores_aeon = lof_aeon.fit_predict(series)
```

2024-11-05 08:12 UTC, CodeLionX commented on aeon/anomaly_detection/tests/test_lof.py
> +    ), "PyOD LOF did not detect anomalies in the expected range."
Not necessary, please remove.

2024-11-05 08:12 UTC, CodeLionX commented on aeon/anomaly_detection/tests/test_lof.py
> +    scores_aeon = lof_aeon._predict(series_test)  # changed from decsion_function
```suggestion
    scores_aeon = lof_aeon.predict(series_test)  # changed from decsion_function
```

2024-11-05 08:12 UTC, CodeLionX commented on aeon/anomaly_detection/tests/test_lof.py
> +    ), "PyOD LOF did not detect anomalies in the expected range."
Not necessary, please remove

2024-11-05 08:12 UTC, CodeLionX commented on aeon/anomaly_detection/tests/test_lof.py
> +def test_lof_default():
This test looks very similar to `test_lof_unsupervised`, which already tests that our LOF has the same results as PyOD's LOF.

Please use this test to check that our LOF produces the correct output (detects the anomaly): You can remove PyOD's LOF and the comparison of the two.

2024-11-05 08:28 UTC, CodeLionX commented on aeon/anomaly_detection/_lof.py
> +    def get_test_params(cls, parameter_set="default"):
This is responsible for the test failures:

```suggestion
    @classmethod
    def _get_test_params(cls, parameter_set="default"):
```

2024-11-06 13:23 UTC, CodeLionX approved these changes

2024-11-22 16:29 UTC, MatthewMiddlehurst commented
Seems to be a conflict here. Not sure if the unresolved conflict needs any action or not.

2024-11-22 17:08 UTC, SebastianSchmidl commented
> Seems to be a conflict here. Not sure if the unresolved conflict needs any action or not.

Fixed.

Were just some duplicated entries in `__all__`, still ready to merge from my side.

2024-11-22 17:09 UTC, SebastianSchmidl approved these changes

2024-11-24 12:13 UTC, merged