Ajb/numpy2
aeon-toolkit/aeon pull request #2216
Opened 2024-10-16 16:40 UTC by TonyBagnall

#### Reference Issues/PRs

test numpy2 compliance over simple fixes

2024-10-16 22:14 UTC, TonyBagnall commented
ok so isolated another weird difference arising in the test function `test_stomp_squared_matrix_profile`

this code
```python
import numpy as np
expected = np.array([[18.00000,9.00000,6.00000,9.00000,18.00000,33.00000],
[19.00000,6.00000,5.00000,9.00000,6.00000,5.00000]])
id_bests = np.vstack(
    np.unravel_index(np.argsort(expected.ravel()), expected.shape)
).T

print(id_bests)
```
produces different output under numpy 1.26 and numpy 2.0. I assume due to tie breaking
1.26 output
[[1 2]
 [1 5]
 [0 2]
 [1 1]
 [1 4]
 [0 1]
 [0 3]
 [1 3]
 [0 0]
 [0 4]
 [1 0]
 [0 5]]

2.0 output
[[1 5]
 [1 2]
 [0 2]
 [1 1]
 [1 4]
 [1 3]
 [0 3]
 [0 1]
 [0 4]
 [0 0]
 [1 0]
 [0 5]]

2024-10-16 22:15 UTC, TonyBagnall commented
(reminds me of the shapelet argsort issue under numba/no numba

2024-10-16 22:28 UTC, TonyBagnall commented
simplified further 

```python
expected = np.array([[18.00000,9.00000,6.00000,9.00000,18.00000,33.00000],
[19.00000,6.00000,5.00000,9.00000,6.00000,5.00000]])
x= [18.00000,9.00000,6.00000,9.00000,18.00000,33.00000,19.00000,6.00000,5.00000,
    9.00000,6.00000,5.00000]
args = np.argsort(x)
```
gives different results in args under differnt numpy versions (and previously with and without numba #622). This is a very minor issue in one test, but we do use argsort quite a lot, might be time to implement our own version ...

![image](https://github.com/user-attachments/assets/1e009616-8860-4670-95a9-428e58c6dfea)

2024-10-16 22:40 UTC, TonyBagnall commented
ah they have added a "stable" argument! Problem solved :)
https://numpy.org/doc/2.0/reference/generated/numpy.argsort.html

2024-10-17 08:04 UTC, TonyBagnall commented
still some weirdness, but tbh there is little to gain from further drilling down. Simplified the test, set kind="stable" and it passes with and without numpy3

2024-10-17 11:02 UTC, MatthewMiddlehurst submitted a review, later dismissed
Cant say I'm a fan of just removing all the expected outputs

2024-10-17 11:02 UTC, MatthewMiddlehurst commented on aeon/transformations/collection/feature_based/_catch22.py
> +        c22_array = np.array(c22_list)
```suggestion
        
        c22_array = np.array(c22_list)
```

2024-10-17 11:06 UTC, TonyBagnall commented
> Cant say I'm a fan of just removing all the expected outputs

if you dont you cannot be backward compatible as far as I can tell

2024-10-17 11:07 UTC, TonyBagnall commented on aeon/similarity_search/matrix_profiles/tests/test_stomp.py
> +K_VALUES = [1]
because there are further issues with k == 3 I am not willing to spend further time debugging, comment can go though

2024-10-17 11:12 UTC, TonyBagnall commented on aeon/similarity_search/matrix_profiles/tests/test_stomp.py
> +K_VALUES = [1]
@baraline this is your test, want to take a look?

2024-10-17 12:42 UTC, CodeLionX commented
The removed outputs are mostly in the performance metrics module. IMO, it has lower priority, so I don't care as much.

The problem is that the examples are checked using a string-comparison, right? Because `np.float64(3.2) == 3.2` should return `True`.

2024-10-17 12:58 UTC, TonyBagnall commented
> The removed outputs are mostly in the performance metrics module. IMO, it has lower priority, so I don't care as much.
> 
> The problem is that the examples are checked using a string-comparison, right? Because `np.float64(3.2) == 3.2` should return `True`.

agree, I think we skip ones we care about and just dont print of the performance metric module. I dont know how docstring runs the comparison, not really motivated to find out

2024-10-17 21:09 UTC, MatthewMiddlehurst commented on aeon/similarity_search/matrix_profiles/tests/test_stomp.py
> +K_VALUES = [1]
still seems to be an issue

2024-10-18 08:01 UTC, CodeLionX requested changes

2024-10-18 08:01 UTC, CodeLionX commented on aeon/similarity_search/matrix_profiles/tests/test_stomp.py
> +K_VALUES = [1]
I agree with @MatthewMiddlehurst that this should be resolved.

2024-10-18 09:02 UTC, TonyBagnall commented on aeon/similarity_search/matrix_profiles/tests/test_stomp.py
> +K_VALUES = [1]
its an issue with the test and argmin, I dont think it should hold up this PR

2024-10-18 20:48 UTC, TonyBagnall commented on aeon/similarity_search/matrix_profiles/tests/test_stomp.py
> +K_VALUES = [1]
its a thankless debugging task for no reward @CodeLionX, hopefully one of you will take it on ...

2024-10-19 11:01 UTC, CodeLionX commented on aeon/similarity_search/matrix_profiles/tests/test_stomp.py
> +K_VALUES = [1]
Got no time for that 🤷🏼 
At least create an issue for this, then

2024-10-21 15:56 UTC, TonyBagnall commented on aeon/similarity_search/matrix_profiles/tests/test_stomp.py
> +K_VALUES = [1]
see #2236

2024-10-21 16:12 UTC, CodeLionX approved these changes

2024-10-21 16:23 UTC, MatthewMiddlehurst approved these changes

2024-10-21 19:44 UTC, merged