[DOC] Rework getting started guide
aeon-toolkit/aeon pull request #2248
Opened 2024-10-25 08:31 UTC by TonyBagnall

fixes #2246 input very welcome, just started though

2024-10-29 18:37 UTC, CodeLionX commented on docs/getting_started.md
> +series (they inherit from the class `BaseSeriesEstimator`). Collections of
BaseCollectionEstimator?

2024-10-29 20:02 UTC, chrisholder commented on docs/getting_started.md
> +- anomaly detection where the goal is to find values or areas of a
For consistency should capitalise Anomaly Detection and Forecasting. Also add more details or "More details coming soon" like for forecasting

2024-10-29 20:03 UTC, chrisholder commented on docs/getting_started.md
> +`aeon` also provides core modules that are used by the specific task modules
I don't think this reads very well? Specifically "used by the specific task modules above" maybe should just be "used by the modules above"

2024-10-29 20:03 UTC, chrisholder commented on docs/getting_started.md
> +- networks, provides core models for deep learning for all time series tasks.
Networks should be capitalised for consistency. Also may want to add "More details coming soon."

2024-10-29 20:06 UTC, chrisholder commented on docs/getting_started.md
> +by default in a numpy array (algorithms use arrays internally whenever possible).
Should be "(algorithms use numpy arrays internally whenever possible)"

2024-10-29 20:08 UTC, chrisholder commented on docs/getting_started.md
> +first two series
?

2024-10-29 20:08 UTC, chrisholder commented on docs/getting_started.md
> +written the notebook.
I assume examples for these will come later

2024-10-29 20:11 UTC, chrisholder commented on docs/getting_started.md
> +new data. See our clustering notebook for [more details](examples/clustering/clustering.ipynb)
Maybe my branch im viewing on the docs is broken - for me on https://aeon-toolkit--2248.org.readthedocs.build/en/2248/getting_started.html this doesnt link to the notebooks. Maybe wrong.

2024-10-29 20:12 UTC, chrisholder commented on docs/getting_started.md
> +longer than the query. [more details](examples/similarity_search/similarity_search.ipynb)
The more details after the full stop without a capital or ending full stop

2024-10-29 20:12 UTC, chrisholder commented on docs/getting_started.md
> +time series into a different time series or a feature vector.
More info link could be nice here

2024-10-30 08:30 UTC, TonyBagnall commented on docs/getting_started.md
> +written the notebook.
yeah I've not go an easy example, will look in the presentation

2024-10-30 08:37 UTC, TonyBagnall commented on docs/getting_started.md
> +written the notebook.
found one

2024-10-30 08:38 UTC, TonyBagnall commented on docs/getting_started.md
> +time series into a different time series or a feature vector.
need to write those notebooks :)

2024-10-30 10:31 UTC, TonyBagnall commented on docs/getting_started.md
> +new data. See our clustering notebook for [more details](examples/clustering/clustering.ipynb)
think ti was maybe not built, links ok for me

2024-10-30 10:31 UTC, TonyBagnall commented on docs/getting_started.md
> +first two series
fixed

2024-10-30 12:08 UTC, MatthewMiddlehurst reviewed
Some incomplete bits in the guide but its not really intended to be complete so will leave it. I can't really review the single loaders easily as I can't tell what has changed due to the reordering so I haven't yet.

> There are two multivariate loaders, uschange and longley. These adopted a structure like this firstly returning y, X is opposite to collections, and secondly there seems no need to split the data in the loader, the user can surely do that themselves.

Forecasting has a different format for its inputs so its not odd for its loaders to be different as well IMO.  Is there a specific column/series you want to forecast for these problems or can you use any of them really. Seems similar to labels being stored as a column of a 2d collection if there is a specific target series.

Not saying the change is bad or wrong, just trying to get a better idea.

> returns numpy array with axis == 0, i.e. n_channels, n_timepoints and returns a data frame with axis == 1 and all the column names set as before.

This seems pretty confusing to swap dimensions with the parameter as well as datatype? I thought we were defaulting to `n_channels, n_timepoints` now.

2024-10-30 12:08 UTC, MatthewMiddlehurst commented on docs/getting_started.md
> +```
This is the clustering example.

There was a section and example on similarity search previously

2024-10-30 12:08 UTC, MatthewMiddlehurst commented on docs/getting_started.md
> +(n_cases, n_channels, n_timepoints)` even if each time series is univariate (i.e.
(n_cases, n_channels, n_timepoints) is repeated here

2024-10-30 12:08 UTC, MatthewMiddlehurst commented on docs/getting_started.md
> +Collection estimators closely follow the `scikit-learn` estimator interface, using
Bit of an inconsistency here where theres no separate section for estimators while there is for series

2024-10-30 12:08 UTC, MatthewMiddlehurst commented on docs/getting_started.md
> +TSR is a term commonly used in forecasting when used in conjunction with a sliding
Would introduce the acronym above or not use it. It's a getting started guide so may not be immediately obvious

2024-10-30 12:10 UTC, MatthewMiddlehurst commented on docs/getting_started.md
> +- Anomaly detection where the goal is to find values or areas of a
I hate github, it didnt even include the line i highlighted

2024-10-30 12:35 UTC, TonyBagnall commented
> Some incomplete bits in the guide but its not really intended to be complete so will leave it. I can't really review the single loaders easily as I can't tell what has changed due to the reordering so I haven't yet.


> > There are two multivariate loaders, uschange and longley. These adopted a structure like this firstly returning y, X is opposite to collections, and secondly there seems no need to split the data in the loader, the user can surely do that themselves.
> 
> Forecasting has a different format for its inputs so its not odd for its loaders to be different as well IMO. Is there a specific column/series you want to forecast for these problems or can you use any of them really. Seems similar to labels being stored as a column of a 2d collection if there is a specific target series.
> 
> Not saying the change is bad or wrong, just trying to get a better idea.

firstly, we are not doing any multivariate forecasting for a while, so this is just to have examples of multivariate single series. They are not specific to forecasting. The previous configuration allowed the user to specify y by column name. I think it was just excessive
> > returns numpy array with axis == 0, i.e. n_channels, n_timepoints and returns a data frame with axis == 1 and all the column names set as before.
> 
> This seems pretty confusing to swap dimensions with the parameter as well as datatype? I thought we were defaulting to `n_channels, n_timepoints` now.

we are defaulting, but it is not universal, see anomaly detection. You cant load into a dataframe with `n_channels, n_timepoints` and keep the column names. I have left the pandas stuff for legacy reasons really. I think I would rather remove these loaders completely than process to have series in rows in a dataframe.

2024-10-30 12:37 UTC, TonyBagnall commented on aeon/datasets/tests/test_single_problem_loaders.py
> -    assert solar.shape == (289,)
they are all tested together in one function

```
FORECASTING_DATA = {
    "shampoo_sales": [load_shampoo_sales, (36,)],
    "lynx": [load_lynx, (114,)],
    "airline": [load_airline, (144,)],
    "solar": [load_solar, (289,)],
    "PBS": [load_PBS_dataset, (204,)],
}


@pytest.mark.parametrize("data", FORECASTING_DATA.keys())
def test_univariate_forecasting_loaders(data):
    """Test baked in loaders of univariate forecasting data."""
    y = FORECASTING_DATA[data][0]()
    assert isinstance(y, np.ndarray)
    y2 = FORECASTING_DATA[data][0](return_array=False)
    assert isinstance(y2, pd.Series)
    assert y2.shape == FORECASTING_DATA[data][1]
    assert y.shape == y2.shape
```

2024-10-30 12:38 UTC, TonyBagnall commented on docs/glossary.md
> +Time series forecasting
yes good point

2024-10-30 12:40 UTC, TonyBagnall commented on docs/getting_started.md
> +- Anomaly detection where the goal is to find values or areas of a
well I am going to do them after this PR

2024-10-30 12:41 UTC, TonyBagnall commented on aeon/transformations/series/_pca.py
> +    >>> data = load_longley(return_array=False)
exactly

2024-10-30 12:44 UTC, TonyBagnall commented on docs/getting_started.md
> +```
not sure what happened to that, good spot!

2024-10-30 12:45 UTC, MatthewMiddlehurst commented
> we are defaulting, but it is not universal, see anomaly detection. 

Where in anomaly detection? I am referring just to inputs, dont really care what format they want the data internally

> You cant load into a dataframe with n_channels, n_timepoints and keep the column names. I have left the pandas stuff for legacy reasons really. I think I would rather remove these loaders completely than process to have series in rows in a dataframe.

cant you just transpose the dataframe? seems very odd if that removes the indicies

2024-10-30 12:54 UTC, TonyBagnall commented
> > we are defaulting, but it is not universal, see anomaly detection.
> 
> Where in anomaly detection? I am referring just to inputs, dont really care what format they want the data internally
> 
> > You cant load into a dataframe with n_channels, n_timepoints and keep the column names. I have left the pandas stuff for legacy reasons really. I think I would rather remove these loaders completely than process to have series in rows in a dataframe.
> 
> cant you just transpose the dataframe? seems very odd if that removes the indicies

I guess I can, seems odd to do so and I thought the examples made it clear, but sure, Need to rewrite the tests that use col_names

2024-10-30 13:00 UTC, TonyBagnall commented on docs/getting_started.md
> +>>> from aeon.datasets import load_airline
can use them on any series though, want to keep the getting started simple

2024-10-30 13:00 UTC, TonyBagnall commented on docs/getting_started.md
> +```
rewrote, simpler

2024-10-30 13:01 UTC, MatthewMiddlehurst commented
I remember some previous changes where we tried to remove `n_timepoints, n_channels` as much as we could. Think it was `df-list` and the other dataframe one for collections. May have been some other changes removing references to it as well.

Seems better to completely follow one format and leave changing that to the `axis` stuff if thats how we want it

2024-10-30 13:01 UTC, TonyBagnall commented on docs/getting_started.md
> +Collection estimators closely follow the `scikit-learn` estimator interface, using
well Collection estimators dont closely follow sci-kit interface imo, since scikit doesnt work with series

2024-10-30 13:03 UTC, TonyBagnall commented
> > we are defaulting, but it is not universal, see anomaly detection.
> 
> Where in anomaly detection? I am referring just to inputs, dont really care what format they want the data internally
> 
> > You cant load into a dataframe with n_channels, n_timepoints and keep the column names. I have left the pandas stuff for legacy reasons really. I think I would rather remove these loaders completely than process to have series in rows in a dataframe.
> 
> cant you just transpose the dataframe? seems very odd if that removes the indicies

yes but you cannot then extract series X["channel_name"], anyway, I have done it and removed the test for column names

2024-10-30 13:04 UTC, MatthewMiddlehurst commented on docs/getting_started.md
> +Collection estimators closely follow the `scikit-learn` estimator interface, using
Sorry, bad place to put it not that github really helps expanding to include other lines. I mean there is a "## Single series estimators" subsection separate to the data part but not one for `## collection estimators` or whatever.

2024-10-30 13:08 UTC, MatthewMiddlehurst commented
You would just use `X.loc["channel_name"]` im pretty sure

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html

2024-10-30 16:44 UTC, TonyBagnall commented on docs/getting_started.md
> +Collection estimators closely follow the `scikit-learn` estimator interface, using
feel free to jump on the branch and make changes

2024-10-31 08:34 UTC, TonyBagnall commented
> You would just use `X.loc["channel_name"]` im pretty sure
> 
> https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html

It was more I didn't want to rewrite the notebooks that used plot_series. But I've ditched that now

2024-11-03 12:51 UTC, hadifawaz1999 requested changes
just small questions, if you want to keep them for later i dont mind

2024-11-03 12:51 UTC, hadifawaz1999 commented on docs/getting_started.md
> +  into a different representation or domain. More details coming soon.
you can now add link to the new transformations notebook

2024-11-03 12:51 UTC, hadifawaz1999 commented on docs/getting_started.md
> +[classification notebooks](examples.md#classification).
link to classification notebook ?

2024-11-04 13:40 UTC, hadifawaz1999 approved these changes
lgtm

2024-11-04 16:58 UTC, CodeLionX approved these changes

2024-11-04 17:34 UTC, merged