[ENH] Remove make_series from anomaly detection
aeon-toolkit/aeon pull request #2282
Opened 2024-10-31 16:22 UTC by TonyBagnall

part of #2281 

anomaly detection tests were calling function to make a random numpy array. The function is legacy, and its not really required to create a random array

2024-11-04 12:01 UTC, CodeLionX requested changes
Thanks for taking on this task. I started to critisize usages of `make_series` in newer PRs.

2024-11-04 17:41 UTC, TonyBagnall commented on aeon/anomaly_detection/tests/test_dwt_mlead.py
> +        pred = ad.predict(series)
sure, just adding coverage when I am in a module

2024-11-04 17:45 UTC, TonyBagnall commented on aeon/anomaly_detection/tests/test_dwt_mlead.py
> +    series = rng.normal(size=(100,))
the problem that function creates a uniform distribution, If you use random uniformly distributed data then the tests of correct region all fail. We could remove those tests but that seemed beyond my remit to get rid of make series. Possibly resolve separately after this PR?

2024-11-04 17:46 UTC, TonyBagnall commented on aeon/anomaly_detection/tests/test_iforest.py
> +    rng = check_random_state(0)
I think check random state is better

2024-11-04 17:56 UTC, MatthewMiddlehurst commented
This does not remove the function itself, but maybe that is best left to a separate PR.

2024-11-05 08:29 UTC, CodeLionX commented on aeon/anomaly_detection/tests/test_dwt_mlead.py
> +    series = rng.normal(size=(100,))
OK, now I get it. Your solution is also fine. Normal distribution makes more sense for anomaly detection 👍🏼

2024-11-05 08:38 UTC, CodeLionX requested changes

2024-11-05 08:38 UTC, CodeLionX commented on aeon/anomaly_detection/tests/test_stomp.py
> +        ad.fit_predict(series)
can also be removed

2024-11-06 13:21 UTC, CodeLionX approved these changes

2024-11-06 14:19 UTC, merged