[ENH] normalise reconciliation
aeon-toolkit/aeon pull request #2289
Opened 2024-11-01 21:38 UTC by TonyBagnall

#### Reference Issues/PRs

Fixes #2075 

First draft, two transformers in the one file, allows unequal length, 

- [ ] will need a fit method to make invertible
- [ ] testing required
- [ ] docs
- [ ] notebook
- [ ] Confirm mutlviariate independent approach

2024-11-02 14:36 UTC, hadifawaz1999 reviewed
i think would be nice to add visual examples of series normalized before and after, either unit tests datas or a non normalized ucr one

2024-11-02 14:40 UTC, TonyBagnall commented
> i think would be nice to add visual examples of series normalized before and after, either unit tests datas or a non normalized ucr one

agreed, after #2279

2024-11-02 14:46 UTC, hadifawaz1999 requested changes
just a few minor things

2024-11-02 14:46 UTC, hadifawaz1999 commented on aeon/transformations/collection/_rescale.py
> +        X: np.ndarray or list
Better to say

X : np.ndarray or list
            Collection to transform. Either a list of 2D arrays with shape
            ``(n_channels, n_timepoints_i)`` or a single 3D array of shape
            ``(n_cases, n_channels, n_timepoints)``.

2024-11-02 14:46 UTC, hadifawaz1999 commented on aeon/transformations/collection/_rescale.py
> +    """Standardarise transformer for collections.
centerer transformer

2024-11-02 14:46 UTC, hadifawaz1999 commented on aeon/transformations/collection/_rescale.py
> +        Transform method to standardize series.
center series

2024-11-02 14:46 UTC, hadifawaz1999 commented on aeon/transformations/collection/_rescale.py
> +            The normalized data.
centered data ?

2024-11-02 14:46 UTC, hadifawaz1999 commented on aeon/transformations/collection/_rescale.py
> +            std_val = np.std(X, axis=-1, keepdims=True)
no need of std division

2024-11-02 14:46 UTC, hadifawaz1999 commented on aeon/transformations/collection/_rescale.py
> +                std_val = np.std(x, axis=-1, keepdims=True)
no need of std division

2024-11-02 14:46 UTC, hadifawaz1999 commented on aeon/transformations/collection/tests/test_rescaler.py
> +def test_standardize():
test_centerer

2024-11-02 14:46 UTC, hadifawaz1999 commented on aeon/transformations/collection/_rescale.py
> +        Transform method to apply the seleted normalisation.
to apply the normaliztion, no need for selected

2024-11-02 16:10 UTC, TonyBagnall commented on aeon/transformations/collection/_rescale.py
> +        X: np.ndarray or list
I dont actually know why we put these doc strings in protected methods

2024-11-02 17:46 UTC, hadifawaz1999 submitted a review, later dismissed
LGTM  but seems a conflict exists

2024-11-04 13:38 UTC, hadifawaz1999 submitted a review, later dismissed

2024-11-05 10:30 UTC, MatthewMiddlehurst commented
`Normalizer` or `Normaliser`? We have other PRs changing to UK english.

2024-11-05 12:52 UTC, TonyBagnall commented
> `Normalizer` or `Normaliser`? We have other PRs changing to UK english.

which other PRs? I went Normaliser then realised the rest of the toolkit is US English

2024-11-05 17:35 UTC, merged