[MNT] Tidy up classification and regression tests
aeon-toolkit/aeon pull request #2314
Opened 2024-11-06 22:19 UTC by MatthewMiddlehurst

todo

2024-11-15 18:07 UTC, TonyBagnall requested changes

2024-11-15 20:46 UTC, MatthewMiddlehurst commented on aeon/base/estimators/interval_based/base_interval_forest.py
> +                "Temporal importance curves are not available for regression."
This pr is the first step for doing this really, now that all the regressors are properly covered in general testing.

2024-11-15 20:51 UTC, MatthewMiddlehurst commented on aeon/base/estimators/interval_based/base_interval_forest.py
> +                "Temporal importance curves are not available for regression."
but yes it is covered here https://github.com/aeon-toolkit/aeon/pull/2314/files#diff-4d4e0a0a86dce2606c69a9f9e4dc24694b606a7db864eb1b1792c659fd9fa743R25

2024-11-18 16:22 UTC, TonyBagnall approved these changes

2024-11-18 16:33 UTC, merged