[ENH] Tidy up loaders and writers
aeon-toolkit/aeon pull request #2325
Opened 2024-11-08 14:40 UTC by TonyBagnall

Fixes #1931 

Tidy up the loaders and writers. Thery dont work with df-list or multindex as yet, but if any demand for this can do it.

2024-11-14 22:47 UTC, MatthewMiddlehurst requested changes
Don't edit the changelogs

2024-11-14 22:47 UTC, MatthewMiddlehurst commented on aeon/datasets/_data_writers.py
> +        _TEST
Is suffix necessary? can just be a part of `problem_name` right?

2024-11-15 17:04 UTC, TonyBagnall commented on aeon/datasets/_data_writers.py
> +        _TEST
its necessary for unequal etc

2024-11-16 13:12 UTC, MatthewMiddlehurst commented
still an edited changelog

2024-11-22 10:06 UTC, MatthewMiddlehurst commented on aeon/datasets/_data_writers.py
> +        _TEST
I dont really see the difference between `problem_name="sample_data_eq.ts"` and `problem_name="sample_data.ts"` + `suffix="_eq" though

2024-11-22 16:50 UTC, TonyBagnall commented on aeon/datasets/_data_writers.py
> +        _TEST
actually it was for train/test, but seeing as you object strongly, I will remove it

2024-11-23 08:46 UTC, merged