[ENH] Whole-series anomaly detection
aeon-toolkit/aeon pull request #2326
Opened 2024-11-08 16:13 UTC by MatthewMiddlehurst

todo

2025-04-19 10:19 UTC, TonyBagnall commented
could you clarify how this differs from imbalanced classification?

2025-04-25 11:30 UTC, SebastianSchmidl commented
@TonyBagnall 
In theory, whole-series AD is an unsupervised task. It neither is clustering because we are not interested in certain groups of time series, but rather in the outlying ones. If the detector requires a training step, I would also just classify it as imbalanced classification.

2025-04-25 11:49 UTC, SebastianSchmidl reviewed
Should we allow supervised usage for whole-series detection?
As I have mentioned in my reply to Tony's comment, I would argue that whole-series AD should be unsupervised. Otherwise, we could just use any time series classifier from aeon for this imbalanced binary-classification task.
Maybe, we should include Patrick M.'s and Andreas' view here as well. E.g., their [ROCKAD-algorithm](https://link.springer.com/chapter/10.1007/978-3-031-30047-9_33) is semi-supervised.

If we focus on unsupervised methods here, I would just have a `fit_predict`-method in the base class.

2025-04-25 11:49 UTC, SebastianSchmidl commented on aeon/anomaly_detection/whole_series/base.py
> +        if not all([x == 0 or x == 1 for x in y]):
`not np.bitwise_or(y == 0, y == 1).all()` would probably be faster. You already checked for `pd.Series` or `np.ndarray` above, so this should be supported by the types. You could also move the conversion to numpy from L197f before this check.

2025-05-02 07:15 UTC, pattplatt commented
> It is a recent change and based off a taxonomy. See #2663. I would keep everything inheriting from the collection base class in the `whole-series` module for now. No issue with additional subpackages from there is required.

> Yes that would diverge from how we design things at the moment. All the current anomaly detectors inherit from a base class which solely handles single series input, while this new base class inherits from one which deals with collections of series. I think eventually we may have a base class which handles collections in `fit` then single series in `predict`/`transform` etc, but I do not see us allowing single classes which switch between them.
> 
> We have algorithms which can be used for both classification and regression, but they are always separated into their own module. Similar case here IMO. If there is shared functionality, it would be best to have that in a separate file then call it from both implementations. If you can reduce from whole-series to pointwise then just calling the whole-series class/functions from the pointwise one sounds fine as well.
> 
> Always open for discussion, but unlikely to change soon IMO.

Ok then we create a new PR to move the current time point based ROCKAD back to /distance_based/_rockad.py and add the whole-series  to /whole_series/_rockad.py? If shared functionality can be put in a seperate file where could this file be located?

2025-05-05 14:04 UTC, SebastianSchmidl commented
## Regarding supervision

OK, I get the points for including all three cases (unsupervised, semi-supervised, and supervised) for whole series AD, despite duplication to classification. This mimics the learning types of TSAD then as well.

## Regarding folder structure

The current module folder is the root for all TSAD algorithms that are grouped into algorithm families (distance, encoding, distribution, etc.). The `whole_series` subfolder marks a new category of algorithms. Because we do not have many algorithms for whole series AD, there is no need for extra sub-subfolders. I would just put whole series ROCKAD in `anomaly_detection/whole_series/_rockad.py`.

@MatthewMiddlehurst, maybe we should have two subfolders in `anomaly_detection`: `series` (current TSAD stuff) and `collection` (the whole series AD estimators) and then branch-off from there?

```
aeon/anomaly_detection
├── series
│   ├── base.py
│   ├── tests
│   │   └── [...]
│   ├── distance_based
│   │   ├── _kmeans.py
│   │   └── [...]
│   └── [...]
├── collection
│   ├── base.py
│   ├── tests
│   │   └── [...]
│   ├── _rockad.py
│   └── [...]
└── __init__.py
```

Common functionality could then live in the base folder or in a separate one (e.g., `aeon/anomaly_detection/_common` or similar).

2025-05-05 16:03 UTC, MatthewMiddlehurst commented
Ok will try formatting like the above and see if there are any issues. Will also move the current ROCKAD implementation.

2025-05-12 15:24 UTC, SebastianSchmidl requested changes

2025-05-12 15:24 UTC, SebastianSchmidl commented on aeon/anomaly_detection/collection/base.py
> +            indices correspond to instance indices in X
Are they required to be predictions (0/1) or are also anomaly scores (in [0, 1]) allowed?

2025-05-12 15:24 UTC, SebastianSchmidl commented on aeon/anomaly_detection/collection/base.py
> +        X = self._preprocess_series(X, axis, True)
```suggestion
        X = self._preprocess_series(X, axis, store_metadata=True)
```
?

2025-05-12 15:24 UTC, SebastianSchmidl commented on aeon/anomaly_detection/collection/base.py
> +        if not all([x == 0 or x == 1 for x in y]):
Same as above: `not np.bitwise_or(y == 0, y == 1).all()` should be faster

2025-05-12 15:24 UTC, SebastianSchmidl commented on aeon/anomaly_detection/collection/base.py
> +            ``(n_channels, n_timepoints)``.
Why is this interface different from `predict` and `fit`? Here, you allow specifying an `axis` and refer to the standard aeon data types.

2025-05-12 15:24 UTC, SebastianSchmidl commented on aeon/anomaly_detection/series/distance_based/__init__.py
> +from aeon.anomaly_detection.series.outlier_detection._one_class_svm import OneClassSVM
❔

2025-05-12 15:24 UTC, SebastianSchmidl commented on aeon/anomaly_detection/series/distance_based/_left_stampi.py
> +class LeftSTAMPi(BaseSeriesAnomalyDetector):
Example import path not updated

2025-05-12 15:24 UTC, SebastianSchmidl commented on aeon/anomaly_detection/series/distance_based/_stomp.py
> +class STOMP(BaseSeriesAnomalyDetector):
Example import path not updated

2025-05-12 15:24 UTC, SebastianSchmidl commented on aeon/anomaly_detection/series/outlier_detection/__init__.py
> +from aeon.anomaly_detection.series.outlier_detection._stray import STRAY
OneClassSVM is missing

2025-05-12 15:24 UTC, SebastianSchmidl commented on aeon/utils/base/_register.py
> +        "anomaly-detector",
Shouldn't this rather be one of `series-anomaly-detector` or `collection-anomaly-detector`? The `AnomalyDetectorBase` is not meant to be inherited, right?

2025-05-12 15:24 UTC, SebastianSchmidl commented on aeon/utils/tags/tests/test_discovery.py
> +    assert tags == all_tags_for_estimator("series-anomaly-detector")
Shouldn't there be something similar for `BaseCollectionAnomalyDetector`? Same for `aeon/utils/tests/test_discovery.py`

2025-05-12 15:24 UTC, SebastianSchmidl commented on docs/api_reference/anomaly_detection.rst
> +    OutlierDetectionAdapter
```suggestion
    ClassificationAdapter
    OutlierDetectionAdapter
    BaseCollectionAnomalyDetector
```

The other bases are also at the bottom

2025-05-13 13:07 UTC, SebastianSchmidl commented
> Thanks for the review, will take a look and reply. Before that I will try get #2652 in though, as it may be a pain to do so after merging this.

Sure thing. #2652 is, however, still failing CI.

2025-05-18 20:30 UTC, MatthewMiddlehurst commented on aeon/anomaly_detection/collection/base.py
> +            indices correspond to instance indices in X
scores also

2025-05-18 20:39 UTC, MatthewMiddlehurst commented on aeon/testing/mock_estimators/_mock_anomaly_detectors.py
> +class MockAnomalyDetector(BaseSeriesAnomalyDetector):
Not for anything here but would be good to include eventually. Can do it here but pretty large already.

2025-05-18 20:42 UTC, MatthewMiddlehurst commented on aeon/utils/tags/tests/test_discovery.py
> +    assert tags == all_tags_for_estimator("series-anomaly-detector")
Don't think we need one for every module, but would do it as a separate issue if so. Every module is included in the estimator discovery testing i believe, as a test parameter.

2025-05-18 20:43 UTC, MatthewMiddlehurst commented on aeon/anomaly_detection/series/distance_based/_left_stampi.py
> +class LeftSTAMPi(BaseSeriesAnomalyDetector):
Fixed. I hate the examples that skip tests 🙂

2025-05-18 20:56 UTC, MatthewMiddlehurst commented
Merged the other AD stuff from main and applied most of the review suggestions. Mostly changes to testing from the merge.

2025-05-20 07:19 UTC, SebastianSchmidl commented on aeon/anomaly_detection/series/distance_based/_left_stampi.py
> +class LeftSTAMPi(BaseSeriesAnomalyDetector):
I can relate 😓

2025-05-20 07:20 UTC, SebastianSchmidl commented on aeon/utils/tags/tests/test_discovery.py
> +    assert tags == all_tags_for_estimator("series-anomaly-detector")
Ok

2025-05-20 07:29 UTC, SebastianSchmidl requested changes

2025-05-20 07:29 UTC, SebastianSchmidl commented on aeon/utils/base/_register.py
> +        "anomaly-detector",
Is this fixed in the current version?

2025-05-28 08:59 UTC, SebastianSchmidl commented on aeon/utils/base/_register.py
> +        "anomaly-detector",
Ah, now I get it! This is the set of non-valid bases to inherit from, which is removed from the set of all base classes (`BASE_CLASS_REGISTER`). 👍🏼

2025-05-30 22:01 UTC, merged