[ENH] Add and Validate `n_layers`, `n_units`, `activation` & `dropout_rate` kwargs to MLPNetwork
aeon-toolkit/aeon pull request #2338
Opened 2024-11-11 06:54 UTC by aadya940

Closes #2337 .

2024-11-11 13:16 UTC, hadifawaz1999 commented on aeon/networks/_mlp.py
> +        self._n_layers = n_layers
better to declare all of them as self before defining the internal versions, so self.activation = activation and then define self._activation

2024-11-11 13:30 UTC, hadifawaz1999 requested changes
Thx for taking care of it.
In general:

- All parameters should be defined as private in constructor before starting anything
- the assertions and all the list checking should only be in build_network method not constructor, this will avoid causing issues on CI (check for example how fcn network is implemented)
- Also given we are parametrizing the network, the associated classifier and regressor should be parametrized as such (also docs) and use them when calling the network
- I left some other comments to check

2024-11-11 13:30 UTC, hadifawaz1999 commented on aeon/networks/_mlp.py
> +        if isinstance(activation, str):
better to declare all of them as self before defining the internal versions, so self.activation = activation and then define self._activation

2024-11-11 13:30 UTC, hadifawaz1999 commented on aeon/networks/_mlp.py
> +            assert (
asserting the len() twice

2024-11-11 13:30 UTC, hadifawaz1999 commented on aeon/networks/_mlp.py
> +        self._n_layers = n_layers
no need to define private for this one with underscore as it wont change

2024-11-11 13:30 UTC, hadifawaz1999 commented on aeon/networks/_mlp.py
> +            self._dropout_rate = [0.2] * self._n_layers
the default value of dropout is not 0.2 in the original implementation (check main branch), its 0.1 then 0.2 then 0.2

2024-11-11 13:30 UTC, hadifawaz1999 commented on aeon/networks/_mlp.py
> +    dropout_rate : Union[int, float, list[Union[int, float]]], optional (default=None)
i would obligate float always for dropout_rate and say that is should be between 0 and 1

2024-11-11 13:30 UTC, hadifawaz1999 commented on aeon/networks/_mlp.py
> +            assert (
asserting on len twice

2024-11-11 13:30 UTC, hadifawaz1999 commented on aeon/networks/_mlp.py
> +        x = keras.layers.Dropout(self._dropout_rate[0])(input_layer_flattened)
better to include this block in the loop
where each block in the loop will be one dropout layer followed by a dense layer

2024-11-11 13:30 UTC, hadifawaz1999 commented on aeon/networks/_mlp.py
> +        output_layer = keras.layers.Dropout(0.3)(x)
i would define a parameter called dropout_last default to 0.3, and document it in details for that this dropout layer is applied at the end

2024-11-18 15:54 UTC, aadya940 commented on aeon/networks/_mlp.py
> +            self._dropout_rate = [0.2] * self._n_layers
How to extrapolate it to `n_layers`? Should I do the follows?
```
self._dropout_rate = [0.1].extend([0.2] * self._n_layers - 1)
```

2025-01-19 15:20 UTC, hadifawaz1999 requested changes
Looks great, just the original default number of units is actually 500 not 200, once this is changed we can get this in

2025-01-22 09:54 UTC, dschrempf commented on aeon/classification/deep_learning/_mlp.py
> +        Dropout rate(s) are typically a number in the interval [0, 1].
As far as I can see, if `dropout_rate` is `None`, it will be set to

```
            self._dropout_rate = [0.1]
            self._dropout_rate.extend([0.2] * (self.n_layers - 1))
```
I think we should adapt this info.

2025-01-25 13:58 UTC, hadifawaz1999 approved these changes

2025-01-25 13:58 UTC, merged