[ENH]check for algorithm_type
aeon-toolkit/aeon pull request #2339
Opened 2024-11-11 09:41 UTC by aryanpola

#### Reference Issues/PRs
Fixes #1952 

#### What does this implement/fix? Explain your changes.
Adds a check for `algorithm_type` in `aeon.testing.estimator_checking._yield_classification_checks.py`

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [ ] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

2024-11-11 09:52 UTC, aryanpola commented
@MatthewMiddlehurst should I raise errors for the absence of the `algorithm_type` tag in the estimator?

2024-11-11 18:38 UTC, TonyBagnall commented
> @MatthewMiddlehurst should I raise errors for the absence of the `algorithm_type` tag in the estimator?

no, they do not have to have them, but if a classifier does have this tag, it should be one of 
{"convolution", "dictionary","distance", "feature", "shapelet", "interval","hybrid","deeplearning"}

thats all you need to check, thanks for your contributions

2024-11-11 20:45 UTC, aryanpola commented
@TonyBagnall I've added `None` to the list of valid algorithms since some have it as none

2024-11-13 10:08 UTC, TonyBagnall requested changes
thanks

2024-11-13 10:08 UTC, TonyBagnall commented on aeon/testing/estimator_checking/_yield_classification_checks.py
> +    if algorithm_type is None:
better to just pass the test if algorithm_type is none that pytest skip

2024-11-13 16:12 UTC, TonyBagnall approved these changes
LGTM, thanks

2024-11-13 16:12 UTC, merged