[ENH] Implemented SimpleImputer
aeon-toolkit/aeon pull request #2347
Opened 2024-11-13 13:26 UTC by notaryanramani

#### Reference Issues/PRs

Fixes #2293 

#### What does this implement/fix? Explain your changes.

Implements `SimpleImputer` class in `aeon.transformations.collections`, along with test cases.

#### Does your contribution introduce a new dependency? If yes, which one?

#### Any other comments?

### PR checklist

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [x] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

##### For new estimators and functions
- [x] I've added the estimator to the online [API documentation](https://www.aeon-toolkit.org/en/latest/api_reference.html).
- [ ] (OPTIONAL) I've added myself as a `__maintainer__` at the top of relevant files and want to be contacted regarding its maintenance. Unmaintained files may be removed. This is for the full file, and you should not add yourself if you are just making minor changes or do not want to help maintain its contents.

##### For developers with write access
- [ ] (OPTIONAL) I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.

2024-11-15 18:04 UTC, TonyBagnall requested changes
thanks for this, but I think the imputation should be for each case and channel independently not for all cases. Given it can be a list, and unequal length, its probably easiest just to iterate over series and do them like that

2024-11-15 18:51 UTC, notaryanramani commented on aeon/transformations/collection/_impute.py
> +        "fit_is_empty": False,
Yes, there is no fit method. Actually I just copied the tags from [here](https://github.com/aeon-toolkit/aeon/issues/2293#issuecomment-2471059166) and skipped to check it 😅.  Will fix that

2024-11-16 10:36 UTC, TonyBagnall commented
thanks but this is still not logically correct, or rather not how I would like it. I want mean/median interpolation to happen independently on each channel and I dont think it is doing that at the moment. Logically
```python
n_channels = X[0].shape(0)
for i in range(len(X)):
    for j in range(n_channels):
           interpolate any missing in X[i][j]
```
Its obviously possible you can do it more efficiently without loops, but I think the outer loop is fine because it generalises the case for list and 3D array collections

2024-11-16 10:41 UTC, notaryanramani commented
I think the parameter `axis=-1` takes care that we need the mean of every channel independently.

2024-11-16 16:50 UTC, TonyBagnall approved these changes
LGTM now, thanks

2024-11-16 16:52 UTC, TonyBagnall commented
@all-contributors add @notaryanramani for code

2024-11-16 16:52 UTC, merged