[ENH] Collection and series base tidy
aeon-toolkit/aeon pull request #2352
Opened 2024-11-14 11:41 UTC by MatthewMiddlehurst

- makes `__init__` abstracts for the classes in `base`
- renames the base series data arrays to contain series in the var name
- check for soft dependencies in `BaseAeonEstimator` rather than in the base classes below
- remove `self.fit_time_` from some collection estimators and the collection base. This was not very consistently used.
- tidy up docs a bit

2024-11-15 10:24 UTC, SebastianSchmidl requested changes

2024-11-15 10:24 UTC, SebastianSchmidl commented on aeon/base/_base.py
> +        _check_estimator_deps(self)
I did not know that this was possible, but seems reasonable for our use case.

More details in the _Notes_-box at the end of https://docs.python.org/3/library/abc.html#abc.abstractmethod

2024-11-15 10:24 UTC, SebastianSchmidl commented on aeon/transformations/collection/base.py
>          super().__init__()
Non-abstract?

The `BaseSeriesTransformer.__init__` is also non-bastract?

2024-11-20 20:03 UTC, MatthewMiddlehurst commented on aeon/transformations/collection/base.py
>          super().__init__()
Made the remaining base classes abstract

2024-11-22 12:21 UTC, SebastianSchmidl approved these changes

2024-11-22 17:00 UTC, TonyBagnall approved these changes

2024-11-22 17:02 UTC, chrisholder approved these changes

2024-11-22 20:22 UTC, chrisholder approved these changes

2024-11-22 20:22 UTC, merged