[REF] Refactor `performance_metrics` into `benchmarking.metrics` and use a local version of `sphinx-remove-toctrees`
aeon-toolkit/aeon pull request #2353
Opened 2024-11-14 12:26 UTC by MatthewMiddlehurst

Moves performance metric and refactors the segmentation metrics into a single file.

Updates the benchmarking API file. While doing this I noticed `sphinx-remove-toctrees` had broke, See https://github.com/executablebooks/sphinx-remove-toctrees/issues/9. This PR introduces a fixed version locally.

2024-11-14 13:32 UTC, SebastianSchmidl requested changes
I did not check whether there are other places still referencing the old metrics. Should be fine, though.

Are the metrics part of the public API? If yes, we should include them in the API reference.

2024-11-14 13:32 UTC, SebastianSchmidl commented on docs/api_reference.md
> -api_reference/performance_metrics
Where is the documentation now?

2024-11-14 15:10 UTC, MatthewMiddlehurst commented on docs/api_reference.md
> -api_reference/performance_metrics
So far with these big module changes I have waited for it to settle down a bit before going into the docs, but this is the last change I wanted to make to benchmarking really.

Will update it under `benchmarking` and make sure the rest of the module is there as well

2024-11-14 18:22 UTC, SebastianSchmidl commented on docs/api_reference.md
> -api_reference/performance_metrics
Makes sense, thank you!

2024-11-15 10:04 UTC, SebastianSchmidl requested changes
Thanks for fixing the sphynx-plugin. I think the PR is still fine in size.

2024-11-15 10:04 UTC, SebastianSchmidl commented on docs/api_reference/benchmarking.rst
> +metrics for a variety of tasks.
This sentence has probably too many `and`s. I don't get it.

2024-11-15 10:04 UTC, SebastianSchmidl commented on docs/api_reference/benchmarking.rst
> +    prediction_ratio
What about the `aeon.benchmarking.metrics.stats` module containing
- check_friedman
- nemenyi_test
- wilcoxon_test

IMO, those are not metrics. I would move them to `aeon.benchmarking.stats` and also add them to the documentation here.

2024-11-15 14:29 UTC, MatthewMiddlehurst commented on docs/api_reference/benchmarking.rst
> +    prediction_ratio
good catch. made the suggested change

2024-11-15 14:54 UTC, SebastianSchmidl approved these changes

2024-11-15 20:36 UTC, merged