[ENH] Added ROCKAD anomaly detector to aeon
aeon-toolkit/aeon pull request #2376
Opened 2024-11-21 16:08 UTC by pattplatt

#### What does this implement/fix? Explain your changes.

Implemented the ROCKAD anomaly detector.

### PR checklist

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [x] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

##### For new estimators and functions
- [X] I've added the estimator to the online [API documentation](https://www.aeon-toolkit.org/en/latest/api_reference.html).
- [ ] (OPTIONAL) I've added myself as a `__maintainer__` at the top of relevant files and want to be contacted regarding its maintenance. Unmaintained files may be removed. This is for the full file, and you should not add yourself if you are just making minor changes or do not want to help maintain its contents.

##### For developers with write access
- [ ] (OPTIONAL) I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.

2024-11-29 09:43 UTC, SebastianSchmidl commented
The CI tests are still failing. Can you check why this is the case?

2024-12-02 14:46 UTC, pattplatt commented
@SebastianSchmidl should be better now

2024-12-04 09:32 UTC, baraline requested changes
Small change needed for a softdep test. For the other ones that are still failing, it look a bit sneaky. Found this issue that could be relevant, https://github.com/scikit-learn/scikit-learn/issues/27499

2024-12-04 09:32 UTC, baraline commented on aeon/anomaly_detection/_rockad.py
> +    }
You will need `capability:multithreading=True` in the tags as you have a n_jobs `parameter`

2024-12-05 17:08 UTC, baraline commented
The issue might be caused by an overflow, see steps to reproduce :
```python
from sklearn.preprocessing import PowerTransformer
transformer = PowerTransformer()
transformer.fit([[23.96], [23.98], [23.99]])
```
Gives
```python-traceback
C:\Users\AntoineGUILLAUME\miniconda3\envs\watson\Lib\site-packages\sklearn\preprocessing\_data.py:3438: RuntimeWarning: overflow encountered in power
  out[pos] = (np.power(x[pos] + 1, lmbda) - 1) / lmbda
...
BracketError: The algorithm terminated without finding a valid bracket. Consider trying different initial points.
```
Changing the inputs slightly will cause the error to either appear or disappear, not familiar with the transformer, but the value lambda used in the power function seems to cause the overflow on some cases. Issue seems to be happening independently of the sklearn version.

2024-12-06 15:53 UTC, pattplatt commented
> The issue is caused by an overflow, see steps to reproduce :
> 
> ```python
> from sklearn.preprocessing import PowerTransformer
> transformer = PowerTransformer()
> transformer.fit([[23.96], [23.98], [23.99]])
> ```
> 
> Gives
> 
> ```
> RuntimeWarning: overflow encountered in power: out[pos] = (np.power(x[pos] + 1, lmbda) - 1) / lmbda
> ...
> BracketError: The algorithm terminated without finding a valid bracket. Consider trying different initial points.
> ```
> 
> Changing the inputs slightly will cause the error to either appear or disappear, not familiar with the transformer, but the value lambda used in the power function seems to cause the overflow. The issue seems to be happening independently of the sklearn version.

Thanks for the suggestions 👍, after testing a little I think the main reason seems to be the window size and stride applied to the input data which leads to the final bracket error.  I will add a fallback and a warning if this occurs.

2024-12-08 16:10 UTC, SebastianSchmidl commented
Could we restrict the `window_size` and `stride` parameters in some way to prevent the error? E.g. limit window_size to >5, <=0.5*n_timepoints or similar?

2024-12-09 16:26 UTC, pattplatt commented
> Could we restrict the `window_size` and `stride` parameters in some way to prevent the error? E.g. limit window_size to >5, <=0.5*n_timepoints or similar?

As I implemented it now, power transform gets deactivated dynamically only if it leads to the error. I also added a ValueError if  n_neighbors are larger than the count of windows. The soft-deps test passes now. What do you think, is this sollution also fine?

2024-12-09 16:33 UTC, baraline commented
If we decide to go with the current implementation, keeping an open issue with the context, the reproduction steps, and the related issues as backlog so we can keep an eye on it. Because as I understand it, the issue is not caused by our usage of the PowerTransformer.

2024-12-09 19:20 UTC, SebastianSchmidl requested changes
Thank you for this contribution. Looks good already. I left some minor code improvements below.

Should we try to get rid of Pandas within the implementation? All things should be possible with NumPy. @baraline your take on this?

2024-12-09 19:20 UTC, SebastianSchmidl commented on aeon/anomaly_detection/_rockad.py
> +        self.Xtp = None  # X: values, t: (rocket) transformed, p: power transformed
`self.Xtp` is not used outside this function. Instead, `self.Xtp_df` is. `self.Xtp` can be removed, and a local variable be used in the try-except-clause.

2024-12-09 19:20 UTC, SebastianSchmidl commented on aeon/anomaly_detection/_rockad.py
> +            Xtp_scaled = self.scaler_.fit_transform(self.Xtp_df)
Here, you use the `StandardScaler` independent of the input parameter `normalise`. Is this intended? If yes, please improve the parameter documentation.

I am also confused by first using `PowerTransformer(standardize=False)` and then standardizing manually afterward. Why not use `PowerTransformer(standardize=True)`?

2024-12-09 19:20 UTC, SebastianSchmidl commented on aeon/anomaly_detection/_rockad.py
> +            Xtp_scaled_sample = Xtp_scaled_sample
Noop, please remove.

2024-12-09 19:20 UTC, SebastianSchmidl commented on aeon/anomaly_detection/_rockad.py
> +        self.list_baggers = []
This should be a fitted member: `self.list_baggers_`

2024-12-09 19:20 UTC, SebastianSchmidl commented on aeon/anomaly_detection/_rockad.py
> +            )
The `self.estimator` member gets overwritten and only stores the last estimator. I think this should be a local variable instead.

2024-12-09 19:20 UTC, SebastianSchmidl commented on aeon/anomaly_detection/_rockad.py
> +            Xtp = self.power_transformer_.transform(Xt)
Is this guaranteed not to raise the bracket-error?

2024-12-09 19:20 UTC, SebastianSchmidl commented on aeon/anomaly_detection/_rockad.py
> +    return df
If this is used only within the `_predict_proba` function, you can replace it with the way easier to maintain statement:

```python
df[~np.isfinite(df)] = 0.0
```

2024-12-09 19:20 UTC, SebastianSchmidl commented on aeon/anomaly_detection/tests/test_rockad.py
> +        ad.fit_predict(series)
Please add tests for the following:

- test of the `kneighbors`-check
- force of bracket error and test if the recovery strategy kicks in

2024-12-10 15:41 UTC, pattplatt commented
> If we decide to go with the current implementation, keeping an open issue with the context, the reproduction steps, and the related issues as backlog so we can keep an eye on it. Because as I understand it, the issue is not caused by the way we use the PowerTransformer right ? But if we can show that the error is bounded between some window size and stride values, we could enforce it.

As it turned out it was a problem with the way it was implemented. I now transpose the data before the transform is applied and now the error is gone, so I think its fine now.

2024-12-10 15:41 UTC, pattplatt commented on aeon/anomaly_detection/_rockad.py
> +        power_transform=True,
You are right, I set the default to False

2024-12-10 15:43 UTC, pattplatt commented on aeon/anomaly_detection/_rockad.py
> +            )
The problem is that the check has to be done after the data is transformed into windows, _check_params is called before. Should we move _check_params to be called after windowing in this case?

2024-12-10 15:45 UTC, pattplatt commented on aeon/anomaly_detection/_rockad.py
> +            Xtp = self.power_transformer_.transform(Xt)
It was the cause, I implemented a transpose and the error is gone, so I also removed the fallback, seems to be cleaner now.

2024-12-10 15:45 UTC, pattplatt commented on aeon/anomaly_detection/_rockad.py
> +    return df
removed the function

2024-12-10 15:47 UTC, pattplatt commented on aeon/anomaly_detection/_rockad.py
> +            Xtp_scaled = self.scaler_.fit_transform(self.Xtp_df)
Yes this makes not much sense as PowerTransformer(standardize) seems to do the same, I removed StandardScaler completely and set PowerTransformer(standardize) True as default

2024-12-10 15:48 UTC, pattplatt commented
> Thank you for this contribution. Looks good already. I left some minor code improvements below.
> 
> Should we try to get rid of Pandas within the implementation? All things should be possible with NumPy. @baraline your take on this?

I removed all Pandas dependencies on the latest commit

2024-12-10 18:58 UTC, baraline commented
Thanks I'll try to have a more throughout look at it this evening, but it looks fine at a glance

2024-12-11 11:27 UTC, SebastianSchmidl requested changes
I could not follow the shapes of the different data representations and check whether transposing the input to the power transformer is actually correct. IMO the transpose is wrong.

2024-12-11 11:27 UTC, SebastianSchmidl commented on aeon/anomaly_detection/_rockad.py
> +            )
Can't we compute the expected window count by `(n_timepoints - window_size - padding_length) / stride + 1` and then compare this against `n_neighbors`?

But you could also keep it here, just add a comment that this check operates on the windows.

2024-12-11 11:27 UTC, SebastianSchmidl commented on aeon/anomaly_detection/_rockad.py
> +            self.power_transformer_ = PowerTransformer()
Members with `_` at the end should be set only from the `fit()` function.

2024-12-11 11:27 UTC, SebastianSchmidl commented on aeon/anomaly_detection/_rockad.py
> +        Xt = self.rocket_transformer_.fit_transform(X)
It is really difficult to track shapes. Am I right with this?

```suggestion
        # X: (n_windows, window_size)
        Xt = self.rocket_transformer_.fit_transform(X)
        # XT: (n_cases, n_kernels)
```

2024-12-11 11:27 UTC, SebastianSchmidl commented on aeon/anomaly_detection/_rockad.py
> +        )
```suggestion
        # X: (n_timepoints, 1) because __init__(axis==0)
        _X, _ = sliding_windows(
            X, window_size=self.window_size, stride=self.stride, axis=0
        )
        # _X: (n_windows, window_size)
```

2024-12-11 11:27 UTC, SebastianSchmidl commented on aeon/anomaly_detection/_rockad.py
> +            Xtp = self.power_transformer_.fit_transform(Xt.T)
`PowerTransformer` expects `(n_samples, n_features)` and `Xt` is in `(n_cases, n_kernels)`. If we transpose, we get `n_samples = n_kernels` and `n_features = n_cases`. This does not sound right to me. Did I miss something?

2024-12-11 11:27 UTC, SebastianSchmidl commented on aeon/anomaly_detection/_rockad.py
> +        k-NN estimator used for anomaly scoring, set after fitting.
This should be `list_baggers_ : Optional[List[NearestNeighbors]`

2024-12-11 11:27 UTC, SebastianSchmidl commented on aeon/anomaly_detection/_rockad.py
> +        self.estimator_: Optional[NearestNeighbors] = None
Unused

2024-12-11 11:27 UTC, SebastianSchmidl commented on aeon/anomaly_detection/_rockad.py
> +            Xtp = Xtp.astype(np.float64).to_numpy()
This should probably be one level deeper within the `if self.power_transformer_ is not None`-branch, right? Otherwise, `Xtp` might not be defined.

2024-12-11 22:25 UTC, baraline commented on aeon/anomaly_detection/_rockad.py
> +            Xtp = self.power_transformer_.fit_transform(Xt.T)
This is how I understand it too, transposing is fixing the bug but output of the PowerTransformer will not be what is expected. IMO If we can't figure out the bug, the solution of having a try catch with warning has you previously did works fine.

2024-12-12 11:49 UTC, pattplatt commented on aeon/anomaly_detection/_rockad.py
> +        Xt = self.rocket_transformer_.fit_transform(X)
I think XT should be: (n_windows, n_kernels*2), Rocket producer for each feature 2 values but the windows remain. Or is n_cases just another term for window?

2024-12-12 13:46 UTC, SebastianSchmidl commented on aeon/anomaly_detection/_rockad.py
> +        Xt = self.rocket_transformer_.fit_transform(X)
Ok, `(n_windows, n_kernels*2)` makes sense, and `n_cases` = `n_windows` 👍🏼

2024-12-13 10:44 UTC, SebastianSchmidl approved these changes

2024-12-13 10:45 UTC, SebastianSchmidl commented on aeon/anomaly_detection/_rockad.py
> +            Xtp_scaled_sample = Xtp_scaled_sample
Is this still in there?

2024-12-13 12:35 UTC, pattplatt commented on aeon/anomaly_detection/_rockad.py
> +            Xtp_scaled_sample = Xtp_scaled_sample
Sorry, thought I already removed this

2024-12-13 13:06 UTC, SebastianSchmidl approved these changes
LGTM, let's give @baraline some time to also review

2024-12-18 07:19 UTC, baraline requested changes
LGTM but one small comment, sorry for the delay, don't hesitate to ping me on slack next time !

2024-12-18 07:19 UTC, baraline commented on aeon/anomaly_detection/_rockad.py
> +                Xtp = Xt
I would add a warning about the inf_columns, changing the shape of the input data (here n_features) should not be done without at least some kind of feedback to the user IMO. When do we get these inf values btw ? They are different from the bug with the power transformer ?

2024-12-18 13:18 UTC, pattplatt commented on aeon/anomaly_detection/_rockad.py
> +                Xtp = Xt
No the inf values are not different from the bug as it seems. I quickly tested if they still occur and it seems because the power transform gets deactivated when the error occurs, the "inf values case" also does not occur anymore. Thus I think, we maybee could also remove the code in fit() as well as _predict_proba(). What do you think?

2024-12-18 18:33 UTC, SebastianSchmidl commented on aeon/anomaly_detection/_rockad.py
> +                Xtp = Xt
If the `inf`s are just a product of the `PowerTransformer`-bug, then we should, IMHO, also remove this code.

2024-12-18 21:16 UTC, baraline commented on aeon/anomaly_detection/_rockad.py
> +                Xtp = Xt
Agreed, this is just confusing if these values only occur due to the supposed bug of PowerTransformer. In that case, we should get rid of the inf values thing.

2024-12-19 09:44 UTC, baraline submitted a review, later dismissed
LGTM, thanks ! :)

2024-12-19 14:13 UTC, MatthewMiddlehurst commented on aeon/anomaly_detection/_rockad.py
> +        n_jobs=1,
We usually have n_jobs at the bottom

2024-12-19 14:13 UTC, MatthewMiddlehurst commented on aeon/anomaly_detection/_rockad.py
> +        super().__init__(axis=0)
This is best put as low down as possible in init to reduce the risk of overwriting attributes set higher up

2024-12-20 15:46 UTC, SebastianSchmidl approved these changes

2024-12-20 15:47 UTC, merged