[ENH] Add LITETimeClassifier Example to Classification Notebook
aeon-toolkit/aeon pull request #2419
Opened 2024-12-01 11:19 UTC by sumana-2705

#### Reference Issues/PRs
Fixes #2295 

#### What does this implement/fix? Explain your changes.
Added LITETimeClassifier example to the `classification.ipynb` file in the examples section, demonstrating its application to `arrow_head` dataset

#### Does your contribution introduce a new dependency? If yes, which one?

No, this contribution does not introduce any new dependencies.

#### Any other comments?

Please let me know if any further adjustments or enhancements are needed for the example. Thank you for reviewing!

### PR checklist

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [x] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

2024-12-01 11:20 UTC, sumana-2705 commented
@all-contributors please add @sumana-2705 for code

2024-12-03 11:48 UTC, hadifawaz1999 commented on examples/classification/classification.ipynb
>  {
<p>no need for that title, the addition of LITETime above is enough</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/aeon-toolkit/aeon/pull/2419/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='30'/>

2024-12-03 11:48 UTC, hadifawaz1999 requested changes
Thank you for the contribution, just a small comment in the notebook, @MatthewMiddlehurst would like your input as well

2024-12-04 10:49 UTC, MatthewMiddlehurst commented
Addition looks fine assuming it is fast to run, could you give a general idea on how long the cell takes for you to process?

Would also update the "Background info and references for classifiers used here" section.

2024-12-04 15:44 UTC, sumana-2705 commented
> Addition looks fine assuming it is fast to run, could you give a general idea on how long the cell takes for you to process?
> 
> Would also update the "Background info and references for classifiers used here" section.

I have updated the classifier description to include runtime information and references. In a Colab environment, it took approximately 6 minutes to run.

2024-12-04 18:39 UTC, MatthewMiddlehurst commented
That is too much unfortunately. This is obviously dependant on setup, but I would prefer around 10 seconds. The runtime is pretty long on our CI https://github.com/aeon-toolkit/aeon/actions/runs/12163243307/job/33921975615?pr=2419#step:6:741.

2024-12-05 02:53 UTC, sumana-2705 commented
It is getting reduced by reducing number of epochs, but accuracy is decreasing. 50 epchs is returning 0.35 accuracy by with 1 min of runtime, 100 epochs is returning 0.59 accuracy with 2 mins of runtime, 200 epochs is returning 0.86 accuracy with 3 mins of runtime. What should I prefer now, should I reduce epochs to reduce runtime, can you please suggest me?

2024-12-09 06:46 UTC, sumana-2705 commented
@MatthewMiddlehurst @hadifawaz1999 

I have made the all required changes, if it seems okay can you please merge this PR?

2024-12-12 19:30 UTC, MatthewMiddlehurst commented on examples/classification/classification.ipynb
> +        "The [LITETime Classifier](https://www.aeon-toolkit.org/en/stable/api_reference/auto_generated/aeon.classification.deep_learning.LITETimeClassifier.html#aeon.classification.deep_learning.LITE
use relative links to the webpages instead of absolute links and links to the github notebook

2024-12-12 19:30 UTC, MatthewMiddlehurst commented on examples/classification/classification.ipynb
> +
[4] and [5] for references

2024-12-13 06:15 UTC, sumana-2705 commented on examples/classification/classification.ipynb
> +
I have corrected it. Thank you for pointing it.

2024-12-13 06:16 UTC, sumana-2705 commented on examples/classification/classification.ipynb
> +        "The [LITETime Classifier](https://www.aeon-toolkit.org/en/stable/api_reference/auto_generated/aeon.classification.deep_learning.LITETimeClassifier.html#aeon.classification.deep_learning.LITE
I have added relative link for deep learning notebook, but I am unable to add like for auto generated link of LITEtime classifier. If it is important can you please guide me how to add it?

2024-12-14 03:52 UTC, sumana-2705 commented on examples/classification/classification.ipynb
> +        "The [LITETime Classifier](https://www.aeon-toolkit.org/en/stable/api_reference/auto_generated/aeon.classification.deep_learning.LITETimeClassifier.html#aeon.classification.deep_learning.LITE
> how much time does the cell take to run now?

It is taking less than 1 minute to run now.

2024-12-15 19:08 UTC, MatthewMiddlehurst approved these changes

2025-01-08 16:37 UTC, sumana-2705 commented
Hello @hadifawaz1999 

Can you please approve the changes and merge the PR if PR looks right, so that I can start workingon other issues. Thank you

2025-01-15 17:04 UTC, hadifawaz1999 approved these changes

2025-01-19 23:37 UTC, merged

2025-01-19 23:38 UTC, MatthewMiddlehurst commented
@all-contributors please add @sumana-2705 for code