[DOC] Created a adding_typehints.md in developers_guide that Fixes issue #1857
aeon-toolkit/aeon pull request #2424
Opened 2024-12-02 17:35 UTC by vedpawar2254

Added a documentation file about adding type hints

#### Reference Issues/PRs

Fixes  #1857

#### What does this implement/fix? Explain your changes.

This adds a file to the developers_guide and the file contains a guide to adding type hints in the project

#### Any other comments?

### PR checklist

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [x] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

2024-12-03 07:03 UTC, baraline commented
Hi! Thanks for the PR, I'm wondering if that kind of content shouldn't be added as a section in the coding standard page rather than on its own. 
@MatthewMiddlehurst do we consider type hint as a standard or simply a good practice?

2024-12-03 15:02 UTC, MatthewMiddlehurst requested changes

2024-12-03 15:02 UTC, MatthewMiddlehurst commented on docs/developer_guide/adding_typehints.md
> +You can provide type hints for function parameters and return values. This helps other developers understand what types of arguments are expected by the function and what type the function returns.
There is a bit a repetition here.

2024-12-03 15:02 UTC, MatthewMiddlehurst commented
> Hi! Thanks for the PR, I'm wondering if that kind of content shouldn't be added as a section in the coding standard page rather than on its own. @MatthewMiddlehurst do we consider type hint as a standard or simply a good practice?

I think see where this ends up then decide

2024-12-07 12:46 UTC, krushndayshmookh commented
I think this should be enforced as a standard to ensure consistent typing as tooling support is important to ensure code quality.

2024-12-07 14:47 UTC, MatthewMiddlehurst approved these changes

2024-12-07 14:47 UTC, merged