[MNT] Tags using enums #2235
aeon-toolkit/aeon pull request #2437
Opened 2024-12-10 19:14 UTC by lucifer4073

### Reference Issues/PRs  
Addresses a portion of #2235. 

### What does this implement/fix?  
This PR replaces string values in `_tags` with their corresponding Enum values in the Clustering module. These changes improve maintainability and reduce errors by standardizing tag values across the module.  

Key points:  
- Algorithm types can now be directly referenced using the Enum class.  
- Data structures and Python dependencies utilize `Enum.value` for consistency.  
- Changes applied across all clustering submodules containing tags.  
- Dependent modules will require refactoring if direct Enum usage is extended.  

### Does your contribution introduce a new dependency?  
No   

### Any other comments?  
This change represents a significant milestone in transitioning to Enum-based tags. Approval for this approach in the Clustering module will allow for escalation to other modules.  

Some examples of usage:  
```python  
_tags = {  
    "capability:multivariate": True,  
    "algorithm_type": ClusteringAlgorithmType.DISTANCE,  
}  

tags = {  
    "capability:multivariate": True,  
    "capability:multithreading": True,  
    "python_dependencies": ClusteringAlgorithmType.TSLEARN.value,  
}  
```

### PR checklist

##### For all contributions
- [x] @all-contributors please add @lucifer4073 
- [x] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

2024-12-12 15:20 UTC, MatthewMiddlehurst requested changes
This seems a lot clunkier that just strings at first glance, not sure I'm a fan currently.

2024-12-12 15:20 UTC, MatthewMiddlehurst commented on aeon/clustering/_clustering_tags.py
I would not do this in the clustering module, it should be more integrated with the other tags stuff in `aeon/utils/tags`.

2024-12-12 15:20 UTC, MatthewMiddlehurst commented on aeon/clustering/_clustering_tags.py
> +    TSFRESH = "tsfresh"
I would not do it for these even if this goes through.

2024-12-12 17:16 UTC, chrisholder requested changes

2024-12-12 17:16 UTC, chrisholder commented on aeon/clustering/_clustering_tags.py
> +class ClusteringAlgorithmType(Enum):
This should just be called "AlgorithmType". We can use it for all modules in the future.

2024-12-12 17:16 UTC, chrisholder commented on aeon/clustering/_clustering_tags.py
> +        Python Dependencies:
I agree with Matt Im not sure if the dependencies tag is useful? Happy for further discussion.

2024-12-17 10:16 UTC, lucifer4073 commented
Hi @MatthewMiddlehurst @chrisholder, I have made the required changes as commented.

Since I have shifted the enum_tags.py to utils module it seems to have a circular import issue for the given test case.

Test case:   `PR Examples / run-notebook-examples (pull_request) Failing after 7m`

Error:
`ImportError: cannot import name 'BASE_CLASS_REGISTER' from partially initialized module 'aeon.utils.base' (most likely due to a circular import) (/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/aeon/utils/base/__init__.py)`

I propose to keep it currently in the clustering module or maybe I would need some help to resolve the error.

2024-12-17 10:21 UTC, lucifer4073 commented on aeon/clustering/_clustering_tags.py
> +class ClusteringAlgorithmType(Enum):
Yes did that

2024-12-17 10:22 UTC, lucifer4073 commented on aeon/clustering/_clustering_tags.py
> +        Python Dependencies:
Removed the dependencies tag

2024-12-17 10:23 UTC, lucifer4073 commented on aeon/clustering/_clustering_tags.py
> +    TSFRESH = "tsfresh"
Will be using strings for python dependencies.

2024-12-31 18:41 UTC, TonyBagnall commented
I think this issue requires some discussion before progressing, as its not obvious how best to do this and the changes, whilst under the hood, are fairly significant in terms of design

2025-03-23 17:43 UTC, MatthewMiddlehurst commented
I thought the closure above was an accident from the force push, but maybe not. Closing for now as theres no more discussion.

2025-03-23 17:43 UTC, closed without merging