[MNT, ENH, DOC] Rework similarity search
aeon-toolkit/aeon pull request #2473
Opened 2024-12-26 19:00 UTC by baraline

#### Reference Issues/PRs
Fixes #2341, #2236, #2028, #2020, #1806

#### What does this implement/fix? Explain your changes.

The previous structure for similarity search was not in line with the structure we would expect considering other aeon modules, the lack of distinct base classes for some tasks, as well as the initial design choice (due to the lack of practical experience with using and expanding the module) lead to some really complex code when working on #2341 to make everything work together. Further expanding the module would have made thing worse.

To make the module more flexible and comprehensible, the following rework is proposed in this PR (AEP to be updated acordingly):
- Focus the module on two distinct tasks : `find_neighbors` and `find_motifs` for all type for similarity search estimators
- Distinguish between two kind of similarity search tasks with the two submodules, `SeriesSearch` and `SubsequencesSearch`. The `SubsequencesSearch` focuses on tasks for which the goal is to find motifs or neighbors in subsequences of time series (e.g. Matrix Profiles, Motiflets, etc.). the `SeriesSearch` focuses on task using whole series (e.g. Indexes such as LSH, iSAX, etc.)
- Keep the flexibility of the `k`, `threshold` and `inverse_distance` parameters to customise search outputs
- Have base classes for families of method to limit code duplication (e.g. `BaseMatrixProfile`, and STOMP, where most existing code was ported)

#### Does your contribution introduce a new dependency? If yes, which one?

No.

#### Any other comments?

As this is still a WIP, I would love some inputs on the structure (notably from @patrickzib !) to make the module more future-proof to future additions and easier to use.

### TODO list :
- [ ] Finish to include testing suite for base estimators in the testing module for the `SubsequenceSearch` part
- [ ] Implement LSH index as a simple first case for `BaseIndexSearch`
- [ ] Implement tests for `SeriesSearch` base class and estimators
- [ ] Update API docs / doc pages 
- [ ] Update notebooks
- [ ] updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.

2025-01-02 13:53 UTC, patrickzib commented
Thank you very much for working on this. 

Some thoughts:

> * Focus the module on two distinct tasks : `find_neighbors` and `find_motifs` for all type for similarity search estimators. Similarly to the `fit`/ `predict` interface we already know well, here, we first `fit` and then either `find_motifs` or `find_neighbors` ("predict" keyword don't make much sense here). We give a collection to use as database in `fit`, and a single series in `find_neighbors` or `find_motifs` to use as query for the search.

That is an interesting problem. Here is my view:

For *whole series similarity search* fit requires a dataset of time series of equal length, and find_neighbors would get one or many query series of this length.

For *subsequence similarity search* fit requires a single time series, and find_neighbors commonly gets a single query sequence which length is shorter than the single series length. It would be fine however, to extend it to multiple short sequences.

There is only one *whole series consensus motif search* paper, which would be the use case of whole matching and motif discovery. The input to fit would be the whole dataset, and find_motif has no input series X. not sure, what an input series X should trigger.

Most papers solve the problem of *motif discovery* in a single long time series, defined as subsequences of the time series. Here, fit gets a single series, and find_motif has no input series X.

> * Distinguish between two kind of similarity search tasks with the two submodules, `SeriesSearch` and `SubsequencesSearch`. The `SubsequencesSearch` focuses on tasks for which the goal is to find motifs or neighbors in subsequences of time series (e.g. Matrix Profiles, Motiflets, etc.). the `SeriesSearch` focuses on task using whole series (e.g. Indexes such as LSH, iSAX, etc.)


> * Have base classes for families of method to limit code duplication (e.g. `BaseMatrixProfile`, and STOMP, where most existing code was ported), so the we can focus on implementing the computational logic when adding new estimators.

What is the difference between BaseMatrixProfile and STOMP?

At least for Motiflets, we cannot use STOMP/MP, as it only gives a 1-NN profile, but we need k-NN profiles. Same problem would be the case, if you want to solve  k-nearest neighbors similarity search.




> #### Questions to answers for motif search :
> * Do we want to make providing `X` optional in `find_motifs` ? Providing X means that we search for subsequences in X that are motifs in the collection given in `fit`. Not providing X would mean that we search for motifs in the collection given in `fit` only. I think it would make sense to make it optional, but would love some comment from people actually doing motif discovery.
> 

I think that X is not meaningful for motif discovery.

> #### Does your contribution introduce a new dependency? If yes, which one?
> No.
> 
> #### Any other comments?
> As this is still a WIP, I would love some inputs on the structure (notably from @patrickzib !) to make the module more future-proof to future additions and easier to use.
> 
> ### TODO list :
> * [x]  Finish to include testing suite for base estimators in the testing module for the `SubsequenceSearch` part and fix them
> * [ ]  Implement LSH index as a simple first case for `BaseIndexSearch`
> * [ ]  Implement tests for `SeriesSearch` base class and estimators
> * [ ]  Update API docs / doc pages
> * [ ]  Update notebooks
> * [ ]  Check docstrings
> * [ ]  Cleanup TODOs in the code
> * [ ]  updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.

2025-01-02 14:20 UTC, baraline commented
Thanks for the inputs @patrickzib😄

> For *whole series similarity search* fit requires a dataset of time series of equal length, and find_neighbors would get one or many query series of this length.

Completely in line with this, but what about the case of unequal length series, with, for example, elastic distance measures? Wouldn't that be a plausible use case?

> For *subsequence similarity search* fit requires a single time series, and find_neighbors commonly gets a single query sequence which length is shorter than the single series length. It would be fine however, to extend it to multiple short sequences.

For this case, I'm defining a length parameter during ``__init__``, and accept a 2D subsequence of shape ``(n_channels, length)`` for ``find_neighbors``, ensuring that ``length`` is not bigger than the length of any series given in `fit`. However, any reason why you think we should restrain ourselves to a single series for `fit` ? 

> There is only one whole series consensus motif search paper, which would be the use case of whole matching and motif discovery. The input to fit would be the whole dataset, and find_motif has no input series X. not sure, what an input series X should trigger.

This is the tricky one for me too. I'm not sure how giving `X` during `find_motifs` on whole series would fit any use case.

> Most papers solve the problem of motif discovery in a single long time series, defined as subsequences of the time series. Here, fit gets a single series, and find_motif has no input series X.

I've been kinda frustrated by this limitation for practical use cases, wouldn't it be fine to loop on series of a collection with the motif discovery methods and then merge the results ? That's how I implemented STOMP for now for example. For each subsequence in `X`, it computes the distance profile to all series in a collection, and keep the top `k` among all of them (also storing the sample ID and timepoint ID).

> What is the difference between BaseMatrixProfile and STOMP?
> At least for Motiflets, we cannot use STOMP/MP, as it only gives a 1-NN profile, but we need k-NN profiles. Same problem would be the case, if you want to solve k-nearest neighbors similarity search.

`BaseMatrixProfile` is simply a base class that defines abstract `compute_matrix_profile` and `compute_distance_profile` methods to be implemented by child classes such as STOMP and the likes (STUMP, etc...). 

The logic for finding neighbors / motifs is then handled in the `BaseSubsequenceSearch`.
As stated above, I already extended STOMP to support k-NN profiles for collections (multivariate and unequal length compatible).

I suppose that in this context, motiflets would either inherit from `BaseMatrixProfile` if you need to implement methods like  `compute_matrix_profile` and `compute_distance_profile`. Otherwise, It would inherit from `BaseSubsequenceSearch` and make its own methods to answer the `find_neighbors`/`find_motifs` tasks. (I would need to read the paper again!)

Note that it's possible to simply raise a "NotImplementedError" or something similar if a method only supports neighbors or motifs search.

My goal here is to find a base class structure that enables us to move most common code to there and focus on the computational optimisations of each method in the child classes.

2025-01-02 16:13 UTC, patrickzib commented
> Completely in line with this, but what about the case of unequal length series, with, for example, elastic distance measures? Wouldn't that be a plausible use case? (all whole series estimators don't have to support it)

Sure. I  did not think of this. 

> > For _subsequence similarity search_ fit requires a single time series, and find_neighbors commonly gets a single query sequence which length is shorter than the single series length. It would be fine however, to extend it to multiple short sequences.
> 
> For this case, I'm defining a length parameter during `__init__`, and accept a 2D subsequence of shape `(n_channels, length)` for `find_neighbors`, ensuring that `length` is not bigger than the length of any series given in `fit`. However, any reason why you think we should restrain ourselves to a single series for `fit` ?

Simplicity :) But I agree that you could have multiple series in fit, too - this would mimic the Shapelet use case, I suppose?

> > Most papers solve the problem of motif discovery in a single long time series, defined as subsequences of the time series. Here, fit gets a single series, and find_motif has no input series X.
> 
> I've been kinda frustrated by this limitation for practical use cases, wouldn't it be fine to loop on series of a collection with the motif discovery methods and then merge the results ? That's how I implemented STOMP for now for example. For each subsequence in `X`, it computes the distance profile to all series in a collection, and keep the top `k` among all of them (also storing the sample ID and timepoint ID).

Sorry, yes, that is what the authors refer to as consensus motif:
https://www.cs.ucr.edu/~eamonn/consensus_Motif_ICDM_Long_version.pdf


> `BaseMatrixProfile` (which inherit `BaseSubsequenceSearch`) is simply a base class that defines abstract `compute_matrix_profile` and `compute_distance_profile` methods to be implemented by child classes such as STOMP and the likes (STUMP, etc...). 

I see. I personally do not like to use the terms matrix-profile for simple k-NN distances or k-NN indices though. It was a brilliant re-framing of EK, such that all 1-NN algorithms are now suddenly an instance of matrix profile. Yet, the concept is much older.

> As stated above, I already extended STOMP to support k-NN profiles for collections (multivariate and unequal length compatible).

Great. 


> > I think that X is not meaningful for motif discovery.
> 
> In the context of motif search in a single series I agree, but wouldn't there be some interest when dealing with a collection ? For example find motifs in the collection at the condition that they are similar to a subsequence in X ? (This is pure speculation)

I would not say that this is impossible, but I have not seen it. :)

2025-01-02 16:23 UTC, baraline commented
> I see. I personally do not like to use the terms matrix-profile for simple k-NN distances or k-NN indices though. It was a brilliant re-framing of EK, such that all 1-NN algorithms are now suddenly an instance of matrix profile. Yet, the concept is much older.

I'm not against the idea of a different naming, especially if methods labelled differently from MPs would fit in the base class without any change of parameter/interface. Would you have any proposal? Something like `BaseNeighborhoodSearch` ?

2025-01-06 11:51 UTC, patrickzib commented
> I'm not against the idea of a different naming, especially if methods labelled differently from MPs would fit in the base class without much change of parameter/interface. Would you have any proposal? Something like `BaseNeighborhoodSearch` ?

In sklearn it is simply `NearestNeighbors` ? :) And it returns indices and distances. 

https://scikit-learn.org/1.5/modules/neighbors.html

2025-02-01 13:07 UTC, baraline commented
I'll leave the implementation of `k-motiflets` for later as a separate estimator so I can focus on getting the testing, tags and docs right for this PR to have the structure for the module set.

2025-03-04 13:13 UTC, patrickzib requested changes
Sorry, only a very brief review. I would have to test the code to give a better review, but I will be leaving for vacation...

2025-03-04 13:13 UTC, patrickzib commented on aeon/similarity_search/series/neighbors/_mass.py
> +        Wheter the subsequences should be z-normalized.
Whether

2025-03-04 13:13 UTC, patrickzib commented on aeon/similarity_search/series/neighbors/_mass.py
> +            Wheter a neighbors of a match to a query can be also considered as matches
whether

2025-03-04 13:13 UTC, patrickzib commented on aeon/similarity_search/series/neighbors/_mass.py
> +@njit(cache=True, fastmath=True)
parallel=True missing

2025-03-04 13:13 UTC, patrickzib commented on aeon/similarity_search/series/neighbors/_mass.py
> +    Compute squared distance profile between query subsequence and a single time series.
It is Euclidean Distance, right?

2025-03-04 13:13 UTC, patrickzib commented on aeon/similarity_search/series/neighbors/_mass.py
> +@njit(cache=True, fastmath=True)
parallel=true missing

2025-03-12 21:11 UTC, baraline commented on aeon/similarity_search/_base.py
> +        X : 2D np.array of shape ``(n_cases, n_timepoints)``
I just didn't find much use case for allowing 3D time series in the predict method. For example, when querying an index, you give a single time series, the same when you perform a query search with MASS, or when computing A/B MPs. 
Allowing 3D could be of interest to perform batch “predictions”, which could make sense in the indexing case, but not so much in the data mining task.

If you have some examples in mind of other input types that would be useful to support, this is not set in stone.

(None is when we perform a analysis on the data given during fit without any querying)

2025-03-12 21:17 UTC, baraline commented on aeon/similarity_search/collection/_base.py
> +            Collections of series to predict on.
Do you mean different from `BaseSimilaritySearch` fit ? 

I convert single series to 3D `(1, n_channels, n_timepoints)`, but I didn't yet add support for unequal length as there was no estimator using it.

2025-03-12 21:21 UTC, baraline commented on aeon/similarity_search/collection/motifs/__init__.py
> +"""Motif search for time series collection."""
I was aiming for something more generic than consensus motifs, simply motif discovery on a collection of time series instead on a single series. I didn't want to bind the module to one terminology. But consensus motif would be the first thing to implement in there yes !

2025-03-12 21:33 UTC, baraline commented on aeon/similarity_search/collection/neighbors/_rp_cosine_lsh.py
> +    for i in prange(X.shape[0]):
I don't think it is, just a habbit, I will test it to be sure !

2025-03-12 21:36 UTC, baraline commented on aeon/similarity_search/collection/neighbors/__init__.py
> +"""Neighbors search for time series collection."""
My idea here is that we would support both whole and subsequence search. But there might be a need for a clearer distinction between the two I agree.

For whole series estimators (example the LSH index estimator by design made for whole series), a generic wrapper to extract subsequences from the input collection would make such estimators compatible with subsequence search.

For subsequences search estimators, I am yet to find a method that is not a loop on single series nn estimators (e.g. MASS) for each series of the collection.

So maybe a submodule to split whole series/subsequence nearest neighbour search ?

2025-03-12 21:40 UTC, baraline commented on aeon/similarity_search/collection/neighbors/_rp_cosine_lsh.py
> +def _hamming_dist(X, Y):
I use it with boolean inputs indeed here as i'm using ^ operator which is bitwise, so yeah naming could be more precise

2025-03-12 21:41 UTC, baraline commented on aeon/similarity_search/series/_base.py
> +        self.reset()
I think `_preprocess_series` should check for that, will confirm

2025-03-12 21:43 UTC, baraline commented on aeon/similarity_search/series/_base.py
> +    def _check_predict_series_format(self, X):
Mostly for cheking the number of channels between fit/predict. I think I could call `_preprocess_series` also here for the ndims/type.

2025-03-12 21:46 UTC, baraline commented on aeon/similarity_search/series/_commons.py
> +    exclusion_size : int
I use the size to define the zone later on :
```python 
min(
    top_k_indexes[_current_k] + exclusion_size,
    len(dist_profile),
)
max(top_k_indexes[_current_k] - exclusion_size, 0)
```
or is the exclusion zone parameter referring to this +/- directly in the litterature?

2025-03-12 21:47 UTC, baraline commented on aeon/similarity_search/series/neighbors/_mass.py
> +@njit(cache=True, fastmath=True)
We cannot parallelise MASS (I think ?), I used pranges out of habbit, will check if it changes anything.

2025-03-12 21:48 UTC, baraline commented on aeon/similarity_search/series/neighbors/_mass.py
> +    Compute squared distance profile between query subsequence and a single time series.
Yes, missing from documentation

2025-03-12 21:48 UTC, baraline commented on aeon/similarity_search/series/neighbors/_mass.py
> +@njit(cache=True, fastmath=True)
Same comment for MASS parallelisation.

2025-03-12 21:50 UTC, baraline commented on aeon/similarity_search/series/neighbors/_mass.py
> +                p = min(p, 1.0)
I don't remember, that's copied from previous code.

I'll try to find again why, i'm sure there is a good reason

2025-03-15 13:15 UTC, baraline commented on aeon/similarity_search/collection/neighbors/__init__.py
> +"""Neighbors search for time series collection."""
Another way to put it is that the module is split by input types (single series and collections) rather than by task. Then, submodules like `neighbors` implement estimators that perform these tasks for the given input type.

If an estimator works for both cases (`series` and `collection`), we would only implement it in `collection` and convert single series into collections.

2025-03-15 13:22 UTC, baraline commented on aeon/similarity_search/collection/neighbors/_rp_cosine_lsh.py
> +    for i in prange(X.shape[0]):
It is equivalent, so I've reverted back to range

2025-03-15 13:40 UTC, baraline commented on aeon/similarity_search/series/_base.py
> +        self.reset()
`_preprocess_series` perform this check

2025-03-15 13:44 UTC, baraline commented on aeon/similarity_search/series/_base.py
> +    def _check_predict_series_format(self, X):
`_preprocess_series` is also called during predict, so I adjusted the check

2025-03-15 13:59 UTC, baraline commented on aeon/similarity_search/series/neighbors/_mass.py
> +                p = min(p, 1.0)
Found it in all other MASS codes, but not in the paper, so I'm not 100% sure

2025-03-17 18:25 UTC, MatthewMiddlehurst reviewed
Some comments for the bits outside the actual module itself. I will have a look at the rest as well, but generally trust you and Patrick agree on something sensible together. Let me know if any of this contradicts a previous review.

2025-03-17 18:25 UTC, MatthewMiddlehurst commented on docs/getting_started.md
> +  or collections.
There is an example on this page which is now outdated.

2025-03-17 18:25 UTC, MatthewMiddlehurst commented on aeon/utils/tags/_tags.py
> +        "class": ["transformer", "similarity-search"],
I would update the description this is needed for more than transformers now

2025-03-17 18:25 UTC, MatthewMiddlehurst commented on aeon/utils/numba/general.py
> +def compute_mean_stds_collection_parallel(X):
Thanks for updating the list at the top, I think this one is still missing though? Alternatively should be protected

2025-03-17 18:25 UTC, MatthewMiddlehurst commented on aeon/utils/numba/general.py
> +def compute_mean_stds_collection_parallel(X):
Not required here but helpful: updating the utils API page where relevant

2025-03-17 18:25 UTC, MatthewMiddlehurst commented on aeon/utils/discovery.py
> +        "similarity_search"
I wouldn't think we want to ignore these. All of these are essentially empty of estimators or for testing only.

2025-03-17 18:25 UTC, MatthewMiddlehurst commented on docs/api_reference/utils.rst
> -    MockSimilaritySearch
This is missing the two new ones

2025-03-17 18:25 UTC, MatthewMiddlehurst commented on aeon/testing/mock_estimators/__init__.py
> -    "MockSimilaritySearch",
Missing the two new ones

2025-03-31 11:16 UTC, patrickzib commented on aeon/similarity_search/collection/_base.py
> +class BaseCollectionSimilaritySearch(BaseCollectionEstimator, BaseSimilaritySearch):
Maybe add typical use cases to the description of the template classes?

2025-03-31 12:16 UTC, baraline commented on aeon/similarity_search/series/motifs/_stomp.py
> +            Available methods are "r_motifs" and "k_motifs". "r_motifs" means we rank
Improved docstring to clear confusion

2025-03-31 12:29 UTC, baraline commented on aeon/similarity_search/series/motifs/_stomp.py
> +        exclusion_factor : float, default=1.
Replaced by multiplication instead of division in all occurences

2025-04-12 21:16 UTC, MatthewMiddlehurst reviewed
Base class comments

2025-04-12 21:16 UTC, MatthewMiddlehurst commented on aeon/similarity_search/collection/tests/test_base.py
> +    X_1D = make_example_1d_numpy()
I would use the test data dict in testing. There are a lot more potential inputs than this IMO.

2025-04-12 21:16 UTC, MatthewMiddlehurst commented on aeon/similarity_search/series/_base.py
> +        self.n_timepoints_ = X.shape[1]
We also have a `self.metadata_` here.

2025-04-12 21:16 UTC, MatthewMiddlehurst commented on aeon/similarity_search/series/_base.py
> +        self.X_ = X
This is likely going to be awful for pickling unless it is actually required for every approach

2025-04-12 21:16 UTC, MatthewMiddlehurst commented on aeon/similarity_search/series/_base.py
> +            )
I'd say use `_check_shape` again but it looks like we dont have one

2025-04-12 21:16 UTC, MatthewMiddlehurst commented on aeon/similarity_search/series/_base.py
> +        """
Like `self.X_` I dont think this should be here unless its used by everything, in which case the parameter should be more integrated into the base class.

2025-04-12 21:16 UTC, MatthewMiddlehurst commented on aeon/similarity_search/series/_base.py
> +            X = self.X_
If you have to save a model you dont really want to save the training data in most cases which this forces. If you want to keep the optimisation have a `fit_predict` probably.

2025-04-15 18:43 UTC, baraline commented on aeon/similarity_search/collection/_base.py
> +        # Store minimum number of n_timepoints for unequal length collections
Rather something I forgot here, I'm not sure if that kind of operation is not best left to child classes when the base class support both cases.

2025-04-15 18:48 UTC, baraline commented on aeon/similarity_search/collection/_base.py
> +            )
Agreed on the collection/2d side, but I don't think preprocess collections checks for consistency between number of channels between fit and predict ?

2025-04-15 18:55 UTC, baraline commented on aeon/similarity_search/collection/tests/test_base.py
> +    X_1D = make_example_1d_numpy()
Switched to use _get_datatypes_for_estimator and FULL_TEST_DATA_DICT

2025-04-15 18:59 UTC, baraline commented on aeon/similarity_search/series/_base.py
> +        self.X_ = X
Likely need to keep X_ for anything as you need to compare the fit series to the predict series, I'm not sure there is an alternative to storing it if that what you meant.

2025-04-15 19:02 UTC, baraline commented on aeon/similarity_search/series/_base.py
> +        self.n_timepoints_ = X.shape[1]
added timepoint index with axis as it is not stored in metadata

2025-04-15 19:04 UTC, baraline commented on aeon/similarity_search/series/_base.py
> +            )
You mean to ensure same number of channels between fit and predict as in collection right ? Can raise an issue so we add the check to BaseAeon later

2025-04-15 19:07 UTC, baraline commented on aeon/similarity_search/series/_base.py
> +        """
It will be used for nearly all series/neighbors estimators, the X_ is similar to storing the fit data for a KNN, I don't think there is a way around it in this context

2025-04-15 19:08 UTC, baraline commented on aeon/similarity_search/series/_base.py
> +        """
The solution would be to have a base class for series/neighbors estimators for the _check_X_index function I guess ?

2025-04-15 19:11 UTC, baraline commented on aeon/similarity_search/series/_base.py
> +            X = self.X_
removed that and made a fit_predict

2025-04-15 19:39 UTC, baraline commented
Based on your comment @MatthewMiddlehurst, I think another set of base class for neighbours / motifs estimator is necessary to not have weird thing in the series & collection base classes. 
I wanted to avoid creating too many bases classes, but it seems necessary to have "cleaner" ones.
I'll put it in place and then you can check back it that feels better

2025-04-19 23:35 UTC, baraline commented
Tried to make additional base classes, but this made the whole module structure feel too overcomplicated. Reverted and instead factored some functions away from the base class and made a fit_predict for stomp to avoid the weird X=None possibility in predict. Open to suggestions if you have some

2025-04-30 12:46 UTC, MatthewMiddlehurst commented on aeon/similarity_search/series/_base.py
> +            )
Yeah should raise an issue or you can just add it here. Not sure why its in one base class and not the other.

2025-04-30 12:58 UTC, MatthewMiddlehurst commented
Its all experimental. Better to just get it in when clear issues are resolved then iterate.

2025-04-30 13:08 UTC, MatthewMiddlehurst commented
It is also possible I am misunderstanding the goal a bit. If you want to do something that fits a collection and predicts on a series, we probably need a new base class for that. The collection and series bases are not really built for it. Not saying has to be done in this PR, but probably where we want to end up.

2025-05-01 14:29 UTC, baraline commented on aeon/similarity_search/series/_base.py
> +            )
Raised issue #2768

2025-05-01 14:39 UTC, baraline commented on aeon/similarity_search/series/_base.py
> +        self.n_timepoints_ = X.shape[timepoint_idx]
I'm can't seem to find a n_timepoints in the metadata stored by BaseSeriesEstimator, so I guess this also need an issue, raised #2769

2025-05-01 14:41 UTC, baraline commented
I think we need to explore this a bit further down the road when more estimators are added to see if it would really fit a use case. 
This could also be solved with a simple wrapper like `predict_series` calling `self.predict([X])`, but let's give it some thought first agree.

2025-05-01 14:43 UTC, baraline commented on aeon/similarity_search/collection/_base.py
> +            )
Added reference to this in #2768, but maybe this function should be integrated in the base class somehow and not left as a standalone. We can discuss that on the issue.

2025-05-08 13:02 UTC, MatthewMiddlehurst approved these changes
This is too big to reasonably review just looking at the code and text. Generally I'm fine with the changes, and the module is experimental so stuff can be modified and removed as required. No one has raised any major objections in the duration of this PR.

In the future I would like to see some generic testing added to make sure these adhere so some structure.

2025-05-09 18:37 UTC, baraline commented
Agreed, will resume work on this module during summer when things cool down, and testing will definitly be an important part of the work

2025-05-10 07:05 UTC, merged