[ENH] New data loaders
aeon-toolkit/aeon pull request #253
Opened 2023-04-04 13:09 UTC by TonyBagnall

the data loaders in datasetys/_data_io.py are a mess, with several changes back and forward, and lots of old code written to comply with python versions we dont have to support any more. 

The standard way is to load everything into nested datatframes, then allow the classifiers to sort it out. In the move away from nested data frames, I have started a rewrite. The basic approach I want is to load into a list of numpy, that can then be converted to 3D numpy if equal length, otherwise left as list of numpy. 

I still need to tidy this up a bit. Ive put in a separate file for now. But its clearly better. For example, when loading FaceDetection
http://timeseriesclassification.com/description.php?Dataset=FaceDetection
```python
from aeon.datasets._data_loader import _load_data, _load_header_info, load_from_tsfile
from aeon.datasets._data_io import load_from_tsfile_to_dataframe
file ="C:\\Data\\FaceDetection\\FaceDetection_TRAIN.ts"
import time
from aeon.datasets._data_io import load_from_tsfile_to_dataframe
start=time.time()
data, y = load_from_tsfile_to_dataframe(file)
print(" Dataframe load = ",time.time()-start)

start=time.time()
data, y, meta_data = load_from_tsfile(file)
print(" Numpy load = ",time.time()-start)
```
loading into data frames gives warnings 

![image](https://user-images.githubusercontent.com/9594042/229801620-c5e53ab8-e686-4d88-b323-b2e792fe6d27.png)

and is much slower

![image](https://user-images.githubusercontent.com/9594042/229801747-66db6e99-8a8f-49aa-8f5a-a103e039a748.png)

2023-04-04 13:20 UTC, TonyBagnall commented
its about three times faster on the univariate data, but the most important thing is to move away from nested_univ

2023-04-04 14:16 UTC, TonyBagnall commented
also first loads direct to numpy and passes that to the classifier, second loads to DF and passes that to the classifier, which will then convert it to numpy. 
 Numpy rocket build =  213.1187698841095
 Dataframe rocket load =  723.0161702632904
thats three times slower, just because of base class nonsense! 

```python
    problem = "FaceDetection"
    start = time.time()
    data, y, meta_data = load_from_tsfile(f"{file}{problem}/{problem}_TRAIN.ts")
    print(" Numpy load = ", time.time() - start)
    print(" Shape of data = ", data.shape)
    print(" Building rocket .....")
    r = RocketClassifier()
    start = time.time()
    r.fit(data, y)
    print(" Numpy rocket build = ", time.time() - start)
    start = time.time()
    data, y = load_from_tsfile_to_dataframe(f"{file}{problem}/{problem}_TRAIN.ts")
    print(" Dataframe load = ", time.time() - start)
    print(" Building rocket .....")
    r = RocketClassifier()
    start = time.time()
    r.fit(data, y)
    print(" Dataframe rocket build= ", time.time() - start)

2023-04-06 12:30 UTC, patrickzib commented
Nice. How would this affect classifiers that cannot handle lists of numpy arrays?

> The basic approach I want is to load into a list of numpy, that can then be converted to 3D numpy if equal length, otherwise left as list of numpy.

Not sure, if I understand correctly: does it automatically converted to 3d numpy array in case of equal length?

2023-04-12 20:55 UTC, chrisholder requested changes

2023-04-12 20:55 UTC, chrisholder commented on aeon/datasets/_data_loader.py
> +    ----------
Comment style needing types for parameters and return

2023-04-12 20:55 UTC, chrisholder commented on aeon/datasets/_data_loader.py
> +    Parameters
same change here comment style

2023-04-12 20:55 UTC, chrisholder commented on aeon/datasets/_data_loader.py
> +
Parameters + return

2023-04-13 09:32 UTC, TonyBagnall commented on aeon/datasets/_data_loader.py
> +    ----------
done

2023-04-13 09:32 UTC, TonyBagnall commented on aeon/datasets/_data_loader.py
> +
done

2023-04-13 16:14 UTC, chrisholder approved these changes

2023-04-13 19:02 UTC, merged