refactor _threads_to_use to _n_jobs
aeon-toolkit/aeon pull request #377
Opened 2023-05-03 19:16 UTC by TonyBagnall

#### Reference Issues/PRs

fixes #102 

#### What does this implement/fix? Explain your changes.

Simple refactor of _n_threads_to_use to _n_jobs

2023-05-04 21:10 UTC, MatthewMiddlehurst requested changes

2023-05-04 21:10 UTC, MatthewMiddlehurst commented on setup.cfg
> -    -n auto
The classic

2023-05-05 07:46 UTC, patrickzib commented
Hey @TonyBagnall , thanks a lot for touching these again! It is a monster.

I am afraid we are not there yet. There are quite a few classes using `self.n_jobs`. 

For the base classes, I do not even understand where the variable `self.n_jobs` was set (possibly being a bug?):

- Clustering: https://github.com/aeon-toolkit/aeon/blob/e7e4592f6135f4fe3c5cb220a60541002719ec5f/aeon/clustering/base.py#L71

- Classification:  https://github.com/aeon-toolkit/aeon/blob/e7e4592f6135f4fe3c5cb220a60541002719ec5f/aeon/regression/base.py#L153

- Regression: https://github.com/aeon-toolkit/aeon/blob/e7e4592f6135f4fe3c5cb220a60541002719ec5f/aeon/regression/base.py#L153


IMO: it would be best to refactor all occurrences of `self.n_jobs` to `self._n_jobs`, too, and there are > 100 occurrences of self.n_jobs :/

2023-05-05 07:50 UTC, patrickzib commented
Sorry, if I am missing something. But how is `self.n_jobs` initialized in these base classes?

2023-05-05 08:00 UTC, TonyBagnall commented on setup.cfg
> -    -n auto
every. bloody. time. :)

2023-05-05 08:16 UTC, patrickzib commented
If we agree on something that is meaningful, I can pick it up and do the changes to the estimators.

Could you explain the logic behind self.n_jobs for me? It seems like a FK twist.

Right now, it seems like every estimator has to set `self.n_jobs` from the same parameter passed to the class - next, each base-class checks  `self.n_jobs` and sets it to `self._n_jobs`. Yet, most classifiers still use `self.n_jobs`, as they are not aware, that the base class set `self._n_jobs`.

2023-05-05 10:12 UTC, MatthewMiddlehurst commented
This was actually me. I put it in the base class to avoid coping the check method in every estimator. I feel having a method will just run into the same issue of people using the estimator `self.n_jobs` over it.

Can either make people process `self.n_jobs` in their own estimator, or just document better/mention it in reviews.

2023-05-05 10:59 UTC, TonyBagnall commented
> 

I dont feel too strongly about it, but I think it should probably all be dealt with in the base class and also be a base class parameter. That or take it out of base class, its neither one nor the other at the moment.

2023-05-05 11:00 UTC, TonyBagnall commented
> 

if we defaulted it to None in the base class it would then fail tests if people reset it in their subclasses?

2023-05-11 12:57 UTC, TonyBagnall commented
what do you think @patrickzib ? Do this PR now and sort out later or close this PR and fix all together? I'm fine either way, I just dont like PRs having around :)

2023-06-02 12:50 UTC, MatthewMiddlehurst commented
I think we should merge this and create a separate issue to convert classifiers/regressors which use `self.n_jobs`. I think the new name is better.

It's difficult to enforce the usage of `check_n_jobs`/`self._n_jobs` other than by review and documentation IMO. I think the current base class way works fine in reducing the amount of copied boilerplate, it just has a bad name.

2023-06-02 12:51 UTC, MatthewMiddlehurst commented
Can go through each estimator and change it in this PR also, I don't mind. Not sure how much work/extra file changes that would be though.

2023-06-03 17:01 UTC, MatthewMiddlehurst approved these changes

2023-06-03 19:05 UTC, merged