Refactor sax
aeon-toolkit/aeon pull request #417
Opened 2023-05-11 15:40 UTC by hadifawaz1999

#### Reference Issues/PRs

#### What does this implement/fix? Explain your changes.

#### Does your contribution introduce a new dependency? If yes, which one?

#### What should a reviewer concentrate their feedback on?

#### Did you add any tests for the change?

#### Any other comments?

### PR checklist

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.
- [ ] For new estimators, I've added the estimator to the online documentation.

2023-05-11 19:15 UTC, patrickzib requested changes
Nice. Thank you. WOuld be even better if we used @njit and/or numpy methods like `np.digitize`

2023-05-11 19:15 UTC, patrickzib commented on aeon/transformations/panel/dictionary_based/_sax.py
> +        self.breakpoints, self.breakpoints_mid = self._generate_breakpoints(
Why are breakpoints generated in transform? Shouldn't this be done once in the constructor and then the same breakpoints are used in transform?

2023-05-11 19:15 UTC, patrickzib commented on aeon/transformations/panel/dictionary_based/_sax.py
> +    def _get_sax_symbols(self, X_paa):
add @njit to it?

2023-05-11 19:15 UTC, patrickzib commented on aeon/transformations/panel/dictionary_based/_sax.py
> +    def _inverse_sax_symbols(self, sax_symbols, series_length):
Could you add documentation to the method?

2023-05-11 19:15 UTC, patrickzib commented on aeon/transformations/panel/dictionary_based/_sax.py
> +    def _get_sax_symbols(self, X_paa):
Could you add documentation to the method?

2023-05-11 19:15 UTC, patrickzib commented on aeon/transformations/panel/dictionary_based/_sax.py
> +        return self._inverse_sax_symbols(
Could you explain what this line does? :)

2023-05-11 19:15 UTC, patrickzib commented on aeon/transformations/panel/dictionary_based/_sax.py
> +        for i_bp, bp in enumerate(self.breakpoints):
Is this the same as: `np.digitize`?
https://numpy.org/doc/stable/reference/generated/numpy.digitize.html

2023-05-11 19:20 UTC, hadifawaz1999 commented on aeon/transformations/panel/dictionary_based/_sax.py
> +        self.breakpoints, self.breakpoints_mid = self._generate_breakpoints(
Yes you are right did not think of that, thanks for noting that out

2023-05-11 19:22 UTC, hadifawaz1999 commented on aeon/transformations/panel/dictionary_based/_sax.py
> +    def _get_sax_symbols(self, X_paa):
Actually there is a version with numba usage njit, its [this commit](https://github.com/aeon-toolkit/aeon/pull/417/commits/eb18f88bb6f00b56fc1a3595cdf334892672ed7f), i did a time analysis on this commit and without using numba, it didnt change the time or make it any faster. The only thing is the code becomes with a lot of details not needed so i decided to drop njit, what do you think ?

2023-05-11 19:22 UTC, hadifawaz1999 commented on aeon/transformations/panel/dictionary_based/_sax.py
> +    def _inverse_sax_symbols(self, sax_symbols, series_length):
will do

2023-05-11 19:24 UTC, hadifawaz1999 commented on aeon/transformations/panel/dictionary_based/_sax.py
> +        return self._inverse_sax_symbols(
basically, if SAX transforms a time series of length 10 to a series of length 5 (n_segments=5), you may need the original length back.

For example if you TS in sax form gave (a, b,a,c,c) and your original length is 10, then the inverse transform will give you (a,a,b,b,a,a,c,c,c,c) this is the idea used in tslearn, the only difference is that i use them both togethere (check return of transform function). Let me know if you prefer to keep them separated such as in tslearn implementation.

2023-05-11 19:25 UTC, hadifawaz1999 commented on aeon/transformations/panel/dictionary_based/_sax.py
> +        for i_bp, bp in enumerate(self.breakpoints):
I never heard of this function my bad :) will look into it and see if i can add it here

2023-05-11 19:27 UTC, hadifawaz1999 commented on aeon/transformations/panel/dictionary_based/_sax.py
> +    def _get_sax_symbols(self, X_paa):
will do

2023-05-11 20:06 UTC, patrickzib commented on aeon/transformations/panel/dictionary_based/_sax.py
> +        return self._inverse_sax_symbols(
I see. Never thought of that before. Could you give an example where this might be beneficial?

my personal preference would be to add a parameter that can turn this on and off, with the default being to reduce the dimensionality.

2023-05-11 20:07 UTC, patrickzib commented on aeon/transformations/panel/dictionary_based/_sax.py
> +    def _get_sax_symbols(self, X_paa):
Good point. There is so much framework going on there with the call to PAA. Would be interesting to profile your refactored class to see where most time is spent.

2023-05-11 22:02 UTC, hadifawaz1999 commented on aeon/transformations/panel/dictionary_based/_sax.py
> +    def _get_sax_symbols(self, X_paa):
my assumption is that PAA is taking too much time, my goal is to refactor it as well like i did for SAX because I noticed that the output of PAA in aeon is different than tslearn.

2023-05-11 22:50 UTC, hadifawaz1999 commented on aeon/transformations/panel/dictionary_based/_sax.py
> +        return self._inverse_sax_symbols(
Well actually when applying sax transform it generates a symbol which in this case will just be an index pointing to the breakpoint value.

For example if we have only 1 breakpoint which  is 0, if the time series value is positive it will be replaces by 1 and if it is negative it will be replaces by 0.
This is the way SAX will make the time series in a more 'digital' space instead of a continuous one.

However, you may don't want to represent each segment by an index that points to the breakpoint, maybe you want a real value to represent each segment, in this case you need to define the middle points between the breakpoints interval. For instance if your alphabet size is 2, your breakpoint will be 0 defining 2 intervals, `]-inf,0]` and `]0,+inf[`. For each segment value given by PAA we will compare the value `x` to 0, if its positive we want it to be replaced this time by a real value that represents this interval `]0,+inf[`. The formula of the calculation is taken from the `tslearn` implementation actually  and this was my understanding of the inverse function. This can be helpful where you want to represent the values of the time segment by a single real value, this value is chosen by creating the breakpoints thresholds. For example in the figure below you can see this being applied on a UCR example, its a way of going back to a continuous form but also still in an approximation form using Gaussian values. So its not completely the inverse because it is not able to give you the orignal time series of course.
![image](https://github.com/aeon-toolkit/aeon/assets/54309336/8cb7de28-3295-4fa5-a979-a155a7b93ef6)

Basically its like defining that each 10 consecutive time stamps (segment length) can be represented by one real value, kind of like a sampling theorem. This is the the way PAA does it, but going also through SAX will have the Gaussian distribution representation instead of only averaging the segment values.

Am not sure if it makes sense what I just explained, I completely understand if it doesn't because it took me some time to understand the concept of this implementation before i decided to port it in. I even have an application for it that I wanted to try, where I use a VAE to go from this discritized space to the original one, modeling it as a generative model from discrete to continuous space using SAX symbols.

But I agree it should be a parameter as you said

2023-05-12 05:45 UTC, patrickzib commented on aeon/transformations/panel/dictionary_based/_sax.py
> +        return self._inverse_sax_symbols(
Sure, I agree, it makes sense to have the inverse for visualization purposes. :) 

But if SAX is applied as a transformer, I would expect it to reduce dimensionality via PAA (i.e. without padding the length back to the original length). padding to the original length increases memory and does not add much additional information for the downstream task.

Maybe even providing two methods transform and inverse_transform might be best? Not sure how other transformers do this.

2023-05-12 05:50 UTC, patrickzib commented on aeon/transformations/panel/dictionary_based/_sax.py
> +        return self._inverse_sax_symbols(
IMO transform should return indices.

2023-05-12 10:35 UTC, hadifawaz1999 commented on aeon/transformations/panel/dictionary_based/_sax.py
> +        return self._inverse_sax_symbols(
I agree, it would be better to divide them because usually users will want the original transform for their work.

2023-05-12 10:36 UTC, hadifawaz1999 commented on aeon/transformations/panel/dictionary_based/_sax.py
> +        return self._inverse_sax_symbols(
And actually your proposal of dividing them is what is done in tslearn as well.

2023-05-12 10:36 UTC, hadifawaz1999 commented on aeon/transformations/panel/dictionary_based/_sax.py
> +        return self._inverse_sax_symbols(
will take care of that and will add documentation providing detailed explanation of the purpose of each function

2023-05-12 10:37 UTC, patrickzib commented on aeon/transformations/panel/dictionary_based/_sax.py
> +        return self._inverse_sax_symbols(
Thank you :)

2023-05-12 10:38 UTC, hadifawaz1999 commented on aeon/transformations/panel/dictionary_based/_sax.py
> +        return self._inverse_sax_symbols(
Should we add the ability for the user to choose the type of the symbols ? What if the user wants the SAX to give back a series of strings for instance. That could be handled easily from the user side but what if its better to make it internal, what do you think @patrickzib ?

2023-05-12 10:42 UTC, patrickzib commented on aeon/transformations/panel/dictionary_based/_sax.py
> +        return self._inverse_sax_symbols(
True, there are many possible return types:

- Array of Indices (Ints)
- Array of characters (String)
- Concatenated into one large binary number: One Long

In SFA, we store an array of indices internally, when a class parameter is set to TRUE, and always return the long representation of the SFA word. But it does not mean that this has to be the case always.

2023-05-12 17:00 UTC, hadifawaz1999 commented on aeon/transformations/panel/dictionary_based/_sax.py
> +        self.breakpoints, self.breakpoints_mid = self._generate_breakpoints(
it is resolved now

2023-05-12 17:00 UTC, hadifawaz1999 commented on aeon/transformations/panel/dictionary_based/_sax.py
> +    def _inverse_sax_symbols(self, sax_symbols, series_length):
all documentation is added to all functions

2023-05-12 17:00 UTC, hadifawaz1999 commented on aeon/transformations/panel/dictionary_based/_sax.py
> +        return self._inverse_sax_symbols(
its taken care of, let me know what you think

2023-05-12 17:01 UTC, hadifawaz1999 commented on aeon/transformations/panel/dictionary_based/_sax.py
> +        for i_bp, bp in enumerate(self.breakpoints):
It works perfectly in one line :) Thanks for the advise of using `np.digitize` !

2023-05-22 08:44 UTC, patrickzib commented on aeon/transformations/panel/dictionary_based/_sax.py
> +        self.breakpoints, self.breakpoints_mid = self._generate_breakpoints(
One last thought: SAX with Gaussian-breakpoints assumes that the data is z-normalized prior to transform. 

Is that taken care of? Sorry, if I miss it or it is hidden in the PAA-transform. Might be more safe to  apply zscore to the data first?

2023-05-30 10:06 UTC, hadifawaz1999 commented on aeon/transformations/panel/dictionary_based/_sax.py
> +        return self._inverse_sax_symbols(
The issue comes from the fact that the number of segments will not always divide the time series length. Given this issue, we can parametrize PAA in order to choose whether or not to discard or pad the transformation till the last time stamps ignored in the segments repartitions. This can and i think should be done in the paa refactor, and then included in the sax refactor.
Thanks for pointing this out !

2023-05-30 10:17 UTC, hadifawaz1999 commented on aeon/transformations/panel/dictionary_based/_sax.py
> +    def _inverse_sax_symbols(self, sax_symbols, series_length):
It should be good now, i emphasized about the returned symbols and what they represent, let me know if its okay

2023-05-30 10:18 UTC, hadifawaz1999 commented on aeon/transformations/panel/dictionary_based/_sax.py
> +        self.breakpoints, self.breakpoints_mid = self._generate_breakpoints(
Thanks for reminding me that, i added a parameter to choose whether or not to z-normalize the input data.

2023-05-30 10:27 UTC, patrickzib commented on aeon/transformations/panel/dictionary_based/_sax.py
> +        are supposed to be z-nromalized, i.e. the mean of each
assumed to be z-normalized
(wording and typo)

2023-05-30 10:37 UTC, patrickzib reviewed
Found some minor typos. And zscore is not totally clear to me. If the data is a 2d numpy array, it should be zscore(X, axis=1), I guess? I.e. row-wise. Or is the data assumed to be a 3d numpy array?

2023-05-30 10:37 UTC, patrickzib commented on aeon/transformations/panel/dictionary_based/_sax.py
> +        time series should b 0 and the standard deviation should be
be instead of b (typo)

2023-05-30 10:37 UTC, patrickzib commented on aeon/transformations/panel/dictionary_based/_sax.py
> +        """Transform the input time seires to PAA segments.
series (typo)

2023-05-30 10:37 UTC, patrickzib commented on aeon/transformations/panel/dictionary_based/_sax.py
> +        alphabet
what other values are supported?

2023-05-30 10:37 UTC, patrickzib commented on aeon/transformations/panel/dictionary_based/_sax.py
> +        alphabet
I.e. currently only Gaussian is supported.

2023-05-30 10:37 UTC, patrickzib commented on aeon/transformations/panel/dictionary_based/_sax.py
> +            raise NotImplementedError("still not added")
raise NotImplementedError(self.distribution, "is still not added")

2023-05-30 10:37 UTC, patrickzib commented on aeon/transformations/panel/dictionary_based/_sax.py
> +            X = scipy.stats.zscore(X, axis=2)
Sorry for asking. Isn't is axis=1? I.e. z-norm is applied for each series.

2023-05-30 10:37 UTC, patrickzib commented on aeon/transformations/panel/dictionary_based/_sax.py
> +            X = scipy.stats.zscore(X, axis=2)
(or is the input 3d?)

2023-05-30 10:37 UTC, patrickzib commented on aeon/transformations/panel/dictionary_based/_sax.py
> +    """Produce the original time series using a Gaussian estimation.
Reconstruct (?) the ...

2023-05-30 10:47 UTC, hadifawaz1999 commented on aeon/transformations/panel/dictionary_based/_sax.py
> +        alphabet
I have been meaning to test with other distributions, such as uniform for instance or beta. I can add at least 2 more now, been planning to make them step by step to avoid including a distribution that doesn't make sense to use.

2023-05-30 10:48 UTC, hadifawaz1999 commented on aeon/transformations/panel/dictionary_based/_sax.py
> +            X = scipy.stats.zscore(X, axis=2)
I assumed that aeon does an internal re-shaping, i remember that was the case in the baseClassifier, will check if its the same in transformer

2023-05-30 10:48 UTC, hadifawaz1999 commented on aeon/transformations/panel/dictionary_based/_sax.py
> +    """Produce the original time series using a Gaussian estimation.
Yes makes sense :p thanks

2023-05-30 10:49 UTC, hadifawaz1999 commented on aeon/transformations/panel/dictionary_based/_sax.py
> +        are supposed to be z-nromalized, i.e. the mean of each
thanks ! will take care of that

2023-05-30 10:52 UTC, patrickzib commented on aeon/transformations/panel/dictionary_based/_sax.py
> +        alphabet
Sure, fine. Just meant to add a docstring saying which ones are supported right now. No need to implement others. :)

2023-05-30 10:52 UTC, hadifawaz1999 commented on aeon/transformations/panel/dictionary_based/_sax.py
> +        alphabet
Oh okay, will do that then

2023-05-30 10:53 UTC, patrickzib commented on aeon/transformations/panel/dictionary_based/_sax.py
> +            X = scipy.stats.zscore(X, axis=2)
@TonyBagnall I think, we are planning to remove the reshaping for transformers and accept numpy 2d input? Or what is the current state here?

2023-05-30 10:57 UTC, hadifawaz1999 commented on aeon/transformations/panel/dictionary_based/_sax.py
> +            X = scipy.stats.zscore(X, axis=2)
yeah makes sense to put -1, this way in the future we do not edit it

2023-05-30 11:31 UTC, patrickzib approved these changes

2023-05-30 14:50 UTC, merged