[BUG] Tslearn clusterers update
aeon-toolkit/aeon pull request #457
Opened 2023-05-26 12:13 UTC by chrisholder

#### Reference Issues/PRs

#### What does this implement/fix? Explain your changes.

The tslearn clusterers want the data to be passed to them in the format (n_instances, n_timepoints, n_channels). As
we use the format (n_instances, n_channels, n_timepoints) this meant for multivariate time series these clusterers
were not working. This fix address this by adding a reshape to ensure the correct format.

#### Does your contribution introduce a new dependency? If yes, which one?

#### What should a reviewer concentrate their feedback on?

#### Did you add any tests for the change?

I updated the tests and additionally made them faster.

#### Any other comments?

### PR checklist

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc).
- [x] Optionally, I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.
- [x] For new estimators, I've added the estimator to the online documentation.

2023-05-29 08:20 UTC, TonyBagnall requested changes
need to resolve the axis swapping

2023-05-29 08:20 UTC, TonyBagnall commented on aeon/clustering/k_shapes.py
> +        _X = X.reshape((X.shape[0], X.shape[2], X.shape[1]))
I'm not sure reshape is correct here, is this always swapping axes correctly? 
```python import numpy as np
X = np.array([[[1,1,1,1],[2,2,2,2]],[[3,3,3,3],[4,4,4,4]]])
print(X.shape)
_X = X.reshape((X.shape[0], X.shape[2], X.shape[1]))
print(_X.shape)
print(_X)
X2 = np.swapaxes(X,1,2)
print(X2.shape)
print(X2)
```
gives different output
[[[1 1]
  [1 1]
  [2 2]
  [2 2]]

 [[3 3]
  [3 3]
  [4 4]
  [4 4]]]
(2, 4, 2)
[[[1 2]
  [1 2]
  [1 2]
  [1 2]]

 [[3 4]
  [3 4]
  [3 4]
  [3 4]]]

2023-05-29 11:30 UTC, chrisholder commented on aeon/clustering/k_shapes.py
> +        _X = X.reshape((X.shape[0], X.shape[2], X.shape[1]))
This is completly correct I've made this change

2023-05-29 13:13 UTC, TonyBagnall approved these changes

2023-05-29 13:14 UTC, TonyBagnall approved these changes

2023-05-30 19:19 UTC, TonyBagnall approved these changes

2023-05-30 19:19 UTC, merged