[ENH] Itakura parallelogram bounding
aeon-toolkit/aeon pull request #512
Opened 2023-06-23 18:32 UTC by chrisholder

#### Reference Issues/PRs

#### What does this implement/fix? Explain your changes.
This PR adds in a new bounding matrix technique called Itakura parallelogram. This bounding constructs a parallogram on the matrix which means there is less warping enabled at the start and end of the path and full warping allowed in the middle. 

#### Does your contribution introduce a new dependency? If yes, which one?
No

#### What should a reviewer concentrate their feedback on?

#### Did you add any tests for the change?
Yes and updated all the distances tests to ensure it is working for them all.

#### Any other comments?

### PR checklist

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc).
- [x] Optionally, I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.
- [x] For new estimators, I've added the estimator to the online documentation.

2023-07-21 11:45 UTC, TonyBagnall requested changes

2023-07-21 11:45 UTC, TonyBagnall commented on aeon/distances/_ddtw.py
> +    itakura_max_slope: float, defaults=None
fix formatting, e.g.
itakura_max_slope : float, default=None

2023-07-21 11:45 UTC, TonyBagnall commented on aeon/distances/_ddtw.py
> +        parallelogram on the bounding matrix. Must be between 0. and 1..
Must be between 0 and 1.

2023-07-21 11:45 UTC, TonyBagnall commented on aeon/distances/_ddtw.py
> +    x: np.ndarray, y: np.ndarray, window: float, itakura_max_slope: float = None
should this not have a default?

2023-07-21 11:45 UTC, TonyBagnall commented on aeon/distances/_ddtw.py
> +    itakura_max_slope: float, defaults=None
itakura_max_slope : float, default=None

2023-08-28 16:44 UTC, TonyBagnall submitted a review, later dismissed

2023-08-28 16:44 UTC, TonyBagnall commented on aeon/distances/_lcss.py
> +        Maximum slope as a % of the number of time points used to create Itakura
proportion not a percentage

2023-08-28 17:02 UTC, chrisholder commented on aeon/distances/_lcss.py
> +        Maximum slope as a % of the number of time points used to create Itakura
Right ill change that everywhere

2023-08-29 12:19 UTC, TonyBagnall approved these changes

2023-08-29 12:19 UTC, merged