Ajb/reg docs
aeon-toolkit/aeon pull request #516
Opened 2023-06-24 22:01 UTC by TonyBagnall

#### Reference Issues/PRs

part of #507 
dependent on https://github.com/aeon-toolkit/aeon/pull/513 and #514 

updates of clustering and regression notebooks and examples.md

2023-07-03 12:19 UTC, MatthewMiddlehurst requested changes
There is another clustering notebook in the `examples/` directory. Is this a duplicate or?

2023-07-03 17:40 UTC, TonyBagnall commented on examples/regression/regression.ipynb
> +{
so do you think duplicate the content of classification? It has overview of

2023-07-03 18:05 UTC, TonyBagnall commented on examples/regression/regression.ipynb
> +{
<p>not sure what happened to the rest of this, I seem to have lost content somewhere</p>

2023-07-03 18:31 UTC, MatthewMiddlehurst commented on examples/regression/regression.ipynb
> +{
This one is specific to the references section, it doesn't translate very well to GitHub 🙂

2023-07-03 18:32 UTC, MatthewMiddlehurst commented on examples/regression/regression.ipynb
> +{
But more generally no it doesnt have to be the same as classification, but currently the main cell has loading data, fitting and predicting all in one. Think it would be good to split it out into multiple cells and show some of the output.

2023-07-03 21:05 UTC, TonyBagnall commented on examples/regression/regression.ipynb
> +{
rewritten this

2023-07-03 21:05 UTC, TonyBagnall commented on examples/regression/regression.ipynb
> +{
take a look now, could still do more

2023-07-04 17:19 UTC, TonyBagnall commented
> There is another clustering notebook in the `examples/` directory. Is this a duplicate or?

duplicate, deleted

2023-07-05 10:15 UTC, MatthewMiddlehurst approved these changes

2023-07-05 10:30 UTC, merged