[BUG] Regression base class score function
aeon-toolkit/aeon pull request #549
Opened 2023-07-07 14:01 UTC by TonyBagnall

fixes #533 

I have also moved the function _internal_convert up to BaseEstimator, since identical functions are in classifier and regressor, and functionality shared with clustering (to do later)

I also added a simple test for base regressor.

2023-07-11 15:56 UTC, MatthewMiddlehurst requested changes
I feel like there should be another class between BaseEstimator and the 3 ML base classes, but not going to push that here.

2023-07-11 20:27 UTC, TonyBagnall commented on aeon/regression/base.py
> -__author__ = ["mloning", "fkiraly"]
didnt realised I had removed it! I think I am in favour of having authors, but can get excessive

2023-07-11 20:29 UTC, TonyBagnall commented on aeon/regression/base.py
> +        y = y.astype("float")
I moved the method up to base, but the base classifier convert does not insist on float, which regression does, so it is enhancing the base estimator method. Could override it I guess

2023-07-11 20:32 UTC, TonyBagnall commented on aeon/regression/base.py
> +        y = y.astype("float")
ah sorry, thats in score, yes

2023-07-11 20:39 UTC, TonyBagnall commented on aeon/regression/base.py
> +        y = y.astype("float")
at least it actually works and is tested now :)

2023-07-12 07:22 UTC, TonyBagnall commented
> I feel like there should be another class between BaseEstimator and the 3 ML base classes, but not going to push that here.

possibly bring this in with the unified validation, although dont know what to call it.

2023-07-12 15:44 UTC, MatthewMiddlehurst approved these changes

2023-07-13 13:16 UTC, merged