[DOC] Glossary rewrite
aeon-toolkit/aeon pull request #694
Opened 2023-08-25 10:08 UTC by MatthewMiddlehurst

#### Reference Issues/PRs

Resolves #601
Resolves #361  

#### What does this implement/fix? Explain your changes.

Rewrites the glossary page mostly. Removes todos and some previous used terminology.

Some sections are the same, others are completely different.

#### What should a reviewer concentrate their feedback on?

The new glossary entries.

2023-08-25 10:51 UTC, TonyBagnall requested changes

2023-08-25 10:51 UTC, TonyBagnall commented on docs/glossary.md
> +    Data with multiple individual {term}`variable` measurements with acoompanying
accompanying

2023-08-25 10:51 UTC, TonyBagnall commented on docs/glossary.md
> +    both. Also referred toas the dependent or endogenous variable(s).
toas -> to as
this does not scan very well

2023-08-25 10:51 UTC, TonyBagnall commented on docs/glossary.md
> +Independant variables
independent

2023-08-25 10:51 UTC, TonyBagnall commented on docs/glossary.md
>  Panel time series
Panel time series -> Time series panel (?)

2023-08-25 10:51 UTC, TonyBagnall commented on docs/glossary.md
> +    Commonly referred to as a {term}`panel time series` depending on context and
Commonly referred to -> Also referred to

2023-08-25 10:51 UTC, TonyBagnall commented on docs/glossary.md
> -Endogenous
Endogenous and Exogenous are common terms in forecasting

2023-08-25 10:51 UTC, TonyBagnall commented on docs/glossary.md
>      Reduction refers to decomposing a given learning task into simpler tasks that can
does this sentence end with can? May jsut be formatting view

2023-08-25 10:51 UTC, TonyBagnall commented on docs/glossary.md
>      When data shows a long-term increase or decrease, this is referred to as a trend.
When time series show

2023-08-25 10:52 UTC, TonyBagnall commented on docs/glossary.md
> +Timepoints
do we really need singular and plural listed on all of these?

2023-08-29 10:15 UTC, MatthewMiddlehurst commented on docs/glossary.md
>      Reduction refers to decomposing a given learning task into simpler tasks that can
Reduction
    Reduction refers to decomposing a given learning task into simpler tasks that can
    be composed to create a solution to the original task. In `aeon` reduction is used
    to allow one learning task to be adapted as a solution for an alternative task.

2023-08-29 10:17 UTC, MatthewMiddlehurst commented on docs/glossary.md
> +Timepoints
I imagine it helps with searching a referencing, i.e. allowing both {term}`Instance` and {term}`Instances` to link to it in the docs.

2023-08-29 17:01 UTC, TonyBagnall commented on docs/glossary.md
> -Endogenous
hmmm, seems a bit more complex than that, seems endogenous means correlated with the error and exogenous means uncorrelated, although of course error is only estimated. I dont mind ducking it

2023-08-29 20:07 UTC, MatthewMiddlehurst commented on docs/glossary.md
> -Endogenous
I'm not sure to be honest. I dont think the old ones were that much better in this regard though.

2023-09-01 18:58 UTC, TonyBagnall approved these changes

2023-09-01 18:58 UTC, merged