[ENH] Clustering module
aeon-toolkit/aeon pull request #697
Opened 2023-08-25 20:58 UTC by hadifawaz1999

This is just a template now, i want to get ideas on how the module will be like, for now i put a up the base class and will see what to add later on in it.

2023-08-28 12:48 UTC, hadifawaz1999 commented
Added an example of a deep clusterer which is an auto-encoder based on the FCN network.
By doing this i added a new network which AE-FCN (Auto-Encoder FCN) and the deep clusterer.

The auto-encoder will be trained to reconstruct the input normally and the clustering will be then evaluated in its latent space (between encoder and decoder).

The clustering evaluation uses kmeans in the latent space.

2023-10-09 08:55 UTC, TonyBagnall requested changes
structure all looks good, comments about docstrings and testing, could you aim for 100% coverage?

2023-10-09 08:55 UTC, TonyBagnall commented on aeon/clustering/deep_learning/ae_fcn.py
> +    n_clusters: int, default=None
soz for being a pedant, but you need a space between variable and colon
n_clusters : int, default=None

2023-10-09 08:55 UTC, TonyBagnall commented on aeon/clustering/deep_learning/ae_fcn.py
> +    """Fully Connected Neural Network (FCN), as described in [1].
as described in [1]_
will link it in the API

2023-10-09 08:55 UTC, TonyBagnall commented on aeon/clustering/deep_learning/ae_fcn.py
> +    FCNClassifier(...)
should be 
AEFCNClusterer

2023-10-09 08:55 UTC, TonyBagnall commented on aeon/clustering/deep_learning/ae_fcn.py
> +        In aeon, time series are stored in numpy arrays of shape (d,m), where d
could you reword this to (n_channels, n_timepoints)?

2023-10-09 08:55 UTC, TonyBagnall commented on aeon/clustering/deep_learning/ae_fcn.py
> +            The shape of the data fed into the input layer, should be (m,d).
same here

2023-10-09 08:55 UTC, TonyBagnall commented on aeon/clustering/deep_learning/ae_fcn.py
> +        X : np.ndarray of shape = (n_instances (n), n_dimensions (d), series_length (m))
n_channels and n_timepoints

2023-10-09 08:55 UTC, TonyBagnall commented on aeon/clustering/deep_learning/base.py
> +    clustering_algorithm: str, default="kmeans"
spacing wrong

2023-10-09 08:55 UTC, TonyBagnall commented on aeon/networks/ae_fcn.py
> +__author__ = ["James-Large", "AurumnPegasus", "hadifawaz1999"]
I think you are sole author of this

2023-10-09 08:55 UTC, TonyBagnall commented on aeon/networks/ae_fcn.py
> +__author__ = ["James-Large", "AurumnPegasus", "hadifawaz1999"]
I think you are sole author of this

2023-10-09 08:55 UTC, TonyBagnall commented on aeon/clustering/deep_learning/tests/test_deep_clusterer_base.py
> +__author__ = ["achieveordie", "hadifawaz1999"]
again, I think you are sole author

2023-10-09 08:55 UTC, TonyBagnall commented on aeon/clustering/deep_learning/tests/test_deep_clusterer_base.py
> +    assert dummy_deep_clr.summary() is not None
do you test _predict and _predict_proba anywhere?

2023-10-09 08:55 UTC, TonyBagnall commented on aeon/clustering/deep_learning/ae_fcn.py
> +    def _score(self, X, y=None):
do you test all this?

2023-10-22 10:18 UTC, hadifawaz1999 commented on aeon/clustering/deep_learning/ae_fcn.py
> +    n_clusters: int, default=None
fixed the docs issue everywhere

2023-10-22 10:18 UTC, hadifawaz1999 commented on aeon/clustering/deep_learning/ae_fcn.py
> +    """Fully Connected Neural Network (FCN), as described in [1].
fixed

2023-10-22 10:18 UTC, hadifawaz1999 commented on aeon/clustering/deep_learning/ae_fcn.py
> +    FCNClassifier(...)
fixed

2023-10-22 10:18 UTC, hadifawaz1999 commented on aeon/clustering/deep_learning/ae_fcn.py
> +        In aeon, time series are stored in numpy arrays of shape (d,m), where d
fixed this everywhere

2023-10-22 10:18 UTC, hadifawaz1999 commented on aeon/clustering/deep_learning/ae_fcn.py
> +            The shape of the data fed into the input layer, should be (m,d).
fixed

2023-10-22 10:19 UTC, hadifawaz1999 commented on aeon/clustering/deep_learning/ae_fcn.py
> +        X : np.ndarray of shape = (n_instances (n), n_dimensions (d), series_length (m))
fixed

2023-10-22 10:19 UTC, hadifawaz1999 commented on aeon/clustering/deep_learning/base.py
> +    clustering_algorithm: str, default="kmeans"
fixed

2023-10-22 10:19 UTC, hadifawaz1999 commented on aeon/networks/ae_fcn.py
> +__author__ = ["James-Large", "AurumnPegasus", "hadifawaz1999"]
fixed this, this is because of my copy paste of all classification code :)

2023-10-22 10:19 UTC, hadifawaz1999 commented on aeon/networks/ae_fcn.py
> +__author__ = ["James-Large", "AurumnPegasus", "hadifawaz1999"]
fixed

2023-10-22 10:19 UTC, hadifawaz1999 commented on aeon/clustering/deep_learning/tests/test_deep_clusterer_base.py
> +__author__ = ["achieveordie", "hadifawaz1999"]
fixed

2023-10-22 10:20 UTC, hadifawaz1999 commented on aeon/clustering/deep_learning/tests/test_deep_clusterer_base.py
> +    assert dummy_deep_clr.summary() is not None
i test now these 2 functions

2023-10-22 10:20 UTC, hadifawaz1999 commented on aeon/clustering/deep_learning/ae_fcn.py
> +    def _score(self, X, y=None):
i test it now

2023-10-22 10:22 UTC, hadifawaz1999 commented
> structure all looks good, comments about docstrings and testing, could you aim for 100% coverage?

Thanks @TonyBagnall for all the comments, let me know if its okay now, coverage should be 100% now if i didn't miss anything

2023-10-22 10:55 UTC, TonyBagnall commented
> > structure all looks good, comments about docstrings and testing, could you aim for 100% coverage?
> 
> Thanks @TonyBagnall for all the comments, let me know if its okay now, coverage should be 100% now if i didn't miss anything

could you resolve any comments that have been resolved please? ta

2023-10-25 15:55 UTC, TonyBagnall approved these changes

2023-10-25 17:01 UTC, merged