[ENH] Proposed aeon deprecation policy
aeon-toolkit/aeon pull request #723
Opened 2023-09-05 18:36 UTC by TonyBagnall

further to the developers meeting on 5th September, those present agreed on trying to re-instate a deprecation policy starting from 0.5.0. This is a draft which I think reflects what we agreed, please feel free to adjust/add/remove.

2023-09-07 06:42 UTC, TonyBagnall commented
I think we should have an exclusion for deprecation policy for any module deemed "experimental". Im thinking the new similarity search and condensing modules

2023-10-05 11:24 UTC, baraline approved these changes
The description of what should be deprecated and for how long is clear to me. The exclusion of experimental modules seems reasonable and is well argumented

2023-10-07 13:02 UTC, dguijo submitted a review, later dismissed
lgtm!

2023-10-11 18:22 UTC, hadifawaz1999 approved these changes
LGTM !

2023-10-13 21:29 UTC, MatthewMiddlehurst requested changes
I will take a closer look tomorrow. The swap to .md seems to have had some casualties

https://aeon-toolkit--723.org.readthedocs.build/en/723/developer_guide/deprecation.html

I can go through and fix the formatting if you want

2023-10-14 08:42 UTC, TonyBagnall commented on docs/developer_guide/deprecation.md
> +==================
nope, have removed one

2023-10-14 22:27 UTC, MatthewMiddlehurst submitted a review, later dismissed
So, I think we should add a bit more to this (#840). However, now that the formatting issues are fixed by the look of things, I don't mind this going in first. Up to you.

2023-10-15 12:14 UTC, MatthewMiddlehurst approved these changes
Happy with the changes. 

@dguijo @baraline @hadifawaz1999 There are a few differences if you want to look again, but the times when you should deprecate and the experimental modules part have remained the same.

Main differences: 
- Can't deprecate from `0.6.1` to `0.7.0`, must do `0.6.1` to `0.8.0`
- Instructions for deprecating keyword arguments/parameters, only need to raise a warning when they are used rather than one for the whole class
- More examples

2023-10-15 14:43 UTC, hadifawaz1999 approved these changes
new changes LGTM !

2023-10-16 09:09 UTC, merged