[ENH] ShapeDTW as a distance function !
aeon-toolkit/aeon pull request #754
Opened 2023-09-20 20:53 UTC by hadifawaz1999

#### What does this implement/fix? Explain your changes.

Implements ShapeDTW in numba inside the distances module

#### Did you add any tests for the change?
Not yet, waiting to see if you agree with the setup till now

#### Any other comments?
Let me know if more information should be added to explain the implementation.
PS: this is not the implementation form the ShapeDBA paper, because ours only work in the case where the descriptor is identity, leaving that as future work and add it as a condition to use the more efficient code. But i made sure my implementation gives the same results as ours in the paper :)

2023-09-21 12:44 UTC, TonyBagnall commented on aeon/distances/_shapedtw.py
> +def shapedtw_distance(
maybe shape_dtw_distance?

2023-09-22 23:31 UTC, hadifawaz1999 commented
Fixed the caching issue @chrisholder , was using a dictionary for the choice of descriptor function which is considered a global large array apparently and can't use it in numba if i want to cache, so replaced it with if statements.

2023-09-23 16:55 UTC, chrisholder requested changes

2023-09-23 16:55 UTC, chrisholder commented on aeon/distances/_shape_dtw.py
> +        This defines which transformation is applied on the sub-sequences.
What are the options include a list of valid options?

I also wouldn't describe my parameter with 'this'. Just say 

```
Defines which transformation is applied on the sub-sequeces. Valid descriptors are: ['identity', ...]. 

Identity is ....<insert description of identity>
other is... <insert description of what the others do>

If not specified then identity is used.
```

2023-09-23 16:55 UTC, chrisholder commented on aeon/distances/_shape_dtw.py
> +        This is the length of the sub-sequences.
Same here just say 

`The length of the sub-sequences to consider`

2023-09-23 16:55 UTC, chrisholder commented on aeon/distances/_shape_dtw.py
> +        This is the length of the sub-sequences.
Change what is mentioned here in all places

2023-09-23 16:55 UTC, chrisholder commented on aeon/distances/_shape_dtw.py
> +        DTW distance between x and y, minimum value 0.
Shape-DTW

2023-09-23 16:55 UTC, chrisholder commented on aeon/distances/_shape_dtw.py
> +            _x.shape[1], _y.shape[1], window, itakura_max_slope
Assuming this is intentional that you don't use the padded arrays for the bounding matrix?

2023-09-23 16:55 UTC, chrisholder commented on aeon/distances/_shape_dtw.py
> +    shapedtw_cost_mat = _dtw_cost_matrix(
I don't exactly know what the transform does but it is important whatever it spits out is the same shape as your bounding matrix provided (some maybe you want to make it here if this does something weird with x and y)

2023-09-23 16:55 UTC, chrisholder commented on aeon/distances/_shape_dtw.py
> +        shapedtw_dist += np.square(np.linalg.norm(x[:, reach + i] - y[:, reach + j]))
Just for consistency across the distance module can you use:

`from aeon.distances._squared import _univariate_squared_distance
`

I guess here then you'd do 

` shapedtw_dist += _univariate_squared_distance(x[:, reach + i], y[:, reach + j])`

2023-09-23 16:55 UTC, chrisholder commented on aeon/distances/_shape_dtw.py
> +        if a < b:
This can be simplified to:

```
if a < b and a < c:
    i -= 1
    j -= 1
elif b < c:
    j -= 1
else:
    i -= 1
```

2023-09-23 16:55 UTC, chrisholder commented on aeon/distances/_shape_dtw.py
> +
Missing docstring for itakura para:

    itakura_max_slope : float, default=None
        Maximum slope as a proportion of the number of time points used to create
        Itakura parallelogram on the bounding matrix. Must be between 0. and 1.
        
 Add this to all the functions that it is specified in below (think you accidently deleted it in all the functions during refactor)

2023-09-23 16:55 UTC, chrisholder commented on aeon/distances/_shape_dtw.py
> +
Just remove this docstring for private method more docs to maintain that no one will see on the API

2023-09-23 16:55 UTC, chrisholder commented on aeon/distances/_shape_dtw.py
> +    Parameters
I would just remove this docstring on the private methods no one will see them on the API

2023-09-23 16:55 UTC, chrisholder commented on aeon/distances/_shape_dtw.py
> +    shapedtw_dist = shape_dtw_distance(
Here effectivly your recomputing the cost matrix again to just get the distance. Is it possible to split up the _shape_dtw_distance function so that the part that gets the distance from the cost matrix is a function that we can call here instead of recomputing the whole cost matrix?

2023-09-23 16:55 UTC, chrisholder commented on aeon/distances/_shape_dtw.py
> +    """Compute the ShapeDTW pairwise distance among a set of series.
Remove the docstring for a private method

2023-09-24 04:30 UTC, hadifawaz1999 commented on aeon/distances/_shape_dtw.py
> +            _x.shape[1], _y.shape[1], window, itakura_max_slope
yup because the bounding matrix should have the same height/width as the cost matrix which has a height/width set to the length of time series on both, so i use the length of the original series instead of the padded one.

2023-09-24 04:32 UTC, hadifawaz1999 commented on aeon/distances/_shape_dtw.py
> +    shapedtw_cost_mat = _dtw_cost_matrix(
it wouldn't make a difference, the bounding matrix takes as input the height/width

the transformation function takes a series of length L + 2 * reach (where L is the length of the original series) and outputs a series of length L again.

2023-09-24 04:34 UTC, hadifawaz1999 commented on aeon/distances/_shape_dtw.py
> +        shapedtw_dist += np.square(np.linalg.norm(x[:, reach + i] - y[:, reach + j]))
but this a multivariate distance not univariate.

`x[:, reach + i]` is a vector in the general case

2023-09-24 04:36 UTC, hadifawaz1999 commented on aeon/distances/_shape_dtw.py
> +
oh yeah good spotting, i forgot to copy it.

2023-09-24 04:38 UTC, hadifawaz1999 commented on aeon/distances/_shape_dtw.py
> +
makes sense

2023-09-24 05:22 UTC, hadifawaz1999 commented on aeon/distances/_shape_dtw.py
> +        This defines which transformation is applied on the sub-sequences.
for now i didn't add new options, but i added through out all the docstrings what you mentioned

2023-09-24 05:22 UTC, hadifawaz1999 commented on aeon/distances/_shape_dtw.py
> +        This is the length of the sub-sequences.
done

2023-09-24 05:22 UTC, hadifawaz1999 commented on aeon/distances/_shape_dtw.py
> +        DTW distance between x and y, minimum value 0.
done

2023-09-24 05:22 UTC, hadifawaz1999 commented on aeon/distances/_shape_dtw.py
> +    Parameters
done

2023-09-24 05:23 UTC, hadifawaz1999 commented on aeon/distances/_shape_dtw.py
> +    shapedtw_dist = shape_dtw_distance(
makes sense, i made a function for that now let me know if thats better

2023-09-24 05:23 UTC, hadifawaz1999 commented on aeon/distances/_shape_dtw.py
> +    """Compute the ShapeDTW pairwise distance among a set of series.
done

2023-09-24 05:31 UTC, hadifawaz1999 commented on aeon/distances/_shape_dtw.py
> +        if a < b:
makes sense :) thanks

2023-09-24 08:57 UTC, chrisholder commented on aeon/distances/_shape_dtw.py
> +        shapedtw_dist += np.square(np.linalg.norm(x[:, reach + i] - y[:, reach + j]))
Is it?

Isn't x here if it's a multivariate:

x = [[1, 2, 3, 4], [5, 6, 7, 8]]

And lets say rech = 1 and i = 0

x[:, 1+0] = x[:, 1]

This would return 

x[:, 1] = [2, 6]

2023-09-24 08:58 UTC, chrisholder commented on aeon/distances/_shape_dtw.py
> +        Identity is ....<insert description of identity>
When I said i mean <insert description of identity> I meant for you to fill in the description :joy:

2023-09-24 08:58 UTC, chrisholder commented on aeon/distances/_shape_dtw.py
> +        This defines which transformation is applied on the sub-sequences.
Fill in the description of identity

2023-09-24 09:12 UTC, hadifawaz1999 commented on aeon/distances/_shape_dtw.py
> +        shapedtw_dist += np.square(np.linalg.norm(x[:, reach + i] - y[:, reach + j]))
oh never mind, i misunderstood :) i meant to say that x is multivariate but once you index the time axis its like having a univariate now even it its a vector now

2023-09-24 09:12 UTC, hadifawaz1999 commented on aeon/distances/_shape_dtw.py
> +        Identity is ....<insert description of identity>
i actually wanted to add it but i guess i forgot after copying it 😂

2023-09-24 09:32 UTC, chrisholder approved these changes
Great addition to the distance module!

2023-09-24 11:05 UTC, merged