[BUG] Medoids empty cluster bug fix
aeon-toolkit/aeon pull request #760
Opened 2023-09-23 19:34 UTC by chrisholder

#### Reference Issues/PRs

Fixes #752 #672 

#### What does this implement/fix? Explain your changes.

There was a bug with PAM implementation where it was performing the wrong swap. I fixed this code and updated the tests.

#### Does your contribution introduce a new dependency? If yes, which one?

#### What should a reviewer concentrate their feedback on?

#### Did you add any tests for the change?

#### Any other comments?

### PR checklist

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc).
- [x] Optionally, I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.
- [x] For new estimators, I've added the estimator to the online documentation.

2023-09-26 11:26 UTC, TonyBagnall requested changes
two very minor points, otherwise looks good

2023-09-26 11:26 UTC, TonyBagnall commented on aeon/clustering/clara.py
> +    init_algorithm : str or np.ndarray, default='random'
the type hint in the constructor still lists this as 
        init_algorithm: Union[str, Callable] = "random",

2023-09-26 11:43 UTC, chrisholder commented on aeon/clustering/k_medoids.py
> +        medoids_idxs = self._init_algorithm
Fixed in kmedoids and clarans

2023-09-26 11:43 UTC, chrisholder commented on aeon/clustering/clara.py
> +    init_algorithm : str or np.ndarray, default='random'
Fixed in clara and clarans

2023-09-26 13:25 UTC, TonyBagnall approved these changes

2023-09-26 14:36 UTC, merged

2023-09-29 19:49 UTC, MatthewMiddlehurst commented on setup.cfg
> +;    --numprocesses auto
Don't do this in the future