[ENH] Adds RED CoMETS classifier
aeon-toolkit/aeon pull request #779
Opened 2023-09-29 08:59 UTC by zy18811

Draft PR adding [RED CoMETS classifier](https://arxiv.org/abs/2307.13679).

Not sure what algorithm type it falls under? So have put into hybrid for now.

Adds a soft dependency to [imbalanced-learn](https://github.com/scikit-learn-contrib/imbalanced-learn). 

### TODO
- Speed up SAX transforms using parallelisation 
- Fix some minor formatting issues
- Add tests
- Add examples in docstrings + add to online documentation

### PR checklist
- [X] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc).
- [X] Optionally, I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [X] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.
- [ ] For new estimators, I've added the estimator to the online documentation.

2023-09-29 12:47 UTC, TonyBagnall commented
great, thanks Luca. The categories are necessarily fluid, but I would probably put it in dictionary based?

2023-09-29 12:48 UTC, TonyBagnall commented
also, would you like to join our slack @zy18811 https://join.slack.com/t/aeon-toolkit/shared_invite/zt-2466yn6zm-5fV0EW8JjSVUoe2hzJjRMw

2023-09-29 13:21 UTC, TonyBagnall commented
could you add some testing code for this? You can use skip test for the soft dependency,  for example, someting like this before each test function

```python
@pytest.mark.skipif(
    not _check_soft_dependencies("imblearn", severity="none"),
    reason="skip test if required soft dependency esig not available",
)
```

2023-10-07 13:01 UTC, TonyBagnall approved these changes
couple of very minor docstring comments, but otherwise this looks great, thank you for the contribution

2023-10-08 22:52 UTC, zy18811 commented on aeon/classification/dictionary_based/_redcomets.py
> +        If `int`, random_state is the seed used by the random number generator;
Is that for everything quoted in docstrings, e.g. the "RandomState" and "None" in following lines, as well or just _int_?

 NB: copied that phrasing from the HC2 docstring so will need fixing there + anywhere else its used. Is it worth me raising an issue for this?

2023-10-09 09:13 UTC, TonyBagnall commented
this test failure is nothing to do with your PR, just a weird tensorflow thing

2023-10-09 21:51 UTC, zy18811 commented on aeon/classification/dictionary_based/_redcomets.py
> +        If `int`, random_state is the seed used by the random number generator;
Okay think I've added double tick quotes everywhere they're appropriate! Raised an [issue](https://github.com/aeon-toolkit/aeon/issues/809) :)

2023-10-09 21:53 UTC, zy18811 commented
Think I've addressed the two docstring issues :)  🚀

2023-10-10 06:26 UTC, TonyBagnall requested changes
one more tiny thing on the soft dependencies and I think its ready, great job

2023-10-10 06:26 UTC, TonyBagnall commented on aeon/classification/dictionary_based/_redcomets.py
> +        from imblearn.over_sampling import SMOTE, RandomOverSampler
with soft dependencies we do a check before the import to give a more informative error. Look in clustering/_k_shapes.py for an example of how its done, but basically import  _check_soft_dependencies at the top then call it like this prior to the import
       _check_soft_dependencies("imblearn", severity="error")

2023-10-10 08:02 UTC, zy18811 commented on aeon/classification/dictionary_based/_redcomets.py
> +        from imblearn.over_sampling import SMOTE, RandomOverSampler
Yep, currently that check is currently in `__init__()`, should it be moved to be directly before the import statement?

2023-10-10 13:24 UTC, TonyBagnall commented on aeon/classification/dictionary_based/_redcomets.py
> +        from imblearn.over_sampling import SMOTE, RandomOverSampler
ah sorry, didnt look closely enough, but yes I think we normally put it in the function with the import.

2023-10-10 17:50 UTC, zy18811 commented on aeon/classification/dictionary_based/_redcomets.py
> +        from imblearn.over_sampling import SMOTE, RandomOverSampler
Okay moved it to the correct location.

2023-10-11 09:12 UTC, TonyBagnall submitted a review, later dismissed
LGTM

2023-10-11 13:45 UTC, MatthewMiddlehurst submitted a review, later dismissed
Hi Luca, thanks for the contribution. Great work.

One minor change to the all-contributors file would be good, I can monitor and merge after that is complete unless anyone else wants to review and request changes.

2023-10-11 13:45 UTC, MatthewMiddlehurst commented on .all-contributorsrc
> +    },
```suggestion
    }
```
Annoyingly this comma breaks the file

2023-10-11 13:46 UTC, MatthewMiddlehurst approved these changes

2023-10-12 11:32 UTC, TonyBagnall approved these changes

2023-10-12 12:38 UTC, merged