[DOC] Tidy up referencing in doc strings
aeon-toolkit/aeon pull request #781
Opened 2023-09-29 19:20 UTC by TonyBagnall

Fixes #685 

sorts of references so not in weird format and link

2023-10-01 15:29 UTC, dguijo requested changes
minor typos. What a tedious work, Tony! Thanks!

2023-10-01 15:29 UTC, dguijo commented on aeon/classification/deep_learning/encoder.py
> +    Adapted from the implementation used in [1]_
Final dot?

2023-10-01 15:29 UTC, dguijo commented on aeon/classification/dictionary_based/_cboss.py
> +    described in Middlehurst, Vickers and Bagnall (2019). [2]_
"... from [1]_ with refinements described in [2]_." ?

2023-10-01 15:29 UTC, dguijo commented on aeon/classification/dictionary_based/_tde.py
> +    from [1]_
final dot?

2023-10-01 15:29 UTC, dguijo commented on aeon/classification/hybrid/_hivecote_v1.py
> +    implementation differs from the one described in [1], in that the STC component
[1]_ ?

2023-10-01 15:29 UTC, dguijo commented on aeon/classification/interval_based/_tsf.py
> +    1]_.
[1]_ in the same line?

2023-10-01 17:32 UTC, TonyBagnall commented
> minor typos. What a tedious work, Tony! Thanks!

lol, I have a strangely large capacity for tedious work like this, its the secret of my success :)

2023-10-02 11:27 UTC, TonyBagnall commented
thanks david, typos corrected.

2023-10-02 13:40 UTC, dguijo approved these changes
lgtm. Thank you, Tony!

2023-10-02 13:42 UTC, merged