[DOC] Add a notebook to describe inheritance structure of base classes
aeon-toolkit/aeon pull request #789
Opened 2023-10-02 11:56 UTC by TonyBagnall

adds a simplified overview of the core class structure of aeon, based on a simple UML by @hadifawaz1999 

I've presented UML with stylised/simplifed code. Happy to do otherwise if anyone has any ideas

I have as a result tweaked a couple of base classes, making fit/predict final and alterning some docstrings to standardise things

2023-10-02 14:10 UTC, dguijo commented on examples/base/img/uml.png
There are three BaseDeepClusterer. The second and third should be Regressor and Classifier, respectively.

2023-10-02 14:11 UTC, dguijo commented on examples/base/img/uml3.png
There are three BaseDeepClusterer. The second and third should be Regressor and Classifier, respectively.

2023-10-02 14:12 UTC, dguijo commented on examples/base/base_classes.ipynb
> +    "main functionsality and may differ in details from the actual implementations.\n",
functionsality -> functionality

2023-10-02 14:14 UTC, dguijo commented on examples/base/base_classes.ipynb
> +    "`networks` class. It has a single abstract method `build_network`.\n",
change "class" by "module"?

2023-10-02 14:16 UTC, dguijo commented on examples/base/base_classes.ipynb
> +    "'LINK]. `BaseForecaster` has the following concrete methods:\n",
replace "API-LINK" with the link.

2023-10-02 14:17 UTC, dguijo commented on examples/base/base_classes.ipynb
> +    "## BaseSeriesAnnotator (aeon.annotation.base)\n",
`BaseSeriesAnnotator` to keep using the same format :smile:

2023-10-02 14:18 UTC, dguijo commented on examples/base/base_classes.ipynb
> +    "## BaseCollectionEstimator (aeon.base)\n",
`BaseCollectionEstimator` to keep using the same format 😄

2023-10-02 14:19 UTC, dguijo commented on examples/base/base_classes.ipynb
> +    "## BaseRegressor (aeon.regression)\n",
`BaseRegressor` to keep using the same format 😄

2023-10-02 14:19 UTC, dguijo commented on examples/base/base_classes.ipynb
> +    "## BaseClassifier (aeon.classification)\n",
`BaseClassifier` to keep using the same format 😄

2023-10-02 14:20 UTC, dguijo commented on examples/base/base_classes.ipynb
> +    " and conversion is donw using the following final methods defined in\n",
donw -> down

2023-10-02 14:20 UTC, dguijo commented on examples/base/base_classes.ipynb
> +    "## BaseClusterer (Aeon.clustering)\n",
`BaseClusterer` to keep using the same format 😄

2023-10-02 14:21 UTC, dguijo commented on examples/base/base_classes.ipynb
> +    "## BaseClusterer (Aeon.clustering)\n",
also, "aeon" instead of "Aeon"

2023-10-02 14:42 UTC, TonyBagnall commented
> Thank you Tony! Great work!
> 
> PS. Sorry for being picky 😅

picky is good! :)

2023-10-02 16:03 UTC, TonyBagnall commented on examples/base/img/uml.png
removed for now, since we dont actually describe base deeps

2023-10-04 07:24 UTC, dguijo requested changes
Tony, there was one comment left. A minor minor thing. Sorry and thank you!

2023-10-04 07:24 UTC, dguijo commented on examples/base/base_classes.ipynb
> +    "## BaseSeriesAnnotator (aeon.annotation.base)\n",
I think this one has to be done?

2023-10-05 07:33 UTC, TonyBagnall commented
> Tony, there was one comment left. A minor minor thing. Sorry and thank you!

done

2023-10-05 15:01 UTC, MatthewMiddlehurst reviewed
Two comments for the base class changes. Rest will be via notebook viewer, probably.

2023-10-05 15:01 UTC, MatthewMiddlehurst commented on aeon/clustering/base.py
>          self.n_clusters = n_clusters
Should this really be a base class parameter? Seems restrictive.

2023-10-05 15:17 UTC, TonyBagnall commented on aeon/clustering/base.py
>          self.n_clusters = n_clusters
that is a question for @chrisholder and beyond the scope of this PR, but I dont see why it should not be a base class parameter with a default?

2023-10-05 17:12 UTC, TonyBagnall commented on aeon/clustering/base.py
>          self.n_clusters = n_clusters
seems fine to me, given it has a default value.

2023-10-05 17:13 UTC, TonyBagnall commented on examples/base/base_classes.ipynb
> +{
<p>not all estimators have fit and predict</p>

2023-10-05 17:16 UTC, TonyBagnall commented on aeon/clustering/base.py
>          self.n_clusters = n_clusters
but maybe raise an issue? Dont really want to hold design discussions on this PR which is just describing the current state

2023-10-05 20:44 UTC, MatthewMiddlehurst commented on examples/base/base_classes.ipynb
> +{
The line it's referring to fit and predict as functions though I assumed. Won't push for it.

2023-10-05 20:45 UTC, MatthewMiddlehurst commented on aeon/clustering/base.py
>          self.n_clusters = n_clusters
ok

2023-10-06 09:09 UTC, TonyBagnall commented on examples/base/base_classes.ipynb
> +{
ah I cant really see the output properly. Maybe you can tweak it later, might be easier

2023-10-06 09:32 UTC, MatthewMiddlehurst commented on examples/base/base_classes.ipynb
> +{
https://app.reviewnb.com/aeon-toolkit/aeon/blob/ajb/base_notebook/examples/base/base_classes.ipynb/ seems to render fine

2023-10-09 13:15 UTC, dguijo approved these changes
LGTM, Tony and Matt. Thank you for your work!

2023-10-09 13:46 UTC, merged