[GOV] Code of Conduct revision
aeon-toolkit/aeon pull request #806
Opened 2023-10-09 14:33 UTC by MatthewMiddlehurst

#### Reference Issues/PRs

Relies on #195
Resolves #35 

#### What does this implement/fix? Explain your changes.

This completely revises the current code of conduct in the style of #195. 

The 340 lines of text in the current document did not prevent any of the issues encountered previously. Having a more streamlined and condensed document which can get across the core principles of our community and contact points is more useful IMO.

The new version piggybacks off the general Python code of conduct for the most part https://www.python.org/psf/codeofconduct/.

2023-10-09 16:39 UTC, TonyBagnall submitted a review, later dismissed
read through it all and it seems just right to me

2023-10-13 11:18 UTC, MatthewMiddlehurst commented
I have updated some of the repo text files to give a bit of a summary rather than just linking the webpage.

2023-10-13 11:31 UTC, TonyBagnall requested changes

2023-10-13 11:31 UTC, TonyBagnall commented on CODE_OF_CONDUCT.md
> +[COCW](https://www.aeon-toolkit.org/en/latest/governance.html#code-of-conduct-workgroup)
need to give full name for COCW

2023-10-13 11:31 UTC, TonyBagnall commented on CODE_OF_CONDUCT.md
> +You can find our full Code of Conduct (CoC) on our [website](https://www.aeon-toolkit.org/en/latest/code_of_conduct.html).
goes to 404 for me

2023-10-13 20:17 UTC, MatthewMiddlehurst commented on CODE_OF_CONDUCT.md
> +You can find our full Code of Conduct (CoC) on our [website](https://www.aeon-toolkit.org/en/latest/code_of_conduct.html).
This is the location post-move on the docs,

2023-10-13 20:19 UTC, MatthewMiddlehurst commented on CODE_OF_CONDUCT.md
> +[COCW](https://www.aeon-toolkit.org/en/latest/governance.html#code-of-conduct-workgroup)
Done

2023-10-16 07:32 UTC, TonyBagnall approved these changes

2023-10-16 09:10 UTC, merged