[ENH] Results loaders for published results
aeon-toolkit/aeon pull request #890
Opened 2023-11-04 20:40 UTC by TonyBagnall

in order to clear up a long standing ambiguity, this PR hard codes loading published results, developed in conjunction with 
https://timeseriesclassification.com/results.php

this is bespoke code, intentionally. These legacy results need to be captured, and I think the best way is to do so explicitly, rather than have general loaders, which are there for dynamically evolving results. 

there is some extra testing, but the basic addition is the function get_bake_off_2017_results, which loads the original bake off results

2023-11-11 11:42 UTC, MatthewMiddlehurst reviewed
Given some of the tests are skipped, we should probably do a full run before merging.

2023-11-11 11:42 UTC, MatthewMiddlehurst commented on aeon/benchmarking/__init__.py
> +    "classifiers_2023",
Does not have to be this PR, but should discuss if all of these should be include in the base of `benchmarking` or sub-packages at some point. Can get a bit messy otherwise, plotting should probably be one as well.

2023-11-11 11:42 UTC, MatthewMiddlehurst commented on aeon/benchmarking/results_loaders.py
> +    suffix="_TESTFOLDS.csv",
Should add this to the docstring

2023-11-11 13:08 UTC, TonyBagnall commented on aeon/benchmarking/__init__.py
> +    "classifiers_2023",
I did test without skips before putting skips in :) I will change docstring below and run again without skips though. I think plotting could be its own module or sub module, but its all over the place and integral to forecasting

2023-11-13 10:58 UTC, dguijo submitted a review, later dismissed
Good work, Tony. The only thing that seems important to me is to discriminate between uni and multivariate bakeoffs. Thanks!

2023-11-13 10:58 UTC, dguijo commented on aeon/benchmarking/results_loaders.py
> +        n_data=112,
112 for multi?

2023-11-13 10:58 UTC, dguijo commented on aeon/datasets/tsc_data_lists.py
> +# 85 UCR univariate time series classification problems in th 2015 version
the

2023-11-13 10:59 UTC, dguijo commented on aeon/benchmarking/results_loaders.py
> +    estimators : list of string
not sure about this nor the space before ":". All this has to be unified imo. Don't know which way is the best though.

2023-11-13 11:02 UTC, TonyBagnall commented on aeon/benchmarking/_critical_difference.py
yes  I think hold off  on this PR until #902 is in

2023-11-16 09:25 UTC, TonyBagnall commented on aeon/benchmarking/results_loaders.py
> +    estimators : list of string
format demanded by sphinx is this: If you dont follow it it generates a lot of warnings

estimators : list
    Capital start, description ends in full stop.

2023-11-16 09:26 UTC, TonyBagnall commented on aeon/benchmarking/results_loaders.py
mentioned in docstrings, can change names, any recommendations?

2023-11-16 10:27 UTC, TonyBagnall commented on aeon/benchmarking/results_loaders.py
> +    estimators : list of string
also sphinx format is 
name : type
or
name : str, default = "foo"

with no full stop there

2023-11-16 10:28 UTC, TonyBagnall commented on aeon/benchmarking/results_loaders.py
> +        n_data=112,
good point :)

2023-11-16 10:51 UTC, dguijo commented on aeon/benchmarking/results_loaders.py
> +    estimators : list of string
ok, maybe we can create a rule for standarising this as some files have a wrong format I think.

2023-11-16 10:53 UTC, dguijo commented on aeon/benchmarking/results_loaders.py
I think maybe: univariate_classifiers_2017, multivariate_classifiers_2021 and univariate_classifiers_2023, or its reduced version, uni_classifiers and multi_classifiers, if we want to keep it short.

2023-11-16 11:05 UTC, TonyBagnall commented on aeon/benchmarking/results_loaders.py
> +    estimators : list of string
I sort of fix it where I see it, but its not a big issue. Sweep could possibly help?

2023-11-21 09:05 UTC, dguijo requested changes
minor stuff. Going to review the notebooks now.

2023-11-21 09:14 UTC, dguijo commented on examples/benchmarking/bakeoff_results.ipynb
> +{
<p>three links?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/aeon-toolkit/aeon/pull/890/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='0'/>

2023-11-21 09:14 UTC, dguijo commented on examples/benchmarking/bakeoff_results.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #1.    from aeon.benchmarking.results_loaders import uni_classifiers_2017
</pre><p>why 2017? don't know if I wrote a comment in the python code about this. </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/aeon-toolkit/aeon/pull/890/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='2'/>

2023-11-21 09:14 UTC, dguijo commented on examples/benchmarking/bakeoff_results.ipynb
> +{
<p>Susequent -&gt; Subsequent</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/aeon-toolkit/aeon/pull/890/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='9'/>

2023-11-22 12:03 UTC, TonyBagnall commented on aeon/benchmarking/results_loaders.py
> +        resamples=100,
it loads the resamples but only returns the default. Its a private method

2023-11-22 12:05 UTC, TonyBagnall commented on examples/benchmarking/bakeoff_results.ipynb
> +{
2017 was when the original bake off was published. There will be a 23 or 24 version if the paper is ever reviewed and accepted

2023-11-22 12:05 UTC, TonyBagnall commented on examples/benchmarking/bakeoff_results.ipynb
> +{
added a comment to that effect

2023-11-22 12:05 UTC, TonyBagnall commented on examples/benchmarking/bakeoff_results.ipynb
> +{
good spot!

2023-11-22 12:10 UTC, TonyBagnall commented on examples/benchmarking/bakeoff_results.ipynb
> +{
removed

2023-11-23 11:33 UTC, MatthewMiddlehurst commented
Think we should maybe split up the imports rather than have it all in the main `benchmarking` `__init__`, but it's all experimental and can change later so don't have to do it here. Fine with this going on when David approves.

2023-11-23 11:36 UTC, merged