Add download_dataset function to _data_loaders.py
aeon-toolkit/aeon pull request #906
Opened 2023-11-16 11:08 UTC by PaulRabich

Added a function ``download_dunction`` to the ``_data_loaders.py`` file.
This functions only downloads a dataset without loading it to memory.

2023-11-16 13:07 UTC, TonyBagnall approved these changes
tiny typo and a formatting request but thanks for this. I think the testing for this needs a bit of a rework, so will add a test for next coverage push.

2023-11-16 13:07 UTC, TonyBagnall commented on aeon/datasets/_data_loaders.py
> +    if successful, string containing the path of the safed file
saved file

2023-11-16 13:07 UTC, TonyBagnall commented on aeon/datasets/_data_loaders.py
> +    safe_path : string, optional (default: None)
our standard format is 
safe_path : str or None, default = None

2023-11-16 17:11 UTC, MatthewMiddlehurst requested changes
If testing will be done in a different PR, I think my only issue is the docs name as well. Fine with it going in after.

2023-11-16 17:11 UTC, MatthewMiddlehurst commented on aeon/datasets/_data_loaders.py
> +    safe_path : string, optional (default: None)
Change `safe` in the parameter and documentation to `save`

2023-11-16 17:15 UTC, MatthewMiddlehurst approved these changes

2023-11-16 17:16 UTC, MatthewMiddlehurst commented
Ignore the failure, unrelated and dealt with in a different PR.

2023-11-16 17:18 UTC, PaulRabich commented
Anything else to do?

2023-11-17 09:21 UTC, merged

2023-11-17 09:21 UTC, TonyBagnall commented
thanks for this

2023-11-17 10:35 UTC, MatthewMiddlehurst commented
@all-contributors add @PaulRabich for code