Change n_dimensions to n_channels
aeon-toolkit/aeon pull request #914
Opened 2023-11-21 16:14 UTC by xiaopu222

#### Reference Issues/PRs

#### What does this implement/fix? Explain your changes.

#### Does your contribution introduce a new dependency? If yes, which one?

#### Any other comments?

### PR checklist

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [ ] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring or governance.

##### For new estimators and functions
- [ ] I've added the estimator to the online [API documentation](https://www.aeon-toolkit.org/en/latest/api_reference.html).

##### For developers with write access
- [ ] Optionally, I've updated aeon's [CODEOWNERS](https://github.com/aeon-toolkit/aeon/blob/main/CODEOWNERS) to receive notifications about future changes to these files.

2023-11-21 16:33 UTC, TonyBagnall requested changes
thanks for this, but you need to replace n_dimensions with n_channels, not just delete it. Also, could you begin your PR with [ENH] and also reference the PR requesting this change in the comments? I didnt realise so many files used n_dimensions in comments still!

2023-11-21 16:33 UTC, TonyBagnall commented on aeon/classification/_dummy.py
> +        X : 3D np.array of shape = [n_instances,, series_length]
need to replace n_dimensions with n_channels, not leave it blank

2023-11-21 16:42 UTC, xiaopu222 commented on aeon/classification/_dummy.py
> +        X : 3D np.array of shape = [n_instances,, series_length]
Yes there is a mistake that i leave a black space rather than a new string name. But i find there are 34 files is using "n_dimensions". Could i double check with you that am i going to replace "n_dimensions" in whole aeon module ?

2023-11-21 16:48 UTC, hadifawaz1999 commented on aeon/classification/_dummy.py
> +        X : 3D np.array of shape = [n_instances,, series_length]
not sure if @TonyBagnall wants to change it throughout all of aeon, but am sure that for deep learning stuff yes we wanted to change it. So at least the deep learning files yes.

Thank you for taking care of this.

2023-11-21 17:43 UTC, TonyBagnall commented on aeon/classification/_dummy.py
> +        X : 3D np.array of shape = [n_instances,, series_length]
may as well change it everywhere @hadifawaz1999 ?

2023-11-21 18:57 UTC, hadifawaz1999 commented on aeon/classification/_dummy.py
> +        X : 3D np.array of shape = [n_instances,, series_length]
Yup i agree @TonyBagnall

2023-11-22 09:30 UTC, TonyBagnall commented on aeon/classification/_dummy.py
> +        X : 3D np.array of shape = [n_instances,, series_length]
ok @xiaopu222 go ahead and fix n_dimensions -> n_channels for all the files, thanks

2023-11-22 18:36 UTC, closed without merging