[ENH] Refactor numpyflat to be numpy2D
aeon-toolkit/aeon pull request #941
Opened 2023-11-28 17:49 UTC by TonyBagnall

#### Reference Issues/PRs

fixes #815 

#### What does this implement/fix? Explain your changes.

Its a good idea imo to rename this, as it no longer means "concatenated multivariate", where it used to be use for a embedded hidden transformation. 

Further reason for this refactor: there is an irreconcilable difference with how we treat 2D numpy in different parts of the toolkit. if we have either
a) a multivariate series with d channels and m timepoints or
b) a collection of univariate n series with m timepoints
stored in a numpy array, do we treat it as

(d,m)/(n,m) or (m,d)/(m,n) 

3D numpy are universally considered to be (n,d,m) and classifiers, clusterers and regressors treat (n,m) as n univariate series. 
However, forecasting and series transformers all treat this  as (m,d)/(m,n) as is usual in that field. It is indicated by type "np.ndarray". 

So, obvious solution would be to have an axis argument, and writing from scratch, thats what we would do. However, there is a mountain of legacy code in the transformers, that involves all kind of auto conversion and transformers that are meant to work with both series and collections. Thus we have this situation, for example

```python 
from aeon.transformations.series.matrix_profile import MatrixProfileTransformer
import numpy as np
# either five series length 10 or 10 series length five
X = np.random.rand(5, 10)
mp2 = MatrixProfileTransformer(window_length=3) #Will shorten series by  2
X2 = mp2.fit_transform(X)
print("Shape  = ",X2.shape) # 2D treated as (m,d) output shape (3, 10)
# either five series with three channels of length 10 or what?
X = np.random.rand(5, 3, 10)
X2 = mp2.fit_transform(X)
print("Shape  = ",X2.shape) #3D treated as (n,d,m) (5, 3, 8)
```
where the same transformer treats 2D treated as (m,d) but a 3D treated as (n,d,m).

2023-12-05 11:09 UTC, MatthewMiddlehurst requested changes
Fine with this in principle, should be careful not to break whats there though. The comments alluding to a `numpy2D` 'Table' type are a little concerning, don't know if that causes conflicts.

2023-12-05 11:09 UTC, MatthewMiddlehurst commented on aeon/classification/compose/_pipeline.py
> +            return X
Will this ever be true if its converted to numpy3D?

2023-12-05 11:09 UTC, MatthewMiddlehurst commented on aeon/datasets/tests/test_data_loaders.py
> +    assert _alias_datatype_check("numpy2D") == "numpy2D"
would swap this function argument to `numpyflat`

2023-12-05 11:09 UTC, MatthewMiddlehurst commented on aeon/datatypes/_panel/_convert.py
> +def from_numpy3d_to_numpy2D(obj, store=None):
naming is a bit inconsistent i.e. 3d and 2D

This happens elsewhere in the file.

2023-12-05 11:09 UTC, MatthewMiddlehurst commented on aeon/datatypes/_panel/_registry.py
> +        "2D np.ndarray of format (n_cases, n_channels)",
`(n_cases, n_timepoints)`?

2023-12-05 11:09 UTC, MatthewMiddlehurst commented on aeon/datatypes/tests/test_lookup.py
> +        return None
Why are the test changes required? I think this may be a consequence of not changing the lists above maybe.

2023-12-05 11:09 UTC, MatthewMiddlehurst commented on aeon/regression/compose/_pipeline.py
> +            return X
same as classification

2023-12-05 11:09 UTC, MatthewMiddlehurst commented on aeon/utils/validation/_convert_collection.py
> +    X_flat = _from_numpy3d_to_numpy2D(X)
3d vs 2D

2023-12-05 17:17 UTC, TonyBagnall commented on aeon/classification/compose/_pipeline.py
>          `X` is converted to `numpy2D` mtype if `X` is of `Table` type.
numpy2D doesnt currently exist as a type afaik

2023-12-05 17:21 UTC, TonyBagnall commented on aeon/classification/compose/_pipeline.py
> +            return X
no, it can go

2023-12-05 17:27 UTC, TonyBagnall commented on aeon/datatypes/_panel/_convert.py
> +def from_numpy3d_to_numpy2D(obj, store=None):
this is in datatypes, not fixing this myself

2023-12-05 17:35 UTC, TonyBagnall commented on aeon/datatypes/tests/test_lookup.py
> +        return None
because numpyflat is explicitly listed as an ambiguous type and are meant to be excluded from checking. 

# mtypes to exclude in checking since they are ambiguous and rare
AMBIGUOUS_MTYPES = ["numpy2D", "alignment_loc"]

you cannot convert to different types unless you fix what it actually means for series. the method ``mtype_to_scitype`` confuses np.ndarray with numpyflat I think. mtype_to_scitype is not ever called with collections.

2023-12-05 17:54 UTC, TonyBagnall commented
> Fine with this in principle, should be careful not to break whats there though. The comments alluding to a `numpy2D` 'Table' type are a little concerning, don't know if that causes conflicts.

which conflicts? numpyflat was only used in places where it meant concatenate dimensions. Everything about datatypes is confusing ....

2023-12-06 00:15 UTC, MatthewMiddlehurst commented
there is also a "table" type with the same name 
![image](https://github.com/aeon-toolkit/aeon/assets/25731235/f214a0b8-375b-4069-b78c-50831e583fce)

2023-12-06 10:23 UTC, TonyBagnall commented
> there is also a "table" type with the same name

ah didnt realise that, I guess thats whats causing the ambiguity in the scitype conversion. I have never looked at the Table type. I dont really want to work with the whole scheme tbh, but I will take a look.

2023-12-06 19:06 UTC, MatthewMiddlehurst approved these changes

2023-12-06 22:21 UTC, merged